### ISSUE TITLE
Change API version used to get consumed artfacts to older version

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#1000]
#999

GenerateReleaseNotes. After the automatic update to 3.50.2, we get: The requested REST API version of "6.1" is out of the valid range for this server. The latest REST API version supported by this server is 5.1

This does have to be a -preview version, so trying 5.1-preview

**Comment by rfennell** [comment]
Fix will be in 3.51.x, this will support 5.1-preview

**Comment by MODUSCarstenScholling** [comment]
Great Richard, thank you!
