### ISSUE TITLE
Keep getting errors in Wiki 

### ISSUE THREAD

**Issue by adamzeit** [rfennell/AzurePipelines#1015]
Hello,

I would like to prai, we use your Release Notes Extension in Azure and we like it very much.
However we have a probelem with publishing with the Wiki Extension.  Here is the yaml.

steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Add Release Notes to WIKI'
  inputs:
    repo: 'https://XXXXXX@dev.azure.com/xxxx/XXXXXX/_git/XXXXXX.wiki'
    filename: '$(FinalFileName)'
    replaceFile: true
    dataIsFile: true
    sourceFile: '$(Build.ArtifactStagingDirectory)/releasenotes.md '
    message: 'Update from Release - $(Release.ReleaseName)'
    tagRepo: false
    gitname: 'Azure Pipelines'
    gitemail: 'azurepipelines@XXXXXX.com'
    useAgentToken: true
    fixSpaces: true
    insertLinefeed: true
    prependEntryToOrderFile: true

I keep getting an error on every occasion through the standard wiki 
"Wiki page ‘/Release Notes/DevOps Release Notes’ could not be found. Ensure that the path of the page is correct and the page exists."

However if I go to the git directory the files are being created as should be (with .md extensions)

What could be the problem?

**Comment by ShahSwapnil** [comment]
I am running into this issue. how did you resolve it?

**Comment by rfennell** [comment]
If this is an intermittent error it is not usually to do with this uploader task, it is usually seen when the previous generate release notes task has failed so the file to upload does not exist.

So when you see this error  check the logs of the prior step.

if it is not intermittent it is usually due to typo in the file path

**Comment by ShahSwapnil** [comment]
Hi Richard, 

Initially I was trying to place the page in "Release-Notes\Core.md" for some reason this wouldn't work. Once I removed the hypen (space) from the "Release-Notes" -> "ReleaseNotes\Core.md" started working. The ReleaseNotes doesn't have a space when it's rendered by ADO but that's a minor thing. 

Btw the extension is fantastic, thank you for creating it and maintaining it. 

Thank you for the quick response.
