### ISSUE TITLE
Release notes generator is not fetching work items from the other repositories

### ISSUE THREAD

**Issue by Karthickvr** [rfennell/AzurePipelines#1017]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

```bash
Hi there,

Thanks for this awesome extension.
Btw, we have the scenario of having multiple repos and using the multi stage yaml pipeline in separate repo for building the latest artifacts from the above said different repos.

The problem is that the release notes generator extention is not fetching the related work items from all these multiple repos but it is only retrieving the work items from the current release management repo where the multi stage yaml pipeline is running.

Would it be possible to pass the repo names list to the release generator extension, that will list all the work items related to that repo and that branch rather only retrieving from the current working branch?

Appreciate your appropriate response and much appreciated.

Thanks,
Rishi
```

### Repo Steps

```bash
Run release notes generator and wiki update extension from the separate multi stage yaml pipeline in other Repository, which is referring to the other multiple repositories as a repo source to build all these components and expected to fetch related work items for those components from these repos but it didn't?
```

### Expected Behavior

```bash
Work items retrieved for all these repositories specified.
```

**Comment by rfennell** [comment]
This is very similar to [this discussion](https://github.com/rfennell/AzurePipelines/discussions/1016). To quote that answer

> Not sure if it 100% of the answer, but have a look at the new consumedArtifacts object. This lists all the consumed resources/artifacts for a pipeline. You can loop across this and it will give items such as the resource names, version and source etc.
> 
> However, it won't dig down to the WI/CS details for a resource. That would require more API calls and we would be getting to a regression nightmare.
> 
> I would suggest the best option might be to
> 
> - Use the release note task in the pipeline that builds the resources, publishing the generate release notes to a WIKI - I have a task for that
> - In the main pipeline use the consumedArtifacts to build a URL to point to the previously generated WIKI page and against publish the release notes to the WIKI
>

**Comment by Karthickvr** [comment]
Hi Richard, 

Thanks for the quick response.  Unfortunately we have many repos (components) to generate release notes and we have some yaml templates, scripts used in this pipeline is have to be checked-in and duplicated in all repos for generating release notes in all repo.  We didnt want to rebuild each repo again for release notes, however it is hard to figure out the usage of consumedArtifacts option without any documentation and examples about that.  The convenient option we are looking  for is to pass on the repository id/name in the main multistage yaml file, where that could fetches out the work item changed to generate the releasenotes file.

Appreciate your appropriate understanding and this feature would be greatly helpful :)

Regards,
Karthick

**Comment by rfennell** [comment]
When I built the new feature it was tested using the following YAML, this just dumped out possible consumed artifact properies

```
# Build {{buildDetails.buildNumber}}
* **Branch**: {{buildDetails.sourceBranch}}
* **Tags**: {{buildDetails.tags}}
* **Completed**: {{buildDetails.finishTime}}
* **Previous Build**: {{compareBuildDetails.buildNumber}}
 
## Global list of ConsumedArtifacts ({{consumedArtifacts.length}})
{{#forEach consumedArtifacts}}
* {{json this}} 
{{/forEach}}

## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
*  **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
{{/forEach}}

```

**Comment by Karthickvr** [comment]
Thanks Richard.  I could get the list of consumedartifacts from the list of resources specified in the yaml pipeline, but that didn't help to retrieve work items from the related build of other repositories unfortunately.  Would be good to have a param/variable array in the release notes extention to list the repos names or ids or reference to the resource name provided in the yaml file, which will retrieve the related work items of the particular repos list and filtered between the last and current pipeline.  Thanks

**Comment by rfennell** [comment]
There will need to be code change to get the extra information to enrich the consumed artifacts. I have have to see what is possible

**Comment by Karthickvr** [comment]
Thanks for adding this feature.  When I tried the below code in my template, get the error 'length is not defined' as below, where there is no length attribute is looked in the code:

{{#forEach consumedArtifacts}}
 {{#forEach this.workitems}}
    {{#with fields}}
        {{#if (eq (get 'System.WorkItemType' this) 'User Story')}}
        - #{{../id}} {{lookup this 'System.Title'}}  
        {{/if}}
    {{/with}} 
 {{/forEach}}  
{{/forEach}}

![image](https://user-images.githubusercontent.com/14084096/121794519-f2f2fb80-cc5c-11eb-82c9-1cfc69a994af.png)

Wonder if there is an inner error in the releasenotes generation and throws out to the client?

Appreciate your appropriate response.  Thanks

**Comment by rfennell** [comment]
The commits and workitems properties only exist if I can populate then. Hence you need to wrapper calling them in a {{#if }} guard as I showed in my sample.

**Comment by Karthickvr** [comment]
Ok, so the workitems and commits list population for the consumedArtifacts is not done yet?  No worries, will wait for that to be released to test and apply in our pipelines. Cheers

**Comment by rfennell** [comment]
No the work is done and live.

If an artefact is an Azure DevOps pipeline artefact an attempt is made to load the details of the CS and WI. You should see a log entry to this effect.

This has been tested against multistage YAML pipelines that consume a mixture of pipeline and repo based artefacts. I am using handlebars if guards around the commits and workitems properties in the template as they only exist for pipeline artefacts where the data can be retrieved

**Comment by Karthickvr** [comment]
Ok, thanks, I'll try with the pipeline artefacts. But in our case, the
artefacts is 4 repositories.

Having one build all multistage pipeline to build all these repositories
and generating release notes with lists of work items and commits for all
these repositories.

Will that work yet to be released?

Cheers,
Karthick

**Comment by rfennell** [comment]
The new logic is 
1.  Get a list consumed artefacts (with the details available on the basic API call)
2. If a pipeline artefact
    - Yes - get the commits and WI associated with the pipeline run referenced as an artefact
    - No - do nothing extra beyond the basic data

**Comment by gchorkawy** [comment]
hi @rfennell, I found that the `consumedArtifacts` object contains only data from currently referenced pipeline artefacts. I was expecting that with the `checkStage: true` option, the `consumedArtifacts` object would contain data from all the referenced pipeline artefacts since the last time the stage was run successfully.

Is this something that is supported? Or can support be added for this use case?

Example
---

To illustrate the situation a bit, consider the following:
- PipelineA 0.0.0 advanced to prod stage with referenced pipeline artefacts:
   - PipelineB 0.0.0
   - PipelineC 0.0.0

- PipelineA 0.0.12 advanced to prod stage with referenced pipeline artefacts:
  - PipelineB 0.0.5
  - PipelineC 0.0.7

I was expecting:
`consumedArtifacts` would contain all WI and commits data for PipelineB from 0.0.0 to 0.0.5, and data for PipelineC from 0.0.0 to 0.0.7.

Actual:
`consumedArtifacts` contains WI and commits data for PipelineB from 0.0.5, and data for PipelineC from 0.0.7.

**Comment by rfennell** [comment]
Currently the behaviour you describe is by design. But I also have the same requirement you have, so I  was considering adding that as a feature. I am just trying to work out how best to implement it.

**Comment by rfennell** [comment]
I have created a new Issue to track this new feature
