### ISSUE TITLE
Azure Extension: Generate Release Notes for WorkItems returned by query

### ISSUE THREAD

**Issue by cluen** [rfennell/AzurePipelines#1037]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

We use the extension in our release pipeline to get release notes per release! All work's great! Many thanks this! 
Our releases are normally terminated to an end of a quartal. Sometimes we need Release Notes for a different timespan (i.e. the changes between 2021-04-30 and now?

### Describe the solution you'd like

It would be really cool to have a page in azure devops (i.e. sidebar menu: Boards / Release Notes) where you select a auery from Azure Devops Queries. And a button to start the generation of release notes for the work items returned by the selected query. The used handlebar template could be pasted to an textarea input (nice to have: combobox to select a handlebar template from file)

**Comment by rfennell** [comment]
That is a very different product, the core is similar, but there would need to be a lot of new work to swap to a WIQ based system as opposed to the current one linked to builds. 

I don't think it will be something I will be attempting, but I will leave it on the backlog. maybe someone else will pick it up.

However, can I draw your attention to my [command line tester for this extension](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/V3/testconsole). I use it in the development of code and templates. One nice feature is it can be used to inject a 'to' and 'from' pair of build run IDs to generate  a list of changes between the runs. This could get you cloe to what you asked for,

**Comment by rfennell** [comment]
Worked out a way to add this feature, should be completed soon

**Comment by rfennell** [comment]
This feature is available in 3.71.x

There is a new parameter where you can provide the WHERE part of the WIQL. This should be edited toselect the WI you required.

```
 - task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes-DEV1.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@3
    inputs:
      wiqlWhereClause: '[System.TeamProject] = "GitHub" and [System.WorkItemType] = "Product Backlog Item"'
```
Note you cannot use `@project`, `@currentiteration` or `@me`, but `@today` is ok

The results of this WIQL will be available in a new independent template array `queryWorkItems` i.e. it is completely separate from all the other WI arrays.

```
# WIQL list of WI ({{queryWorkItems.length}})
{{#forEach queryWorkItems}}
   *  **{{this.id}}** {{lookup this.fields 'System.Title'}}
{{/forEach}}
```

**Comment by jamers99** [comment]
@rfennell so if I understand this right, this is **not** a filtered down version of this.workItems? Bummer, how would you recommend filtering down the list of work items? I need only the work items that have a release notes field specified. Would you recommend if statements in the template?

**Comment by rfennell** [comment]
You are correct that WQL return is a separate list.

To filter any array of WI you are right you can either
- Use handlebar {{if}} statements
- A custom javascript module that filters the array [a bit like this](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/each_with_sort_by_field.js)

**Comment by jamers99** [comment]
Awesome, thanks! 
Great product and support BTW!
