### ISSUE TITLE
Version PowerShell task fails if naming clash exists with Configuration module

### ISSUE THREAD

**Issue by Sarkimedes** [rfennell/AzurePipelines#1042]
### Azure DevOps Extensions

Manifest Versioning

### Platform

Azure DevOps Services

### Describe the bug

```bash
The Version Powershell task relies on a module named Configuration. If another module exists on the machine which defines some of the same commands, execution of the task fails as Install-Module does not allow modules to be installed with name clashes unless -AllowClobber is specified.
```

### Repo Steps

```bash
1. Install PSDepend on a build server from the PowerShell gallery
2. Attempt to run a build which versions a PowerShell file using the task
```

### Expected Behavior

```bash
Either: 
- The task should run in this situation.
Or:
- There should be a flag I can set on the task to allow me to override the default behaviour of Install-Module when it encounters a naming clash.
```

### Logging Information

```bash
Excerpt of Azure Pipelines build logs:

##[debug]00:00:10.4205656 PowerShell Script 'PSModule' Function 'Install-Package' returns null.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]PackageManagement\Install-Package : The following commands are already available on this system:'Add-MetadataConverter,ConvertFrom-Metadata,ConvertTo-Metadata,Export-Metadata,Get-ManifestValue,Import-Metadata,Update-Manifest'. This module 'Metadata' may override the existing commands. If you still want to install this module 'Metadata', use -AllowClobber parameter.
##[debug]At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
##[debug]+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
##[debug]+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],     Exception
##[debug]    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack    ageManagement.Cmdlets.InstallPackage
##[debug] 
##[debug]Script stack trace:
##[debug]at Install-Module<Process>, C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1: line 9711
##[debug]at <ScriptBlock>, E:\Agent\_work\_tasks\VersionPowerShellModule_036278fe-8a47-426b-b5b3-bef05334db00\2.29.16\Update-PowerShellModuleVersion.ps1: line 89
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Exception: The following commands are already available on this system:'Add-MetadataConverter,ConvertFrom-Metadata,ConvertTo-Metadata,Export-Metadata,Get-ManifestValue,Import-Metadata,Update-Manifest'. This module 'Metadata' may override the existing commands. If you still want to install this module 'Metadata', use -AllowClobber parameter.
##[error]The following commands are already available on this system:'Add-MetadataConverter,ConvertFrom-Metadata,ConvertTo-Metadata,Export-Metadata,Get-ManifestValue,Import-Metadata,Update-Manifest'. This module 'Metadata' may override the existing commands. If you still want to install this module 'Metadata', use -AllowClobber parameter.
```

**Comment by rfennell** [comment]
I will have a look at this when I get a chance and sort out a fix

**Comment by Sarkimedes** [comment]
Quick note on repro steps: It looks like there was an older version of the Configuration module already installed on my build server which was the source of the name clash, so repro steps should read:

1. Install Configuration 1.3.1 or lower from the PowerShell gallery
2. Attempt to run a build which versions a PowerShell file using the task

**Comment by rfennell** [comment]
I have a look at this and think there is a bigger issue than loading the `configuration` module. 

From my tests, I find when I use a Microsoft hosted build agent the task works as expected, but fails on a locally hosted agent in my development PC. However,  I don't get the error you see, mine fails earlier with issues loading `PowerShellGet`, I think due to having PowerShell 7 on my machine

> ##[debug]Finding the latest version of the Configuration module on the PSGallery
> VERBOSE: Loading module from path 'C:\program files\powershell\7\Modules\PackageManagement\PackageManagement.psm1'.
> VERBOSE: Populating RepositorySourceLocation property for module PackageManagement.
> VERBOSE: Loading module from path 'C:\Program 
> Files\WindowsPowerShell\Modules\PackageManagement\1.4.5\PackageManagement.psm1'.
> VERBOSE: Loading module from path 'C:\program files\powershell\7\Modules\PackageManagement\PackageManagement.psd1'.
> VERBOSE: Loading 'FormatsToProcess' from path 'C:\program 
> files\powershell\7\Modules\PackageManagement\PackageManagement.format.ps1xml'.
> VERBOSE: Loading module from path 'C:\program files\powershell\7\Modules\PackageManagement\PackageManagement.psm1'.
> ##[debug]Caught exception from task script.
> ##[debug]Error record:
> ##[debug]C:\agents\richardfennell\_work\_tasks\VersionPowerShellModule_036278fe-8a47-426b-b5b3-bef05334db00\2.29.16\Update-PowerShellModuleVersion.ps1 : The 'Find-Module' command was found in the module 'PowerShellGet', but the module could not be loaded. For more information, run 'Import-Module PowerShellGet'.
> ##[debug]At line:1 char:1
> ##[debug]+ . 'C:\agents\richardfennell\_work\_tasks\VersionPowerShellModule_0362 ...
> ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ##[debug]    + CategoryInfo          : ObjectNotFound: (Find-Module:String) [Update-PowerShellModuleVersion.ps1], CommandNotFou    ndException
> ##[debug]    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule,Update-PowerShellModuleVersion.ps1
> ##[debug] 
> ##[debug]Script stack trace:
> ##[debug]at <ScriptBlock>, C:\agents\richardfennell\_work\_tasks\VersionPowerShellModule_036278fe-8a47-426b-b5b3-bef05334db00\2.29.16\Update-PowerShellModuleVersion.ps1: line 86
> ##[debug]at <ScriptBlock>, <No file>: line 1
> ##[debug]at <ScriptBlock>, <No file>: line 22
> ##[debug]at <ScriptBlock>, <No file>: line 18
> ##[debug]at <ScriptBlock>, <No file>: line 1
> ##[debug]Exception:
> ##[debug]System.Management.Automation.CommandNotFoundException: The 'Find-Module' command was found in the module 'PowerShellGet', but the module could not be loaded. For more information, run 'Import-Module PowerShellGet'. ---> System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'C:\program files\powershell\7\Modules\PackageManagement\fullclr\Microsoft.PackageManagement.dll' was not loaded because no valid module file was found in any module directory.
> 

Before I try to sort this, I think it is worth looping in @ChrisLGardner, who help to author this task, to see if he has any suggestions to manage these PS & module version issues

**Comment by ChrisLGardner** [comment]
I'll do some testing tomorrow to see if we can handle the case where another version of Configuration exists locally already. It might be a better idea to save the module in the task directly at run time then import that directly.

Not sure what we can do about that PowerShellGet error, might be worth trying to open a PS 7 session and import the module to see what error it actually gives you.

**Comment by rfennell** [comment]
Done some research...

- When a pipeline runs a PowerShell3 based task it runs it in a 5.1.19041.1023 version PowerShell session
- Strangely on my PC (with PowerShell 7 installed, and whatever versions Windows 10 carries)
   - If I run the script directly from a 5.1.19041.1023 PowerShell prompt it works. It is loading the PowerShellGet module from `C:\Program Files\WindowsPowerShell\Modules`
   - However, if I run it within an Azure Pipeline, on an agent on the same PC, the loading of the PowerShellGet module fails (it tries to use `C:\program files\powershell\7\Modules` when run within a pipeline)
- I have managed to do a local 'fix' the problem by
   - Removing the logic to load PowerShellGet
   - Removing the logic to try to find newer versions of the Configuration module
   - Force the loading of the version of the configuration module shipped in the tasks i.e. `Import-Module "$PSScriptRoot\1.3.0\Configuration.psd1" -force`

So a couple of questions @ChrisLGardner  

- Is do you think this is an acceptable solution?
- It is interesting that in the past few days I have seen a number of problems with loading modules from PSGallery. Have there been any changes, or have they removed old packages that you are aware of?

**Comment by ChrisLGardner** [comment]
The gallery has been a bit flaky recently from what I've heard from various folks, mostly slowness but some people were reporting it being unavailable to them and working for others.

I think that solution works fine but we should probably update the version of the module we're shipping with the task (either manually or at build time) just to ensure we keep on top of any bug fixes that get shipped out. I don't think it changes often so might be best to just do it manually for now (last update to the module was earlier this month, previous one was 6 months ago).
