### ISSUE TITLE
Ability to split build notes out per repo in a project

### ISSUE THREAD

**Issue by kilasuit** [rfennell/AzurePipelines#1059]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

As a user working in an Azure DevOps project with multiple repositories & multiple builds per repository, 
I would like to group builds under a repo specific path in the wiki,
As so that I can better see what build relates to which repo

### Describe the solution you'd like

Ability to ensure that the release notes for builds can be grouped per repository for easier viewing

**Comment by rfennell** [comment]
Does the `consumedartfacts` not help for this use case? 

This gives you an array of consumed artefacts for a YAML  pipeline, each entry with their associated WI and CS
