### ISSUE TITLE
How do I correlate pullRequest and workItems ?

### ISSUE THREAD

**Issue by reemak** [rfennell/AzurePipelines#1067]
**Not Working** 

## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
* **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
* Associated Work Items
{{#forEach this.workitems}}
   {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
   {{/with}}
{{/forEach}}
{{/forEach}}

I want to show : 
- Pull Request 
- - Associated Work item to pull request

Can someone please help

**Comment by rfennell** [comment]
This is the sample as provided in the [wiki](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task)

```
## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
* **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
* Associated Work Items
{{#forEach this.associatedWorkitems}}
   {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
   {{/with}}
{{/forEach}}
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
{{#forEach this.associatedCommits}}
    - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
{{/forEach}}
{{/forEach}}
```

**Comment by reemak** [comment]
This does not work 

associatedWorkitems does not show anything

**Comment by rfennell** [comment]
I have just retested this template fragment

```
## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
* **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
* Associated Work Items
{{#forEach this.associatedWorkitems}}
   {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}} 
   {{/with}}
{{/forEach}}
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
{{#forEach this.associatedCommits}}
    - [{{truncate this.commitId 7}}]({{this.remoteUrl}}) - {{get_only_message_firstline this.comment}}
    {{#with (lookup_a_pullrequest_by_merge_commit ../../inDirectlyAssociatedPullRequests  this.commitId)}}
      - Associated PR {{this.pullRequestId}} - {{this.title}} 
    {{/with}}
{{/forEach}}
{{/forEach}}
```

It gives the following output

![image](https://user-images.githubusercontent.com/324718/130762937-6ab64de8-8bf3-4a13-ba8c-64d9abc85e88.png)

So just as expected.

If I use the task parameters to dump the raw JSON data used by the Handlebars template as a file

```
    "dumpPayloadToFile": "true",
    "dumpPayloadFileName": "payload.json",
````

I get the following block of `pullRequest` data

>     "pullRequests": [{
>             "repository": {
>                 "id": "bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59",
>                 "name": "VSTSBuildTaskValidation",
>                 "url": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59",
>                 "project": {
>                     "id": "670b3a60-2021-47ab-a88b-d76ebd888a2f",
>                     "name": "GitHub",
>                     "state": "unchanged",
>                     "visibility": 0,
>                     "lastUpdateTime": "0001-01-01T00:01:15.000Z"
>                 }
>             },
>             "pullRequestId": 34,
>             "codeReviewId": 34,
>             "status": 3,
>             "createdBy": {
>                 "displayName": "Richard Fennell (Work MSA)",
>                 "url": "https://spsprodeus24.vssps.visualstudio.com/Ac0efb61e-a937-42a0-9658-649757d55d46/_apis/Identities/b1fce0e9-fbf4-4202-bc09-a290def3e98b",
>                 "_links": {
>                     "avatar": {
>                         "href": "https://dev.azure.com/richardfennell/_apis/GraphProfile/MemberAvatars/aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj"
>                     }
>                 },
>                 "id": "b1fce0e9-fbf4-4202-bc09-a290def3e98b",
>                 "uniqueName": "bm-richard.fennell@outlook.com",
>                 "imageUrl": "https://dev.azure.com/richardfennell/_api/_common/identityImage?id=b1fce0e9-fbf4-4202-bc09-a290def3e98b",
>                 "descriptor": "aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj"
>             },
>             "creationDate": "2021-08-25T08:53:25.953Z",
>             "closedDate": "2021-08-25T08:53:36.125Z",
>             "title": "Updated readme.md",
>             "description": "Updated readme.md\n\n#13",
>             "sourceRefName": "refs/heads/prtest",
>             "targetRefName": "refs/heads/master",
>             "mergeStatus": 3,
>             "isDraft": false,
>             "mergeId": "12de3e70-c325-4ce9-b7be-35773ef8cf24",
>             "lastMergeSourceCommit": {
>                 "commitId": "f68cf80106cc273a949dcc9ebb794fa1b9af4dc6",
>                 "url": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6"
>             },
>             "lastMergeTargetCommit": {
>                 "commitId": "7d854a5110823b9a352b4547c65aedccfcbd513c",
>                 "url": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/7d854a5110823b9a352b4547c65aedccfcbd513c"
>             },
>             "lastMergeCommit": {
>                 "commitId": "ae2fd44ad6d86242d0340f0f263a8f118ed870c8",
>                 "url": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/ae2fd44ad6d86242d0340f0f263a8f118ed870c8"
>             },
>             "reviewers": [],
>             "url": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/pullRequests/34",
>             "_links": {
>                 "self": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/pullRequests/34"
>                 },
>                 "repository": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59"
>                 },
>                 "workItems": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/pullRequests/34/workitems"
>                 },
>                 "sourceBranch": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/refs/heads/prtest"
>                 },
>                 "targetBranch": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/refs/heads/master"
>                 },
>                 "statuses": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/pullRequests/34/statuses"
>                 },
>                 "sourceCommit": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6"
>                 },
>                 "targetCommit": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/7d854a5110823b9a352b4547c65aedccfcbd513c"
>                 },
>                 "mergeCommit": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/ae2fd44ad6d86242d0340f0f263a8f118ed870c8"
>                 },
>                 "createdBy": {
>                     "href": "https://spsprodeus24.vssps.visualstudio.com/Ac0efb61e-a937-42a0-9658-649757d55d46/_apis/Identities/b1fce0e9-fbf4-4202-bc09-a290def3e98b"
>                 },
>                 "iterations": {
>                     "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/pullRequests/34/iterations"
>                 }
>             },
>             "completionOptions": {
>                 "mergeCommitMessage": "Merged PR 34: Updated readme.md\n\nUpdated readme.md\n\n#13\n\nRelated work items: #13",
>                 "deleteSourceBranch": true,
>                 "squashMerge": true,
>                 "mergeStrategy": 2,
>                 "autoCompleteIgnoreConfigIds": [8]
>             },
>             "supportsIterations": true,
>             "completionQueueTime": "2021-08-25T08:53:34.794Z",
>             "labels": [],
>             "associatedWorkitems": [{
>                     "id": 13,
>                     "url": "https://dev.azure.com/richardfennell/_apis/wit/workItems/13"
>                 }
>             ],
>             "associatedCommits": [{
>                     "treeId": "62eb6a77adaf874af1816a2c272dcf9956b2c926",
>                     "commitId": "f68cf80106cc273a949dcc9ebb794fa1b9af4dc6",
>                     "author": {
>                         "name": "Richard Fennell (Work MSA)",
>                         "email": "bm-richard.fennell@outlook.com",
>                         "date": "2021-08-25T08:53:13.000Z",
>                         "imageUrl": "https://dev.azure.com/richardfennell/_apis/GraphProfile/MemberAvatars/aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj"
>                     },
>                     "committer": {
>                         "name": "Richard Fennell (Work MSA)",
>                         "email": "bm-richard.fennell@outlook.com",
>                         "date": "2021-08-25T08:53:13.000Z",
>                         "imageUrl": "https://dev.azure.com/richardfennell/_apis/GraphProfile/MemberAvatars/aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj"
>                     },
>                     "comment": "Updated readme.md\n\n#13",
>                     "parents": ["7d854a5110823b9a352b4547c65aedccfcbd513c"],
>                     "url": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6",
>                     "remoteUrl": "https://dev.azure.com/richardfennell/GitHub/_git/VSTSBuildTaskValidation/commit/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6",
>                     "_links": {
>                         "self": {
>                             "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6"
>                         },
>                         "repository": {
>                             "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59"
>                         },
>                         "web": {
>                             "href": "https://dev.azure.com/richardfennell/GitHub/_git/VSTSBuildTaskValidation/commit/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6"
>                         },
>                         "changes": {
>                             "href": "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/f68cf80106cc273a949dcc9ebb794fa1b9af4dc6/changes"
>                         }
>                     },
>                     "push": {
>                         "pushedBy": {
>                             "displayName": "Richard Fennell (Work MSA)",
>                             "url": "https://spsprodeus24.vssps.visualstudio.com/Ac0efb61e-a937-42a0-9658-649757d55d46/_apis/Identities/b1fce0e9-fbf4-4202-bc09-a290def3e98b",
>                             "_links": {
>                                 "avatar": {
>                                     "href": "https://dev.azure.com/richardfennell/_apis/GraphProfile/MemberAvatars/aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj"
>                                 }
>                             },
>                             "id": "b1fce0e9-fbf4-4202-bc09-a290def3e98b",
>                             "uniqueName": "bm-richard.fennell@outlook.com",
>                             "imageUrl": "https://dev.azure.com/richardfennell/_api/_common/identityImage?id=b1fce0e9-fbf4-4202-bc09-a290def3e98b",
>                             "descriptor": "aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj"
>                         },
>                         "pushId": 8877,
>                         "date": "2021-08-25T08:53:14.016Z"
>                     }
>                 }
>             ]
>         }
>     ],
> 

This contains the associations I expect.

All I can assume this that your PR merge policy is not adding the required associations. Not sure why my test is fairly simple and straightforward 

1. Open Azure DevOps in a browser
2. Create a branch off main
2. Make some commits (with an associated WI)
3. Create a PR (it seems the associated WI)
4. Complete the PR (I this test it was a squash merge, but I have also tested merge commits)
5. The build runs on the merge to main

All I can suggest is look at your raw JSON payload and see if there is a difference, also what is your PR merge strategy?

**Comment by vaishnav-canarys** [comment]
I am having the same issue, i am running the release notes task on Azure devops server 2019.

Template Output which i am giving below

## Associated Pull Requests (2)
* **[47]( http://devopserver/tfs/erviceInstaller.cs)/pullRequest/47)** Updated test
* Associated Work Items
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
     - [f2bbb89](http://devopserver/tfs/erviceInstaller.cs) Updated test
* **[46](http://devopserver/tfs/erviceInstaller.cs)/pullRequest/46)** Updated DirectServiceInstaller.cs
* Associated Work Items
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
    - [f2bbb89](http://devopserver/tfs/erviceInstaller.cs)

**Comment by rfennell** [comment]
The task has fou d two PRs associated with the building, both linked to the commit F2bbb89. Only WI associated with these commission will be picked up.
