### ISSUE TITLE
Not able to get the difference work item from last release to current release if we manually linked the Work items with latest build number.

### ISSUE THREAD

**Issue by santhoshmp43** [rfennell/AzurePipelines#1103]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

Not able to get the difference work item from last release to current release if we manually linked the Work items with latest build number.

“The data source for the generated Release Notes is the Azure DevOps REST API's comparison calls that are also used by the Azure DevOps UI to show the associated Work items and commit/changesets between two builds/releases. Hence this task should generate the same list of work items and commits/changesets as the Azure DevOps UI, though it attempts to enrich this core data with extra information.”

### Repo Steps

...

**Comment by SWarnberg** [comment]
To give more details into this issue, let me elaborate. The API [Get Work Items Between Builds](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get-work-items-between-builds?view=azure-devops-rest-6.0) is not returning manually linked work items, whereas the API [Get Build Work Items Refs](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get-build-work-items-refs?view=azure-devops-rest-6.0) returns those work items, for each build.
One option to give support for this request is to add a new parameter to the task and, when set, the **Get Build Work Items Refs** is used instead.

**Comment by santhoshmp43** [comment]
Hi Richard

Thank You for your precious time,

Answer to your comments ,
* Does this match what is needed?
	yes it will match our requirement as @SWarnberg mentioned in the above comments, So a parameter by default off where we can choose to generate manually linked work items also along with regular auto linked work Items by Azure.
* Would it be better to place these 'manually linked' WI in separate array to the existing workitems array?
	No , I guess we can club both manually linked and auto linked based on some parameter is good idea , instead of separate array.

Note : 
I'm using Version 3 of this tasks , I have written an MD Template file to fetch the work items between releases .

**Comment by mhemp2021** [comment]
Hi @rfennell 

I appreciate your help.

After testing this this with a live release and build, it still did not work for me.

I am using Version 3.72.2 of Generate Release Notes.

I have a YAML Build which doesn't have stages defined (hence using ___default) and I am using the Generate Release Notes in a Classic Release pipeline to pickup the release notes from the build.  
I have attached a bug manually to the build, and expected it to be added to the release notes.
I have the "Check for Manually Linked WI" checked.
Still no luck.
In the log, I can't see any mention of it checking for Manual Linked Work items....

What am I missing?
Do i need stages?
Can I use the "WIQL Where Clause" instead to bring in the work items i need from a query or is that just filtering the already found work items?

**Comment by rfennell** [comment]
Could you send we a debug log so I can see what is happening. We should see the new manual check running and we can compare the number of WI found by each call prior to the removal of duplicates. 

As you mention you could use the new wiql query. The builds a separate list of WI to main list.

See https://blogs.blackmarble.co.uk/rfennell/2021/10/30/new-features-for-my-azure-devops-release-notes-extension/

**Comment by mhemp2021** [comment]
Hi Richard,

I've sent you an email.

Cheers

**Comment by rfennell** [comment]
OK there are a few things going on here

**Code Path and the manually added WI fix**
I can see from your log that you are using the default fix to bypass API limits #349 

```
2021-11-04T10:08:46.8747392Z Checking what commits and workitems have changed from [XXX-20211104-4][ID 803] => [XXX-20211104-5] [ID 804]
2021-11-04T10:08:46.8748005Z Defaulting on the workaround for build API limitation (see issue #349 set 'ReleaseNotes.Fix349=false' to disable)
2021-11-04T10:08:46.8748529Z Using workaround for build API limitation (see issue #349)
2021-11-04T10:08:46.8749689Z Processing commits found
```

This code path does not make use of the new 'checkForManuallyLinkedWI: true' parameter as it should not need it, the #349 fix already makes calls based on the build. However, if you want to test this theory set a build variable `ReleaseNotes.Fix349=false` (the default is on), or make a change in your local runner config file. This will use the code path that does not use the fix and hence use the new feature.

**Direct API call**
You mention that you can't see the WI listed in an API call

```
/_apis/build/builds/804/workitems?api-version=6.0&$top=10000
```
If this is the case, then I am not sure what we can do, as this is the call I am making to get the associations

**Comment by mhemp2021** [comment]
Thanks for the help @rfennell 

I can't turn ReleaseNotes.Fix349=false as I am using the Classic Release Pipeline.  Is there a way of doing this with Classic? 

Also, you misread my comment about the api call --> I **CAN** see the manually linked work item in that API call.  I am not sure if you are using this call, or doing it some other way... but that call is definately picking up the work item (#5235)

**Comment by mhemp2021** [comment]
Hi @rfennell 

I tried with ReleaseNotes.Fix349 = false and it is **now working**!

So this means I am limited to 200 works items per build in the release - correct?

**Comment by rfennell** [comment]
Looks like I need to re investigate the fix349 code.

**Comment by rfennell** [comment]
I have revised (and simplified) the calls to the new manual wi check to make sure all code paths calls them even when the fix349 code is used.

If you want to try it locally it is in the PR #1135, I will get it pushed through the release pipeline

**Comment by rfennell** [comment]
It is shipped in 3.74.3

**Comment by mhemp2021** [comment]
Thanks @rfennell 
I will try it out today.

**Comment by mhemp2021** [comment]
@rfennell 

Ok, tried it out - yes it's working now with and without fix349 turned on.

Thanks!
