### ISSUE TITLE
XplatGenerateReleaseNotes@3 - Unable to change time zone of displayed date

### ISSUE THREAD

**Issue by ddprince-yaksa** [rfennell/AzurePipelines#1108]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Extension Version

3

### Describe the bug

Under the handlebar template, we are using the moment helper, which allows us to format the date output to a specific way, like this: {{moment buildDetails.lastChangedDate zone="(clientTimeZone)" format="YYYY/MM/DD HH:mm ZZ"}}. 

Unfortunately, I tried to use it like defined in the documentation and even though I changed the zone to something else, it always stays in UTC.

### Repo Steps

Use {{moment buildDetails.lastChangedDate zone="-4:00" format="YYYY/MM/DD HH:mm ZZ"}} or any other dates in your handlebars template. The output will be in UTC.

### Expected Behavior

```bash
Output should be in the specified time zone.
```

**Comment by rfennell** [comment]
Have you tried using this [custom module sample](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/date_formatter.js)

**Comment by rfennell** [comment]
The date_formatter is what you make it as it is custom extension, edit it to do what you require

```js
// A Handlebars Helper to allow bespoke date formatting
// Azure DevOps returns dates in the format "Mon Aug 09 2021 08:31:02 GMT+0000 (Coordinated Universal Time)"
// This functions swaps them to a local format e.g."August 09, 2021 - 08:31"
/* Usage
    {{date_formatter buildDetails.startTime}
*/
module.exports = {date_formatter(theDate) {
    return theDate.toLocaleString();
}};
```
