### ISSUE TITLE
This task uses Node 6 execution handler, which will be deprecated soon

### ISSUE THREAD

**Issue by DanRogers99** [rfennell/AzurePipelines#1137]
### Azure DevOps Extensions

Manifest Versioning

### Platform

Azure DevOps Services

### Describe the bug

This task uses Node 6 execution handler, which will be deprecated soon. use the Node 10 handler instead.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md
### Repo Steps

parameters:
- name: versionNumber # name of the parameter; required
  default: '0.0'

steps:
- task: PowerShell@2
  displayName: Set the name of the build (i.e. the Build.BuildNumber)
  inputs:
    targetType: 'inline'
    script: |
      [string] $buildName = "${{ parameters.versionNumber }}"
      Write-Host "Setting the name of the build to '$buildName'."
      Write-Host "##vso[build.updatebuildnumber]$buildName"
- task: VersionDotNetCoreAssemblies@2
  displayName: 'Patch DotNetCore versions'
  inputs: 
     Path: '$(Build.SourcesDirectory)'
     VersionNumber: '${{ parameters.versionNumber }}'
     Injectversion: False
     VersionRegex: '\d+\.\d+\.\d+'
     FilenamePattern: '.csproj'
     OutputVersion: OutputedVersion
     AddDefault: true

**Comment by rfennell** [comment]
Fair point I should review my Node version on am my tasks

**Comment by rfennell** [comment]
All have been updated bar the WIKIPDF tasks, this will be released soon using the new cross platform .NET  6 based tools via PR #1141 , but I am waiting for an update of the command line tool it uses
