### ISSUE TITLE
Not able to display custom linked work item

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#1140]
### Discussed in https://github.com/rfennell/AzurePipelines/discussions/1138

<div type='discussions-op-text'>

<sup>Originally posted by **JaydeepUniverse** November 12, 2021</sup>
Generally in the work item we can see 2 or 3 types of linked work items: Parent, Child, Related
and in the related work item we have diff. kind of work item types like  - bug, task, test plan, test case

We have created custom linked work item type called: Tested By for test plan and test case Ex,

![image](https://user-images.githubusercontent.com/25937808/141428445-15885516-1743-452b-9bb8-0f1cd0d7edde.png)

To get the parent work item details we're using below code
```
{{#forEach this.relations}}
    {{#if (contains this.attributes.name 'Parent')}} 
        {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}} 
            #{{this.id}} 
        {{/with}} 
    {{/if}} 
{{/forEach}}
```

and similarly I created another code for Tested By as below, But then issue is those tested by linked work items are not showing up
```
{{#forEach this.relations}}
    {{#if (contains this.attributes.name 'Tested By')}} 
        {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}} 
            #{{this.id}} 
        {{/with}} 
    {{/if}} 
{{/forEach}}
```

We have few work items for which "Tested By" linked work item is not implemented yet, so to cross check other behavior I have noticed is that, I have created new code to get "Related" work items, what I get is related work items but other work items which are type of "Test case" or "Test plan" are not coming in the list
```
{{#forEach this.relations}}
    {{#if (contains this.attributes.name 'Related')}} 
        {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}} 
            #{{this.id}} 
        {{/with}} 
    {{/if}} 
{{/forEach}}
```

Kindly advise how we can resolve this?

Let me know if any other details are needed

Thanks,
Jaydeep</div>

**Comment by rfennell** [comment]
Adding a new array object the template can use that lists the `tested` related items for a WI

**Comment by JaydeepUniverse** [comment]
@rfennell any ETA when this will be implemented?

**Comment by rfennell** [comment]
It is on the backlog as a future enhancement, but I have no plans to implement it in the short term. Happy to consider PR if someone else has time
