### ISSUE TITLE
.Net Core/Android Version steps throw on Windows 10 as of 11/12/2021 update 

### ISSUE THREAD

**Issue by jasells** [rfennell/AzurePipelines#1144]
Using TFS 2017 (on premise, latest update)  I am now getting "A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details."

Just ran multiple pipelines last week with version 2.30.12, but version 2.31.5 has broken all my pipelines!

Is there any way to roll back my locally installed version, or has anyone else reported an issue?

**Comment by rfennell** [comment]
TFS2017 must not support Node10 execution. 

All my release pipelines are however public, so you can download any past version, this should be the previous public release. You can find the .VSIX as an artifact on the first stage

https://dev.azure.com/richardfennell/GitHub/_build/results?buildId=9119&view=results

**Comment by jasells** [comment]
Ahhh, well I probably don't have Node10 installed on my build system...

**Comment by jasells** [comment]
> TFS2017 must not support Node10 execution.

Are you saying this might be both TFS server and build agent issue?  The error appears to currently only indicate it is an issue with Node.js not being available on the agent....

**Comment by rfennell** [comment]
The update was to swap from the Azure Devop agent Node6 execution engine to Node10 as Node6 is reaching end of life support. 

I am not sure installing Node10 on the agent will help as the copy of node is shipped within  the agent. It is an agent limitation

I think you will have to roll back to the older version of my task or much better still update to a Azure DevOps Server 2020. TFS2017 reaches end of mainstream support in January. I always patching TFS/Azure DevOps Server within 6 months of a new release, if not for the new features for the security patches

**Comment by jasells** [comment]
Understood on the limitations.  Is there anyway to add some meta data to the extension so that it is marked as incompatible with TFS2017?   This seems to have been an automatic update, so I expect there's some kind of versioning info available to avoid this?

Even if I manually roll back the local extension  install, what keeps it from getting re-updated?

**Comment by jasells** [comment]
That seems to have worked!  we are now back on v2.30.12 on our local TFS2017.  One thing that was a little unclear after uploading the old visix to TFS was that you *also* have to install it from the list of available extensions in the Manage Extensions tab. That will take you to the store-page for the extension, where you have to click install again, which will install the *local* version, not the latest store version.
