### ISSUE TITLE
Bundle header version compatibility check failed

### ISSUE THREAD

**Issue by yfrindel** [rfennell/AzurePipelines#1169]
### Azure DevOps Extensions

WIKI PDF Generator

### Platform

Azure DevOps Services

### Extension Version

4.4.0

### Describe the bug

Since November 15th 2021, I have the following error : 
![image](https://user-images.githubusercontent.com/22955005/146153312-e27381d0-1073-42f2-bf56-e47b81b12b36.png)
I noticed that the issue appeared after than a new version of the wikiPDFExport app has been installed.
With the version 3.3.1 it was good, and now with the version 4.4.0 it's broken.
Could you help me please?
it's my setup : 
![image](https://user-images.githubusercontent.com/22955005/146154125-4d19dfb0-6e0c-4f63-810c-5975e23066a6.png)
 

### Repo Steps

execute the build

**Comment by yfrindel** [comment]
I have found this comment just right now, so I'm trying the solution : 
![image](https://user-images.githubusercontent.com/22955005/146156474-1f59ae73-fa33-4a42-b4fb-bdc5b9c7b317.png)

**Comment by yfrindel** [comment]
I have now : 
![image](https://user-images.githubusercontent.com/22955005/146160359-0111d2a6-1011-425f-94f9-dd352670061b.png)

**Comment by rfennell** [comment]
That error is being generated by the [MaxMelcher/AzureDevOps.WikiPDFExport](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport) tool that my task wrappers. I think your problem might be related to breaking changes in the [V4.0.x version](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/releases/tag/4.0.0) (the cross-platform version) you have to handle headers and footers differently

I would suggest running the command line locally on your PC against the repo to validate the settings you are passing in. You can see the command line generated by my task in the log i.e Ln 40 of the log.

If you cannot resolve the settings required, you will need to log any issues about the command-line tool in its own repo [here](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues)

If you do want to keep running the 3.x version of the command line tool, you can switch my task from automatically downloading the current version, to using a copy of the EXE you have put in a known location and passed in a task parameter

**Comment by yfrindel** [comment]
I took a look in the documentation
![image](https://user-images.githubusercontent.com/22955005/146164611-8b86e4c2-f512-47e5-840b-7f2bcdd9eeee.png)
but I'm not sure to know how to use the arguments "--footer-template" and "--header-template"
I tried 
![image](https://user-images.githubusercontent.com/22955005/146164818-86ae67c8-7380-42dd-ad2c-005ea62cc86a.png)
but it doesn't work. What's the format to use? Do you have an example please?

**Comment by rfennell** [comment]
As I said, I only wrapper the tool I don't provide support for it here. You need to check the AzureDevOps.WikiPDFExport command line tool repo  at https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport for documentation and support.

A quick look on the homepage there shows the following information

> --footer-template, --header-template,
> Headers and footers can be added to the document by the --header-* and --footer* template arguments respectfully. In header and footer string supplied the following variables will be substituted. See [PDF options from puppeteer](https://pptr.dev/#?product=Puppeteer&show=api-pagepdfoptions).
>
>[pageNumber] Replaced by the number of the pages currently being printed
>[topage] Replaced by the number of the last page to be printed
>[totalPages] Replaced by the current date in system local format
>--footer-template-path, --header-template-path
>Provide a path to html files that will be added as header and footer. See [example-footer.html](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/example-footer.html), [example-header.html](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/example-header.html)

I would hope this provide the samples you are looking for

**Comment by yfrindel** [comment]
Ok it works if you specify directly the template in argument 
![image](https://user-images.githubusercontent.com/22955005/146166331-07b2ab7b-f4fc-475b-8a8c-c6403e042958.png)
Thanks

**Comment by yfrindel** [comment]
fixed

**Comment by rfennell** [comment]
Glad your are unblocked
