### ISSUE TITLE
Exception calling “DownloadString” with “1” argument(s)

### ISSUE THREAD

**Issue by FredxSavage** [rfennell/AzurePipelines#1208]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Extension Version

1.17.5

### Describe the bug

Hello,

Using the extension BuildVariableTask, i am now getting an error 
"##[error]Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a send.""

I found that it may be because my scripts are not supporting TLS 1.2, but i saw that adding oneline may be able to solve the issue.
It could be something like this: 
############Call Web clientt############

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

### Repo Steps

...

**Comment by martindelisle** [comment]
https://devblogs.microsoft.com/visualstudio/azure-devops-requires-tls-1-2-on-all-connections-including-visual-studio/

**Comment by rfennell** [comment]
2.6.7 should be on TLS1.2
