### ISSUE TITLE
Cannot install Manifest Versioning Build Tasks

### ISSUE THREAD

**Issue by vbtrek** [rfennell/AzurePipelines#1269]
### Azure DevOps Extensions

Manifest Versioning

### Platform

Azure DevOps Server (TFS) - Specify Version

### Azure DevOps Server (TFS) Version

2019

### Describe the bug

Im getting the following error when trying to install on DevOps 2019 Self Hosted:
![image](https://user-images.githubusercontent.com/26403480/160691575-9c8f1285-52ed-48b3-8e65-7687e005d933.png)

`Task definition input 'Injectversion' and Task definition input 'VersionRegex' must belong to same group as they are dependent inputs for Task with ID 'e23ccfaa-0d23-4fb7-b9f1-215b3060c452'.`

I saw a similar issue for one of you other tools.

### Repo Steps

Install on self hosted Azure DevOps Server 2019.

**Comment by rfennell** [comment]
Interesting that does not show up in Azure DevOps Services.

There was a missing `group`  parameter in the `task.json`. The fix PR is being processed now. 

It will be released as 2.37.x

**Comment by vbtrek** [comment]
Thanks for this. When will I see the new version on the Visual Studio MarketPlace?
