### ISSUE TITLE
When using YAML Release pipeline on Azure DevOps, incorrect commits are included or there is no way how to include only correct one

### ISSUE THREAD

**Issue by kine** [rfennell/AzurePipelines#1331]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Extension Version

3.85.2

### Describe the bug

Setup:
1 - pipeline yaml file for release is stored in the repository together with the code of the app
2 - there is separate build yaml pipeline, creating the builds which will be released
3 - Release pipeline Run is associated with the latest master/main commit, but some different build pipeline artifact is released (older one), which is associated with some older commit
4 - The change log is including even the WIs associated with latest commits (commits after the released build commit), because global commits are taken for the current build run (release pipeline run), which is associated with latest master/main commit

There is no way (or I do not know it), how to include only WIs associated with the commits between last release and the released artifact commit.

### Repo Steps

1 - create pipeline for building the app, save it as YAML into the repository, into main branch
2 - create release pipeline for the app, save it as YAML into the repository, into main branch
3 - Create commit, associate WI AAA with it
4 - build it (build X)
5 - Create commit, associate WI BBB with it
6 - Run the release pipeline, select build X artifact for release
7 - check the change log, it will include WI AAA and even BBB, because the release pipeline run from step 6 is associated with commit from step 5 (correctly, but it is not what we are releasing)

### Expected Behavior

Expected is, that the change log will include only WI AAA, not WI BBB, because there is only one commit released as part of the release pipeline.

### Logging Information

<img width="450" alt="image" src="https://user-images.githubusercontent.com/110221/188173064-154f0cdd-c23a-461f-afb1-592961c2cd18.png">

Change log will include all the WIs, not only WI 1. Cannot have way how to filter/get only the WI1.

**Comment by rfennell** [comment]
The WI/CS to be included in a given set of release notes are returned by the Microsoft API calls based on the changes between provided build run IDs

- [WI](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get-build-work-items-refs?view=azure-devops-rest-7.1)
- [Commits/Changesets](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get-changes-between-builds?view=azure-devops-rest-7.1)

If you run the task with debug enabled, you will see all the API calls used.

What is returned is beyond my control. My task just formats it.

Sorry, I don't think I can offer a solution here.

**Comment by rfennell** [comment]
This task is driven by Azure DevOps API calls that use the build IDs as the boundaries for finding Wi and Commits. I have some both 'hacks' in there e.g. WIQL options, but fundamentally it is these API calls that do the work. I am to reflect what the Azure DevOps UI shows.

You could of course develop something else, but the API does not lend itself to that and it would hence be a very different task from my design  aims

**Comment by kine** [comment]
May be one question:

Could OverrideActiveBuildReleaseId help in this? When I set it to the build run I am releasing by the pipeline?

**Comment by rfennell** [comment]
It could, that is a recent addition from the community. It, with the OverrideBuildReleaseID allows you to pick both boundary conditions

**Comment by kine** [comment]
I will try it. For now I will close this... Thanks!
