### ISSUE TITLE
Get all parent workitems of work items in pipeline artifacts

### ISSUE THREAD

**Issue by keepcalmandbuild** [rfennell/AzurePipelines#1334]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

When I generate release notes for a pipeline that consumes pipeline artifacts, I would like to have the fields of parent work items available for consumed artifacts, not just references to them. I would like something with the same data structure as "relatedWorkItems".

This would allow me to display parents and filter them by their fields. For example, if a task work item is linked to a commit, I would like to show its user story parent or feature grandparent in the release notes like it's currently possible for the primary artifact.

With relatedWorkItems of the primary artifact this is possible:
{{#forEach relatedWorkItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Feature')}}
#{{../id}}   
{{/if}}
{{/with}}
{{/forEach}}

I could not find a way to do the same for other consumed pipeline artifacts. The parameter getAllParents  does not seem to have any effect on consumed artifacts.

### Describe the solution you'd like

I would like additional data added to consumedArtifacts if getAllParents is enabled.
I have tried this approach locally on my machine, I was able to add a "parentexperiment" object by calling getAllParentWorkitems as it is called to create "relatedWorkItems" for the primary artifact. See example below.

This would work for me.

Example:

```
globalConsumedArtifacts.push({
                                        "artifactCategory": (currentBuildArtifact as any).artifactCategory,
                                        "artifactType": (currentBuildArtifact as any).artifactType,
                                        "alias": (currentBuildArtifact as any).alias,
                                        "properties": {
                                            "projectId": (currentBuildArtifact as any).properties.projectId
                                        },
                                        "versionName": `${(lastGoodBuildArtifact as any).versionName} - ${(currentBuildArtifact as any).versionName}`,
                                        "commits":	await enrichChangesWithFileDetails(
                                            gitApi,
                                            tfvcApi,
                                            await buildApi.getChangesBetweenBuilds((currentBuildArtifact as any).properties.projectId, (lastGoodBuildArtifact as any).versionId, (currentBuildArtifact as any).versionId),
                                            gitHubPat),
                                        "workitems": await getFullWorkItemDetails(workItemTrackingApi, wi),
                                        "parentexperiment": await getAllParentWorkitems(workItemTrackingApi, artifactworkitems),
                                    });
```

### Describe alternatives you've considered

Generating release notes of consumed artifacts separately and join markdown files, but comparing the correct pipeline IDs would be challenging.

**Comment by rfennell** [comment]
Happy to consider PR if you have a working prototype
