### ISSUE TITLE
wiqlFromTarget of WorkItemLinks has returned results ignored and thus they are not used by the tool

### ISSUE THREAD

**Issue by Josephpul** [rfennell/AzurePipelines#1346]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

The changes made for #1279  are perhaps outdated as it using "WorkItemLinks" for the "wiqlFromTarget" always seems to ignore the returned values.

The results seem to come back in the "workItemRelations" object, not the work items object.__

### Repo Steps

For a classic release pipeline run of Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts

Set wiqlFromTarget to "WorkItemLinks" and no matter what query you use no results will be found and you will always see "Found no WI using WIQL" in the log.

### Expected Behavior

workItemRelations are pulled from the response and used in subsequent steps of the process.

### Logging Information

I added a log in ReleaseNodesFunctions.ts at line 1958

 agentApi.logDebug(JSON.stringify(queryResponse));
and found the response to look like this (with data in workItemRelations but no workItems element)
{
	"queryType": 3,
	"queryResultType": 2,
	"asOf": "2022-09-23T20:40:00.777Z",
	"columns": [		
	],
	"sortColumns": [
	],
	"workItemRelations": [		
	]
}

**Comment by rfennell** [comment]
Released as 3.88.4
