### ISSUE TITLE
Handle empty fields

### ISSUE THREAD

**Issue by Froostx** [rfennell/AzurePipelines#1348]
I want to handle my #if that recognizes when a custom field is empty. I found in the plugin source code that there is a helper called "isEmpty", but I can't get it to work.

Here is my template:
```
{{#return_parents_only this.workItems this.relatedWorkItems}}
{{#if (or (contains (lookup this.fields 'System.WorkItemType') 'User Story') (contains (lookup this.fields 'System.WorkItemType') 'Feature'))}}
{{#if (isEmpty (lookup this.fields 'Custom.ReleaseNotes'))}}
emtpy
{{else}}
{{#with fields}}
* **{{{get 'System.Title' this}}}:** {{{sanitize (get 'Custom.ReleaseNotes' this)}}}
{{/with}}
{{/if}}
{{/if}}
{{/return_parents_only}}
```

Any ideas will be very helpful :)
thx

**Comment by rfennell** [comment]
On a first look I thought that would seem to be the appropriate helper, but I think on second reading it is designed to check for empty arrays, not sure how it works for strings.

I would look at [checking the length is zero](https://github.com/helpers/handlebars-helpers#lengthEqual)

The other option is to write your own custom handlebars extension, but that does seem over the top for this problem/

**Comment by Froostx** [comment]
> 

Checking if the length is zero seems to be my solution here, but not sure how to use it.

I tried this, but is not working.
```
## 🚨 What's New
{{#return_parents_only this.workItems this.relatedWorkItems}}
{{#if (or (contains (lookup this.fields 'System.WorkItemType') 'User Story') (contains (lookup this.fields 'System.WorkItemType') 'Feature'))}}
{{#if (not (lengthEqual (lookup this.fields 'Custom.ReleaseNotes') 0))}}
{{#with fields}}
* **{{{get 'System.Title' this}}}:** {{{sanitize (get 'Custom.ReleaseNotes' this)}}}
{{/with}}
{{/if}}
{{/if}}
{{/return_parents_only}}
```

**Comment by rfennell** [comment]
If don't have the same project structure as you, but this template works for me as expected, only showing the task is there is a populated custom release notes field

```
{{#forEach this.workItems }}

# with no filter (for diags)
{{#with fields}}
* **{{{get 'System.Title' this}}}:** {{{sanitize (get 'Custom.ReleaseNotes' this)}}}
{{/with}}
Length - {{length (lookup this.fields 'Custom.ReleaseNotes')}}
Length is zero - {{lengthEqual (lookup this.fields 'Custom.ReleaseNotes') 0}}


# with filter

{{#if (contains (lookup this.fields 'System.WorkItemType') 'Task') }}
{{#if (not (lengthEqual (lookup this.fields 'Custom.ReleaseNotes') 0))}}
{{#with fields}}
* **{{{get 'System.Title' this}}}:** {{{sanitize (get 'Custom.ReleaseNotes' this)}}}
{{/with}}
{{/if}}
{{/if}}

{{/forEach}}
````

**Comment by Froostx** [comment]
> If don't have the same project structure as you, but this template works for me as expected, only showing the task is there is a populated custom release notes field
> 
> ```
> {{#forEach this.workItems }}
> 
> # with no filter (for diags)
> {{#with fields}}
> * **{{{get 'System.Title' this}}}:** {{{sanitize (get 'Custom.ReleaseNotes' this)}}}
> {{/with}}
> Length - {{length (lookup this.fields 'Custom.ReleaseNotes')}}
> Length is zero - {{lengthEqual (lookup this.fields 'Custom.ReleaseNotes') 0}}
> 
> 
> # with filter
> 
> {{#if (contains (lookup this.fields 'System.WorkItemType') 'Task') }}
> {{#if (not (lengthEqual (lookup this.fields 'Custom.ReleaseNotes') 0))}}
> {{#with fields}}
> * **{{{get 'System.Title' this}}}:** {{{sanitize (get 'Custom.ReleaseNotes' this)}}}
> {{/with}}
> {{/if}}
> {{/if}}
> 
> {{/forEach}}
> ```

Sorry for the delayed response. It seems that I'm doing it right using that #if, it's the same thing you wrote there, I don't know why it didn't work for me at first. I'm going to make a couple more attempts and keep you updated on the result. Thanks.
