### ISSUE TITLE
Specification of multiple version fields

### ISSUE THREAD

**Issue by bgillet** [rfennell/AzurePipelines#1356]
### Azure DevOps Extensions

Manifest Versioning

### Is your feature request related to a problem? Please describe.

In a Dotnet Core project file (.csproj), there may be up to 3 different version fields.

![image](https://user-images.githubusercontent.com/3019854/193304715-de81fd22-d9c9-4c33-8d05-cb5c5580959f.png)

But the extension let us specify only one version field at a time and if not specified, the default behavior of the extension doesn't take into account the `FileVersion `field.

![image](https://user-images.githubusercontent.com/3019854/193305279-80482b72-58b6-4bc0-a3ff-93b257e3d823.png)

### Describe the solution you'd like

I would like to be able specifying the fields I want to replace with my version number by giving a list of values separated with commas.

For example : `Version, AssemblyVersion, FileVersion`

**Comment by rfennell** [comment]
The array of fields are now exposed as a parameter `versionFields`, that contains a comma separated list of field name. The default is 'Version, VersionPrefix, AssemblyVersion' so as to not change historic behaviour

This is released in 2.39.2
