### ISSUE TITLE
Reusing an existing filename results in multiple entries in the .order file

### ISSUE THREAD

**Issue by erwin-faceit** [rfennell/AzurePipelines#1360]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Describe the bug

When using the options replacefile and updateOrderFile, you will get duplicate entries in the .order file if the filename already exists.

### Repo Steps

Use the variables:

```
replaceFile: true
updateOrderFile: true
```

in a pipeline, and use the same filename when generating release notes.

### Expected Behavior

A single entry in the .order file, but you might need another setting. When the file already exists, you have two options:

a. Remove the existing entry, and append or prepend the new filename
b. Leave the existing entry alone, and do nothing

### Logging Information

The order file that is currently in source control:

```
release-9.4.5
release-9.4.5
release-9.4.5
release-9.4.5
release-9.4.5
```

**Comment by rfennell** [comment]
Fix released as 1.44.3
