### ISSUE TITLE
Default value for `sourceFolder` contains an incorrect syntax

### ISSUE THREAD

**Issue by finkinfridom** [rfennell/AzurePipelines#1376]
As per here: https://github.com/rfennell/AzurePipelines/blob/main/Extensions/WikiUpdater/WikiFolderUpdaterTask/task/task.json#L78

the `defaultValue` property is set as `${build.sourcesdirectory)` while it should be `$(Build.SourcesDirectory)` (there is a wrong curly brace).

Thanks

**Comment by rfennell** [comment]
Thanks for point that out, I will get a fix out ASAP
