### ISSUE TITLE
TF401019: Git repository does not exist

### ISSUE THREAD

**Issue by delpierro140** [rfennell/AzurePipelines#1452]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Repo Steps

...

**Comment by rfennell** [comment]
This is probably that you have not granted the build user permission to access to the Git Repo.

Check the instructions for all the various scenarios in the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks#authentication)

**Comment by delpierro140** [comment]
Thanks for your answer.
Is it because I cant’t change the setting?




***@***.***

***@***.***<https://www.ct-netze.de>


Pierre Glodek


Tel:
E-Mail: ***@***.******@***.***>


COMPUTIME Netzwerkservice Gmbh

HR-B 200771 | GF: Olaf Lange



        ***@***.***

***@***.***




Von: Richard Fennell ***@***.***>
Gesendet: Dienstag, 3. Januar 2023 10:00
An: rfennell/AzurePipelines ***@***.***>
Cc: Glodek, Pierre ***@***.***>; Author ***@***.***>
Betreff: Re: [rfennell/AzurePipelines] TF401019: Git repository does not exist (Issue #1452)


This is probably that you have not granted the build user permission to access to the Git Repo.

Check the instructions for all the various scenarios in the WIKI<https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks#authentication>

**Comment by rfennell** [comment]
I can see you are trying to access the Project WIKI repo, by default the build service user has no access to this this repo. Your options are

1. Grant the build service user permission to the repo (as documented in the WIKI)
2. Use a different users passing in a PAT to the task (again documented in the WIKI)
