### ISSUE TITLE
PR count is not fetching when 2nd time of new pipeline run and WI is not fetching all the time.

### ISSUE THREAD

**Issue by 1669233** [rfennell/AzurePipelines#1458]
As you [we discussed](https://github.com/rfennell/AzurePipelines/discussions/1438) already that task can only get commits, WI and PRs related to the current pipeline.

PR count is coming when first time run pipeline. If you run again as same pipeline it won’t fetch even PR is open.
But it is not fetching the WI(Azure) for current pipeline.
this is one scenario: - Unfortunately, first time some error occurs so could not get the current PR, Commit and WI so if run again got only commit of current pipeline. In this scenario how to get PR, WI and Commit details.
I used below inputs for your reference. Could you please help on this.

Let me know if I missed any inputs format or need to add anything.

```
inlinetemplate: |
         ## Build {{buildDetails.buildNumber}}
               * **Branch**: {{buildDetails.sourceBranch}}
               * **Tags**: {{buildDetails.tags}}
               * **Completed**: {{buildDetails.finishTime}}
               * **Previous Build**: {{compareBuildDetails.buildNumber}}
               
           {{#forEach pullRequests}}
           * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
           * Created by {{this.createdBy.displayName}} {{thos.creationDate}}
           * Reviewed by:
           {{#forEach this.reviewers}}
           * {{this.displayName}}
           {{/forEach}}
           * Associated Work Items
           {{#each_with_sort_by_field this.associatedWorkitems "System.Tags"}}
           {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
           - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
           {{/with}}
           {{/each_with_sort_by_field}}
           * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
           {{#forEach this.associatedCommits}}
           - [{{truncate this.commitId 7}}]({{this.remoteUrl}}) - {{get_only_message_firstline this.comment}}
           {{#with (lookup_a_pullrequest_by_merge_commit ../../inDirectlyAssociatedPullRequests this.commitId)}}
           - Associated PR {{this.pullRequestId}} - {{this.title}}
           {{/with}}
           {{/forEach}}
           {{/forEach}}
         checkStage: true
   stopOnRedeploy: true
   sortCS: true
   sortWi: true
   showOnlyPrimary: true
   searchCrossProjectForPRs: true

**Comment by rfennell** [comment]
I assume you are rerunning the pipeline for testing. Remember it is normal to get different results on each run as each past run is seen by the next run, thus altering the range of build considered.

If you want to do repeated runs for testing look at the [command line tester](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole), it was built to diagnose problems and test templates.

Using this tool you can debug through the task to find where the PR detection logic does not meet your needs.
