### ISSUE TITLE
Release Notes with Shared Query

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#1476]
### Discussed in https://github.com/rfennell/AzurePipelines/discussions/1475

<div type='discussions-op-text'>

<sup>Originally posted by **keepcalmandbuild** February 22, 2023</sup>
Hello, I love the GenerateReleaseNotes Node based Cross Platform extension and I am exploring how to capture a baseline of known bugs at the time of the release. I read about wiqlFromTarget and wiqlWhereClause. I would like a similar functionality, that uses an existing shared query ID instead of wiql to specify the work item query for release notes. My motivation is that I would like to be able to have only one query, to be sure that data visualization is consistent across different "media". For example, I would like to reuse the same query for release notes and dashboard.
I have thought of including a query link in the markdown template and publish it in the wiki as a workaround, but in that case the wiki would show the current results of the query at the time of opening the wiki, not the results at the time of release notes generation.</div>

**Comment by rfennell** [comment]
he only reason I could see this not working would be permissions, if the agent running the build did not have access to read shared queries. Even if this was the case it should only be a case of altering permissions.

The basic API call (via the Node SDK) is along the lines of

https://dev.azure.com/<org>/<project>/_apis/wit/queries/Shared%20Queries/Query1?$expand=all&api-version=7.0

From this call we can get the JSON for the WIQL

There would need to be some string handling to extract the where clause of the WIQL (as the task handles the columns used), but all doable

I will promote this discussion to be a tracked enhancement, not sure when I will get around to it

**Comment by keepcalmandbuild** [comment]
Thank you for considering this idea. Regarding permissions, using the normal system token would work for me. I can set up the required permissions in the query.

**Comment by rfennell** [comment]
I found a bit of time to look at this and will is done. The updated code is being released as 4.3.3

There are now two ways to use WIQL

| parameter | Description |
|-|-|
| wiqlSharedQueryName | The name (can include sub folder path) of a Shared Work Item Query in the `Shared Queries` folder that will be used to retrieve work items e.g. `Query1` or `My Folder/Query1`. <br>Notes: This parameter if defined will be used in preference to the other WIQL parameters. <br>The query must be saved as a 'Shared Query'. <br>As with the other WIQL parameters, you cannot use the all the @ parameter such as `@project`, `@currentIteration` or `@Me`, but `@Today` works, and the query must return the Work Item ID `[System.Id]` as a column |

or


| parameter | Description |
|-|-|
| wiqlWhereClause | A where clause to get a get a list of work items using a WIQL Query e.g. `[System.TeamProject] = 'Project Name' and [System.WorkItemType] = 'Product Backlog Item'`. Note you cannot use the all the @ parameter such as `@project`, `@currentIteration` or `@Me`, but `@Today` works. To aid in the creation of  your WIQL Where clauses the [WIQL Editor](https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor) extension is highly recommended |
| wiqlFromTarget | The FROM target for the WIQL Query.  e.g. `SELECT [System.Id] FROM workitems WHERE ...` (Default is WorkItems) |

**Comment by keepcalmandbuild** [comment]
Awesome, thank you very much!!

**Comment by keepcalmandbuild** [comment]
I believe there has been a copy paste accident in the wiki https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task

<html>
<body>


queryWorkItems | the array of WI returned by by the WIQL, if a wiqlSharedQueryName or wiqlSharedQueryName and wiqlWhereClause are defined. Note that this array is completely independent of all other WI arrays.
-- | --



</body>
</html>
Should it be "...or wiqlFromTarget and wiqlWhereClause are defined" ?

**Comment by rfennell** [comment]
Thanks @keepcalmandbuild  for point that  out, pushing an update out now
