### ISSUE TITLE
 An error occurred trying to start process  - Argument list too long

### ISSUE THREAD

**Issue by rodolfourb** [rfennell/AzurePipelines#1479]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Azure DevOps Server (TFS) Version

2.5.2

### Extension Version

2.5.2

### Describe the bug

Not able to update or Wiki on Azure, still or error showing "'/home/vsts/agents/3.217.1/externals/node16/bin/node' with working directory '/home/vsts/work/r1/a '. Argument list too long" in the process of generating the artifact we can see that it was successfully generated.

Criação do *.MD
2023-02-27T20:35:13.2200643Z Writing output file /home/vsts/work/r1/a/v0.2.1-ci.77b01.md
2023-02-27T20:35:13.2238460Z Finished writing output file /home/vsts/work/r1/a/v0.2.1-ci.77b01.md
2023-02-27T20:35:13.2239006Z Output variable 'release_wiki_content' set to value of first generated release notes
2023-02-27T20:35:13.2239594Z Writing output variable release_wiki_content
2023-02-27T20:35:13.3078482Z ##[section]Finishing: Generate Release Notes based on Release Comparison API

### Repo Steps

Create steps:

- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@4
  displayName: 'Generate Release Notes based on Release Comparison API'
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)/$(Release.ReleaseName).md '
    outputVariableName: 'release_wiki_content'
    templateLocation: InLine
    inlinetemplate: |
         :blue_book: ## Release Notes for {{buildDetails.buildNumber}}
         |||
         |-|-|
         |:rocket: **Release**| {{buildDetails.buildNumber}}|
         |:file_folder: **Branch**| {{buildDetails.sourceBranch}}|
         |**Environment**| {{currentStage.name}}|
         |**Tags**| {{buildDetails.tags}}|
         |**Date**| {{buildDetails.startTime}}|
         |:date:**Completed**| {{buildDetails.finishTime}}|
         |**Previous Build**| {{compareBuildDetails.buildNumber}}|
         
         ## Associated Pull Requests ({{pullRequests.length}})  :construction_worker
         {{#forEach pullRequests}}
         * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
         * Associated Work Items
         {{#forEach this.associatedWorkitems}}
            {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
             - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
            {{/with}}
         {{/forEach}}
         * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
         {{#forEach this.associatedCommits}}
             - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
         {{/forEach}}
         {{/forEach}}
         
         ## Global list of WI with PRs, parents and children
         {{#forEach this.workItems}}
         {{#if isFirst}}### WorkItems {{/if}}
         *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
            - **WIT** {{lookup this.fields 'System.WorkItemType'}}
            - **Tags** {{lookup this.fields 'System.Tags'}}
            - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
            - **Description** {{{lookup this.fields 'System.Description'}}}
            - **PRs**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Pull Request')}}
         {{#with (lookup_a_pullrequest ../../pullRequests  this.url)}}
               - {{this.pullRequestId}} - {{this.title}}
         {{/with}}
         {{/if}}
         {{/forEach}}
            - **Parents**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Parent')}}
         {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
               - {{this.id}} - {{lookup this.fields 'System.Title'}}
               {{#forEach this.relations}}
               {{#if (contains this.attributes.name 'Parent')}}
               {{#with (lookup_a_work_item ../../../../relatedWorkItems  this.url)}}
                  - {{this.id}} - {{lookup this.fields 'System.Title'}}
               {{/with}}
               {{/if}}
               {{/forEach}}
         {{/with}}
         {{/if}}
         {{/forEach}}
            - **Children**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Child')}}
         {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
               - {{this.id}} - {{lookup this.fields 'System.Title'}}
         {{/with}}
         {{/if}}
         {{/forEach}}
            - **Tested By**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Tested By')}}
         {{#with (lookup_a_work_item ../../testedByWorkItems  this.url)}}
               - {{this.id}} - {{lookup this.fields 'System.Title'}}
         {{/with}}
         {{/if}}
         {{/forEach}}
         {{/forEach}}
         
         # Global list of CS ({{commits.length}})
         {{#forEach commits}}
         {{#if isFirst}}### Associated commits{{/if}}
         * ** ID{{this.id}}**
            -  **Message:** {{this.message}}
            -  **Commited by:** {{this.author.displayName}}
            -  **FileCount:** {{this.changes.length}}
         {{#forEach this.changes}}
               -  **File path (TFVC or TfsGit):** {{this.item.path}}
               -  **File filename (GitHub):** {{this.filename}}
         {{/forEach}}
         {{/forEach}}
         
         ## List of WI returned by WIQL ({{queryWorkItems.length}})
         {{#forEach queryWorkItems}}
         *  **{{this.id}}** {{lookup this.fields 'System.Title'}}
         {{/forEach}}
         
         ## Manual Test Plans :running:
         | Run ID | Name | State | Total Tests | Passed Tests |
         | --- | --- | --- | --- | --- |
         {{#forEach manualTests}}
         | [{{this.id}}]({{this.webAccessUrl}}) | {{this.name}} | {{this.state}} | {{this.totalTests}} | {{this.passedTests}} |
         {{/forEach}}
         
         ## Global list of ConsumedArtifacts ({{consumedArtifacts.length}})
         | Category | Type | Version Name | Version Id | Commits | Workitems |
         |-|-|-|-|-|-|
         {{#forEach consumedArtifacts}}
          |{{this.artifactCategory}} | {{this.artifactType}} | {{#if versionName}}{{versionName}}{{/if}} | {{truncate versionId 7}} | {{#if this.commits}} {{this.commits.length}} {{/if}} | {{#if this.workitems}} {{this.workitems.length}} {{/if}} |
         {{/forEach}}
     
    checkStage: true

###########################################################

steps:

- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiFolderUpdaterTask.WikiFolderUpdaterTask@2
  displayName: 'Git based WIKI Folder Updater'
  inputs:
    repo: 'https://dev.azure.com/****/****/_git/****%C3%A7%C3%A3o-CS.wiki'
    branch: wikiMaster
    targetFolder: 'Release-Version-Notes/$(Build.Repository.Name)/$(Release.DefinitionName)/'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    message: '$(Release.ReleaseName).md '
    gitname: git.user
    gitemail: 'git.user@****.com'
    useAgentToken: true

###################################################

2023-02-27T20:35:14.1745701Z ##[section]Starting: Git based WIKI Folder Updater
2023-02-27T20:35:14.1749824Z ==============================================================================
2023-02-27T20:35:14.1749922Z Task         : Git based WIKI Folder Updater from Black Marble
2023-02-27T20:35:14.1749988Z Description  : A tools to update or create a set of files in a folder in WIKI based in a Git repo 
2023-02-27T20:35:14.1750077Z Version      : 2.5.2
2023-02-27T20:35:14.1750132Z Author       : Richard Fennell
2023-02-27T20:35:14.1750187Z Help         : Version: 2.5.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2023-02-27T20:35:14.1750294Z ==============================================================================
2023-02-27T20:35:14.2463235Z ##[error]An error occurred trying to start process '/home/vsts/agents/3.217.1/externals/node16/bin/node' with working directory '/home/vsts/work/r1/a'. Argument list too long
2023-02-27T20:35:14.2473654Z ##[section]Finishing: Git based WIKI Folder Updater

### Expected Behavior

It is expected that the Wiki presents data from the release note.

### Logging Information

Steps:

- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@4
  displayName: 'Generate Release Notes based on Release Comparison API'
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)/$(Release.ReleaseName).md '
    outputVariableName: 'release_wiki_content'
    templateLocation: InLine
    inlinetemplate: |
         :blue_book: ## Release Notes for {{buildDetails.buildNumber}}
         |||
         |-|-|
         |:rocket: **Release**| {{buildDetails.buildNumber}}|
         |:file_folder: **Branch**| {{buildDetails.sourceBranch}}|
         |**Environment**| {{currentStage.name}}|
         |**Tags**| {{buildDetails.tags}}|
         |**Date**| {{buildDetails.startTime}}|
         |:date:**Completed**| {{buildDetails.finishTime}}|
         |**Previous Build**| {{compareBuildDetails.buildNumber}}|
         
         ## Associated Pull Requests ({{pullRequests.length}})  :construction_worker
         {{#forEach pullRequests}}
         * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
         * Associated Work Items
         {{#forEach this.associatedWorkitems}}
            {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
             - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
            {{/with}}
         {{/forEach}}
         * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
         {{#forEach this.associatedCommits}}
             - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
         {{/forEach}}
         {{/forEach}}
         
         ## Global list of WI with PRs, parents and children
         {{#forEach this.workItems}}
         {{#if isFirst}}### WorkItems {{/if}}
         *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
            - **WIT** {{lookup this.fields 'System.WorkItemType'}}
            - **Tags** {{lookup this.fields 'System.Tags'}}
            - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
            - **Description** {{{lookup this.fields 'System.Description'}}}
            - **PRs**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Pull Request')}}
         {{#with (lookup_a_pullrequest ../../pullRequests  this.url)}}
               - {{this.pullRequestId}} - {{this.title}}
         {{/with}}
         {{/if}}
         {{/forEach}}
            - **Parents**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Parent')}}
         {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
               - {{this.id}} - {{lookup this.fields 'System.Title'}}
               {{#forEach this.relations}}
               {{#if (contains this.attributes.name 'Parent')}}
               {{#with (lookup_a_work_item ../../../../relatedWorkItems  this.url)}}
                  - {{this.id}} - {{lookup this.fields 'System.Title'}}
               {{/with}}
               {{/if}}
               {{/forEach}}
         {{/with}}
         {{/if}}
         {{/forEach}}
            - **Children**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Child')}}
         {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
               - {{this.id}} - {{lookup this.fields 'System.Title'}}
         {{/with}}
         {{/if}}
         {{/forEach}}
            - **Tested By**
         {{#forEach this.relations}}
         {{#if (contains this.attributes.name 'Tested By')}}
         {{#with (lookup_a_work_item ../../testedByWorkItems  this.url)}}
               - {{this.id}} - {{lookup this.fields 'System.Title'}}
         {{/with}}
         {{/if}}
         {{/forEach}}
         {{/forEach}}
         
         # Global list of CS ({{commits.length}})
         {{#forEach commits}}
         {{#if isFirst}}### Associated commits{{/if}}
         * ** ID{{this.id}}**
            -  **Message:** {{this.message}}
            -  **Commited by:** {{this.author.displayName}}
            -  **FileCount:** {{this.changes.length}}
         {{#forEach this.changes}}
               -  **File path (TFVC or TfsGit):** {{this.item.path}}
               -  **File filename (GitHub):** {{this.filename}}
         {{/forEach}}
         {{/forEach}}
         
         ## List of WI returned by WIQL ({{queryWorkItems.length}})
         {{#forEach queryWorkItems}}
         *  **{{this.id}}** {{lookup this.fields 'System.Title'}}
         {{/forEach}}
         
         ## Manual Test Plans :running:
         | Run ID | Name | State | Total Tests | Passed Tests |
         | --- | --- | --- | --- | --- |
         {{#forEach manualTests}}
         | [{{this.id}}]({{this.webAccessUrl}}) | {{this.name}} | {{this.state}} | {{this.totalTests}} | {{this.passedTests}} |
         {{/forEach}}
         
         ## Global list of ConsumedArtifacts ({{consumedArtifacts.length}})
         | Category | Type | Version Name | Version Id | Commits | Workitems |
         |-|-|-|-|-|-|
         {{#forEach consumedArtifacts}}
          |{{this.artifactCategory}} | {{this.artifactType}} | {{#if versionName}}{{versionName}}{{/if}} | {{truncate versionId 7}} | {{#if this.commits}} {{this.commits.length}} {{/if}} | {{#if this.workitems}} {{this.workitems.length}} {{/if}} |
         {{/forEach}}
     
    checkStage: true

###########################################################

steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiFolderUpdaterTask.WikiFolderUpdaterTask@2
  displayName: 'Git based WIKI Folder Updater'
  inputs:
    repo: 'https://dev.azure.com/****/****/_git/****%C3%A7%C3%A3o-CS.wiki'
    branch: wikiMaster
    targetFolder: 'Release-Version-Notes/$(Build.Repository.Name)/$(Release.DefinitionName)/'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    message: '$(Release.ReleaseName).md '
    gitname: git.user
    gitemail: 'git.user@****.com'
    useAgentToken: true

###################################################

2023-02-27T20:35:14.1745701Z ##[section]Starting: Git based WIKI Folder Updater
2023-02-27T20:35:14.1749824Z ==============================================================================
2023-02-27T20:35:14.1749922Z Task         : Git based WIKI Folder Updater from Black Marble
2023-02-27T20:35:14.1749988Z Description  : A tools to update or create a set of files in a folder in WIKI based in a Git repo 
2023-02-27T20:35:14.1750077Z Version      : 2.5.2
2023-02-27T20:35:14.1750132Z Author       : Richard Fennell
2023-02-27T20:35:14.1750187Z Help         : Version: 2.5.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2023-02-27T20:35:14.1750294Z ==============================================================================
2023-02-27T20:35:14.2463235Z ##[error]An error occurred trying to start process '/home/vsts/agents/3.217.1/externals/node16/bin/node' with working directory '/home/vsts/work/r1/a'. Argument list too long
2023-02-27T20:35:14.2473654Z ##[section]Finishing: Git based WIKI Folder Updater

**Comment by rfennell** [comment]
Have a look at #1024 it seems similar

That issues was due to the agent type running the task, it is exactly as the message says the problem that the command generated for shell out to run Git (done by the simple-git module) is  too long

**Comment by rodolfourb** [comment]
Thank you, item #1024 helped to resolve the issue.
