### ISSUE TITLE
Link broken from depreciated extension page.

### ISSUE THREAD

**Issue by JJKW1984** [rfennell/AzurePipelines#1480]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

The link on title Node based Release Notes Generator extension on the [Generate Release Notes Build Task (PowerShell)](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task&ssr=false) page is broken.

### Repo Steps

1. Go to ['...'](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task&ssr=false)
2. Click on 'Node based Release Notes Generator'
3. Scroll down to notice it doesn't load because it is missing the h from http://

### Expected Behavior

Link should point to correct github page.

**Comment by rfennell** [comment]
This has been fixed in the WIKI and the source, but I am not redeployed this depreciated extension to the marketplace, so the typo will remain there
