### ISSUE TITLE
GenerateReleaseNotes ADO Task v4, unable to pull results

### ISSUE THREAD

**Issue by Danondso** [rfennell/AzurePipelines#1488]
Hello!

I'm working on setting up a task in ADO that will generate release notes, I've so far gotten it working using the console tester tool. Here's my settings.json, obfuscated the team foundation and project. 

```json
{
    "TeamFoundationCollectionUri": "####",
    "TeamProject": "####",
    "buildId": "",
    "releaseDefinitionId": "11517",
    "releaseId": "",
    "environmentName":"MacOS",
    "templatefile": "build-handlebars-template.md",
    "outputfile": "output.md",

    "dumpPayloadToConsole": "false",
    "dumpPayloadToFile": "false",
    "dumpPayloadFileName": "payload.json",

    "templateLocation": "File",
    "inlinetemplate": "",
    "outputVariableName": "no available in this tool",
    "showOnlyPrimary": "false",
    "replaceFile": "true",
    "appendToFile": "false",
    "getParentsAndChildren": "true",
    "getAllParents": "true",
    "searchCrossProjectForPRs": "true",
    "stopOnRedeploy": "false",
    "SortWi": "true",
    "SortCS": "true",
    "customHandlebarsExtensionCodeAsFile": "",
    "customHandlebarsExtensionCode": "",
    "customHandlebarsExtensionFile": "",
    "customHandlebarsExtensionFolder": "",
    "overrideStageName": "",
    "checkStages": "false",
    "Fix349": "true",
    "tags": "",
    "overrideActiveBuildReleaseId":"",
    "overrideBuildReleaseId": "",
    "getIndirectPullRequests": "false",
    "considerPartiallySuccessfulReleases": "false",
    "checkForManuallyLinkedWI": "true",

    "wiqlWhereClause": "",
    "getPRDetails": "true",
    "getTestedBy": "false",

    "maxRetries": "3",
    "pauseTime": "5000",

    "stopOnError": "false"
}
```

The problem I'm having is whenever I try to set up the task (v4) in a release pipeline, it never wants to pull the results. It seems like the main difference is that I'm unable to set the releaseDefinitionId (which makes sense considering the task is tied to a release). Outside of that I'm not entirely sure why this setup would be working fine locally but not via the task. My main goal here is to fetch the work items associated with a build that the release is based off of and then add work item links, super simple. 

Should I be generating the notes in the build pipeline instead? If so I was curious about documentation for yml based pipelines, it seems like the [link for that](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task-YAML) doesn't contain anything. 

Thanks in advance!
~ Dublin

**Comment by rfennell** [comment]
Sorry about [the wiki YAML page](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task-YAML), the last release's page update had failed it seems, it is fixed now.

Can I confirm if you are using YAML (which I assume you are) or a Classic Build & Release?

Also, can you, upload a log file for a run for the task, with the `system.debug=true` variable set, so I can check what is being processes

**Comment by Danondso** [comment]
Hey thanks for getting that sorted out. Our build is yml based and our release is classic. 

Will try to get you the log file once I get into work here 👍

**Comment by rfennell** [comment]
And to confirm you are running the task in the release?

The logic is very different between when it runs in a Classic release and then used in a Classic Build or either single stage or multistage YAML.

**Comment by Danondso** [comment]
Correct I'm running the task in a classic release. 

And good to know, my alternate route for getting this setup was to generate them at build time instead.

**Comment by rfennell** [comment]
Generating them at build and release are both good options, but they tell you different things and we use both

- In a build it is the changes since the last success build. Assuming your CI build is reliable, this is the changes since the last commit/PR
- In a release (or multistage YAML) you can do the changes since it was last released, successfully, to that stage/environment. So the notes are made up of many builds if you don't do continuous deployment i.e. deploy each CI build

Have you had a look at this  [video of conference session video I did on the subject](https://www.youtube.com/watch?v=xaV3dFoQdV8&t=332s)?

The issue I have always had with testing this task with Classic Releases is that unless you force failure in a stage or increment the consumed builds before each test you tend to get no associated WI/CS returned as though you are redeploying the items deployed have not changed. 

That is why I wrote the command line tester to make it easier to repeatably test templates

**Comment by Danondso** [comment]
Ah that distinction helps a good bit, I didn't get around to debugging the release job and based on what you're saying and what I'm trying to do (release notes on a per build basis) it sounds like generating them at build time better suits what I'm trying to do. Our CI process is fairly consistent now but our CD process is in flux so they wouldn't be as reliable right now. 

I went ahead and setup the release notes task in our build pipeline and it's generating what I'm expecting to see. I think I'm good at this point, thanks for adding the README back and the explanation of what it's doing in a build vs release context.

**Comment by rfennell** [comment]
Glad you find the task useful, and thanks for pointing out the wiki was broken

**Comment by Danondso** [comment]
Yeah it's making our lives way easier! Feel free to close this out I'n sure I've got everything I need here 👍
