### ISSUE TITLE
The task Start a DevTest Labs VM never completes

### ISSUE THREAD

**Issue by mhoult22** [rfennell/AzurePipelines#1489]
We have this task in our release pipeline along with the Stop task.
There are no issues with the Stop, it stops our DevTest Labs VM in around 1-2 mins.
The Start task starts our VM in a similar time, but the task itself never completes.

The only workaround I can think of is to put a timeout of 3 mins on the task and mark as "Continue on error".  This then returns "partially completed".

I have never had the task fail to start the VM, it is purely that it doesn't recognise the VM has started.
Do you have any suggestions please?
Thank you.

**Comment by rfennell** [comment]
As noted in the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/DevTestLabs#note) I had a similar problem testing when I made a configuration issue. Yours seems reversed but simular

> A strange effect is that of you get the wrong value such as that you use ones for the VMs and not the Environment, it is possible the start task works but the stop tasks fails.

So I would check, I guess for at l leats the hundredth time the ID for the URL

**Comment by mhoult22** [comment]
Thank you @rfennell.  After raising this issue I also tried running a script to start the VM, rather than this task.  The result was the same.  I've checked the ID and it is correct, and using the script the ID is generated for me, and again is correct.  Guess all I can do is the 2 minute timeout and "continue on error", as although it gives me a "warning" state for my pipeline stage it does work.

Script below for reference:

```
$devTestLabName = "$(devtestlab_labname)"
$vMToStart = "$(VM_ATPController)"

# The action on the virtual machine (Start or Stop)
$vmAction = "Start"

# Get the lab information
$devTestLab = Get-AzResource -ResourceType 'Microsoft.DevTestLab/labs' -ResourceName $devTestLabName

# Start or stop the VM and return a succeeded or failed status
$returnStatus = Invoke-AzResourceAction `
                    -ResourceId "$($devTestLab.ResourceId)/virtualmachines/$vMToStart" `
                    -Action $vmAction `
                    -Force

if ($returnStatus.Status -eq 'Succeeded') {
    Write-Output "##[section] Successfully updated DTL machine: $vMToStart, Action: $vmAction"
}
else {
    Write-Error "##[error] Failed to update DTL machine: $vMToStart, Action: $vmAction"
}

```

**Comment by rfennell** [comment]
@mhoult22 yes, that seems all you can do. The code for this extension is just an extension of the [Microsoft DevLabs one](https://marketplace.visualstudio.com/items?itemName=ms-azuredevtestlabs.tasks) so I don't think there is any more we can do, unless the [Microsoft Dev labs task issue list](https://github.com/Azure/azure-devtestlab/issues) has offers any suggestions for similar problems.

**Comment by mhoult22** [comment]
OK, thank you @rfennell, I'll close this off and look through the Microsoft task list you suggest.  Thanks for your help.
