### ISSUE TITLE
YAML Build Pipelines with Universal Packages not working for release notes generation

### ISSUE THREAD

**Issue by schmolfi** [rfennell/AzurePipelines#1499]
### Discussed in https://github.com/rfennell/AzurePipelines/discussions/1498

<div type='discussions-op-text'>

<sup>Originally posted by **schmolfi** April  6, 2023</sup>
Hello,

we currently try to move everything from classic release pipelines to YAML.
In our classic release pipelines, we use universal packages as artifact resources. The problem is, that universal packages can not be integrated as pipeline resources in YAML.
Therefore, we download particular universal packages with the following YAML task.

            - task: UniversalPackages@0
              displayName: Download universal package ${{ artifact.value.universalPackage }}
              inputs:
                command: download
                downloadDirectory: $(Build.ArtifactStagingDirectory)/${{ artifact.value.universalPackage }}
                feedsToUse: internal
                vstsFeed: ****
                vstsFeedPackage: ${{ artifact.value.universalPackage }}
                vstsPackageVersion: ${{ artifact.value.version }}
                
The problem right now is, that task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@3 doesn't find the downloaded packages. Is there any option to configure that?     </div>

**Comment by rfennell** [comment]
Sorry, you are right, there is no way to show this in the release notes using my task.

The only option I can think of is for you to write a custom handlebars extension (see the wiki for instructions and samples) that could either

- scan the agent working folder for the universal package download 
- call the Azure DevOps Rest api for the timeliness to read the build log
