### ISSUE TITLE
Ability to compare build from different buildDefinition 

### ISSUE THREAD

**Issue by cedrox** [rfennell/AzurePipelines#1508]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

Yes,
We use multiple YAML pipeline to build/release. Today, I don't think we are able to compare 2 build that come from a different pipeline definition

### Describe the solution you'd like

Be able to generate release note between 2 build id, no matter from what pipeline they come

### Describe alternatives you've considered

Use custom powershell code in the pipeline to answer this specific case

### Additional context

Also, is the parameter in the documentation is "checkStage" or "checkStages"

![image](https://github.com/rfennell/AzurePipelines/assets/10764310/9b214ac6-f42d-4685-9620-f7f319239aab)

vs

![image](https://github.com/rfennell/AzurePipelines/assets/10764310/f43c6b70-8b40-48b9-9e92-cce0b5cfc541)

**Comment by rfennell** [comment]
This enhancement would require a complete rewrite of the task as the underlying API calls it uses to get the changes between builds use the template ID.

**Comment by cedrox** [comment]
Thanks for the clarification @rfennell !
Today we use git tag each time we generate a version for from our release or hotfix pipeline. Can we imagine having this delta between 2 version from this and not from build api ?
Thanks

**Comment by cedrox** [comment]
Thanks for your answer @rfennell

**Comment by cedrox** [comment]
This is a huge limitation on our side. 
Do you think creating the Release note from Pull Request mechanism would be a good option to concider ? 
The idea is to compare 2 release branch. For exemple, merging branch 1.24 to 1.25 would get all the PR and associated WI...
Thanks

**Comment by rfennell** [comment]
The way the task finds associated WI/Commit for a PR is bespoke logic (looking for merge commits), so it may work for you, or you may need to write your own logic if you wish it to do something else 

It is always worth a try, the [command line tester](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole) can be really useful to explore what is possible

**Comment by rfennell** [comment]
Closing as labelled as WONTFIX
