### ISSUE TITLE
Manifest Versioning Build Tasks (netframework version)

### ISSUE THREAD

**Issue by JohnsonYu1** [rfennell/AzurePipelines#1511]
### Azure DevOps Extensions

Manifest Versioning

### Platform

Azure DevOps Services

### Describe the bug

.Net Framework version doesn't work. the version is not updated as I expect. it is still the one defined in AssemblyInfo.cs

name: '1.$(date:yyyy).$(DayOfYear)$(rev:.r)'

- task: VersionAssemblies@3
inputs:
Path: '$(Build.SourcesDirectory)'
VersionNumber: '$(Build.BuildNumber)'
InjectVersion: true
VersionRegex: '\d+\.\d+\.\d+\.\d+'
FilenamePattern: 'AssemblyInfo.*'
Field: 'AssemblyVersion'
OutputVersion: 'OutputedVersion'

### Repo Steps

...

**Comment by rfennell** [comment]
Can you run the pipeline with diagnostics on (check the box when queuing the run or set a variable system.debug=true) and upload the log here so I can see what is happening

The detailed logs usually shows what the issue is (commonly one of search paths being wrong).

Also can I check the version of .NET framework you are targeting, this task is for .NET 4.8 and older, you need to use the >NET Core one for newer versions

**Comment by JohnsonYu1** [comment]
I have two projects in one solution, the second one is a lib project.

looks like you have update them, 
##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
##[debug]INPUT_PATH: 'D:\a\1\s'
##[debug]INPUT_VERSIONNUMBER: '1.2023.151.4'
##[debug]INPUT_INJECTVERSION: 'true'
##[debug]INPUT_VERSIONREGEX: '\d+\.\d+\.\d+\.\d+'
##[debug]INPUT_OUTPUTVERSION: 'OutputedVersion'
##[debug]INPUT_FIELD: 'AssemblyVersion'
##[debug]INPUT_FILENAMEPATTERN: 'AssemblyInfo.*'
##[debug]Source Directory: D:\a\1\s
##[debug]Filename Pattern: AssemblyInfo.*
##[debug]Version Number/Build Number: 1.2023.151.4
##[debug]Version Filter to extract build number: \d+\.\d+\.\d+\.\d+
##[debug]Field to update (all if empty): AssemblyVersion
##[debug]Inject Version: true
##[debug]Output: Version Number Parameter Name: OutputedVersion
##[debug]Using the version number directly
##[debug]Extracted Version: 1.2023.151.4
##[debug]Will apply 1.2023.151.4 to 2 files.
##[debug]Updating only the 'AssemblyVersion' version
##[debug]D:\a\1\s\www\Properties\AssemblyInfo.cs - version applied
##[debug]Updating only the 'AssemblyVersion' version
##[debug]D:\a\1\s\_source\dotnet\_******************_\Properties\AssemblyInfo.cs - version applied
##[debug]Set the output variable 'OutputedVersion' with the value 1.2023.151.4
##[debug]Processed: ##vso[task.setvariable variable=OutputedVersion;]1.2023.151.4


but my debug is still not what I expected in the debug("version": "1.0.8551.24590",)
System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString()

**Comment by rfennell** [comment]
Looks it is finding your `assembly.cs` files and updating the expect fields, so are running this versioning task **BEFORE** you run the compile the project?

Most of the tasks in the extension, including both the .NET versioning tasks, updates the source file, so should be run prior to the compile. 

The exceptions are the DACPAC version which has to be done after the compile and the the XML/JSON ones that are not compiled

**Comment by JohnsonYu1** [comment]
Yes, before build

- task: VersionAssemblies@3
      inputs:
        Path: '$(Build.SourcesDirectory)'
        VersionNumber: '$(Build.BuildNumber)'
        InjectVersion: true
        VersionRegex: '\d+\.\d+\.\d+\.\d+'
        FilenamePattern: 'AssemblyInfo.*'
        Field: 'AssemblyVersion'
        OutputVersion: 'OutputedVersion'

    - script: echo '$(Build.BuildNumber)'
    - script: echo '$(OutputedVersion)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'

**Comment by JohnsonYu1** [comment]
I did a dirty publish.

I can see assemblyinfo.cs of the second project (lib) has been updated correctly.
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.2023.151.12")]
##[debug]D:\a\1\s_source\dotnet_******************_\Properties\AssemblyInfo.cs - version applied
and from Metadata of dll, I can see it is correct.

but the main project (below) was not updated.
still old one: [assembly: AssemblyVersion("1.0.*")]
##[debug]D:\a\1\s\www\Properties\AssemblyInfo.cs - version applied  (seems wrong here)

**Comment by rfennell** [comment]
So, if I understand you correctly,.. 

> `D:\a\1\s\www\Properties\AssemblyInfo.cs` has not been updated, even though the version task log says it has been updated.

Is there anything in your build that could cause the file `D:\a\1\s\www\Properties\AssemblyInfo.cs` to be reverted as part of the pipeline prior to building the `www` project?

Or any way the `www.dll` could have been cached and not rebuilt?

**Comment by JohnsonYu1** [comment]
I  "cat the two assemblyinfo.cs" out after VersionAssemblies task.

one changed:
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.2023.151.16")]
[assembly: AssemblyFileVersion("1.0.0.0")]


one doesn't change:
// by using the '*' as shown below:
[assembly: AssemblyVersion("1.0.*")]

**Comment by JohnsonYu1** [comment]
I have simplified pipeline, nothing should be in except VersionAssemblies task

- stage: build
  jobs:
  - job:
    steps:
    # - task: NodeTool@0
    #   inputs:
    #     versionSpec: '14.x'

    # - task: Npm@1
    #   inputs:
    #     command: 'install'
    #     workingDir: 'www'

    # - task: gulp@0
    #   inputs:
    #     gulpFile: 'www/gulpfile.js'
    #     targets: 'sass-compile'
    #     gulpjs: 'node_modules/gulp/bin/gulp.js'
    #     enableCodeCoverage: false

    # - task: NuGetToolInstaller@1

    # - task: NuGetCommand@2
    #   inputs:
    #     command: 'restore'
    #     restoreSolution: '$(solution)'
    #     vstsFeed: '9c01d89b-0458-41c5-bdb0-4d18902c2f0e/1f26eb19-a087-4efa-8cf9-30c13bc23954'

    - task: VersionAssemblies@3
      inputs:
        Path: '$(Build.SourcesDirectory)'
        VersionNumber: '$(Build.BuildNumber)'
        InjectVersion: true
        VersionRegex: '\d+\.\d+\.\d+\.\d+'
        FilenamePattern: 'AssemblyInfo.*'
        Field: 'AssemblyVersion'
        OutputVersion: 'OutputedVersion'

    - script: echo '$(Build.BuildNumber)'
    - script: echo '$(OutputedVersion)'
    - script: cat '$(Build.SourcesDirectory)\_source\dotnet\****************\Properties\AssemblyInfo.cs'
    - script: cat '$(Build.SourcesDirectory)\www\Properties\AssemblyInfo.cs'


----
one changed:
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '' as shown below:
// [assembly: AssemblyVersion("1.0.")]
[assembly: AssemblyVersion("1.2023.151.16")]
[assembly: AssemblyFileVersion("1.0.0.0")]

one doesn't change:
// by using the '' as shown below:
[assembly: AssemblyVersion("1.0.")]

**Comment by JohnsonYu1** [comment]
And yes, your understanding is correct.
D:\a\1\s\www\Properties\AssemblyInfo.cs has not been updated, even though the version task log says it has been updated.

**Comment by rfennell** [comment]
Ok, I need to try to replicate this, what Visual Studio template type is the WWW based on ?

**Comment by JohnsonYu1** [comment]
yes, it should be asp.net MVC

**Comment by rfennell** [comment]
I have build a worked example of my understanding of your usage. It is in a [public Azure DevOps project](https://dev.azure.com/richardfennell/Issues1511/_build?definitionId=126&_a=summary) so you can see the code and pipeline.

I have checked it is updating the `assemblyinfo.cs` files and that the resultant DLLs have the expected versions.

As I cannot reproduce your issue, can you see how this working example differs from your code?

**Comment by JohnsonYu1** [comment]
Thank you very much for your efforts.

**Comment by rfennell** [comment]
Did you get anywhere with your pipeline?

**Comment by JohnsonYu1** [comment]
I tried another task for "assemblyinfo". And it worked for me. I might try your .net core one when it is time. Thank you for your help.

**Comment by JohnsonYu1** [comment]
seems another task is working for one of my solution. but failed on another solution by not changing the version. interesting. I will try to see if I can find the reason.

**Comment by rfennell** [comment]
Yes, that makes sense as the parameter you are passing into the task to detect the version is `VersionRegex: '\d+.\d+.\d+.\d+'`

Your solution is one fix, the other is to alter the regex filter to match your needs

Glad you are sorted
