### ISSUE TITLE
Unable to get details on PR related work items

### ISSUE THREAD

**Issue by Japeth** [rfennell/AzurePipelines#1551]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

It looks like the function "lookup_a_work_item" may have some issues, or something else is going on.

I've nearly cut-and-pasted the example for querying the associated PRs and Work Items for a build, but the work items for each PR do not show up.  However, the query does know that there ARE work items, and how many, and what the links to them are.  Which lead me down the path to believing it is the "lookup_a_work_item" function that is not doing what it needs to.

Here is my markdown:

      ## Build {{buildDetails.buildNumber}}
      * **Branch**: {{buildDetails.sourceBranch}}
      * **Tags**: {{buildDetails.tags}}
      * **Completed**: {{buildDetails.finishTime}}
      * **Previous Build**: {{compareBuildDetails.buildNumber}}

      ## Strategy
      - **Communication Plan** - Email notifications are sent during each event of the pipeline either requesting approval to deploy or providing management with status updates.
      - **Risk Analysis** - The pipeline performs minimal automated smoke testing of the internet endpoints.  The team will perform manual validation, including validation of Akamai and Azure endpoints.
      - **Implementation Plan** - Feature changes are developed in story branches based off of main.  The story branch is built and tested against non-prod environments.  A PR is open to merge the changes into the main branch.  A release branch is then cut from the main branch and deployed to the Pre-Prod environment for further testing.  Once all controls have been met the release branch is then deployed to the Production environment.
      - **Backout Plan** - Redeploy previous Release branch.
      - **Pre-install Test Plan** - The pipeline executes unit tests and smoke tests.  If any of these stages fail then the pipeline cannot proceed further and exits out.
      - **Post-install Test Plan** - The pipeline performs minimal automated smoke testing of the internet endpoints.  The team will perform manual validation, including validation of Akamai and Azure endpoints.

      ## Associated Pull Requests ({{pullRequests.length}})
      {{#forEach pullRequests}}
      ### **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
      * Associated Work Items ({{this.associatedWorkitems.length}})
      {{#forEach this.associatedWorkitems}}
        {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
          - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
        {{/with}}
      {{/forEach}}
      * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
      {{#forEach this.associatedCommits}}
          - [{{this.commitId}}]({{replace this.remoteUrl " " "%20"}}) -  {{this.comment}}
      {{/forEach}}
      {{/forEach}}

And the markdown release notes that are generated:

# Notes for build

## Build [adt001] Digital NonProd Env Build.254.2
* **Branch**: refs/heads/story/release-notes-comparison
* **Tags**: 
* **Completed**: 
* **Previous Build**: [npd000] Digital NonProd Env Build.250.2

## Strategy
- **Communication Plan** - Email notifications are sent during each event of the pipeline either requesting approval to deploy or providing management with status updates.
- **Risk Analysis** - The pipeline performs minimal automated smoke testing of the internet endpoints.  The team will perform manual validation, including validation of Akamai and Azure endpoints.
- **Implementation Plan** - Feature changes are developed in story branches based off of main.  The story branch is built and tested against non-prod environments.  A PR is open to merge the changes into the main branch.  A release branch is then cut from the main branch and deployed to the Pre-Prod environment for further testing.  Once all controls have been met the release branch is then deployed to the Production environment.
- **Backout Plan** - Redeploy previous Release branch.
- **Pre-install Test Plan** - The pipeline executes unit tests and smoke tests.  If any of these stages fail then the pipeline cannot proceed further and exits out.
- **Post-install Test Plan** - The pipeline performs minimal automated smoke testing of the internet endpoints.  The team will perform manual validation, including validation of Akamai and Azure endpoints.

### **[2577](https://dev.azure.com/removed/b5cf4ec3-b4b5-4309-8c4c-d6628fcae0d8/_git/5c5dde05-800d-421c-9d9c-53ab671321e4/pullRequest/2577)** Enable suffix to fix destroy pipeline issue
* Associated Work Items (1)
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
    - [5d1427389986a95b0371d3f474592700196375d1](https://dev.azure.com/removed/DigAPB/_git/MC%20Connected%20Baseline/commit/5d1427389986a95b0371d3f474592700196375d1) -  Merge branch &#x27;main&#x27; into story/30809_destroy_suffix
    - [cc8223fb515c090e29b0bfbb6fb3236c8a1437eb](https://dev.azure.com/removed/DigAPB/_git/MC%20Connected%20Baseline/commit/cc8223fb515c090e29b0bfbb6fb3236c8a1437eb) -  Enable suffix to fix destroy pipeline issue
    - [3a872cc7a6f560b30f0596017d4d3f9619411ff4](https://dev.azure.com/removed/DigAPB/_git/MC%20Connected%20Baseline/commit/3a872cc7a6f560b30f0596017d4d3f9619411ff4) -  Adding adt008 configs
### **[2573](https://dev.azure.com/removed/b5cf4ec3-b4b5-4309-8c4c-d6628fcae0d8/_git/5c5dde05-800d-421c-9d9c-53ab671321e4/pullRequest/2573)** Adding adt008 configs
* Associated Work Items (1)
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
    - [3a872cc7a6f560b30f0596017d4d3f9619411ff4](https://dev.azure.com/removed/DigAPB/_git/MC%20Connected%20Baseline/commit/3a872cc7a6f560b30f0596017d4d3f9619411ff4) -  Adding adt008 configs
### **[2553](https://dev.azure.com/removed/b5cf4ec3-b4b5-4309-8c4c-d6628fcae0d8/_git/5c5dde05-800d-421c-9d9c-53ab671321e4/pullRequest/2553)** Destroy Pipeline Fix
* Associated Work Items (1)
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
    - [7e286375312f3c4fd4cfc64f1fc1aed4cee302f1](https://dev.azure.com/removed/DigAPB/_git/MC%20Connected%20Baseline/commit/7e286375312f3c4fd4cfc64f1fc1aed4cee302f1) -  Updated steps-terraform-show.yaml
    - [e53dc8ab2cc1e3ac2e377ddf5423ec1882be4241](https://dev.azure.com/CostcoWholesale/DigAPB/_git/MC%20Connected%20Baseline/commit/e53dc8ab2cc1e3ac2e377ddf5423ec1882be4241) -  Updated steps-terraform-show.yaml

### Repo Steps

- Use markdown as above.
- Generate release notes
- View!

### Expected Behavior

That the related work items are able to be populated.

**Comment by Japeth** [comment]
I also want to add, I realize my ADO repo has spaces in it, which is why I added `- [{{this.commitId}}]({{replace this.remoteUrl " " "%20"}}) -  {{this.comment}}`, which fixed a bunch of links for the commits.

I tried that with this line:
`{{#with (lookup_a_work_item ../../relatedWorkItems (replace this.url " " "%20"))}}`
but unfortunately that didn't seem to help at all.

**Comment by rfennell** [comment]
I am still a little unclear as to what you problem is? Is it that all the expected PR associated WI have been found but the link Urls are still mall formed?

Handlebars, and hence this task is extensible. I include a library of useful [Handlebars functions](https://github.com/helpers/handlebars-helpers) and have written a few that are particularly useful and you can add you [own Handlebar Javascript extension functions](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task#handlebar-extensions) to perform any operation you wish.

The `lookup_a_work_item` is one of the extensions I have written and include in the task, all it does is find a WI in an array based on a the WI ID in a URL. This is used by the task to find details of WI the task has already discovered from previous steps (to reduce API calls)

```JS
  handlebars.registerHelper("lookup_a_work_item", function (array, url) {
            var urlParts = url.split("/");
            var wiId = parseInt(urlParts[urlParts.length - 1]);
            return array.find(element => element.id === wiId);
        });
```

It is possible that this fails due to spaces, but I would expect your usage of  `{{#with (lookup_a_work_item ../../relatedWorkItems (replace this.url " " "%20"))}}` to fix that.

Can you run the task with debugging enabled to get a detailed log so we can see what is happening? This can be done

- Set a variable `system.debug=true'
- Check the 'diagnostic' checkbox when queuing a run
- BEST - use the [command line tester](https://github.com/rfennell/AzurePipelines/blob/main/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole/readme.md) - best as it allows easy rerunning of the task when testing without the need for a build agent

**Comment by iamchandanys** [comment]
Hello @Japeth, even am facing the same issue. Did you manage to fix the issue?

```
## Build {{buildDetails.buildNumber}}
* **Branch**: {{buildDetails.sourceBranch}}
* **Tags**: {{buildDetails.tags}}
* **Completed**: {{buildDetails.finishTime}}
* **Previous Build**: {{compareBuildDetails.buildNumber}}

## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
* **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
* Associated Work Items ({{this.associatedWorkitems.length}})
{{#forEach this.associatedWorkitems}}
   {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
   {{/with}}
{{/forEach}}
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
{{#forEach this.associatedCommits}}
    - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
{{/forEach}}
{{/forEach}}
```

The template I have used is as shown above.

**Comment by rfennell** [comment]
I was never provide any details for the failure, to progress can you 

Can you run the task with debugging enabled to get a detailed log so we can see what is happening? This can be done

- Set a variable `system.debug=true'
- Check the 'diagnostic' checkbox when queuing a run
- BEST - use the [command line tester](https://github.com/rfennell/AzurePipelines/blob/main/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole/readme.md) - best as it allows easy rerunning of the task when testing without the need for a build agent
