### ISSUE TITLE
Test console settings json.file properties implicitly are expected to be strings and can be silently ignored if not set to strings

### ISSUE THREAD

**Issue by Stan-Stani** [rfennell/AzurePipelines#1561]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

Properties in the test console --filename JSON seem to implicitly need to be strings.

For example, `"overrideBuildReleaseId": "6485"` works but `"overrideBuildReleaseId": 6485` is treated as if the property was not set.

https://github.com/rfennell/AzurePipelines/blob/aa1b2d89a5548b64cfd6f32231dca19f11dd3eeb/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts#L1174

### Repo Steps

1. Set `overrideBuildRelaseId` to a `number` (not a `string`) and watch it be ignored in the test console program logging.

### Expected Behavior

Either numbers should be vaild for the Ids, or the documentation should explicitly and conspicuously state that all values of properties in the test console --filename file should be strings. Errors being thrown if the type is not correct would be nice too.

**Comment by rfennell** [comment]
This parameter needs to be a string as that is what is passed in by Azure DevOps when the task is run. Hence the main task logic does the null/empty string parsing. 

That said, I have improved the checking of the console tester parameters in #1572 so that should help a bit
