### ISSUE TITLE
 How can we get the WorkItems (different projects) details when associated with PR?

### ISSUE THREAD

**Issue by SBhavana8** [rfennell/AzurePipelines#1565]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

    - task: XplatGenerateReleaseNotes@4
      displayName: 'Generate Release Notes'
      inputs:
        outputfile: '$(System.DefaultWorkingDirectory)inline.md'
        outputVariableName: 'OutputText'
        templateLocation: 'InLine'
        inlinetemplate: |
          # Notes for build  **{{buildDetails.buildNumber}}**
          |||
          |-|-|
          | **{{buildDetails.definition.name}}**|  **{{buildDetails.buildNumber}}**|
          | **Date**| {{buildDetails.startTime}}|
          | **Branch**| {{buildDetails.sourceBranch}}|
          | **BuildDate.Attempt**| {{buildDetails.buildNumber}}|
          | **Tags**| {{buildDetails.tags}}|
          | **Completed**| {{buildDetails.finishTime}}|
          | **Previous Build**| {{compareBuildDetails.buildNumber}}|
          | **Build Number**| {{buildDetails.id}}|
          | **Build Trigger PR Number**| {{lookup buildDetails.triggerInfo 'pr.number'}}|
          
          # Included Packages
          ## Artifacts published by build ({{publishedArtifacts.length}})
          | Name| Type |
          |-|-|
          {{#forEach publishedArtifacts}}
          |{{this.name}} | {{this.resource.type}} | 
          {{/forEach}}
          
          ## Associated Pull Requests ({{pullRequests.length}})
          {{#forEach pullRequests}}
          * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
          * Associated Work Items
          {{#forEach this.associatedWorkitems}}
            {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
              - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
            {{/with}}
          {{/forEach}}
          * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
          {{#forEach this.associatedCommits}}
              - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
          {{/forEach}}
          {{/forEach}}
          
          
          # Global list of WI ({{workItems.length}})
          {{#forEach workItems}}
          {{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
          *   **{{this.id}}**  {{lookup this.fields 'System.Title'}}
            - **WIT** {{lookup this.fields 'System.WorkItemType'}}
            - **Tags** {{lookup this.fields 'System.Tags'}}
            - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
          {{/forEach}}
          ...
          * Associated Work Items
          {{#forEach this.associatedWorkitems}}
            - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup_work_item_across_projects this.id}}
          {{/forEach}}
            # Global list of WI ({{workItems.length}})
          {{#forEach workItems}}
            {{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
            *   **{{this.id}}**  {{lookup_work_item_across_projects this.id}}
              - **WIT** {{lookup this.fields 'System.WorkItemType'}}
              - **Tags** {{lookup this.fields 'System.Tags'}}
              - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
          {{/forEach}}

        checkStage: true
        overrideStageName: 'false'
        stopOnRedeploy: true
        sortCS: true
        sortWi: true
        showOnlyPrimary: true
        searchCrossProjectForPRs: true
        dumpPayloadToConsole: true
        dumpPayloadToFile: true
        replaceFile: false
        appendToFile: true
        getParentsAndChildren: true
        getAllParents: true
        getIndirectPullRequests: true
        stopOnError: true
        considerPartiallySuccessfulReleases: true
        
        
 I have used this handlebars template to generate release notes.

When I am trying to get PR details in generated release notes, I can only get details of workitems that are in the current project, and I am unable to get workitems (workitems from different projects within the same organization) details associated with the PR.

<img width="743" alt="image" src="https://github.com/rfennell/AzurePipelines/assets/97936282/abc719e5-0ad4-41b2-a3c5-00769019e238">

<img width="488" alt="image" src="https://github.com/rfennell/AzurePipelines/assets/97936282/0805ba17-34ea-4ea9-9342-484156fd6897">

### Repo Steps

...

**Comment by rfennell** [comment]
Can you provide a detailed log of the task running, with either the `system.debug=true` variable set or the diags checkbox when you queue the build.

Al so not that PRs are found using bespoke logic where I check for merge commits, if this is not the merge model you are using the task may not find your PRs - but a look at the detailed log will show what is happening.

**Comment by SBhavana8** [comment]
Hi Richard

<img width="760" alt="pr" src="https://github.com/rfennell/AzurePipelines/assets/97936282/81bb76c6-4f56-45d1-978f-438407f60e2e">

Note: Highlighted in red is the cross-project(**MyApp**) work item; highlighted in green is the current project(**generating-release-notes**) work item, where I have associated both work items with PR. I can only find work items that are in the current project when I generate the release notes; I couldn't find work items that are from Cross-project.

<img width="576" alt="pr1" src="https://github.com/rfennell/AzurePipelines/assets/97936282/d4f2597c-7978-45cd-bc48-2970929bdbd5">

In Release notes, I can only see one work item is associated with PR whereas the work item - 16(user story) from my another project(MyApp) within the organisation is not getting reflected (as highlighted in red) within associated workitems in the generated release notes.

[logs_385.zip](https://github.com/rfennell/AzurePipelines/files/13412775/logs_385.zip)
Please find attached logs and let me know in case of any further details.

**Comment by SBhavana8** [comment]
Hi Richard,
 
We have used the same package( azure-devops-node-api  ) to consume the Azure devops API.  By using the below code and able to fetch the associated WI for the PR even in cross project. Could you please advise any changes any parameters to be passed in the release notes task?

Below is the code I tested with:
 
``` const azdev = require('azure-devops-node-api');
 
// Your Azure DevOps organization URL
const orgUrl = '[https://xxxx.visualstudio.com/';](https://xxxx.visualstudio.com/%27;)
 
// Personal Access Token
const token = 'xxx';
 
async function getPullRequestWorkItems() {
    const authHandler = azdev.getPersonalAccessTokenHandler(token);
    const connection = new azdev.WebApi(orgUrl, authHandler);
    const gitApi = await connection.getGitApi();
    const repositoryId = 'xxxx'; // Replace with your repository ID
    const pullRequestId = xx; // Replace with your pull request ID
 
    try {
        const workItemRefs = await gitApi.getPullRequestWorkItemRefs(repositoryId, pullRequestId);
        console.log('Work Item References:', workItemRefs);
    } catch (error) {
        console.error('Error fetching work item references:', error);
    }
}
 
getPullRequestWorkItems();```

**Comment by rfennell** [comment]
I have no idea then why those work items form another project are now appearing as that is basically the same code I use.

All I can suggest is doing some local debugging using the [command line tester](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole) add more debug lines and see what what throws up

**Comment by SBhavana8** [comment]
Hi Richard,
Please find the attached log and screenshot as well . I am able to see the cross project WI in the WI list  using the testconsole as per your earlier comment .Unfortunately i am  not able to get WI of the cross-project to get published in the wiki or PDF generator . Please help us to get the issue resolved .
 
 
<img width="217" alt="Screenshot 2023-11-23 at 5 00 18 PM" src="https://github.com/rfennell/AzurePipelines/assets/97936282/8497eae9-9a56-42db-8045-29d9196380ce">

Below is the handle bar template i am using... does this needs any change as well please let me know if am doing anything wrong.
 
```
    - task: XplatGenerateReleaseNotes@4
      displayName: 'Generate Release Notes'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/version-1'))
      inputs:
        outputfile: '$(System.DefaultWorkingDirectory)inline.md'
        outputVariableName: 'OutputText'
        templateLocation: 'InLine'
        inlinetemplate: |
          # Notes for build  **{{buildDetails.buildNumber}}**
          |||
          |-|-|
          | **{{buildDetails.definition.name}}**|  **{{buildDetails.buildNumber}}**|
          | **Date**| {{buildDetails.startTime}}|
          | **Branch**| {{buildDetails.sourceBranch}}|
          | **BuildDate.Attempt**| {{buildDetails.buildNumber}}|
          | **Tags**| {{buildDetails.tags}}|
          | **Completed**| {{buildDetails.finishTime}}|
          | **Previous Build**| {{compareBuildDetails.buildNumber}}|
          | **Build Number**| {{buildDetails.id}}|
          | **Build Trigger PR Number**| {{lookup buildDetails.triggerInfo 'pr.number'}}|
          
          # Included Packages
          ## Artifacts published by build ({{publishedArtifacts.length}})
          | Name| Type |
          |-|-|
          {{#forEach publishedArtifacts}}
          |{{this.name}} | {{this.resource.type}} | 
          {{/forEach}}
          
          ## Associated Pull Requests ({{pullRequests.length}})
          {{#forEach pullRequests}}
          * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
          * Associated Work Items
          {{#forEach this.associatedWorkitems}}
            {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
              - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
            {{/with}}
          {{/forEach}}
          * Associated Commits (this s commits on the PR source branch not associated directly with the build)
          {{#forEach this.associatedCommits}}
              - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
          {{/forEach}}
          {{/forEach}}
          
        checkStage: true
        overrideStageName: 'false'
        stopOnRedeploy: true
        sortCS: true
        sortWi: true
        showOnlyPrimary: true
        searchCrossProjectForPRs: true
        dumpPayloadToConsole: true
        dumpPayloadToFile: true
        replaceFile: false
        appendToFile: true
        getParentsAndChildren: true
        getAllParents: true
        getIndirectPullRequests: true
        stopOnError: true
        considerPartiallySuccessfulReleases: true
        checkForManuallyLinkedWI: true
        wiqlFromTarget: 'WorkItems'
        wiqlSharedQueryName: 'workitems_query'
    - task: WikiUpdaterTask@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/version-1'))
      inputs:
        repo: 'xxxx'
        branch: 'main'
        filename: 'recentreleasenotes.md'
        replaceFile: false
        appendToFile: true
        dataIsFile: true
        sourceFile: '$(System.DefaultWorkingDirectory)inline.md'
        message: 'Update from Build'
        gitname: 'xxx'
        gitemail: 'xxxx'
        useAgentToken: false
        password: 'xxx'
        localpath: '$(System.DefaultWorkingDirectory)\repo'
        insertLinefeed: true
        RetryMode: 'Pull'

    - task: WikiPdfExportTask@3
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/version-1'))
      inputs:
        cloneRepo: false
        singleFile: '$(System.DefaultWorkingDirectory)inline.md'
        password: 'xxx'
        localpath: '$(System.DefaultWorkingDirectory)\repo'
        outputFile: '$(Build.ArtifactStagingDirectory)/PDF/ReleaseNotes.pdf'
        ExtraParameters: '--breakPage --printbackground --css "$(System.DefaultWorkingDirectory)\style.css" --header-template-path "$(System.DefaultWorkingDirectory)\header.html" --footer-template-path "$(System.DefaultWorkingDirectory)\footer.html"'
    ```

**Comment by rfennell** [comment]
The techniques I use in the cases like this is to add a block to dump out the content of the `relatedWorkItems` array as this contains all the work items found irrespective of how they were found e.g. direct associations, parents, children, PR linked etc. The `json` keyword helps here as it dump the whole object as opposed to you having to list them out.
```
      {{#forEach relatedWorkItems}}
           {{json this}}
      {{/forEach}}
   ```

This should confirms you have the WI you expect.

I would then expect the standard PR block to work, but you will be able to see why it does not manage the match the URL from the PR with WI

```
      ## Associated Pull Requests ({{pullRequests.length}})
      {{#forEach pullRequests}}
      * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
      * Associated Work Items
      {{#forEach this.associatedWorkitems}}
        {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
          - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
        {{/with}}
      {{/forEach}}
      * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
      {{#forEach this.associatedCommits}}
          - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
      {{/forEach}}
      {{/forEach}}
      
      ```

**Comment by SBhavana8** [comment]
Hi Richard, Thanks for your inputs.
The issue was resolved by turning off the below two settings in the project. Now I can get work items from cross-projects in the generated release notes.

<img width="426" alt="image" src="https://github.com/rfennell/AzurePipelines/assets/97936282/14b7bf97-44aa-483f-ac02-e3ff9ab49679">

**Comment by rfennell** [comment]
Ah, yes that would explain it. Glad you are sorted

**Comment by iamchandanys** [comment]
Hello @SBhavana8, Thanks for your solution. 

After disabling the below two options,

![image](https://github.com/rfennell/AzurePipelines/assets/25676168/7c94edd9-bb4f-46b1-aa27-e60ac24cb078)

Am facing the below error while running the WikiUpdater task

![Screenshot 2024-01-18 170457](https://github.com/rfennell/AzurePipelines/assets/25676168/925079e8-4411-47b6-9f5c-067e527058ef)

May I please know did you faced the same? If yes, how you manage to fix it?

FYI - @rfennell
