### ISSUE TITLE
AzureRM is getting deprecated and retired by Microsoft

### ISSUE THREAD

**Issue by siddharthgrd** [rfennell/AzurePipelines#1567]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

AzureRM is getting deprecated and retired by Microsoft and I can see in code AzureRM powershell modules are used. Is there any plan to handle this feature and moving to Az powershell?

### Describe the solution you'd like

Move from AzureRM to Az powershell as per Microsoft Lifecycle Event on 29 February 2024

### Additional context

https://learn.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-11.0.0

**Comment by rfennell** [comment]
The Release Notes Generator Task as it don't make any calls using PowerShell as it is written in Node.JS

So I do not understand why you have logged this question stating 'I can see in code AzureRM powershell modules are used'
