### ISSUE TITLE
`azure-devops-node-api` is incorrectly typed and can return `null` which causes errors

### ISSUE THREAD

**Issue by Stan-Stani** [rfennell/AzurePipelines#1579]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

When a work item is deleted but still exists as a relation, e.g. an item that appears in the related work part of an Azure Devops work item as: 
![image](https://github.com/rfennell/AzurePipelines/assets/14880397/ef4e9c09-193f-4afb-af95-3a84cc58c9ea)
the `azure-devops-node-api` `workItemTrackingApi.getWorkItem()` returns null, despite it not being typed as ever returning null. Since `null` isn't handled, the AzurePipelines `getAllDirectRelatedWorkitems()`  https://github.com/rfennell/AzurePipelines/blob/663e7b2ea0f32a5dbec8be120696767e917a9bff/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts#L807 throws an error at line `805` later when it tries to read properties from that `null`: `if (!relatedWorkItems.find(element => element.hasOwnProperty("id") && element.id === id)) {...}`

I have an issue open with `azure-devops-node-api` but I don't know when or if they will fix the incorrect typing. https://github.com/microsoft/azure-devops-node-api/issues/574#issuecomment-1845260705

I've experimented with trying to override their types in the `XplatGenerateReleaseNotes` to include a possible return of `null` so we can easily see where we need to handle it from TS complaints that would then happen, but TS has not been at all amenable to a hard override. Even casting the type to include `null` doesn't work. 

I'm not sure what the best way to guard against this incorrect typing of a library that is consumed here in `AzurePipelines`. The only workable solution I can think of is to add `null` handling to all uses of the `azure-devops-node-api`. I'm frustrated I can't just re-type the api to make that handling easier as TS would then flag the uses that don't handle null values. I feel this unhandled `null` likely could happen anywhere we use `azure-devops-node-api`.

### Repo Steps

Have a deleted work item still in the relations of a work item and run the test console.

### Expected Behavior

A null item isn't added to the `relatedWorkItems` or `XplatGenerateReleaseNotes` doesn't try to read the properties of the null value.

**Comment by rfennell** [comment]
> I have an issue open with azure-devops-node-api but I don't know when or if they will fix the incorrect typing. https://github.com/microsoft/azure-devops-node-api/issues/574#issuecomment-1845260705

Good luck on the issue raise with the Node API - I have had one open for years related to timeouts with no response
