### ISSUE TITLE
Improve XplatGenerateReleaseNotes Get PR details performance

### ISSUE THREAD

**Issue by M4sterG** [rfennell/AzurePipelines#1587]
### Azure DevOps Extensions

Artifact PR Description

### Is your feature request related to a problem? Please describe.

As stated in the docs keeping the `getPRDetails` option to true results in poor performance when generating release notes. In our projects there many repositories and a huge amount of PRs resulting in the pipeline task taking a lot of time. However we can't set this flag to false because we need the PR details in our release notes.

### Describe the solution you'd like

We added two optional parameters (`getPRDetailsRepositoryId`, `getPRDetailsRefName`) in the task which are then passed to `getPullRequests`  function and finally to the filter `GitPullRequestSearchCriteria`.  We then tested locally our changes and observed a significant improvement in the performance of the function.

**Comment by rfennell** [comment]
I will have a look at PR #1588, thanks for suggesting it

**Comment by rfennell** [comment]
PR #1588 looks fine, just added a bit more documentation. I will get it merged and it will be released as 4.14.x
