### ISSUE TITLE
While displaying list of work items, can we display latest 5/10 work items as release notes having limitation of 5000 characters in App center

### ISSUE THREAD

**Issue by mislekush** [rfennell/AzurePipelines#1591]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

Yaml template which is describing Work items and Pull request showing all items and pull request in release notes.
my requirement is latest 5 items to be displayed in release notes

### Describe the solution you'd like

We can loop through work items and get the latest 5 elements.

**Comment by rfennell** [comment]
You don't need an enhancement of the task, you can write it yourself using the customization options available.

Basically you write your own JavaScript based module  to implement your own loop See [this loop sample](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203%20(and%20later)/each_with_sort_by_field.js) that loops with sort. You could modify this exit after returning a fixed number of  items.

See [this part of WIKI](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task#handlebar-extensions) on using extensions

**Comment by rfennell** [comment]
I think you module needs to be more like  https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203%20(and%20later)/each_with_sort_by_field.js

passing the array back as an enumerable item

**Comment by mislekush** [comment]
Thank you very much Richard.
solution suggested by you worked for me.
