### ISSUE TITLE
"#" character escaping in the gitflow template doesn't seem to work

### ISSUE THREAD

**Issue by rrussell0** [rfennell/AzurePipelines#1596]
In this template file:
https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203%20(and%20later)/gitflow-template.hbs

The commits section:
{{#forEach commits}}
<small><span style="font-family: 'Consolas'"><a href="{{../buildDetails.repository.url}}/commit/{{id}}">{{truncate id 5}}</a></span> by <b>{{author.displayName}}</b> {{#if (gt changes.length 0)}}({{inflect changes.length "file" "files" true}} changed) {{/if}}- <i> {{replace message '#' '# '}} </i></small>  
{{/forEach}}

This seems to have a replace method that should escape # symbols, but this doesn't seem to be happening. Do I need to explicitly add the handlebars-helpers extension to the task somewhere? I've tried to modify the replace statement but I have one specific ticket that used markdown that breaks the formatting of the release notes. 

1. Have a PR/commit that contains "####" in the commit message
2. Generate release notes
3. View release notes to see that the TOC is broken due to picking up the # # # #.

**Comment by rfennell** [comment]
You should not need any special declaration for the `replace` function as it is including automatically as part of the https://github.com/helpers/handlebars-helpers?tab=readme-ov-file#replace.

You can of course write your own [as detailed here](https://github.com/helpers/handlebars-helpers?tab=readme-ov-file#replace) but you should not need to
