### ISSUE TITLE
Unhandled: Unexpected token error after recent extension update(s). 

### ISSUE THREAD

**Issue by cardelo1** [rfennell/AzurePipelines#1831]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Server (TFS) - Specify Version

### Azure DevOps Server (TFS) Version

Azure DevOps 2020 (on-prem; private agent; Classic Release Pipeline)

### Extension Version

3.1.4

### Describe the bug

The WIKI Updater Task (Git based WIKI Folder Updater) was previously working but is now generating the following error:
Unhandled: Unexpected token ;
D:\_work2\_tasks\WikiFolderUpdaterTask_2f22eed4-2ef7-407e-98d8-3b20ca0a5352\2.12.21\node_modules\glob\node_modules\minimatch\dist\cjs\index.js:192
    options;
           ^
SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\_work2\_tasks\WikiFolderUpdaterTask_2f22eed4-2ef7-407e-98d8-3b20ca0a5352\2.12.21\node_modules\glob\dist\commonjs\index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

### Repo Steps

Run the "Git based WIKI Folder Updater" step after successfully running the "Generate Release Notes based on Release Comparison API" step.  Now fails on Azure DevOps 2020 (on-prem) with a private build agent.

### Expected Behavior

This step used to properly add a new version of release notes to the project wiki.

### Logging Information

Unhandled: Unexpected token ;
D:\_work2\_tasks\WikiFolderUpdaterTask_2f22eed4-2ef7-407e-98d8-3b20ca0a5352\2.12.21\node_modules\glob\node_modules\minimatch\dist\cjs\index.js:192
    options;
           ^
SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\_work2\_tasks\WikiFolderUpdaterTask_2f22eed4-2ef7-407e-98d8-3b20ca0a5352\2.12.21\node_modules\glob\dist\commonjs\index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by rfennell** [comment]
I suspect this is related to the version of Node on your Azure DevOps 2020 Server agents.

I would recommend your set your task to us the V2 version which is fully supported for Node10 based agents. This is functionally the same, the V3 version has changes for Node16 based runner

**Comment by cardelo1** [comment]
Thanks for the reply.  Actually, the previous error happened while using V2.  However, I switched to V3 and then received a different error:
"2024-03-26T17:40:56.8006850Z ##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details."

**Comment by rfennell** [comment]
FYI: The V3 implementation only support NODE16, which is not present on AZDO Server V2 agents. V3 I think is shipped with AZDO Server 2022, hence not present on your agents - any plans to upgrade ? (though that is not a reason not to fix this issues as 2020 is still a supported version)

So, I am building a 2020 server to try to repo the issue, but I fear I will have problems issuing an update to my V2 task now I have moved to V3. I need to check my options.



One questions for the repo, how are you authenticating with the Git Repo - AgentToken or PAT?

**Comment by vijng** [comment]
Also got this issue now with the same version, 2.12.21. On-prem Azure TFS Server.

**Comment by cardelo1** [comment]
> FYI: The V3 implementation only support NODE16, which is not present on AZDO Server V2 agents. V3 I think is shipped with AZDO Server 2022, hence not present on your agents - any plans to upgrade ? (though that is not a reason not to fix this issues as 2020 is still a supported version)
> 
> So, I am building a 2020 server to try to repo the issue, but I fear I will have problems issuing an update to my V2 task now I have moved to V3. I need to check my options.
> 
> One questions for the repo, how are you authenticating with the Git Repo - AgentToken or PAT?

Thanks.  I'm using the AgentToken (w/ this setting - Run with Build Agent Credentials).  We may be able to update Node.js on the build server, but that could break other builds.  It would have to be a last resort at the moment.

**Comment by rfennell** [comment]
Update - I have a repo for the problem and I will have to patch the V2 version. This means a change to my deployment model so I can ship both the V3 and V2 versions in parallel

**Comment by rfennell** [comment]
@cardelo1 I agree updating your Node version is probably not a good idea. The other option is to move the classic build to YAML where you can pin the version of the task e.g. `wikupdatertask@2.1.1`

The best solution I have found, other than a revert to V2 as V4, is to do a parallel ship of the V2 and V3 versions in a single package, this allows support for V2/Node10 (as used on AZDO 2020) and V3/Node10/Node16 (as in AZDO 2022 and AZDO Services).

Building this VSIX package format causes a bit of complexity, I am not sure I can get it out today, but I hope to have out after the easter break. 

Sorry for the inconvenience.

**Comment by cardelo1** [comment]
No problem at all.  It's an awesome tool and worth the wait.  Have an excellent holiday!

**Comment by rfennell** [comment]
I have just released as new VSIX package that contains both

- V3.21.1
- V2.14.2

This should fix your issues (I have tested on a Azure DevOps Server 2020 and the cloud service).

**Comment by cardelo1** [comment]
Wow that was fast.  Thank you so much!

**Comment by vijng** [comment]
I can also confirm that the issue is resolved. However, we now/still have the same issue for the "Wiki PDF Export" task, version 3.7.13.

**Comment by rfennell** [comment]
> I can also confirm that the issue is resolved. However, we now/still have the same issue for the "Wiki PDF Export" task, version 3.7.13.

I have republished WIKI PDF Updater with both the V3.9.1 for Agent V2.x and V4.2.9 for Agent V3.x, can you retest

**Comment by vijng** [comment]
Yes, works now, thank you!!
