### ISSUE TITLE
Cannot install Generate Release Notes (Crossplatform) extension on-premise

### ISSUE THREAD

**Issue by HaGGi13** [rfennell/AzurePipelines#1862]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Server (TFS) - Specify Version

### Azure DevOps Server (TFS) Version

Azure DevOps Server 2020.1

### Extension Version

4.16.13

### Describe the bug

When I try to install Generate Release Notes (Crossplatform) v4.16.13 out of the Marketplace or manually via package upload (downloaded from [Projects test AzDO instance pipeline](https://dev.azure.com/richardfennell/GitHub/_build/results?buildId=11636&view=artifacts&pathAsName=false&type=publishedArtifacts)) the package validation fails.
I try to install it in an Azure DevOps Server 2020.1 on-premies instance.

Following find a screenshot of the tried Marketplace installation:
> ![image](https://github.com/rfennell/AzurePipelines/assets/4867233/9bb76075-ba5a-48b7-81cf-ef52bf06122f)

The next screenshot displays the manual package installation try:
> ![image](https://github.com/rfennell/AzurePipelines/assets/4867233/b1a0afd6-7e1b-4c32-87df-ccc03f4e3ce4)

**Additional information**
We have in parallel the deprecated marked not crossplatform version installed.

### Repo Steps

1. Go to "_Generate Release Notes (Crossplatform)_" extension Marketplace page
   1. In Azure DevOps Server click upper right corner shopping bag
   2. Click "_Browse Marketplace_"
   3. Search for "Generate Release Notes (Crossplatform)" extension
2. Click "_Get it free_"
3. An error message appears:
> ![image](https://github.com/rfennell/AzurePipelines/assets/4867233/9bb76075-ba5a-48b7-81cf-ef52bf06122f)

### Expected Behavior

The select collection page appears and I can click _"Install"_ to install the extension:
> ![image](https://github.com/rfennell/AzurePipelines/assets/4867233/8d244889-3717-428f-a9ce-702da9261b60)

**Comment by rfennell** [comment]
Sorry for the delay in looking at this, I have been able to repo it. Should have a fix out soon

**Comment by rfennell** [comment]
Fixed in 4.17.x
