### ISSUE TITLE
Cannot find user defined WIQL query

### ISSUE THREAD

**Issue by jgelon** [rfennell/AzurePipelines#1891]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Extension Version

4.17.12

### Describe the bug

When I fill in the `wiqlSharedQueryName` for a shared query the generator is not able to find that query;

Getting Work Items using user defined WIQL query '/Shared Queries/Release X'
Cannot find user defined WIQL query '/Shared Queries/Release X'

![image](https://github.com/rfennell/AzurePipelines/assets/3374701/930968f0-3be4-4af0-898e-df6bb29309c0)

### Repo Steps

1. Set Pipeline steps

```
steps:
- task: XplatGenerateReleaseNotes@4
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.html'
    templateLocation: 'InLine'
    inlinetemplate: |
      <html>
      <h1>Features in release ({{queryWorkItems.length}})</h1>
      <ul>
      {{#forEach queryWorkItems}}
      <li>
          <strong>{{this.id}}</strong> <span>{{lookup this.fields 'System.WorkItemType'}}</span>: <span>{{lookup this.fields 'System.Title'}}</span><br />
          <span>{{lookup this.fields 'System.State'}}</span> | <span>{{lookup this.fields 'System.AreaPath'}}</span>
      </li>
      {{/forEach}}
      </ul>
      </html>
    dumpPayloadToConsole: false
    dumpPayloadToFile: True
    replaceFile: True
    getParentsAndChildren: false
    getAllParents: True
    getIndirectPullRequests: False
    stopOnError: False
    considerPartiallySuccessfulReleases: False
    checkForManuallyLinkedWI: False
    getPRDetails: false
    getTestedBy: false
    wiqlSharedQueryName: "Release X"
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
```

2. Run pipeline
3. Check logs

### Expected Behavior

Queries are loaded from shared query

**Comment by rfennell** [comment]
Have a look at #1872 , the issue is usually permission related i.e. the build service does not by default have permissions to see the shared queries

**Comment by jgelon** [comment]
That was indeed the case, may I advise to put this next to the documentation for `wiqlSharedQueryName`
