### ISSUE TITLE
fatal: write error: No space left on device

### ISSUE THREAD

**Issue by tletie** [rfennell/AzurePipelines#1969]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Extension Version

3.23.6 (Latest)

### Describe the bug

Hi All,

When using this extension to generate the auto release note from a repo hosted in azure dev as describe in [this article](https://www.wagemakers.net/posts/automatic-devops-release-notes/), an error occur when running the pipeline job in the shared hosted server (provided by Microsoft). The job get error as 
[error]Error: Cloning into '/home/vsts/work/1/s\repo'...
fatal: write error: No space left on device
Here is a snapshot of the issue:
![image](https://github.com/user-attachments/assets/5a631126-785c-465e-a2ff-7f524c0c1292)
 

### Repo Steps

1. Login to azure dev
2. Go to pipeline
3. Create new pipeline (Select Azure Repos Git => select zSpace repository => Select .Net Desktop) and paste the yaml file as in the article
4. Run the pipeline
...

### Expected Behavior

Should be able to generate auto release note

**Comment by rfennell** [comment]
Given the error message I would assume your build agent is out of disk space. 

When our build agent disks are fill we clean out the build working folder `_work` under the agent folder, or enable a [maitenance job](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#what-is-a-maintenance-job)
