### ISSUE TITLE
Handlebar extension, "lookup_a_pullrequest", not able to handle lowercase "%2f" in url string.

### ISSUE THREAD

**Issue by henrikamnas** [rfennell/AzurePipelines#1980]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

A few weeks ago the associated PRs for our work items in our releasenotes report started becoming empty on occasion. 

I think the underlying issue is that Azure DevOps for some reason, in the relations array under the list of workitems, started returning the url string with a lowercase "%2f" which causes the split statement in the 
"lookup_a_pullrequest" function [here](https://github.com/rfennell/AzurePipelines/blob/6d5eaeacf0abdc1483821dbaab192b4f0c54fd32/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts#L989) to not work as expected. Just adding a toUpperCase() there should solve the issue I think.

Let me know if I can assist in anyway possible!

### Repo Steps

1. Generate a releasenotes report that uses the lookup_a_pullrequest function to link workitems to pull request.
2. On some cases the PRs will not be associated with the workitems.

### Expected Behavior

For the pull request to be linked to the workitem.

### Logging Information

Below is the handlebar template we are using:

# Global list of WI with PRs, parents and children
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
####  **[{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}})**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}}
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
   - **PRs**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Pull Request')}}
{{#with (lookup_a_pullrequest ../../pullRequests  this.url)}}
      - **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})**  {{this.title}}
         - Source branch: {{ replace this.sourceRefName "refs/heads/" "" }}
         - Target branch: {{ replace this.targetRefName "refs/heads/" "" }}
         - Created by: {{this.createdBy.displayName}}
         - Created at: {{this.creationDate}}
         - Approvers:
{{#forEach this.reviewers}}
            - {{this.displayName}}
{{/forEach}}
{{/with}}
{{/if}}
{{/forEach}}
   - **Parents**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - **[{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}})**  {{lookup this.fields 'System.Title'}}
      {{#forEach this.relations}}
      {{#if (contains this.attributes.name 'Parent')}}
      {{#with (lookup_a_work_item ../../../../relatedWorkItems  this.url)}}
         - #{{this.id}} - {{lookup this.fields 'System.Title'}}
      {{/with}}
      {{/if}}
      {{/forEach}}
{{/with}}
{{/if}}
{{/forEach}}
   - **Children**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Child')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - **[{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}})**  {{lookup this.fields 'System.Title'}}
{{/with}}
{{/if}}
{{/forEach}}
   - **Tested By**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Tested By')}}
{{#with (lookup_a_work_item ../../testedByWorkItems  this.url)}}
      - **[{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}})**  {{lookup this.fields 'System.Title'}}
{{/with}}
{{/if}}
{{/forEach}}
{{/forEach}}

**Comment by rfennell** [comment]
I will look to getting this addressed

**Comment by rfennell** [comment]
Fixed in 4.19.2
