### ISSUE TITLE
VersionIOSPlistManifest@2 is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task.

### ISSUE THREAD

**Issue by Arslan-Pervaiz** [rfennell/AzurePipelines#2013]
### Azure DevOps Extensions

Manifest Versioning

### Platform

Azure DevOps Services

### Azure DevOps Server (TFS) Version

Azure DevOps Server latest

### Extension Version

2.38.6

### Describe the bug

##[warning]Task 'Version .NET Core Assemblies' version 2 (VersionDotNetCoreAssemblies@2) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

### Repo Steps

Build throws warning on this task

**Comment by rfennell** [comment]
This is not a bug, all you need to do is update your pipeline to use `VersionDotNetCoreAssemblies@3`

Version @3 of this task and hence Node16 support has been available since Dec 2022

**Comment by Arslan-Pervaiz** [comment]
Do i need to update something because I was getting this

`A task is missing. The pipeline references a task called 'VersionDotNetCoreAssemblies' with version '3'. This indicates that the specific task version can not be found. (job 'Job', step ''.)`

**Comment by Arslan007** [comment]
I think ADO was having installed older version as default and when we explicitly installed from Marketplace then it worked and start showing me @3

Thanks

**Comment by rfennell** [comment]
Good news you are unblocked
