### ISSUE TITLE
Release Notes XPLAT - Doesn't produce any release notes for new Rm environment

### ISSUE THREAD

**Issue by gregpakes** [rfennell/AzurePipelines#327]
### VSTS Extension you are using
Release Notes XPLAT

### Where are you running it?
VSTS

### Version of Extension/Task
2.x

### Expected behaviour and actual behaviour

I just wanted to log this issue for discussion.

If you create a new environment in RM and use the release notes task, currently no release notes will be generated.

I'm not 100% sure what I would expect it to do, but the options seem to be to create releasenotes for the entire repo from the beginning of time, or to keep current behaviour and produce nothing.

### Steps to reproduce the problem

- Create a new environment in RM
- Add the task

**Comment by rfennell** [comment]
I think this was reported last week in #319 - I produced a fix and shipped it. It was just as case of on the first run making sure the compare release to be the same current release. So really minor. 

Is this the same issue?

**Comment by gregpakes** [comment]
I think it's subtly different.  This one is about what releasenotes should be included if it's never been deployed before.  Should it be either all the commits since the beginning of time, or none (current behaviour).

**Comment by rfennell** [comment]
I would go with all commits, but I think this is a personal choice ?

Maybe there should be an advanced checkbox option that defaults to the current behaviour, which I think is show all?

**Comment by gregpakes** [comment]
I think it would be a waste of effort to build in a choice.  It only matters on the first run.

I agree with you that it should be all commits.

**Comment by rfennell** [comment]
Isn't that the default now?

**Comment by gregpakes** [comment]
I'm afraid not.  It shows nothing.  That's why I created the issue.

**Comment by rfennell** [comment]
Taken forever but shipped in 2.81
