### ISSUE TITLE
Running pester task in 32 bit doesn't preserve system.debug set to true

### ISSUE THREAD

**Issue by hintbw** [rfennell/AzurePipelines#334]
### VSTS Extension you are using
*There are a number of VSTS extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*
Pester
### Where are you running it?
*VSTS or on-premise TFS (if so what version)*
VSTS
### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*
Most recent (version 8) public version of the task
### Expected behaviour and actual behaviour
Expected behavior
If system.debug is set to true for a VSTS build, I would expect that setting to be preserved in the execution of the task and pester tests whether running in a 32 bit powershell session or 64 bit powershell session

Actual Behavior
System.debug set to true is only preserved when the pester task is run with the default 64 bit powershell. When run in 32 bit, no verbose/debug level logging is output.

### Steps to reproduce the problem
Set system.debug to true for a build definition with the pester task in it.
With the 32 bit checkbox set to false, run the build and observe the output in the log for that task.

Update the build definition and set the 32 bit checkbox to true and run the build and observe the output in the log for that task.

When comparing the two, the differences in the amount of output will be observed.

**Comment by ChrisLGardner** [comment]
Can you replicate this on 7.x? 

I'll double check this in our test environments as well to see what I can find.

**Comment by ChrisLGardner** [comment]
I've done some investigation into this and I can't see how it ever worked previously (assuming it ever did). I also can't see a way to make it work. 

I'll experiment with it a bit more but I suspect it's not going to work the same way it does without that flag.

**Comment by ChrisLGardner** [comment]
Tracking this at https://github.com/pester/AzureDevOpsExtension/issues/11 in case I come up with some solution that'll work for this.
