### ISSUE TITLE
Add support for Directory.Build.props

### ISSUE THREAD

**Issue by SWarnberg** [rfennell/AzurePipelines#346]
### Manifest Versioning Build Tasks
It would be good to add support for Directory.Build.props files since it's a preferred way of versioning multiple .NET Core projects.
I tried to change the Filename Pattern to ".props", but I get the error from the task:
`Skipping file Directory.Build.props as is not a .NETCore Project
`

**Comment by rfennell** [comment]
That sounds that it should not be too hard, as the message you are seeing is caused by a simple if check on a string, so adding another option should be possible

**Comment by chriskooken** [comment]
Hey Richard, I would love this as well. I am using docker and I have dotnet restore as a stage in my build file. In order to take advantage of docker caching, I don't want to modify my project files, just a single Directory.Build.props file. Please let me know if we can add this.

**Comment by rfennell** [comment]
I have eventually got to this, sorry it took so long.

There is now special handling to allow directory.build.props as the file pattern, if this set no SDK name is required. This has been tested against sample data

```
<Project>
  <PropertyGroup>
    <Version>1.2</Version>
    <FileVersion>1.2.1811.0</FileVersion>
    <Product>A test</Product>
    <Company>ABC Inc</Company>
    <Copyright>Copyright © </Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
```

This is release as 2.23.5
