### ISSUE TITLE
To get full filename associated with a change set in report

### ISSUE THREAD

**Issue by VarunNag** [rfennell/AzurePipelines#347]
### VSTS Extension you are using
I am using Generate Release Notes Build Task

### Where are you running it?
Running on VSTS 

### Version of Extension/Task
I am using the current public version

### Expected behaviour and actual behaviour
Is it possible to get changeset with associated file name. I am using the sample template to get a release/build report. I want to include changesets with associated files in the report.

### Steps to reproduce the problem
Configure the Generate Release Notes Build Task and run build to get a build/release report. The generated report does not show files associated with changesets.

**Comment by rfennell** [comment]
I answered the same question on the [marketplace](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task&tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiJtcy5HYWxsZXJ5Tm90aWZpY2F0aW9ucy5xbmEtdXBkYXRlZC1zdWJzY3JpcHRpb24iLCJTVHlwZSI6IkNPTiIsIlJlY2lwIjozLCJFbGVtZW50IjoiaGVyby9jdGEifQ%3D%3D#qna) I think you @VarunNag  may have asked it.

The answer I gave there holds true....

No without a change to the code, the $csdetail object is populated with changeset details, but there is no detail on the files in the changeset 

The call I use is 

$($tfsUri)/$($teamproject)/_apis/build/builds/$($buildid)/changes?api-version=2.0&`$top=$($maxItems)"

I would need to make a further call to populate a sub-list of files

If this is important to you, you could add an issue on the project's Git repo, but I am focusing attention on the CrossPlatform generate release of this extension now (but I think this will suffer the same issue)

Happy to consider PRs if you wish to make the change, but I have no immediate places to make the change

**Comment by VarunNag** [comment]
Hi, Yes, As discussed in market place, I have added an issue on the project's Git repo. I am new to Git Hub, 
I will try and make a change and create a PR.

**Comment by VarunNag** [comment]
Hi @rfennell, I am working on this requirement and going through the powershell script, Have you got a tutorial or some instructions to the run the application locally to do modifications and test, I found the method "Get-BuildChangeSets" in GenerateReleaseNotes.psm1 file, which is building the changeset data from VSTS, I found the call used "$($tfsUri)/$($teamproject)/_apis/build/builds/$($buildid)/changes?api-version=2.0&`$top=$($maxItems)". To add code to make a further call and get the file details, I want to get the script running.

**Comment by rfennell** [comment]
Hi @VarunNag, all the major work for the task is done in a module, the PS1 only really handles parameters and some looping over build focused based functions.

So for local debug I just use a local test PS1 that calls the build release note function. I wanted to avoid putting such a test harness in source control as it would be full of secrets and just local settings. 

So the file contains the following with hard coded value

`$outputmarkdown = Invoke-Template -template $template -builds $builds -releases $releases -stagename $stageName -defname $builddefname -releasedefname $releasedefname -emptySetText $emptySetText

`

**Comment by VarunNag** [comment]
Thanks @rfennell ,

Running the script, I got following error in PS.

Unable to find type [Mode].
At C:\buildNotes\ReleaseNotes.ps1:18 char:25
+         $modeStack.Push([Mode]::BODY)
+                         ~~~~~~
    + CategoryInfo          : InvalidOperation: (Mode:TypeName) [], RuntimeExc 
   eption
    + FullyQualifiedErrorId : TypeNotFound
 
Get-Mode : The term 'Get-Mode' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At C:\buildNotes\ReleaseNotes.ps1:36 char:21
+             $mode = Get-Mode -line $line
+                     ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Mode:String) [], CommandNot 
   FoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Unable to find type [Mode].
At C:\buildNotes\ReleaseNotes.ps1:41 char:27
+             if ($mode -ne [Mode]::BODY) {
+                           ~~~~~~
    + CategoryInfo          : InvalidOperation: (Mode:TypeName) [], RuntimeExc 
   eption
    + FullyQualifiedErrorId : TypeNotFound

We not connecting to VSTS URI, what values to be passed for above parameters -builds, -releases, -stageName, -defname, -releasedefname.

**Comment by rfennell** [comment]
I am going to close this issue as I do not plan to make any enhancements to the PowerShell based task. Any enhancement will be for the Node based version
