### ISSUE TITLE
Allow ability to overwrite only part of 

### ISSUE THREAD

**Issue by keithpatton** [rfennell/AzurePipelines#354]
### VSTS Extension you are using
Version .Net Core Assemblies

### Where are you running it?
VSTS

### Version of Extension/Task
Current public version as of July 17th  2018

### Expected behaviour and actual behaviour
We store our version in source control as follows <version>0.6.0</version>. 
Rather than over-writing the entire version, we would like to be able to append the 4th build number from VSTS. At present, whilst we can extract any value from the VSTS build number via regex, this build number must completely replace the target version.

### Steps to reproduce the problem
See above.

**Comment by rfennell** [comment]
I have no plans to implement such as feature but happy to consider PRs as always

**Comment by rfennell** [comment]
But thinking about it I am working on #306 so that might provide a solution

**Comment by rfennell** [comment]
I am going to close this as repeated  I think by #306 
Reopen of this is not the case.
