### ISSUE TITLE
Associated change sets/commits missing items

### ISSUE THREAD

**Issue by kfuller002** [rfennell/AzurePipelines#376]
### VSTS Extension you are using
Generate Release Notes Build Task

### Where are you running it?
TFS Version 15.117.27414.0

### Version of Extension/Task
 2.22.1

### Expected behaviour and actual behaviour
Using this extension for a release, when i kick off a release I'm comparing the commits that TFS lists for this deployment to the commits listed by the extension.  It's appears to always be off by 1 commit.  When TFS lists 3 the extension is always listing 2, almost like the loop is off by 1. 

### Steps to reproduce the problem
I'm using the below template which is provided by this github project.
I have a release with nothing but this task pointed at this template.
I kick off a release of an older build.
Then i'll kick off the most recent build so there are changes to capture.
Then looking at the output, it appears to be missing the oldest item.
You can use the commits tab on the specific release details to compare two versions, when the versions line up with what the extension is comparing, i always have 1 less item and it's the oldest one.

Template:

`# Release notes for release $defname
**Release Number**  : $($release.name)    
**Release completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$release.modifiedOn) 

**Changes since last successful releases to '$stagename'**   
**Including releases:**   
 $(($releases | select-object -ExpandProperty name) -join ", " )   

## Builds  
@@BUILDLOOP@@
### $($build.definition.name)  
**Build Number**  : $($build.buildnumber)    
**Build completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.finishTime)     
**Source Branch** $($build.sourceBranch)  
  
#### Associated work items  
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')] $($widetail.fields.'System.Title')  [Status: $($widetail.fields.'System.State')]
@@WILOOP@@  
  
#### Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.changesetid)$($csdetail.commitid)$($csdetail.id)** $($csdetail.comment)    
@@CSLOOP@@  
----------
@@BUILDLOOP@@`

**Comment by rfennell** [comment]
As you are running this task in a release can I suggest you move from this older PowerShell based task that uses my own logic, and may contain the issue you have seen and use the newer Node based task that uses  same APIs as the Azure DevOps UX

[Generate Release Notes (Crossplatform)](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes)

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
