### ISSUE TITLE
PackageReferences version numbers are also updated when Versioning .Net Core Assemblies

### ISSUE THREAD

**Issue by JesperHenriksen-Groupcare** [rfennell/AzurePipelines#382]
### Azure DevOps Extension you are using
Version .Net Core Assemblies

### Where are you running it?
Azure DevOps Service (VSTS)

### Version of Extension/Task
2.*

### Expected behaviour and actual behaviour
I want the task to update the version tag inside the `<PropertyGroup>`, not the PackageReferences version tag

### Steps to reproduce the problem
In a project file like below; both version tags are updated...

`<Project Sdk="Microsoft.NET.Sdk">`
  `<PropertyGroup>`
`    <TargetFramework>netstandard20</TargetFramework>`
`    <Version>1.18.3.0</Version>`
`  </PropertyGroup>`

`  <ItemGroup>`
`    <PackageReference Include="Ical.Net">`
`        <Version>4.1.8</Version>`
`    </PackageReference>`
`  </ItemGroup>`
  
`</Project>`

**Comment by JesperHenriksen-Groupcare** [comment]
Btw. I have fixed it locally by moving the version tag into an attribute
`<PackageReference Include="Ical.Net" Version="4.1.8" />`

**Comment by rfennell** [comment]
Need to investigate, that's a filtering issue thought, needs a better one

**Comment by rfennell** [comment]
I have had a look and I can't see an obvious form of regex filter or code change (beyond your workaround see above).

So sorry I am going to have to consider this one a Know Issue for now - can't see a way to sort it.

I will close it, please reopen if there are any new ideas, or submit a PR if you have a code fix
