### ISSUE TITLE
GenerateReleaseNotes causing Cannot bind argument to parameter 'Message' because it is null error when NOT using "Generate for only this Release"

### ISSUE THREAD

**Issue by rogersmj** [rfennell/AzurePipelines#383]
### Azure DevOps Extension you are using
Generate Release Notes

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.23.1

### Expected behaviour and actual behaviour
When the option "Generate for only this Release" is NOT checked, the task fails with error:

`GenerateReleaseNotes causing Cannot bind argument to parameter 'Message' because it is null`

When that option is checked, the task runs fine.

However, if my understanding of that option is correct (and I really don't know, because it's not mentioned on the wiki page), I need to disable it to get a full change set since the last release to a particular environment. With that option turned on, I am not getting complete changesets since the last time I deployed a release. I deployed a release yesterday to production for an app, and the release notes only showed a single commit (from the last build) rather than all commits since the last release to prod.

### Steps to reproduce the problem
With the task as part of a release pipeline, turn off the option Generate for only this Release and execute the release.

I already read through #110 and tried using switching to an inline template instead of file, and it made no difference. Still got the error.

**Comment by rfennell** [comment]
What is the template you are using?

My guess is that it contains a call to a field that is only present is there are multiple releases being consider.

My usual tactic in this situation is to remove all the lines from the template (hence using the inline model is easier) and  adding them one by one to fine the one that causes the issue

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
