### ISSUE TITLE
When I switch between Inline and File, it continues to use the Inline template specified. 

### ISSUE THREAD

**Issue by muklin** [rfennell/AzurePipelines#395]
### Azure DevOps Extension you are using
PS version - https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes%20-Tasks 

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.23.1

### Expected behaviour and actual behaviour
When I switch to File, any template specified in the Inline box is ignored.

### Steps to reproduce the problem
Set an inline template. Save
Change to using a File in the codestream. Save,
Run. 

The file in the Inline box will be what is shown in the log. (and in my case was giving me the ol' "System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null." error)

**Comment by rfennell** [comment]
I need to check this one, I will try to have a look over the weekend

**Comment by rfennell** [comment]
I have tried and cannot repo this issue. Are you sure a cut & paste typo did not get introduced when moving from inline to file?

The usual reason for this error is a typo (or all to an unavailable property) in the template

**Comment by muklin** [comment]
I have the file in source control, git.  I couldn't work out why the template output (that is so usefully posted early on in the task's execution) was still showing a value from _several_ commits ago.  I changed it several times, trying to work out where that template  was coming from.  

I couldn't save the task with empty text in the inline box, so Deleting the task and recreating and selecting and specifying File from the beginning.  So in that sense I suppose this could have changed something else. 

But I'm fairly confident the behaviour I saw was indicative that what I said originally was what was happening.   

I have a workaround now though, so not an issue if you can't repro.

**Comment by rfennell** [comment]
Ok thanks for the extra info. I tried adding the task with an inline task, running it, swap to file and running and back a couple of time.

As long as you have a workaround lets close the issue for now, reopen if it reoccurs and have anything that will help repo
