### ISSUE TITLE
Pester Task: Allow recursive for CodeCoverageFolder

### ISSUE THREAD

**Issue by PatrickGrub** [rfennell/AzurePipelines#397]
### Azure DevOps Extension you are using
Pester Task

### Where are you running it?

Cloud Azure Pipeline

### Version of Extension/Task
Latest

### Expected behaviour and actual behaviour

I want to set the `CodeCoverageFolder` for a specific Folder recursively.
I tried following in my `yml` file
```YML
CodeCoverageFolder: '$(Build.SourcesDirectory)\Files\*'
CodeCoverageOutputFile: 'PesterCodeCovarge.xml'
```

I think you pass it directly to Pester and in this case, I cannot make a pattern to read the folder recursively! Read here more https://github.com/pester/Pester/issues/490

A solution would be 
```
$files = Get-ChildItem .\File -File -Recurse -Include *.ps1
Invoke-Pester -Path \Files.Test -CodeCoverage $files
```

Is it possible to change in my YML something that he will use all files recursively inside the `CodeCoverageFolder` folder?

**Comment by ChrisLGardner** [comment]
I think we can handle this in a few ways, we can add a switch to the task to tell it to recurse (defaulting to false) and then handle that in the task to automatically figure out what files you want to do code coverage on and pass that to Pester. 

It shouldn't take too much work and I'll see if I can get it done over the next week or so.

**Comment by ChrisLGardner** [comment]
Digging into the code I found we should already be handling this as we've got the following lines:

```
$Files = Get-ChildItem -Path $CodeCoverageFolder -include *.ps1, *.psm1 -Exclude *.Tests.ps1 -Recurse |
        Select-object -ExpandProperty Fullname
```

What happens if you drop the \* from the end of your CodeCoverageFolder? It shouldn't make a difference but it's worth a try.

**Comment by PatrickGrub** [comment]
You are right it worked now!
Probably my fault sorry and thanks for the hint.
