### ISSUE TITLE
##[error]File not found: '/Users/vsts/agent/2.142.1/work/_tasks/VersionAndroidManifest_3fccabf1-a604-48c1-a96c-9f5f1841391d/2.1.7\ApplyVersionToManifest.js'

### ISSUE THREAD

**Issue by Imroath** [rfennell/AzurePipelines#398]
### Azure DevOps Extension you are using
Versioning extension, Task Version Android Manifest Version 2.1.7

### Where are you running it?
- Azure DevOps Service (VSTS) - MacOS pipeline

### Version of Extension/Task
Task Version Android Manifest Version 2.1.7

### Expected behaviour and actual behaviour
I expect the task to work but it doesn't work wnd shows an error:

2018-11-26T14:30:50.8086490Z ##[error]File not found: '/Users/vsts/agent/2.142.1/work/_tasks/VersionAndroidManifest_3fccabf1-a604-48c1-a96c-9f5f1841391d/2.1.7\ApplyVersionToManifest.js'
2018-11-26T14:30:50.8103290Z ##[debug]System.IO.FileNotFoundException: File not found: '/Users/vsts/agent/2.142.1/work/_tasks/VersionAndroidManifest_3fccabf1-a604-48c1-a96c-9f5f1841391d/2.1.7\ApplyVersionToManifest.js'
File name: '/Users/vsts/agent/2.142.1/work/_tasks/VersionAndroidManifest_3fccabf1-a604-48c1-a96c-9f5f1841391d/2.1.7\ApplyVersionToManifest.js'

### Steps to reproduce the problem
Just run the task. 

Most likely the issue is that in task.json, because the file path is specified as 
       "target": "$(currentDirectory)\\ApplyVersionToManifest.js",
Where actual path is: src/ApplyVersionToManifest.ts

**Comment by Imroath** [comment]
Thank you for your fast response. I would really appreciate a quick fix:)

**Comment by rfennell** [comment]
Check out the version I just pushed live 2.2.1.
Works OK for my test builds on Mac, Windows and Linux hosted agents

**Comment by Imroath** [comment]
Thank you very much. I will check it tomorrow morning as soon as I get to work. Huge thanks for taking care of it so fast. It is a pleasure to work with professionals like You.
