### ISSUE TITLE
Set linked variable groups varibale is not working

### ISSUE THREAD

**Issue by okkaido** [rfennell/AzurePipelines#400]
Hi Richard,

we have installed the _Build Updating Tasks_ in Azure DevOps Service (VSTS) and using the _Set variable on a build definition_ (v1.9.5) Task in our build definition.

We have created an variable group named _Versioning_ which contains a variable named _Patch_.

We linked the variable group to our build definition.

We want now to auto increment the variable _Patch_ within the agent job.
**Task properties:**
Build selection Mode: _Only primary build artifact_
Variable to update: _Patch_
Update mode: _Autoincrement_
Rest: default values

Whats the Goal:
We want to auto increment the variable _Patch_. We have some other build definitions and they are using this variable also.

**Issue**:
We get the following error message after execution:
_**Cannot increment variable [Patch] either the variable could not be found or the value is not numeric**_

The error log with _System.Debug=true_:
[Error_Log_Set_Variable_On_A_Build_Task.txt]
(https://github.com/rfennell/AzurePipelines/files/2618661/Error_Log_Set_Variable_On_A_Build_Task.txt)

Best regards,
Tobias

**Comment by okkaido** [comment]
Hi Richard,

the Patch value is currently set to two (2).

I attached some pictures of my configuration in Azure DevOps:
![01_library_variablegroup_versioning](https://user-images.githubusercontent.com/45382438/49092085-857b4d00-f261-11e8-9c10-a52dda31fe10.PNG)

![02_pipeline_release_variables](https://user-images.githubusercontent.com/45382438/49092100-89a76a80-f261-11e8-90c2-52659d247d60.PNG)

![03_setvariableonabuilddefinition_task](https://user-images.githubusercontent.com/45382438/49092105-8c09c480-f261-11e8-8f2c-abeac78e4a52.PNG)

Best regards,
Tobias

**Comment by rfennell** [comment]
OK I have done some research and it will need a write of the task to work, at present I check for pipeline variables not variable groups they have a different [api](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/update?view=azure-devops-rest-4.1).

This would be an enhancement, it will go on the backlog, but I don't know when I will have it done

**Comment by okkaido** [comment]
Hi Richard,

yes:
- we have a _Build Pipeline_ and not a _Release Pipeline_
- the _Patch_ variable is in a variable group
- it is working with variables which are defined in the build definition (as in your example with _var1_)

Ok, thank you very much for your investigations.

I will wait for the new version :)

Best regards,
Tobias

**Comment by okkaido** [comment]
Hi Richard,

it's working as expected.

Thank you very much.

Best regards,
Tobias
