### ISSUE TITLE
Adding Extension to Azure Devops does not show task.

### ISSUE THREAD

**Issue by acoroian** [rfennell/AzurePipelines#403]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

Generate Release Notes (Crossplatform)

### Where are you running it?
- Azure DevOps Service (VSTS)
Running this in the cloud. 

### Version of Extension/Task
Using current public version

### Expected behaviour and actual behaviour
Expected to install extension and see task i can add to my project. 

Actual behavior is that it installs the extension but no task shows up. I installed the non crossplatform version and a task showed up for that one after reinstalling the extension. The first time this one showed no task as well.

### Steps to reproduce the problem

Install extension. Add task does not work. 

Let me know if i can provide any more information.

**Comment by rfennell** [comment]
Had any luck thus far?

**Comment by acoroian** [comment]
I am trying to use it with a Build instead of a Release. I will try with a release and write back. 
I did try to reinstall it just in case. (the non XPlatform version needed to be reinstalled for me to see the task)

**Comment by rfennell** [comment]
That is correct. The xplat version is release only due to APIs it uses. The PowerShell version should work in both builds and releases.

So are you working as needed now?

**Comment by rajbos** [comment]
I had the same issue, because I was searching for `Cross platform`, as that was the name of the extension I added. Searching for `notes` or `xplaftorm` eventually helped 🤦‍♂️ . Maybe you can make that distinction clear somewhere or rename the task?

**Comment by rfennell** [comment]
Yes, I have struggled with the name, I think it is confusing as you say. 

On the next update of both the PowerShell (Builds and Releases) and Node (Release only) I will update the readme/marketplace page/wiki page. Ans do something with the titles

If it is OK I will close this issue now. If this issue remains a problem please do not hesitate to re-open it
