### ISSUE TITLE
Add Support for StyleCop 6.0.0

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#408]
### Azure DevOps Extension you are using
StyleCop

### Requirement
From MarketPlace Q&A [Bastian Mattes]

> I get exceptions when using "_" as a variable name. The newest StyleCop (https://www.nuget.org/packages/StyleCop/6.0.0-beta04) fixes this. Could you update the extension to use the newest StyleCop? Thanks!

So update to provide support for StyleCop 6

**Comment by rfennell** [comment]
StyleCop task changes require a change in the underlying StyleCop Command line DLL (a different project)

I need to see if I can support both old and new.

I don't want to commit to a Beta version before release, so this update might be delayed

Needs invetigation

**Comment by gartenriese2** [comment]
@rfennell Any update on this? [StyleCop 6.1.0](https://www.nuget.org/packages/StyleCop/6.1.0) has been released last month.

**Comment by rfennell** [comment]
I have not had time to look at this thus far, been working on other extension. I am not sure when I will get round to it. 

I am happy to look at PRs if someone else has more time

**Comment by rfennell** [comment]
An update...

Made a start, [updated the wrapper class this task is based on to 6.1.0](https://github.com/rfennell/StyleCopCmdLine/releases/tag/V6.1.0). I need to pull this into the extension and test it

**Comment by rfennell** [comment]
Just been released as 3.0.2. V2 still supports StyleCop 5
