### ISSUE TITLE
could not compare 4.4.3  to 4.5.0-beta1

### ISSUE THREAD

**Issue by JoshDouglasOU** [rfennell/AzurePipelines#412]
running pester test runner from azure devops pipeline i'm getting this error and it's failing the task

System.Management.Automation.RuntimeException: Could not compare "4.4.3" to "4.5.0-beta1"
Error: "Cannot convert value "4.5.0-beta1" to type "System.Version". Error: "Input string was not in a correct format."" ---> System.Management.Automation.PSInvalidCastException: Cannot convert value "4.5.0-beta1" to type "System.Version". Error: "Input string was not in a correct format." ---> System.FormatException: Input string was not in a correct format.

Not sure where it's getting the beta1 from.

**Comment by JoshDouglasOU** [comment]
kinda new to this.  pretty sure it's a private agent.  I've got 5 agents and tasks and it only fails on 1 of them with this error.


does this help.  not sure where to put the system.debug

 at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
2019-01-04T16:59:19.2877283Z    at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
2019-01-04T16:59:19.2877536Z    at System.Version.TryParseVersion(String version, VersionResult& result)
2019-01-04T16:59:19.2877686Z    at System.Version.Parse(String input)
2019-01-04T16:59:19.2877842Z    --- End of inner exception stack trace ---
2019-01-04T16:59:19.2878054Z    at System.Management.Automation.LanguagePrimitives.ConvertViaParseMethod.ConvertWithoutCulture(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
2019-01-04T16:59:19.2878266Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-01-04T16:59:19.2878403Z    --- End of inner exception stack trace ---
2019-01-04T16:59:19.2878576Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-01-04T16:59:19.2878771Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2019-01-04T16:59:19.2879152Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2019-01-04T16:59:19.2879641Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by ChrisLGardner** [comment]
The line or two above that is what populates $NewestPester using Find-Module but that shouldn't show prerelease versions by default, so something like $PSDefaultBoundParameters must be changing how it's making its calls. I've got a fix in mind that should override that and ensure it only looks for full releases.

I should be able to get that fix out tomorrow or the day after.
________________________________

**Comment by JoshDouglasOU** [comment]
thank you.  Yes agree. In testing, newestpester is coming back with the prerelease and I couldn't figure out why since default was don't show prerelease

**Comment by ChrisLGardner** [comment]
I've just release 8.9.1 which should fix this by forcing -AllowPrerelease to be false when running Find-Module. 

Can you test it and let me know if it's still happening for you.

**Comment by JoshDouglasOU** [comment]
thank you.  Here is the new error

A parameter cannot be found that matches parameter name 'AllowPrerelease'.

**Comment by JoshDouglasOU** [comment]
then here is another failure
it's still finding it

 Find-Module -Name Pester -AllowPrerelease:$false

Version              Name                                Repository           Description                                                                                                                                       
-------              ----                                ----------           -----------                                                                                                                                       
4.5.0-beta2          Pester                              PSGallery            Pester provides a framework for running BDD

**Comment by ChrisLGardner** [comment]
So after doing more testing with that fix, I'm still seeing issues as Find-Module is the part throwing the error on the conversion of semantic versioning to System.Version format. 

I'm going to have to investigate more on ways to fix this so I'm reverting the current fix. 

Is it possible for you to check which version of PowerShellGet is installed on your build agent? Upgrading that to a newer version should work if it's on one of the many versions of 1.0.0.1.

**Comment by JoshDouglasOU** [comment]
I had to downgrade packagemanagement to 1.2.2  the other newer ones kept finding the beta version.

**Comment by ChrisLGardner** [comment]
Which versions of PowerShellGet and Packagemanagement are you now on? I'll spin up a box with those and do some further testing? I'll also make sure I've got one with 1.2.2 or higher on to see if I still get the issue there too.
________________________________

**Comment by JoshDouglasOU** [comment]
packagemanagement is 1.2.2
I had 1.2.4 and those errored.

one server has powershellget 2.0.3 and 1.0.0.1 and those seem to both work as long as packagemanagement is 1.2.2

**Comment by ChrisLGardner** [comment]
So after a bunch of testing with various versions of both PowerShellGet and PackageManagement I'm not able to replicate it output the prerelease versions of Pester without specifying -AllowPrerelease. 

I've also tested the code paths we have in our extension and they correctly handle various versions of both. If AllowPrerelease is available then it'll try to use it, if it's not then it'll just use the version of Pester that we ship with the extension. Can you test the latest version of the extension and see if you still have problems? If you do then can you run the build and set the build variable system.debug to true (you can do it when you queue a build) and share the logs? The version of the extension should be 8.11
