### ISSUE TITLE
[error]Required: 'SystemVssConnection' service endpoint URL

### ISSUE THREAD

**Issue by faikozgur** [rfennell/AzurePipelines#420]
### Azure DevOps Extension you are using
Update Build Variable Task

### Where are you running it?
TFs 2018

### Version of Extension/Task
1.13.11

### Expected behaviour and actual behaviour
getting following error:
[error]Required: 'SystemVssConnection' service endpoint URL

Last successful run was with version 1.12.2

**Comment by faikozgur** [comment]
Thanks. I have downgraded to version 1.12.2.

**Comment by rfennell** [comment]
I am checking to see what the better solution is - if any

**Comment by rfennell** [comment]
I have tested on TFS2018.3 and it works OK. 

As this is the current version I am closing the issue

1.12.2 used the old engine and that can be used if required, and can be obtained f[rom here ](https://dev.azure.com/richardfennell/GitHub/_build/results?buildId=2662)
