### ISSUE TITLE
Setting the Android Build number in Azure

### ISSUE THREAD

**Issue by burf2000** [rfennell/AzurePipelines#424]
### Azure DevOps Extension you are using
Version Android Manifest 2.4.2

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.4.2

### Expected behaviour and actual behaviour
It to build a APK with the version number 
Version Name will be: 2019.1
Version Code will be 31

### Steps to reproduce the problem
So I must be missing something as I am super new to Azure DevOps
I used the Android template, the versioning says it updates 1 file
![screenshot 2019-01-31 at 15 01 11](https://user-images.githubusercontent.com/319453/52062792-14119080-2569-11e9-9dcd-ad3f1ccf12ce.png)

![screenshot 2019-01-31 at 14 59 20](https://user-images.githubusercontent.com/319453/52062714-f3e1d180-2568-11e9-94ce-0557262f23b4.png)

The APK builds, but when I download it, the manifest still says 1 and 1.0

What am I missing

**Comment by rfennell** [comment]
Can't see anything obvious that looks right.

Try running a build with the system.debug variable to true. Should get more logging in all your tasks. We can then make sure we are uploading the right files and then using these in the build.

But saying that I can't see why you would have two copies of the manifest.

Only other thing I can think of is does the gradle build do anything with the manifest?

**Comment by burf2000** [comment]
Thank you for trying to help.  My gradle script seems to inject the version code/number (both 1) as default.

I have removed this and manually added versionCode='1', versionName='1.0' to the manifest tag in the manifest

I assume it searches for the tag property and replaces it?

**Comment by rfennell** [comment]
Yes [my task](https://github.com/rfennell/AzurePipelines/blob/master/Extensions/Versioning/VersionAndroidManifest/src/ApplyVersionToManifestFunctions.ts) does some basic find and replace, you can see the code in this repo 

```
export function updateManifestFile (filename, versionCode, versionName) {
    var filecontent = fs.readFileSync(filename).toString();
    fs.chmodSync(filename, "600");
    filecontent = filecontent.replace(/versionCode=\"([^"]*)\"/g, `versionCode=\"${versionCode}\"`);
    filecontent = filecontent.replace(/versionName=\"([^"]*)\"/g, `versionName=\"${versionName}\"`);
    fs.writeFileSync(filename, filecontent);
}
```

So should be fine replacing your markers

**Comment by burf2000** [comment]
This is the manifest, is there anything wrong?
And the version stage should be before the gradle build>

<?xml version="1.0" encoding="UTF-8"?>
<manifest
    versionCode='1'
    versionName='1.0'
    compileSdkVersion='28'
    compileSdkVersionCodename='9'
    package='uk.co.reach.apolloclient'
    platformBuildVersionCode='1'
    platformBuildVersionName='1.0'>
  <uses-sdk
      minSdkVersion='15'
      targetSdkVersion='28'>
  </uses-sdk>
  <uses-permission
      name='android.permission.INTERNET'>
  </uses-permission>
  <uses-permission
      name='android.permission.ACCESS_NETWORK_STATE'>
  </uses-permission>
  <uses-permission
      name='android.permission.GET_ACCOUNTS'>
  </uses-permission>
  <uses-permission
      name='android.permission.READ_PROFILE'>
  </uses-permission>
  <uses-permission
      name='android.permission.READ_CONTACTS'>
  </uses-permission>
  <application
      theme='@res/0x7F0E0007'
      label='@res/0x7F0D002A'
      icon='@res/0x7F0C0000'
      allowBackup='true'
      supportsRtl='true'
      roundIcon='@res/0x7F0C0001'
      appComponentFactory='android.support.v4.app.CoreComponentFactory'>
    <activity
        name='uk.co.reach.apolloclient.VisitListActivity'>
    </activity>
    <activity
        name='uk.co.reach.apolloclient.LoginActivity'>
      <intent-filter>
        <action
            name='android.intent.action.MAIN'>
        </action>
        <category
            name='android.intent.category.LAUNCHER'>
        </category>
      </intent-filter>
    </activity>
    <activity
        name='com.microsoft.aad.adal.AuthenticationActivity'>
    </activity>
  </application>
</manifest>

**Comment by rfennell** [comment]
We need to see the manifest file after the task as run

1. Do you have a access to a private on prem build agent, in which case just look after the build has run
2. Add a copy to your build to drop the manifest file into the drops location.

Also did the detailed logging show anything?

I am at a clients site today, so won't be able to answer much, but will look as soon as I can

**Comment by burf2000** [comment]
So I disabled the gradle build task and copied all the files after the stamping to the artifact store, the manifest was not updated?  I have attached screenshots of everything, it would be great to fix this

My default values in the manifest are:
**android:versionCode='1'
android:versionName='1.0'** 

![screenshot 2019-02-01 at 15 58 10](https://user-images.githubusercontent.com/319453/52133930-50f98800-263a-11e9-9915-da850d18a4fe.png)

![screenshot 2019-02-01 at 16 00 40](https://user-images.githubusercontent.com/319453/52134027-8f8f4280-263a-11e9-84e5-4ae64b3753ec.png)

<img width="708" alt="screenshot 2019-02-01 at 16 01 30" src="https://user-images.githubusercontent.com/319453/52134066-aa61b700-263a-11e9-965c-a23f252e7c0a.png">

**Comment by rfennell** [comment]
No problem I will build a test based on your sample. Hopefully over the weekend

**Comment by rfennell** [comment]
Think I found it.  For an immediate fix wwap

```
<manifest
    versionCode='1'
    versionName='1.0'
```
for

```
<manifest
    versionCode="1"
    versionName="1.0'
```
and it should work. I have been testing against Xamarin generated manifests and they use double quotes not single and the regex only handles that.

The change should not have an effect on the workings of the manifest.

Let me know if what works

I will look at a better fix

**Comment by burf2000** [comment]
Thank you so much for fixing this!!

**Comment by rfennell** [comment]
Great I will close this issue then
