### ISSUE TITLE
The source folder link tooltip for Version Nuget Package says "VSIX"

### ISSUE THREAD

**Issue by StingyJack** [rfennell/AzurePipelines#427]
### Azure DevOps Extension you are using
Version Nuget Package

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.*

### Steps to reproduce the problem
![image](https://user-images.githubusercontent.com/15381181/52221337-f301b600-286e-11e9-89a9-e7da2702e0fe.png)

**Comment by rfennell** [comment]
Thanks for pointing that out. I will fix it in the next release

**Comment by rfennell** [comment]
This has been fixed and released
