### ISSUE TITLE
Version Powershell modules - Unable to find repository PSGallery

### ISSUE THREAD

**Issue by JeffreyH1989** [rfennell/AzurePipelines#434]
### Azure DevOps Extension you are using
Extension: Manifest Versioning Build Tasks. Task: Version Powershell modules (v 2.6.1)

### Where are you running it?
On-premise, TFS 2018 update 2

### Version of Extension/Task
Current public version (2.6.1)

### Expected behaviour and actual behaviour
During the Powershell versioning task, the script tries to retrieve the latest version of the Configuration module. However, we are using an internal PS Gallery repository instead of the default one. The [script](https://github.com/rfennell/AzurePipelines/blob/master/Extensions/Versioning/VersionPowerShellModule/src/Update-PowerShellModuleVersion.ps1#L84) tries to find the module from the PSGallery. This step fails, since there is no PSGallery repository available.

![image](https://user-images.githubusercontent.com/7312153/52768794-b97b3880-302e-11e9-8062-e2c04f4f63b4.png)

### Steps to reproduce the problem
Unregister the PSGallery from your local package management, and register your own one with a different name. 

Might be an idea to use a checkbox in the task if you want to use the default Configuration module or try finding for a new version. Or use a parameter for the ps gallery name.

**Comment by ChrisLGardner** [comment]
Hi

I'll swap it over to using a similar process as the Pester task and pick up whatever repository is available and use that. I'll try to get a new release out in the next few days.
________________________________

**Comment by JeffreyH1989** [comment]
Thanks for the quick reply and solution, awesome extension!

**Comment by ChrisLGardner** [comment]
Fixed in the latest release.
