### ISSUE TITLE
Android : Plugin is updating platformBuildVersionCode & platformBuildVersionName by mistake 

### ISSUE THREAD

**Issue by burf2000** [rfennell/AzurePipelines#435]
### Azure DevOps Extension you are using
Version Android Manifest 2.6.1

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
* Azure DevOps Service (VSTS)

### Version of Extension/Task
2.6.1

### Expected behaviour and actual behaviour

Plugin should update versionCode & versionName but not update platformBuildVersionCode & platformBuildVersionName.

### Steps to reproduce the problem

Build an Android app that comes from Android Studio/Gradle

**Comment by rfennell** [comment]
Could upload a sample of your manifest file that has the issue. I will add a test to the suite and make sure it is handled correctly

**Comment by burf2000** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest
    versionCode='10031'
    versionName='1.0.0.31.ftg-app-android-ci_development_20190211_134413'
    compileSdkVersion='28'
    compileSdkVersionCodename='9'
    package='com.acosta.ftg'
    platformBuildVersionCode='10031'
    platformBuildVersionName='1.0.0.31.ftg-app-android-ci_development_20190211_134413'>
  <uses-sdk
      minSdkVersion='24'
      targetSdkVersion='28'>
  </uses-sdk>
  <application
      theme='@res/0x7F0C0005'
      label='@res/0x7F0B0027'
      icon='@res/0x7F0A0000'
      name='com.acosta.ftg.FtgApp'
      allowBackup='true'
      supportsRtl='true'
      roundIcon='@res/0x7F0A0001'
      appComponentFactory='android.support.v4.app.CoreComponentFactory'>
    <activity
        name='com.acosta.ftg.views.MainActivity'>
      <intent-filter>
        <action
            name='android.intent.action.MAIN'>
        </action>
        <category
            name='android.intent.category.LAUNCHER'>
        </category>
      </intent-filter>
    </activity>
  </application>
</manifest>
```

**Comment by rfennell** [comment]
Thanks, i will have a look as soon as I can, hopefully over the weekend

**Comment by burf2000** [comment]
Thank you

**Comment by rfennell** [comment]
Have just shipped 2.7.2, this adds extra checks to make sure the variable update is preceded by a space or android:xxx

Does this fix your issues?

**Comment by burf2000** [comment]
Sadly not

<?xml version="1.0" encoding="UTF-8"?>
<manifest
    versionCode='10047'
    versionName='1.0.0.47.ftg-app-android-ci_development'
    compileSdkVersion='28'
    compileSdkVersionCodename='9'
    package='com.acosta.ftg'
    platformBuildVersionCode='10047'
    platformBuildVersionName='1.0.0.47.ftg-app-android-ci_development'>
  <uses-sdk
      minSdkVersion='23'
      targetSdkVersion='28'>
  </uses-sdk>
  <application
      theme='@res/0x7F0C0005'
      label='@res/0x7F0B0027'
      icon='@res/0x7F0A0000'
      name='com.acosta.ftg.FtgApp'
      allowBackup='true'
      supportsRtl='true'
      roundIcon='@res/0x7F0A0001'
      appComponentFactory='android.support.v4.app.CoreComponentFactory'>
    <activity
        name='com.acosta.ftg.ui.VisitActivity'>
      <intent-filter>
        <action
            name='android.intent.action.MAIN'>
        </action>
        <category
            name='android.intent.category.LAUNCHER'>
        </category>
      </intent-filter>
    </activity>
    <provider
        name='android.arch.lifecycle.ProcessLifecycleOwnerInitializer'
        exported='false'
        multiprocess='true'
        authorities='com.acosta.ftg.lifecycle-trojan'>
    </provider>
  </application>
</manifest>

**Comment by burf2000** [comment]
I actually think this is grade doing this now

**Comment by rfennell** [comment]
Ok that makes sense, I struggled to get a problem with the sample you sent, I added extra checking. Not sure there is much more I can do

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
