### ISSUE TITLE
WorkItems during release

### ISSUE THREAD

**Issue by BlueBasher** [rfennell/AzurePipelines#438]
### Azure DevOps Extension you are using
GenerateReleaseNotesTask

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Currently public version

### Expected behaviour and actual behaviour
It is by design that getting the workItems list is using different logic than the Azure DevOps UI. For our use-case the WI's in the Release WI Difference list is the correct one.
Have you thought of adding a setting to specify the generator to use the same logic? (https://github.com/Microsoft/azure-devops-node-api/blob/e852eb96355ff697564e16cb02578450c3076445/api/ReleaseApi.ts#L104)
If so I could try to contribute a PR for this.

**Comment by rfennell** [comment]
I have versions of the generate release notes task. An older powershell based one that uses my own logic. This can hence work in builds and releases.

I also have a cross platform platform that does use the ms API as does the Azure DevOps ui, but this can only work in releases

**Comment by BlueBasher** [comment]
Indeed, apologies, I thought the crossplatform was the only difference.
