### ISSUE TITLE
Unable to access build information needed in release notes

### ISSUE THREAD

**Issue by wpschaub** [rfennell/AzurePipelines#441]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
Azure DevOps Service (VSTS)

### Version of Extension/Task
2.8.1

### Expected behaviour and actual behavior
Expected to have access to $build information, similar to the PowerShell based Release Notes task.

### Steps to reproduce the problem
Unable to access $build information and task fails with environmental $env:BUILD_BUILDNUMBER.

**Comment by rfennell** [comment]
I thought those variables works

To name a release  (in options) I use

`Release - $(Build.BuildNumber) Attempt $(rev:r)
`
To pickup the build number (the version in my my case), so I had assumed the variables existed elsewhere. I need to look at it

**Comment by wpschaub** [comment]
Sorry, I should have used the most obvious, the Build variables. Verified and working.
