### ISSUE TITLE
BuildTasks Update Build Variable Task fails on OSX agent

### ISSUE THREAD

**Issue by shaynemarriage** [rfennell/AzurePipelines#443]
BuildTasks - Update Build Variable Task - 1.13.11
- Azure DevOps Server 2018

The task fails on an OSX agent with the error below.
A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system.

**Comment by rfennell** [comment]
Yes that is correct, they are written in PowerShell which is not support on Lunix or Mac.

They would need a complete rewrite in Node, something I have no immediate plans to do.

**Comment by DinoSourcesRex** [comment]
I have personally replaced the usage of this with a powershell script. It's not ideal but [here's](https://gist.github.com/DinoSourcesRex/48db15c50635225b970840425e46a3d1) the info for anyone who wants a similar solution.

**Comment by rfennell** [comment]
Took a while, but released in V2.0.20
