### ISSUE TITLE
Pester Task: Trying to download in a isolated env. during run

### ISSUE THREAD

**Issue by PsychoticCob** [rfennell/AzurePipelines#447]
### Azure DevOps Extension you are using
Pester Tasks

### Where are you running it?
On premise - Azure DevOps Server 

### Version of Extension/Task
Latest

### Expected behaviour and actual behaviour:
When starting a test run I get the following error messages:

**Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
Unable to download the list of available providers. Check your internet connection.
System.Exception: No match was found for the specified search criteria for the provider 'Nuget'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.**

This is an environment that has no internet access. 

### Steps to reproduce the problem

- Kick off the test
- script makes it to: **Adding additional module path [] to $env:PSModulePath**
- The list of errors generated are:

**##[warning]MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
 ##[warning]Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
 ##[warning]Unable to download the list of available providers. Check your internet connection.
 ##[warning]Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
 ##[warning]Unable to download the list of available providers. Check your internet connection.
 ##[error]System.Exception: No match was found for the specified search criteria for the provider 'Nuget'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
 ##[error]System.Management.Automation.MethodInvocationException: Exception calling "ShouldContinue" with "2" argument(s): "The method or operation is not implemented." ---> System.NotImplementedException: The method or operation is not implemented.**

**Comment by ChrisLGardner** [comment]
Interesting, I'll look at modifying our check to handle cases where internet access isn't an option and fall back to the version of Pester that we ship with the extension. It'll probably be this weekend at the earliest before I can get to this.

**Comment by PsychoticCob** [comment]
Thanks. I love this product. You guys have done a great job!

Eric

**Comment by ChrisLGardner** [comment]
This has been fixed in the latest release 8.13.3
