### ISSUE TITLE
Log the api calls being made in XplatGenerateReleaseNotes

### ISSUE THREAD

**Issue by rajbos** [rfennell/AzurePipelines#448]
### Azure DevOps Extension you are using
XplatGenerateReleaseNotes

### Where are you running it?
- Azure DevOps Servicein a release

### Version of Extension/Task
Currently public version

### Question
Could you document or just log the API calls being made? I am searching for several properties that I want to add to the markdown file and this is rather hard to figure out. I've found some properties by looking at the API documentation, but I is so helpful to just run the API call (in the browser) and checking the information available from it. 
There are some references in the closed issues list, but that is still searching for the information in the dark.

Example 1: I want to show a link to the commit in the CSLOOP, but cannot find how to do so. 
Example 2: the name of the environment/stage we are running in with this task. 
Example 3:I  have found the link to the release definition: `${releaseDetails.releaseDefinition._links.web.href}`, but cannot find the link to the release itself.

**Comment by rfennell** [comment]
This Node versions uses the Azurew DevOps Node API to make the calls, so the task does not build the URL calls directly, so I cannot output them the log.

There is no reason you could not write a Node test harness to do you exploration in VSCode or similar. All the calls that are made to the API task code in this repo.

Also, I guess you could run a private build agent and have fiddler running, maybe, to  see the API calls. But I think I would write a local test harness.

Sorry I don't have a quicker answer

**Comment by rajbos** [comment]
Having the json objects you use visible in debug mode would help too :-). Fiddler doesn't pick up the calls because the agent runs in a different user space (IIRC). 

No experience with Node, how can I run the task from the commandline?

**Comment by rfennell** [comment]
The basic process is 

1. install Node 
2. you can then trasnpile with NPM
3. run you node App

The source code has tests that follow this basic model. I have written local tests that hit the end points with hard coded params

**Comment by rfennell** [comment]
I think I need to write a test harness to export the JSON objects, and it get it in the documentation, its is the only way

**Comment by rfennell** [comment]
I have knocked up a quick tool, you can find it in the tools folder in the repo

It outputs the whole **release** object returned. I will get this into the documentation (readme, wiki etc.), this will occur on the next release.

For now here it is, hope it helps

```
{ id: 1285,
  name: 'Release - 2969 Attempt 1',
  status: 2,
  createdOn: 2019-03-13T20:26:38.767Z,
  modifiedOn: 2019-03-13T20:26:38.767Z,
  modifiedBy:
   { displayName: 'Richard Fennell (Work MSA)',
     url:
      'https://spsprodeus24.vssps.visualstudio.com/Ac0efb61e-a937-42a0-9658-649757d55d46/_apis/Identities/b1fce0e9-fbf4-4202-bc09-a290def3e98b',
     _links: { avatar: [Object] },
     id: 'b1fce0e9-fbf4-4202-bc09-a290def3e98b',
     uniqueName: null,
     imageUrl: null,
     descriptor: 'aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj' },
  createdBy:
   { displayName: 'Richard Fennell (Work MSA)',
     url:
      'https://spsprodeus24.vssps.visualstudio.com/Ac0efb61e-a937-42a0-9658-649757d55d46/_apis/Identities/b1fce0e9-fbf4-4202-bc09-a290def3e98b',
     _links: { avatar: [Object] },
     id: 'b1fce0e9-fbf4-4202-bc09-a290def3e98b',
     uniqueName: null,
     imageUrl: null,
     descriptor: 'aad.NzQzY2UyODUtN2Q0Ny03YjNkLTk0ZGUtN2Q0YjA1ZGE5NDdj' },
  environments:
   [ { id: 3258,
       releaseId: 1285,
       name: 'Tests - Windows',
       status: 4,
       variables: {},
       variableGroups: [],
       preDeployApprovals: [Array],
       postDeployApprovals: [Array],
       preApprovalsSnapshot: [Object],
       postApprovalsSnapshot: [Object],
       deploySteps: [Array],
       rank: 1,
       definitionEnvironmentId: 58,
       environmentOptions: [Object],
       demands: [],
       conditions: [Array],
       createdOn: 2019-03-13T20:26:38.830Z,
       modifiedOn: 2019-03-13T20:28:16.267Z,
       workflowTasks: [],
       deployPhasesSnapshot: [Array],
       owner: [Object],
       schedules: [],
       release: [Object],
       releaseDefinition: [Object],
       releaseCreatedBy: [Object],
       triggerReason: 'ReleaseStarted',
       timeToDeploy: 1.6166666666666667,
       processParameters: {},
       preDeploymentGatesSnapshot: [Object],
       postDeploymentGatesSnapshot: [Object] },
     { id: 3259,
       releaseId: 1285,
       name: 'Add data for next run',
       status: 4,
       variables: {},
       variableGroups: [],
       preDeployApprovals: [Array],
       postDeployApprovals: [Array],
       preApprovalsSnapshot: [Object],
       postApprovalsSnapshot: [Object],
       deploySteps: [Array],
       rank: 2,
       definitionEnvironmentId: 61,
       environmentOptions: [Object],
       demands: [],
       conditions: [Array],
       createdOn: 2019-03-13T20:26:38.860Z,
       modifiedOn: 2019-03-13T20:28:07.877Z,
       workflowTasks: [],
       deployPhasesSnapshot: [Array],
       owner: [Object],
       schedules: [],
       release: [Object],
       releaseDefinition: [Object],
       releaseCreatedBy: [Object],
       triggerReason: 'ReleaseStarted',
       timeToDeploy: 1.4802166666666667,
       processParameters: {},
       preDeploymentGatesSnapshot: [Object],
       postDeploymentGatesSnapshot: [Object] } ],
  variables: { 'system.debug': { value: 'true' } },
  variableGroups: [],
  artifacts:
   [ { sourceId: '670b3a60-2021-47ab-a88b-d76ebd888a2f:53',
       type: 'Build',
       alias: 'AddCommitToRepo',
       definitionReference: [Object],
       isPrimary: true,
       isRetained: true },
     { sourceId:
        '670b3a60-2021-47ab-a88b-d76ebd888a2f:bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59',
       type: 'Git',
       alias: '_VSTSBuildTaskValidation',
       definitionReference: [Object],
       isRetained: false },
     { sourceId:
        'e0d0d2b2-6ff5-40a8-9dc7-3588e913cc50:rfennell/AzurePipelines',
       type: 'GitHub',
       alias: '_rfennell_AzurePipelines',
       definitionReference: [Object],
       isRetained: false } ],
  releaseDefinition:
   { id: 23,
     name: 'Validate - Git XplatGenerateReleaseNotes',
     path: '\\Testing',
     projectReference: null,
     url:
      'https://richardfennell.vsrm.visualstudio.com/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/Release/definitions/23',
     _links: { self: [Object], web: [Object] } },
  releaseDefinitionRevision: 28,
  description: '',
  reason: 1,
  releaseNameFormat: 'Release - $(Build.BuildNumber) Attempt $(rev:r)',
  keepForever: false,
  definitionSnapshotRevision: 1,
  logsContainerUrl:
   'https://richardfennell.vsrm.visualstudio.com/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/Release/releases/1285/logs',
  url:
   'https://richardfennell.vsrm.visualstudio.com/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/Release/releases/1285',
  _links:
   { self:
      { href:
         'https://richardfennell.vsrm.visualstudio.com/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/Release/releases/1285' },
     web:
      { href:
         'https://richardfennell.visualstudio.com/670b3a60-2021-47ab-a88b-d76ebd888a2f/_release?releaseId=1285&_a=release-summary' } },
  tags: [],
  triggeringArtifactAlias: null,
  projectReference: { id: '670b3a60-2021-47ab-a88b-d76ebd888a2f', name: null },
  properties: {} }

```

**Comment by rfennell** [comment]
I am going to close this issue, re-open if this is not enough

**Comment by rajbos** [comment]
Thanks, this already helps. For the other calls I've sort of reversed engineered the calls being made to the ones below. For me the loops are the place that are the hardest to find the correct information for.

## CSLOOP items:
[Builds - Get Changes Between Builds](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get%20changes%20between%20builds?view=azure-devops-rest-5.0#response)

## WILOOP items:
[Builds - Get Work Items Between Builds](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get%20work%20items%20between%20builds?view=azure-devops-rest-5.0#resourceref)

For example: I want to add links in the release notes to both the workitems and the changes.

For the workitems you can use the general format:
* https://dev.azure.com/ORGANIZATION/PROJECT/_workitems/edit/${widetail.id}

But for the commits this is not possible, since they are related to the branch used in the build. I haven't found out how to get that out of it.

**Comment by rfennell** [comment]
I can look at doing the same for the other call, or so can you the tool is in the /tools folder of this repo

To run

- Clone the repo
- Change into tool/exporttool folder
- npm install
- npm run build
- npm run app

And it runs, of you edit the .ts file, as you will need to as it points to my instance, rerun the last two command
