### ISSUE TITLE
GenerateReleaseNotesTask uses incorrect uri for release information

### ISSUE THREAD

**Issue by KapteinYvo** [rfennell/AzurePipelines#449]
### Azure DevOps Extension you are using
GenerateReleaseNotesTask

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.23.1

### Expected behaviour and actual behaviour
Expected: Get information about releases when running the task in a release pipeline with parameter Generate for only this Release set to False. 
Actual: Task breaks with a 404 (not found)

### Steps to reproduce the problem
Set parameter Generate for only this Release to False.

**Comment by rfennell** [comment]
This is associated with the PR #450 provided by @kapteinYvo

**Comment by rfennell** [comment]
Sorry poor admin - this was fixed in #422 and released
