### ISSUE TITLE
Version .NET Core Assemblies doesn't support VersionPrefix or VersionSuffix

### ISSUE THREAD

**Issue by jamesmcroft** [rfennell/AzurePipelines#451]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

Version .NET Core Assemblies

### Where are you running it?
*You can run the extensions in the cloud or on-premise*

- Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

2.7.2

### Expected behaviour and actual behaviour

Unsure whether this should be part of this extension or not, but as the Version .NET Core Assemblies task can be used to version .NET Standard csproj files for creating NuGet packages, it currently doesn't support the ability to set the version suffix value such as -alpha. 

e.g.
```xml
<Version>1.2.3-alpha</Version>
```

### Steps to reproduce the problem

- Configure a prerelease tag within the build variables where the tag contains the hypen, e.g. -alpha.
- Set the Version Number variable to $(Build.BuildNumber)$(PrereleaseTag)

When building the project, notice only the $(Build.BuildNumber) variable is used as part of the Version .NET Core Assemblies task.

**Comment by jamesmcroft** [comment]
So after taking a look at the typescript that makes up the extension, I realised my error.

I hadn't updated the Regex value in the advanced properties to match with the optional prerelease tags.

**Comment by rfennell** [comment]
@jamesmcroft on the advanced menu select the 'inject version' option. The version you pass into the version number parameter is now just used without any further regex processing. So you could just enter  $(Build.BuildNumber)$(PrereleaseTag) and it get used as is
