### ISSUE TITLE
XplatGenerateReleaseNotes loop by work item type

### ISSUE THREAD

**Issue by alanwales** [rfennell/AzurePipelines#454]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
- Azure DevOps Service

### Version of Extension/Task
v2

First of all great job! The release notes generation works really well and we will continue to use the task. It would really help to have the ability to loop through work item types like Features, Bugs etc. Filtering by Tag is great but our business users (who create the features and epics) will not remember to do this so we just want to show which features are part of the release using the Feature work item type. We could also then show a list of bugs fixed by using the Bug work item type etc

**Comment by rfennell** [comment]
This task is limited by what the Microsoft API returns for the 'differences between build xxx and yyy' call.

If user have not associated features with a commit, they won't be seen in the list.

I guess if users don't tag they won't add features either.

Or have I misunderstood?

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
