### ISSUE TITLE
Enhancement request: Use pre-installed Pester module

### ISSUE THREAD

**Issue by Novanet-** [rfennell/AzurePipelines#462]
## Azure DevOps Extension you are using
Pester

### Where are you running it?
TFS 2018

### Version of Extension/Task
V7

## Requirement

Re-add the task parameter where you specify a file path to an installed Pester module, for the task to use.
**Reason**: The maximum Pester version our code works with currently is 4.4.2, as the changes regarding signing in subsequent versions causes things to break, and we don't currently have the resources to address this. Therefore we haven't been able to upgrade to v8 of this task as the option to specify manually installed Pester module has been removed, leaving only the built-in version (4.6, which is too high), or downloading the latest version from the gallery (which is also too high).

Alternatively I guess maybe you could add a parameter to specify the maximum version of Pester to be used, and then when downloading the module from the gallery you could pass this value through like you can with -MaximumVersion when using Install-Module .

**Comment by ChrisLGardner** [comment]
That's something I'm going to do when I get time. Similar to how the Azure PS task works where you either specify latest or a version you need.

It's on my list for the next time I get a chance to work on it and will mean a breaking change to v9. It'll still fallback to whatever we ship when it can't get to the gallery.
________________________________

**Comment by Novanet-** [comment]
Ah ok that all sounds good.

**Comment by ChrisLGardner** [comment]
This is now being tracked over on the new repo for the new version of this task https://github.com/pester/AzureDevOpsExtension/issues/8
