### ISSUE TITLE
Enhancement request: Ability to specify working directory for Pester task

### ISSUE THREAD

**Issue by bergmeister** [rfennell/AzurePipelines#465]
### Azure DevOps Extension you are using

`richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8` (public, unmodified version)

### Where are you running it?

- Azure DevOps Service

### Version of Extension/Task

`richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8` (public, unmodified version)

### Expected behaviour and actual behaviour

I have Pester tests that I need to pass path parameters to it. I use the hashtable syntax using the `scriptFolder` property to pass those. Because of this I have to pre-pend `$(Build.SourcesDirectory\Path)`, which makes the parameters line very long in yaml.
It would be nice if there was a `workingDirectory` property that specified from which folder `Invoke-Pester` gets called.

cc @ChrisLGardner

**Comment by ChrisLGardner** [comment]
Tracking this over at https://github.com/pester/AzureDevOpsExtension/issues/9
