### ISSUE TITLE
Approval's Details 

### ISSUE THREAD

**Issue by sureshvr-work** [rfennell/AzurePipelines#472]
### Azure DevOps Extension you are using
Generates a release notes file in a format of your choice for Azure DevOps Pipeline Builds or Releases

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version: 3.0.8

Is there a way to get the Release approval's name, comments and date ?

i'm using the Generate Release note extension in the Release pipeline. As soon as Manager approve the release, this process will kicks in. I want to include who approved this release and details like comments, date etc.,

**Comment by rfennell** [comment]
This is the PowerShell based version of the task, and the API call is in the form

`https://vsrm.dev.azure.com/<org name>/<team project>/_apis/release/releases/<id>?api-version=3.0-preview`

If you run this in [Postman ](https://www.getpostman.com/) or call API in browser, you can see the JSON returned for  the release and work out the path required

Looking at this I think you will need something like

`$release.environments[index of stage interested in].preDeployApprovals.approvedby.displayname
$release.environments[index of stage interested in].preDeployApproval.comments
`
Hope that helps

**Comment by rfennell** [comment]
If this issue remains a problem please do not hesitate to re-open it
