### ISSUE TITLE
Version Regex parameter should not be mandatory field or hidden

### ISSUE THREAD

**Issue by DJHaose** [rfennell/AzurePipelines#473]
### Azure DevOps Extension you are using
- Version Assemblies

### Where are you running it?
- Azure DevOps

### Version of Extension/Task
- Latest from Marketplace

### Expected behaviour and actual behaviour
My objective is having a version number tracked by developers under the field `AssemblyVersion` (already checked in source code), another version number used by devops team, `AssemblyInformationalVersion` (modified by Version Assemblies to use Azure DevOps Pipeline Build Number)

- The attached screenshot outlines my expected behavior currently doesn't work unless I export the pipeline into JSON format remove RegEx filter then import as new build pipeline
![Version Assemblies](https://user-images.githubusercontent.com/13004969/56610642-ed01b280-65dd-11e9-957a-0920e2a4325c.png)
- Version RegEx Filter needs to be blank in my example, but it's required field
- Inject version set to true to disable RegEx validation of my Azure Build Number e.g. master.20190422.1. But checking this box also hides the RegEx Filter.

### Steps to reproduce the problem
- Repo with any .NET project with `[assembly: AssemblyInformationalVersion("")]` inside Assembly Information .cs file.
- Azure DevOps build pipeline with Version .NET Assemblies step before build step to replace `AssemblyInformationalVersion` with `$(Build.BuildNumber)`
- Looking at build artifact we don't see DLL/executable property -> Details tab -> Product Version field as Azure Pipeline Build Number

### Suggested solution
- Modify task.json, remove `required: true` for VersionRegex input
- Modify task.json, remove `visibleRule: InjectVersion = false` for VersionRegex input

**Comment by rfennell** [comment]
Thanks for bring this to my attention, and providing a solution. 

I think for consistency I should make the change for all the tasks in then extension

I will do this as soon as I have time

**Comment by rfennell** [comment]
I have made the changes you suggest to the Version .NET Assemblies task, and released as 2.11.2. Can't help thinking there is a better solution, clearing the versionregex parameter, or putting extra logic around its use, but your solution has the lease knock on effects.

Let me know if it works for you.

**Comment by DJHaose** [comment]
Just tested works as expected, thank you!!
