### ISSUE TITLE
Enhancement Request Release Notes Task: Prevent errors on parallel updates to the same wiki

### ISSUE THREAD

**Issue by rajbos** [rfennell/AzurePipelines#478]
### Azure DevOps Extension you are using
Generate Release Notes XPlatform 2.9.6

### Where are you running it?
- Azure DevOps Service

### Expected behaviour and actual behaviour
Running two parallel releases updating the same wiki will result in an error where:
1. the first task pulls the wiki repo, 
1. then the second task also pulls the wiki repo
1. the first task updates the repo and pushes it into Azure DevOps
1. the **second** task now also wants to push, but can't because the repo has been updated server side.

Not sure if you already rebase the repo (since you do a clean clone everytime), but checking if the repo has been updated between pulling and pushing seems like the correct step to prevent these errors. Since the wiki repo we have is 650 Mb I see that it takes 20 seconds to download it, hence the issue.

### Steps to reproduce the problem
Run to releases in parallel that will update the same wiki.

**Comment by rfennell** [comment]
I think this is more a WIKI updater issue. You are right a final pull before the update and push should reduce the window for the error to occur. But I think it is always going to exist unless I put in a retry?

**Comment by rajbos** [comment]
Agreed: it would only lessen the issue and it would still be possible to trigger the error. 
It would reduce the errors, and probably substantially 😄 .

**Comment by rfennell** [comment]
This was actually a one line change., I just took the chance to move to a YAML build and make some release pipeline changes, hence the number of aborted attempts.

It now does a git pull before the file write to disk to try to reduce concurrency issues

Release as 1.3.8

**Comment by rajbos** [comment]
Great! Thank you so much 👍👍

**Comment by rajbos** [comment]
Hi Richard,

if I look inside Azure DevOps is see that we are running the extension with version 2.9.6 (`Generate Release Notes XPlatform`). On the marketplace, this is listed as the current version and as Last updated on 4/17/2019, 4:45:20 PM.

Can I update it somehow? And what is the disconnect between 2.9.6 and the 1.3.8 you mention?

**Comment by rfennell** [comment]
You can see all the history of the release https://dev.azure.com/richardfennell/GitHub/_release?definitionId=13 and obviously in this repo.

There was a major refactor between V1 and V2, that was done over a year ago done by @gregpakes. I shipped both version in the package for best part of a year, just in case any breaking issue. But an effort was made to avoid any breaking changes in templates.

I did not see any issues so to reduce my support surface I dropped the V1 the package as V2 had the many more features. 

That answer the question?

**Comment by rajbos** [comment]
Sorry, completely missed the fact that you updated the [WIKI updater task](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WIKIUpdater-Tasks) ! I was diffing with the `Generate release notes task`!

**Comment by rfennell** [comment]
OK, so I guess you are OK?

**Comment by rajbos** [comment]
Need some more testing, we thought we had the same behavior, hence the search for the correct version. Will let you know.

**Comment by luizfdias** [comment]
It seems this problem still exists. When working with multiple releases at the same time, I get the following message:

2020-08-28T08:25:58.8529213Z ##[error]Error: To https://***.visualstudio.com/***/_git/***.wiki
 ! [remote rejected] wikiMaster -> wikiMaster (TF401028: The reference 'refs/heads/wikiMaster' has already been updated by another client, so you cannot update it. Please try again.)
error: failed to push some refs to 'https://***.visualstudio.com/***/_git/***.wiki'

2020-08-28T08:25:58.8544992Z ##[error]Error: To https://***.visualstudio.com/***/_git/***.wiki
 ! [remote rejected] wikiMaster -> wikiMaster (TF401028: The reference 'refs/heads/wikiMaster' has already been updated by another client, so you cannot update it. Please try again.)
error: failed to push some refs to 'https://greenflux.visualstudio.com/***/_git/***.wiki'


WIKI Updated Task Version: 1.14.4.
