### ISSUE TITLE
Use of Newer api-version Breaks Compatibility with TFS 2017

### ISSUE THREAD

**Issue by mesheets** [rfennell/AzurePipelines#479]
### Azure DevOps Extension you are using
Set Variable on a Build Definition

### Where are you running it?
TFS 2017 Version 15.117.27414.0

### Version of Extension/Task
richardfennellBM.BM-VSTS-BuildUpdating-Tasks-1.13.11.vsix

### Expected behaviour and actual behaviour
Attempting to run the Set Variable on a Build Definition task to increment a build variable fails with the following error message: "Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found"

### Steps to reproduce the problem
1. Install richardfennellBM.BM-VSTS-BuildUpdating-Tasks-1.13.11.vsix on TFS 2017 Version 15.117.27414.0
2. Include the Set Variable on a Build Definition task in a build definition
3. Configure the Set Variable on a Build Definition task to increment a build variable
4. Save and queue the build definition

### Additional information
On TFS 2017 Version 15.117.27414.0, I was encountering this issue and seemed to have traced it down to this commit to [Update to use api-version4](https://github.com/rfennell/AzurePipelines/commit/19f489ba140456c66174b385ca85120db2fed544#diff-765596521f90e301d3fd98e2a7f78de7) that broke compatibility with TFS 2017.  If the api-version is 2.0 (as it was prior to that commit) or even 3.0, it works, but with api-version set to 4.0, the action fails and the error message cited in this issue title is returned.

The VSIX file is richardfennellBM.BM-VSTS-BuildUpdating-Tasks-1.13.11.vsix, which is what is downloaded from https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-BuildUpdating-Tasks for on-premises installs.

In the  "Version" options for the "Set Variable on a Build Definition" task, the only option is "1.*"

If there was a way to download the last VSIX prior that commit, that might even suffice, but I haven't yet found a way to download earlier versions——Marketplace always seems to push the latest release.

**Comment by rfennell** [comment]
I have all the old VSIX package in the build systems, so can upload the one previous to the one you want, I think it will 1.4.1 judging by the date, so around April of last year

You can download the VSIX packages direct from the build https://dev.azure.com/richardfennell/GitHub/_build/results?buildId=1104 

The ZIP will have a private  (-DEV) and public version of the VSIX, you need the public version for TFS

You also have access to older and newer builds too, but I think that is the one where the change occur judging by date. The 1.5.x and onwards is when the API change occured
