### ISSUE TITLE
Task is Updating Referenced NuGet Package versions causing the build to fail, 2019 edition

### ISSUE THREAD

**Issue by Rzpeg** [rfennell/AzurePipelines#483]
Hey.
I am experiencing exactly the same issue as https://github.com/rfennell/AzurePipelines/issues/183

### Azure DevOps Extension you are using
VersionDotNetCoreAssembliesTask@2 AND VersionAssembliesTask@2 

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service

### Version of Extension/Task
Currently public version, @2

### Expected behaviour and actual behaviour
_Expected_
DotNet core related version numbers are updated in the csproj

_Actual_
DotNet core and referenced NuGet package versions are being updated in the csproj

### Steps to reproduce the problem
1. VersionDotNetCoreAssemblies@2
2. NuGetCommand@2 /restore
3. VSBuild@1

**Comment by Rzpeg** [comment]
Experiencing the same issue now on Azure DevOps. The task is updating the referenced NuGet package versions. Maybe you should update the script to ignore the Version tag if inside the PackageReference tag ? At the moment, this gets updated:

```
  <PackageReference Include="Serilog.Exceptions">
      <Version>4.1.0</Version>
    </PackageReference>
```

**Comment by rfennell** [comment]
I will get a test written to repo the problem, and look for a fix

**Comment by Rzpeg** [comment]
@rfennell
Thanks in advance.

**Comment by rfennell** [comment]
I am struggling to repo the problem. I have a unit test that processes the following file

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>VersionedLibrary</AssemblyName>
    <AssemblyVersion>1.2.3.4</AssemblyVersion>
    <Description>A description</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Serilog.Exceptions">
      <Version>4.1.0</Version>
    </PackageReference>
  </ItemGroup>

</Project>


```

I expect the 1.2.3.4 to be changed and nother else, which is in the case in my test.

Could you provide the whole of your .csproj and also what setting are you using for the task, just to make sure I am running the same config. I am assuming I have missed an edge case

**Comment by Rzpeg** [comment]
That's strange. Maybe it's the other plugin? We run different plugins in the same time
Here's our config:

- task: VersionAssemblies@2
  displayName: Versioning (.NET Framework)
  inputs: 
      Path: '$(Build.SourcesDirectory)'
      VersionNumber: '$(Build.BuildNumber)'
      InjectVersion: false
      VersionRegex: '\d+\.\d+\.\d+\.\d+'
      FilenamePattern: 'AssemblyInfo.*'

- task: VersionDotNetCoreAssemblies@2
  displayName: Versioning (.NET Core)
  inputs: 
     Path: '$(Build.SourcesDirectory)'
     VersionNumber: '$(Build.BuildNumber)'
     Injectversion: false
     VersionRegex: '\d+\.\d+\.\d+\.\d+'
     FilenamePattern: '.csproj'

- task: VersionJSONFile@2
  displayName: Versioning (NPM package.json)
  inputs: 
     Path: '$(Build.SourcesDirectory)'
     VersionNumber: '$(Build.BuildNumber)'
     VersionRegex: '\d+\.\d+\.\d+\.\d+'
     FilenamePattern: 'package.json'
     versionForJSONFileFormat: '{1}.{2}.{3}.{4}'

- task: VersionAngularFile@2
  displayName: Versioning (Angular environment.stg.ts)
  inputs: 
     Path: '$(Build.SourcesDirectory)'
     VersionNumber: '$(Build.BuildNumber)'
     Injectversion: false
     VersionRegex: '\d+\.\d+\.\d+\.\d+'
     FilenamePattern: 'environment.stg.ts'
     versionForJSONFileFormat: '{1}.{2}.{3}.{4}'

- task: VersionAngularFile@2
  displayName: Versioning (Angular environment.prod.ts)
  inputs: 
     Path: '$(Build.SourcesDirectory)'
     VersionNumber: '$(Build.BuildNumber)'
     Injectversion: false
     VersionRegex: '\d+\.\d+\.\d+\.\d+'
     FilenamePattern: 'environment.prod.ts'
     versionForJSONFileFormat: '{1}.{2}.{3}.{4}'

**Comment by rfennell** [comment]
Got a nice repo now, not sure what happened before.

The only way to fix this is to move to Xpath parsing, which is a complete rewrite. Needs to go on the backlog, but not sure when I will have time

**Comment by Rzpeg** [comment]
There might be a way to do this with regex.
We need only version tags inside the PropertyGroup which contains our project version tags, not ItemGroup which contain our nugets.
using regex `<PropertyGroup.*>((.|\n)*?)<\/PropertyGroup>` you can get the needed group, 
and then using this regex over the resulting group `<Version.*>((.*)*?)<\/Version>` to get the version

**Comment by rfennell** [comment]
Oh, nice, let me try

Your regrex skills are obviously better than mine

**Comment by rfennell** [comment]
@Rzpeg Should be fixed in 2.11.11

As side note you can use 

`<PropertyGroup.*>((.|\n)*?)<\/PropertyGroup>
`
This is find in regex testers but fails in node. The answer turned out to be

`<PropertyGroup>([\s\S]*?)<\/PropertyGroup>`

Let me know how it goes for you

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while.

**Comment by Rzpeg** [comment]
@rfennell Thanks! Can't verify - I've refactored every csproj, like I mentioned before.

**Comment by rfennell** [comment]
That's fine, thanks for finding the issue
