### ISSUE TITLE
Unable to run extension with no internet connection

### ISSUE THREAD

**Issue by Scott-Emberson** [rfennell/AzurePipelines#493]
### Azure DevOps Extension you are using
Generate Release Notes Build Task

### Where are you running it?
- Team Foundation Server 2017.3

### Version of Extension/Task
3.0.8

### Question
Is it possible to run this extension on a server where there is no internet, if not can you please tell me what URL/Server it is calling?

**Comment by rfennell** [comment]
Yes you can, the easiest way to find the API calls is to look at the generate release notes powershell modules in this repo. But it is basically just the build details and release details
