### ISSUE TITLE
Suggestion: Each template needs an image to show what its output would look like

### ISSUE THREAD

**Issue by yannduran** [rfennell/AzurePipelines#499]

**Comment by rfennell** [comment]
What is the context for this? Which extension.

If it is either of the release notes ones a preview is not viable
- the template is hugely variable so would have to be generated
- if generated where would it be shown? There is no option in the pipelines UI or YAML

I tend to preview in a Markdown editor of my choice, such as VSCode, outside the pipeline process

**Comment by yannduran** [comment]
Sorry about that! I meant for the **sample templates**. And I meant for the images to be in the same _SampleTemplates_ folder here in this repo.

If there were an image for each sample template, it would make it much easier to see if any of them look like they'd be useful. Or if maybe they could be modified to suit. Otherwise it means installing **each template** and trying them out.

Thanks!

**Comment by rfennell** [comment]
No sure how useful this would be, at least to me, as it is easy to just load the markdown in you editor of choice to have a look at the basic layout. 

I am not sure putting a PNG in the file is that discoverable in GitHub

The templates are only meant to be a basic starting point.

**Comment by yannduran** [comment]
Thanks for the reply Richard!

I had a look at the md files and nothing made any sense to me, so I guess I'm in the wrong place :-)
