### ISSUE TITLE
Error Deserialize Invalid JSON primitive

### ISSUE THREAD

**Issue by Ludo-CVS** [rfennell/AzurePipelines#503]
### Azure DevOps Extension you are using
Generate Release Notes Build Task 

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Last pubic

### Expected behaviour and actual behaviour
[tasklog_5.log](https://github.com/rfennell/AzurePipelines/files/3247524/tasklog_5.log)

### Steps to reproduce the problem
Process CD VSTS

**Comment by rfennell** [comment]
If you enter the following URL, from the script in browser, as a user with suitable creds i.e. can login to the Azure DevOps organsiation

`https://vsrm.dev.azure.com/lcouveignes//POC_Deploiement_Function_Azure/_apis/release/releases/48?api-version=3.0-preview`

It should list some JSON, my guess is it will not and will give an error message.

Also try 

`https://vsrm.dev.azure.com/lcouveignes//POC_Deploiement_Function_Azure/_apis/release/releases?api-version=3.0-preview`

This should show all the releases available. 

It looks like an access problem.

Other option is to try my newer [Cross platform version](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) that uses newer API calls

**Comment by Ludo-CVS** [comment]
his url is automatically automatically. I can not parameter.
How can I solve the problem of access?

**Comment by rfennell** [comment]
The build/release agent is presumably running as a user in the build service accounts group. By default members of this group should have access to the API. So I am surprised you are seeing this problem.

A few things to check
- who is the build agent running as, can they see this URL
- do you get the same problems with the Microsoft hosted build agent

**Comment by rfennell** [comment]
As you are asking question about uploading the results of this task, can I assume you are work?

if so can you provide details of the solution in this call in case it help others in the future

**Comment by Ludo-CVS** [comment]
I work with azure devops online.
After nothing special about my Ci / CD

**Comment by rfennell** [comment]
When it works with hosted but not with private it usually means

- rights on the Agent PC
- rights of the account running the agent
- firewalls blocking calls

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
