### ISSUE TITLE
WIKI Updater Tasks : Error  The path used to clone the repo vsts

### ISSUE THREAD

**Issue by Ludo-CVS** [rfennell/AzurePipelines#504]
### Azure DevOps Extension you are using
WIKI Updater Tasks

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Last public

### Expected behaviour and actual behaviour
[tasklog_6.log](https://github.com/rfennell/AzurePipelines/files/3247956/tasklog_6.log)

**Comment by rfennell** [comment]
The log shows it is a security issue, the agent account has no permissions to access the repo

```
019-06-03T14:06:36.6689654Z fatal: unable to update url base from redirection:
2019-06-03T14:06:36.6690228Z   asked for: https://buildagent:***@dev.azure.com/lcouveignes/POC_Deploiement_Function_Azure/_wiki/wikis/POC_Deploiement_Function_Azure.wiki/info/refs?service=git-upload-pack
2019-06-03T14:06:36.6693434Z    redirect: https://spsprodweu2.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Flcouveignes%2FPOC_Deploiement_Function_Azure%2F_wiki%2Fwikis%2FPOC_Deploiement_Function_Azure.wiki%2Finfo%2Frefs%3Fservice%3Dgit-upload-pack&redirect=1&aadinmsa=true&hid=f8f09c97-638f-4bd9-b7b1-bb766e8a977c&context=eyJodCI6MiwiaGlkIjoiYWU1OGMxODktNzI0ZC00OTJkLTlmYjUtZmE1OWVlNGIwMTgyIiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
2
```
You need to grant the build agent user at least read permissions, or provide a PAT in the password field, [see](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks)

**Comment by Ludo-CVS** [comment]
the agent account has permissions to access but he write the release note file to $(System.DefaultWorkingDirectory)

**Comment by rfennell** [comment]
To use the built in security you have to enable OAUTH for the release, see the wiki, but the key point is

> UseAgentToken - If true the task will use the built in agent OAUTH token, if false you need to provide username & password/PAT". __Note for use of the OAUTH token to work you must allow the pipeline to access the OAUTH Token and grant contribute access to target Azure DevOps WIKI to the Project Collection Build Service user (assuming this is the account the pipeline is running as). The default is false__

**Comment by Ludo-CVS** [comment]
Here are the permissions of my agent.
![Capture](https://user-images.githubusercontent.com/51324515/58863025-41ef1900-86b2-11e9-85f8-3aeb8ba4cc2f.PNG).

**Comment by rfennell** [comment]
I think you missed the point.

On the wiki updater task select to use the agent creds
![Capture2](https://user-images.githubusercontent.com/324718/58866998-980f8c80-86b1-11e9-8101-e8f588ecdcd5.PNG)

And for the agent stage make sure oAuth is configured
![Capture](https://user-images.githubusercontent.com/324718/58867041-a8c00280-86b1-11e9-860d-4339459ebd21.PNG)

You can see a sample on my release pipeline for this extension in the test stage at https://dev.azure.com/richardfennell/GitHub/_releaseProgress?_a=release-pipeline-progress&releaseId=1420

**Comment by Ludo-CVS** [comment]
Here is my configuration of my release

![Capture](https://user-images.githubusercontent.com/51324515/58872880-453fd000-86c5-11e9-895f-2290a1e93aeb.PNG)
![Capture2](https://user-images.githubusercontent.com/51324515/58872881-45d86680-86c5-11e9-9649-e47da4449156.PNG)

**Comment by rfennell** [comment]
A q[uick search of Stackoverflow shows](https://stackoverflow.com/questions/43835309/git-push-gives-fatal-unable-to-update-url-base-from-redirection) the error your log shows is usually down to a bad repo url

Given this not sure about your target Git url

`Variable: Repo [dev.azure.com/lcouveignes/POC_Deploiement_Function_Azure/_wiki/wikis/POC_Deploiement_Function_Azure.wiki]`

should it not be
`Variable: Repo [dev.azure.com/lcouveignes/POC_Deploiement_Function_Azure/_git/POC_Deploiement_Function_Azure.wiki]`

as this is the form of my test one 

`Variable: Repo [dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki]`

**Comment by Ludo-CVS** [comment]
This is a git repository, I want to put it on a TFS repository...

**Comment by rfennell** [comment]
Do you mean TFVC? 

... if so the tool only support Git based repos, as the documentation says either on GitHub or Azure DevOps. if you want to upload to any other location you will need to write some PowerShell or find another task.

Otherwise I can assure you the sample I sent to is a WIKI hosted on Azure DevOps.

**Comment by Ludo-CVS** [comment]
OK thanks you

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
