### ISSUE TITLE
Enhancement request: Allow filtering based on work item fields

### ISSUE THREAD

**Issue by enufacas** [rfennell/AzurePipelines#505]
### Azure DevOps Extension you are using
GenerateReleaseNotes (XPlat version)

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Expected behaviour and actual behaviour
First want to say the GenerateReleaseNotes extension is awesome.
 
Second, have you considered the ability to allow filtering of items based off of work item fields in addition to the current ability to filter based on a tag? In my case I am using a custom defined field to decorate work items as user consumable\needed for release notes.  It's just a true\false bool I have added to my work item templates. My plan is to work around it for now with a script that will add a given tag based on the bool being set. 

Thanks again for the time

**Comment by rfennell** [comment]
I see no reason why this is not possible, but I fear a boolean based model might be a bit specific to your usage. Something where there is a `field:ABC=999` might be more useful. It's ca case of sorting a tidy syntax

I have no immediate plans to do this, but will leave it on the backlog. Always happy to consider PRs

**Comment by CodeRevver** [comment]
+1 on this.  Ideally I'd like to be able to filter out Tasks so that the release notes only include user stories and bugs

**Comment by pomarc** [comment]
+1, I'd like to have separate sections of the release notes document for Bugs, PBIs... so a filetr like `@@WILOOP:fields.'System.WorkItemType'="Issue" `would be super cool.

ah, yes, the extension is awesome.

**Comment by rfennell** [comment]
Release in 2.19.17 [see wiki for usage](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task)
