### ISSUE TITLE
PowerShell Gallery Exception Fails Pester Test Runner Task

### ISSUE THREAD

**Issue by iainbrighton** [rfennell/AzurePipelines#507]
### Azure DevOps Extension you are using
Pester Test Runner

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
8.13.3

### Expected behaviour and actual behaviour
When there is problem communicating with the PowerShell Gallery to download the latest version of Pester and an exception is generated, the task fails. The bundled/fallback version is used and the Pester tests still complete, but the exception still causes the task to fail.

![image](https://user-images.githubusercontent.com/7023258/59287344-61191800-8c69-11e9-9c5f-1664cdb4fbc5.png)

![image](https://user-images.githubusercontent.com/7023258/59287455-97569780-8c69-11e9-8746-58cc9b70b30d.png)

**Comment by ChrisLGardner** [comment]
This should be fixed now with release 8.14.5
