### ISSUE TITLE
Not working on Hosted Ubuntu 1604 Build Agent

### ISSUE THREAD

**Issue by DaveKLloyd** [rfennell/AzurePipelines#512]
### Azure DevOps Extension you are using
I am using [GenerateReleaseNotes Node based Cross Platform Task](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task)

### Where are you running it?
On Azure DevOps

### Version of Extension/Task
Version 2.9.6

### Expected behaviour and actual behaviour
Trying to run it on a **Hosted Ubuntu 1604** build agent
I am getting this error: 
The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

The Wiki says: **Can be used on any type of release agents (Windows, Mac or linux)**

### Steps to reproduce the problem
I trimmed back the template just to try and get past this issue to this. 

```
# Release notes
## Notes for release  ${releaseDetails.releaseDefinition.name}
**Release Number**  : ${releaseDetails.name}
**Release completed** : ${releaseDetails.modifiedOn}
**Compared Release Number**  : ${compareReleaseDetails.name}
```

**Comment by rfennell** [comment]
Strange it should work, I have tests on Linux hosted VM, winder if they have been updated in some way?

I need to test it, I will gt back to you

**Comment by rfennell** [comment]
I have just done a test run using a validation release I had and the Generate release notes step worked fine. The following email step errored, but this because that is defiantly Windows specific.

You can see my logs here https://dev.azure.com/richardfennell/GitHub/_releaseProgress?_a=release-environment-logs&releaseId=1446&environmentId=3809, the test project is public

The template was

```
## Notes for release  ${releaseDetails.releaseDefinition.name}    
**Release Number**  : ${releaseDetails.name}    
**Release completed** : ${releaseDetails.modifiedOn}     
** Build Number**: $(Build.BuildNumber)
**Compared Release Number**  : ${compareReleaseDetails.name}    

### All associated work items  
@@WILOOP@@  
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
@@WILOOP@@  

### Associated work items with 'Tag 1' 
@@WILOOP:TAG 1@@  
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
@@WILOOP:TAG 1@@  

### Associated work items with 'Tag 1' and 'Tag 2' 
@@WILOOP:TAG 1:TAG2@@  
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
@@WILOOP:TAG 1:TAG2@@    

### Associated work items with 'Tag 2' and 'Tag 1' 
@@WILOOP:TAG2:TAG 1@@  
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
@@WILOOP:TAG 1:TAG2@@    
  
### Associated commits
@@CSLOOP@@  
* ** ID ${csdetail.id} ** ${csdetail.message}    
@@CSLOOP@@

```

Can you check the top of the release notes task log and make sure you are not using the older Windows specific version. It is easy to get them confused in the marketplace and task editor. I really should ave done something better with the names

**Comment by DlloydAtRogers** [comment]
Thanks for this. I had moved it into a separate agent Job that used a hosted windows agent, and I played around with it there. Then I saw your response and moved it back into the ubuntu agent and now it works. :) I have no idea what else I did. It's definitely the Cross platform version.

**Comment by rfennell** [comment]
Strange, lets call this one closed then? 

Put it down to the strange world of devops!
