### ISSUE TITLE
Cant Find the task in "Add Step"

### ISSUE THREAD

**Issue by Yonnatan** [rfennell/AzurePipelines#513]
Azure DevOps Extension you are using?
Generate Release Notes (Crossplatform)

Where are you running it?
Azure DevOps Service (VSTS) On Prem

Expected behaviour and actual behaviour?
Expecting to find the Task on a Build Job , but i only see the PS Version option and not the Xplatform.

Steps to reproduce the problem
Install Extension , Edit a Build , search for Generate Release Notes task , find only the PS version.

Let me know if i can provide any more information.
Tried to Uninstall the PS Version thinking maybe they collide somehow , and reinstalled the Xplatform version , did not help .

**Comment by rfennell** [comment]
The cross platform version is only supported in releases, not builds.

I think this is best place to do release notes, but if you must generate them in a release then try not older Generate Release notes (powershell version)
