### ISSUE TITLE
Generate Release Notes failing 

### ISSUE THREAD

**Issue by scriptmonkey69** [rfennell/AzurePipelines#516]
I am running the Generate Release notes extension in Azure DevOps using the current version. 
The extension is configured using a standard template from the Marketplace website for the Generate Release Notes extension.

The attached file is the complete log for the extension execution.

[GRN Issue.txt](https://github.com/rfennell/AzurePipelines/files/3434270/GRN.Issue.txt)

**Comment by scriptmonkey69** [comment]
Ok I found the solution myself, basically the server was being forced by a registry setting to use TLS 1.2, so I had to enabled TLS 1.2 for Powershell and make it the default.

The following link explains the issue and provides 2 powershell commands required to update the registry.

https://johnlouros.com/blog/enabling-strong-cryptography-for-all-dot-net-applications

**Comment by rfennell** [comment]
Thanks for providing the solution
