### ISSUE TITLE
Warning on task execution handler Windows Agent

### ISSUE THREAD

**Issue by ramu20061992** [rfennell/AzurePipelines#517]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

StyleCop Runner Build Task by Richard Fennell (Black Marble) extention.Task is StyleCop Runner
### Where are you running it?
*You can run the extensions in the cloud or on-premise*
Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*
3
### Expected behaviour and actual behaviour
Should not be warning as Task 'StyleCop' (3.0.2) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
### Steps to reproduce the problem
Just run the task in Classic Designer mode of Build pipeline

**Comment by rfennell** [comment]
Yep, should have migrated that one by now. I will get it done as soon as I can

**Comment by ramu20061992** [comment]
Thanks for the update. Also one one observation from my side. In StyleCop Runner task,Warning messages are not VSTS warning text  and hence we could not see explicit warning count in task executor summary. Could you please look at it ?

**Comment by rfennell** [comment]
@ramu20061992 off the top of my head, I am not sure how much I can do about that, as the Azure DevOps task just wrappers an instance of the StyleCop Console which handles the output. All the task does is attach the logs to the build. However, I will have a look to see what  can do whilst moving the task to the PS3 execution engine.

To to let you know too, I am considering marking this task as deprecated once I complete these updates. I not longer use it myself, we moved to SonarQube for analysis a good while ago, and I don't really have the time to support it. As a depricated task it will still be available and functional, but I won't be offering support.

**Comment by StingyJack** [comment]
@rfennell - this shows up on the Version Assemblies task as well. 
![image](https://user-images.githubusercontent.com/15381181/62380697-b827c480-b517-11e9-9853-293cc021a366.png)

Do you want a separate issue logged for that task?

**Comment by rfennell** [comment]
@StingyJack thanks for reporting the Versioning task, I am aware it is an issue for all my older tasks and am currently in the process of fixing them.

**Comment by rfennell** [comment]
The StyleCop task has been moved to the PS3 engine.

I have looked at the logging,  as the warning are generated within the StylecCop console I can see no quick way to address the logging them out as Azure DevOps warnings.

As I have to move an number of other tasks to PS3 execution, I am not going to investigate any further at this time.

Released a 3.1.5
