### ISSUE TITLE
FileCopy Task Bug - File type parameter not working

### ISSUE THREAD

**Issue by rudisugi** [rfennell/AzurePipelines#535]
### Azure DevOps Extension you are using
This is for the FileCopy task, version 3.3.14

### Where are you running it?
I'm running this task on TFS 2017 on premise Version 15.117.27024.0

### Version of Extension/Task
V3.3.14

### Expected behaviour and actual behaviour
When we specify file type with comma delimited, it should restrict the file copy to just those specific file types (extension). We've provided the parameter like this: *.ps1,*.wsp and it will be ignored. I checked the powershell code behind this task and it seems that the file type parameter is not included as part of the powershell parameter declaration, therefore any value pass to it will be gone/unused.

### Steps to reproduce the problem
Put in any string into File Type field and the task will not use it

**Comment by rfennell** [comment]
That sounds like a bug, I will investigate when I get a chance

**Comment by rfennell** [comment]
I have a repo, looking at a fix now

**Comment by rudisugi** [comment]
I replaced line 15 in the FileCopy.ps1 with the following:
$includeInput = Get-VstsInput -Name "include"

and that seems to correct the problem.

**Comment by rfennell** [comment]
Yes that should be the basis of a fix. Guess you are the first person to use that option

**Comment by rfennell** [comment]
release as 3.4.1
