### ISSUE TITLE
Build Update Retention Task does not appear in On-Premise TFS

### ISSUE THREAD

**Issue by SchulzDL** [rfennell/AzurePipelines#537]
### Azure DevOps Extension you are using
Build Update Tasks - specifically the Build Update Retention Task

### Where are you running it?
On-premise TFS 2018 Update 4

### Version of Extension/Task
1.16.1

### Expected behaviour and actual behavior
That I would see this task in the list of available tasks to perform. 

### Steps to reproduce the problem
 There are two other tasks that are part of this extension for variable tasks and I see both of those but the Retention Task does not appear.  Is there some reason that this would be the case that two of the tasks would appear in the list and one would not?

**Comment by rfennell** [comment]
This task is set, via the [task manifest](https://github.com/rfennell/AzurePipelines/blob/master/Extensions/BuildUpdating/BuildRetensionTask/task.json), to only be available in releases.

The other two tasks in the extension are set to run in builds and releases

**Comment by rfennell** [comment]
@SchulzDL I have been thinking, I am assuming you have a use case for setting build retention within a build. The reason the task does not allow this is because I did not have one. Do you think it is worth changing the flag?

It is worth noting that these build/release usage flags in the manifest are ignored if you are using a YAML build, so that is a wotkaround

**Comment by SchulzDL** [comment]
Hi Richard,

Thanks for thinking about this.  I have a client where they can’t really use the release pipelines just yet.  They have different branches and builds for their dev/test and release paths.  When they build this final build they wanted that build to be locked and are doing this as the last step of this release build.  They are on TFS 2018 and YAML builds are not there yet.  When they upgrade to Azure DevOps Server 2019, I guess the YAML could be an alternative.  However, they would really like to start using this task now.

Thanks

Donald Schulz<sip:dschulz@imaginet.com>
Senior DevOps Consultant  |  Imaginet<http://www.imaginet.com/>  | MCTS, MCP
dschulz@imaginet.com<mailto:dschulz@imaginet.com>  |  P 972.607.4836  |  C 805.813.1829  |  tw: @justimaginet<http://www.twitter.com/justimaginet>  |  fb: justimaginet<http://www.facebook.com/justimaginet>

**Comment by rfennell** [comment]
I will make the change to the manifest to enable the task in builds. I just need to check it will work, as it was not designed to

**Comment by SchulzDL** [comment]
Thanks Richard

Donald Schulz<sip:dschulz@imaginet.com>
Senior DevOps Consultant  |  Imaginet<http://www.imaginet.com/>  | MCTS, MCP
dschulz@imaginet.com<mailto:dschulz@imaginet.com>  |  P 972.607.4836  |  C 805.813.1829  |  tw: @justimaginet<http://www.twitter.com/justimaginet>  |  fb: justimaginet<http://www.facebook.com/justimaginet>

**Comment by rfennell** [comment]
1.17.5 has the change, the build retension task can now be used in a build to set the build's own retension. 

All the other options for artifact selection are invalid in a build as they require access to details only stored in a release

Let me know how it goes

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
