### ISSUE TITLE
VersionDotNetCoreAssemblies doesn't support SDK style projects which don't use Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by jamesmcroft** [rfennell/AzurePipelines#543]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

Versioning

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

2.16.3

### Expected behaviour and actual behaviour

Expected .NET Standard .csproj to be updated with build version number.

Actual .NET Standard .csproj wasn't updated with build version number, possibly due to the SDK not being Microsoft.NET.Sdk

### Steps to reproduce the problem

Create a new .NET project using the SDK style .csproj format (e.g. .NET Core or .NET Standard). 

Change the SDK that is being used from Microsoft.NET.Sdk to an alternative.

Run Version .NET Core Assemblies over project.

Notice in the logs that it didn't detect the project and skipped over it
> Skipping file `GalaSoft.MvvmLight.csproj` as is not a .NETCore Project

Example of .NET Standard project using alternate SDK - https://github.com/jamesmcroft/mvvmlight/blob/master/GalaSoft.MvvmLight/GalaSoft.MvvmLight/GalaSoft.MvvmLight.csproj

**Comment by rfennell** [comment]
This has been released in 2.17.4  - allows a string separated lists of namespaces. It defaults to Microsoft.NET.Sdk
