### ISSUE TITLE
When using the Wiki updater, .md is overwritten

### ISSUE THREAD

**Issue by Danbuhr** [rfennell/AzurePipelines#545]
### Where are you running it?
cloud
- Azure DevOps Service (VSTS)

### Version of Extension/Task
1.5.1

### Expected behaviour and actual behaviour

When pushing new data to existing .md file in the wiki, it should be appended.

Instead the files are overwritten. Not sure if fs.writefilesync flag is set correctly for append?

### Steps to reproduce the problem

Push data to same .md file twice..

Maybe there could be a flag on the task overwrite/append?

**Comment by rfennell** [comment]
Had a quick look at the code, that should not be too hard. I will try to get it done ASAP

**Comment by rfennell** [comment]
I have released 1.6.2 with the option to append. The default remains override

**Comment by Danbuhr** [comment]
Amazing! Thx so much, and thx for the super-fast response time - great!

**Comment by rfennell** [comment]
Glad you find the extension useful
