### ISSUE TITLE
Pester Test Runner Build Task: Not handing off to next task if pester return a failed test

### ISSUE THREAD

**Issue by mortenlerudjordet** [rfennell/AzurePipelines#548]
### Azure DevOps Extension you are using
Pester Test Runner Build Task

### Where are you running it?
Hosted Agent (windows-2019, vs2017-win2016, win1803)

### Version of Extension/Task
Latest published through VS marketplace

### Expected behaviour and actual behaviour
Running Pester test with no failure works as expected

Running pester test that returns a failure will stall the task indefinitely.
Last logged using debug:
```
##[error]Microsoft.PowerShell.Commands.WriteErrorException: Pester returned errors
##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.PowerShell.Commands.WriteErrorException: Pester returned errors
``` 
After this the task will keep on running and never move on even with "continue on error" set.

### Steps to reproduce the problem

Have the task execute an pester test with a failure
See the message:
```
##[error]Microsoft.PowerShell.Commands.WriteErrorException: Pester returned errors
```
Then observe that the task will not end, nor move on to the next task in pipeline.
Adding a timeout value on the task will force it to move on, and result of the failed pester test is as expected.

Maybe there is something I'm doing wrong, so please correct me if I'm in error here.

**Comment by ChrisLGardner** [comment]
I haven't seen any issues with this, if it's still and issue @mortenlerudjordet can you raise an issue over at https://github.com/pester/AzureDevOpsExtension where the new version will be based. If you can include some examples of the tests you've got and a debug log of a test run then that would help track down what might be happening.
