### ISSUE TITLE
Version .NET Core Assemblies - cant handle csproj files without <PropertyGroup>

### ISSUE THREAD

**Issue by Stephan-Hoffmann** [rfennell/AzurePipelines#549]
### Azure DevOps Extension you are using
Manifest Versioning Build Tasks / Version .NET Core Assemblies

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
It is the currently public version (2.17.4)

### Expected behaviour and actual behaviour
Its happily finding all my csproj files, and applies the version number to some of them. Then it fails without any diagnostics with this error

Checking if any version fields to update
Getting just the PropertyGroup that contains the version fields
##[error]Unhandled: Cannot read property '0' of null

I checked the next csproj and it didn't have a PropertyGroup entry. I added it and the task completed successfully. 

### Steps to reproduce
Create a csproj without any PropertyGroup entry. Oh, and the group needs to be unconditional.

**Comment by rfennell** [comment]
I have just released 2.18.2 which now if it finds no <propertygroup> entries adds one at the end of the file
