### ISSUE TITLE
Version not applied to csproj with PropertyGroup

### ISSUE THREAD

**Issue by Stephan-Hoffmann** [rfennell/AzurePipelines#551]
### Azure DevOps Extension you are using
Manifest Versioning Build Tasks / Version .NET Core Assemblies

### Where are you running it?
Azure DevOps Service (VSTS)

### Version of Extension/Task
It is the currently public version (2.18.2)

### Expected behaviour and actual behaviour
I expect the version to be applied to all csproj files. However, it does not modify an existing group.
When there is no ProjectGroup tag, it adds one with the version applied (see #459 ) to the project file. (good)
When there is a ProjectGroup tag, it does NOT modify the project file despite the logs saying so. (bug?) 

I've check this behaviour by adding a powershell script right after the version task and print out the csproj file.  

### Steps to reproduce the problem
I guess simple check when happens when there is a PropertyGroup.

**Comment by rfennell** [comment]
Strange, all my tests pass, I need to dig into this work out what the gap is. Just to confirm the three core test cases are

- Update existing version in the first propertygroup
- Add new version if none present in the first propertygroup - **this is the failing one**
- Add a propertygroup and version if neither is present

**Comment by rfennell** [comment]
To check the .csproj that is not being update looks a bit like this?
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>VersionedLibrary</AssemblyName>
    <Description>A description</Description>
  </PropertyGroup>

</Project>
```

**Comment by Stephan-Hoffmann** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Synergies.WebApi</AssemblyName>
    <DocumentationFile>bin\Release\netcoreapp2.2\Synergies.WebApi.xml</DocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.AzureKeyVault.HostingStartup" Version="2.0.4" />

    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.2.1" />
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="3.0.4" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="2.2.5" />
    <PackageReference Include="Microsoft.OData.Core" Version="7.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="4.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="4.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="4.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzureIntegration.API\AzureIntegration.API.csproj" />
    <ProjectReference Include="..\AzureIntegration\AzureIntegration.csproj" />
    <ProjectReference Include="..\DataAccess.API\DataAccess.API.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\Repository.API\Repository.API.csproj" />
    <ProjectReference Include="..\Repository\Repository.csproj" />
    <ProjectReference Include="..\Services.API\Services.API.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>
</Project>

**Comment by Stephan-Hoffmann** [comment]
Things like TargetFramework I'll specify in a Directories.Build.props file. 

But I also have got that also for some other projects where version injection works - when I don't have any property group in the csproj...

**Comment by Stephan-Hoffmann** [comment]
For completeness, this is the output from the task


> Checking if any version fields to update
> 
> Getting just the PropertyGroup that contains the version fields
> 
> Found <PropertyGroup> block
> 
> Processing Field Version
> 
> Processing Field VersionPrefix
> 
> Processing Field AssemblyVersion
> 
> No version fields present, so add a Version field
> 
> Getting just the PropertyGroup that contains the version fields
> 
> Found <PropertyGroup> block
> 
> The <Version> version is not present in the .csproj file so adding it
> 
> d:\a\1\s\WebApi\WebApi.csproj - version applied

**Comment by rfennell** [comment]
Thanks for the sample, perfect for me to try a repo

**Comment by rfennell** [comment]
I have written a fix, there was a code path if no <targetframework> could be found that failed to update the file.

This will go out in 1.19.x, but there is another versioning fix being done #547 by @ChrisLGardner  that is blocking the release at present, they will will go out as a pair soon.

**Comment by rfennell** [comment]
It should be in 1.19.6

**Comment by Stephan-Hoffmann** [comment]
Yes, this did it. Thank you, much appreciated!
