### ISSUE TITLE
Question: Run Generate Release Notes Build Task anywhere

### ISSUE THREAD

**Issue by stefaneicher** [rfennell/AzurePipelines#555]
I would like to generate Release Notes not on TFS but somewhere else ( another Windows machine).

I there a way I can run the code of this "Generate Release Notes Build Task"  somehow outside of TFS?

Regards Stefan

**Comment by rfennell** [comment]
It would take some work on your part, but yes. You have a couple of choices
- You can us the older [Powershell version ](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask)that uses my own logic to create the document
- Or you can use the newer [Node version](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/XplatGenerateReleaseNotes/V2) that uses the same calls as the Microsoft UI

In both case you would need to edit the .ps1/.ts file that is the tasks entry point to get the parameters via the command line or config file as opposed to from the build agent via the agent API.

Also you would have to provide a PAT token to access the Azure DevOps API - at present the build agents PAT token is used.

But it is certainly possible. Just needs some editing of entry functions

**Comment by stefaneicher** [comment]
Thanks for the answer.
I will let you know  If we decide to go the "Use Generate Release Notes Build Task outside of TFS"-route.
If so, I would try to adapt the node or ps version and maybe provide a PR such that others could also benefit from it.

**Comment by rfennell** [comment]
I have decided that I won't ever be porting this PowerShell task to run on any platform other then Windows. This is basically down to the fact that the Azure DevOps agent can only run 'full' PowerShell on Windows. There is no PowerShell Core support and as far as I can see no plans to add it. The direction of travel is all Node.JS base.

However, I can offer an alternative to this task, my [Cross Platform Generate Release Notes](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) now, as of 2.17.10, can be run in a build as well as a release. Hopefully that should address your needs 

Also so #580
