### ISSUE TITLE
Using {0:dd/MM/yy HH:mm:ss} gives 'Unexpected token {'

### ISSUE THREAD

**Issue by ramyzbeidy** [rfennell/AzurePipelines#556]
In Generate Release Notes tasks, once i set the template to have

> {0:dd/MM/yy HH:mm:ss}

I'm getting an error: 

> ##[error]SyntaxError: Unexpected token {

**Comment by rfennell** [comment]
Is with the 'Generate Release Notes' or 'Cross Platform Generate Release Notes'?

Could you provide a sample of your whole template

**Comment by ramyzbeidy** [comment]
This is only reproduced in Cross platform extension

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rfennell** [comment]
I will have a look at it

**Comment by rfennell** [comment]
I have done some experimentation and you can't use the date format in this manner in a template. 

The reason for the error is that '{' character is used for two jobs, the date format and marking of the block to expand in the template  - problem is it can't do both.

I have been experimenting with a small test harness that processes a single line using my task's **FixLine** function, to validate the line, and node's **Eval** function to actually expand the line

 ```
var valuetoexpand = "value of abc";
var datetime = new Date();
var line = "This is a line ${valuetoexpand} ${datetime.toString()}";
var fixed = fixline(line);
var processedLine = eval(fixed);
Console.log(processedLine);
```
This give the processed output
> This is a line value of abc Fri Oct 11 2019 12:37:51 GMT+0100 (British Summer Time)

If you want some complex datetime format you would have to use something like

`var line = "This is a line ${valuetoexpand} ${datetime.getDay()}/${datetime.getMonth()}/${datetime.getFullYear()} ${datetime.getHours()}:${datetime.getMinutes()}";
 `

Which gives

> This is a line value of abc 5/9/2019 12:50

That's the only option available

**Comment by JulienM28** [comment]
I tried this:

````
var datetime = new Date();
##${releaseDetails.name} ${datetime.getDay()}/${datetime.getMonth()}/${datetime.getFullYear()}
````
returns me datetime  is not defined

and this
````
${var datetime = new Date();}
##${releaseDetails.name} ${datetime.getDay()}/${datetime.getMonth()}/${datetime.getFullYear()}
````
returns me var is an invalid token

I misse something, it's obvious, but what ?

Thanks.
