### ISSUE TITLE
Nuget pack for .net standard not updating version(build number) in .csproj file

### ISSUE THREAD

**Issue by ramesh580** [rfennell/AzurePipelines#557]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)
- Azure DevOps Server (on-premise TFS, if so what version)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

### Steps to reproduce the problem
I have created a pipeline for a (.net standard 1.1)solution. This pipeline is to build and release a new nuget package for this solution. I have created the task like, NuGet restore, version .net core assemblies, visual studio build, NuGet pack and NuGet push (image is attached).

In the Nuget pack, set the automatic package versioning as 'Use an environment variable' and an Environment variable as "Build.BuildNumber". Under options set the build number format as 1.0.0$(rev:.r).

When I execute this build, it gets success and a new Nuget package is generated and published to a feed whereas the version still remains 1.0.0.0 in .csproj. I used version .net core assemblies to update the version in .csproj.This task log showing version is updated but it's not. Attached log for this task.
<img width="919" alt="Task structure" src="https://user-images.githubusercontent.com/36506448/66466304-1933c180-eaa0-11e9-91bb-a73dc41ea1a0.png">
<img width="1440" alt="version  net core assemblies log" src="https://user-images.githubusercontent.com/36506448/66466307-19cc5800-eaa0-11e9-9e87-d6e2a973abef.png">

**Comment by rfennell** [comment]
Can you provide a sample of your CSPROJ. It seems there are more possible start formats than I expect, so in some cases the logic fails. I thought I had trapped them all but, look like I missed one

**Comment by ramesh580** [comment]
Here is my .csproj file
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
    <Version>4.0.0.2</Version>
  </PropertyGroup>

  <Import Project="..\ActionLog.Core\ActionLog.Core.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
  </ItemGroup>

</Project>
I am trying to update version tag in propertyGroup

**Comment by rfennell** [comment]
I think the problem could be the order of the <properygroup>, let me check the code

**Comment by rfennell** [comment]
I have written a test that uses your sample .csproj - [in this folder](https://github.com/rfennell/AzurePipelines/tree/issue557-netcore-version-second-block/Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata) on it's branch.

Issue is it passes, the version is updated.

So I think the problem lies else where. 

When I have been building nuget packages I have used .nupspec files, and I have a task in this same extension to version them, but it has been a while since I created on, so I might be using old development patterns.

Have you tried adding, and updating a .nuspec file?

**Comment by ramesh580** [comment]
> I have written a test that uses your sample .csproj - [in this folder](https://github.com/rfennell/AzurePipelines/tree/issue557-netcore-version-second-block/Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata) on it's branch.
> 
> Issue is it passes, the version is updated.
> 
> So I think the problem lies else where.
> 
> When I have been building nuget packages I have used .nupspec files, and I have a task in this same extension to version them, but it has been a while since I created on, so I might be using old development patterns.
> 
> Have you tried adding, and updating a .nuspec file?

<img width="470" alt="2019-10-08_13h23_43" src="https://user-images.githubusercontent.com/36506448/66544115-d3850080-eb54-11e9-9ee4-2220e7b4f573.png">
As i attacheed the image here, it shows it updated whereas when i open the solution in Visual studio and checked the version in .csproj file. it didnt changed.

**Comment by ramesh580** [comment]
> OK I need to attack this a different way. I think the .NETCore versioner is working, at least according to my unit tests, but for some reason the setting of the version if the NUGET package is failing. You can of course test this if you are using private build agent by looking at the files on the build agent at the end of the build.
> 
> So, I think I need to create a .NET Standard .CSPROJ that creates a Nuget package and trace where it gets the version from. As I said I always use Nuspec files so have not investigated this usage

its n
<img width="1033" alt="2019-10-10_15h48_18" src="https://user-images.githubusercontent.com/36506448/66560690-806f7580-eb75-11e9-9280-0ab6e391f89f.png">
ot working either

**Comment by rfennell** [comment]
Just to clarify, are you call my Nuspec file versioner task before running the Nuget pack - to up date the version field in nuspec file? 

As I remember passing the -version x.x.x.x is not enough, but I might be wrong.

Also can I confirm you have actionlog.nuspec under source control or is it being generated from the .csproj on each run?

**Comment by rfennell** [comment]
I have tried to repo the problem with this [build](https://dev.azure.com/richardfennell/GitHub/_build/results?buildId=3510&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a) which builds the code in this [repo](https://dev.azure.com/richardfennell/GitHub/_git/NugetSample). 

Problem is I can't get a repo of the issue, I seem to be getting a versioned build, the DLL is versioned so it the nugetpackage and the nuspec file.

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>NugetSample</id>
    <version>1.2.19283.1</version>
    <title>NugetSample</title>
    <authors>NugetSample</authors>
    <owners>NugetSample</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Description</description>
    <dependencies />
  </metadata>
</package>
```
Can you see how my test build does not match your problem?

**Comment by ramesh580** [comment]
<img width="1435" alt="2019-10-11_12h33_58" src="https://user-images.githubusercontent.com/36506448/66631781-9ab45c80-ec24-11e9-83ff-5a82b80a5d9a.png">
My build also remins the same nit version in .csproj is not updating.
Even in your repo it still shows 9.0.0.0 in version in .csproj
<img width="1440" alt="2019-10-11_12h42_19" src="https://user-images.githubusercontent.com/36506448/66631836-bd467580-ec24-11e9-85fc-fa94cc23471a.png">

**Comment by rfennell** [comment]
Oh I think I might understand the issue. 

The task, like all my versioning task, only update the .CSPROJ file on the build agent for the production of the DLL/Package. **IT DOES NOT** update the source file in the source repo, these files are read only to the build. 

All my tasks make the assumption that the version number in the source code is irrelevant. It is the build that generates the version number and 'stamps' this as the version on the DLL & Packages. As the build will be associated with a changeset/commit, if required, the source for any given build can always be obtained.

The nice thing about this model is that as the version in source control is say the default of 1.0.0.0,  if we ever see a build in test/uat/release that has the version 1.0.0.0 we know the build came from a Dev machines and not via the official release channel. So know someone is not following process

If you do want to write back changes to source control look at
-  [A TFVC set of tasks](https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-tfvc-tasks)
- [Run Git commands in a build](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)

Does that help?

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
