### ISSUE TITLE
Wrong assigned by value

### ISSUE THREAD

**Issue by ramyzbeidy** [rfennell/AzurePipelines#558]
Using 

> [Assigned by: $($widetail.fields.'System.AssignedTo')]

Generates wrong output:

> Assigned by: @{url=http://192.168.0.123:9090/tfs/NTXTFS/_apis/Identities/6a614084-faee-4e38-bb86-5b022ca8d439; id=6a614084-faee-4e38-bb86-5b022ca8d439; _links=System.Object[]; imageUrl=http://192.168.0.123:9090/tfs/NTXTFS/_api/_common/identityImage?id=6a614084-faee-4e38-bb86-5b022ca8d439; descriptor=win.Uy0xLTUtMjEtMzM2NTMzNjE1MS0xMTUwNTM3NC0yNzEyNzEzMzUxLTY4OTE; uniqueName=NETIKS\ramy.zbeidy; displayName=Ramy Zbeidy}]

**Comment by rfennell** [comment]
As this has the forma $(....) can I assume this is the PowerShell Release notes task?

That output would suggest that the field you are looking for does not have the defined in the object, so it has done an object dump. I do no special processing on the WI or CS objects, I just expose the available fields in the returned object.

My first guess is you need something like

**Comment by rfennell** [comment]
I have confirmed for the PowerShell based Release Notes Task template to get the assigned user display name should be

```
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo'.displayName)] $($widetail.fields.'System.Title')  
@@WILOOP@@  
```

If you miss off the .display name the processor just dumps the whole AssignedTo object as string.

I will update the [demo templates](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/GenerateReleaseNotes%20(Original%20Powershell%20based))
