### ISSUE TITLE
I need only the diff. from last deploy, in my release notes

### ISSUE THREAD

**Issue by Danbuhr** [rfennell/AzurePipelines#560]
### Azure DevOps Extension you are using
Generate Release Notes for Pipeline Builds or Releases

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

### Expected behaviour and actual behaviour
I'm actually not sure what the expected behaviour should be, but I'm trying to get the latest changes for a production deployment, so this is more of a "how to do" question.

### Steps to reproduce the problem
Use the template parts from the support guidelines

So I have this small template:

```
<h1> Release notes for release $(release.DefinitionName) </h1>


**Release Name**  : $(release.ReleaseName)
**Release attempt number**  : $(release.AttemptNumber)
**Release completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$release.modifiedOn)
**Release Requested for** $(release.RequestedFor) ($(release.RequestedForEmail))


---


**Changes since last successful release to '$stagename' Including releases**    $(($releases | select-object -ExpandProperty name) -join ", " ) .



<details>
<summary>Associated work items</summary>


<br>


@@WILOOP@@
* #$($(widetail).id)
@@WILOOP@@


</details> 


---


<br>
```

And When I run it, I get a nice wiki page, but regarding the associated work items, I get both those that are from the previous deployment, and the changes that are in the current.

So for example, if i previously deployed version 99 to production, and have moved up to 102, I will get associated work items from 99, 100, 101 and 102.

What I need for the release notes, is only 100, 101 and 102 aka "the latest changes".

In the build template there's a compared version, that gives exactly the latest changes, but how can I do the same in release?

And once again, thanks for a great addition to Azure devops! :)

**Comment by rfennell** [comment]
I need to try to repo that. But a couple of things that could help

- If you set a release variable **system.debug = true** you will get more detailed logging. It would be useful if you could upload the log for generate release notes task (with any anonymisation your required)
- Have you considered my Cross Platform Generate Release notes, unlike this PowerShell based one which uses my own home grown logic, it uses the standard Microsoft API calls, just like the Azure Devops UI, it might give results you want. Just note the template format differs slightly as is written in Node as opposed to PS

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
