### ISSUE TITLE
Cannot get author of commit in @@CSLOOP@@

### ISSUE THREAD

**Issue by dagett** [rfennell/AzurePipelines#563]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform) 

### Where are you running it?
Cloud: https://dev.azure.com/...

### Version of Extension/Task
Version: 2.14.1

### Expected behaviour and actual behaviour

In `@@CSLOOP@@` construct I use `${csdetail.id}` and `${csdetail.message}` to get the commit id and the commit message. I would also like to get **author** and possibly
which **repository** the commit is from (there are many artifacts picked up by extension, each with its own repo) but have not been successful

### Steps to reproduce the problem

Various attempts, like `${csdetail.author}`,  `${csdetail.author.name}`,  `${csdetail.author.email}`, `${csdetail.committer.name}`  inspired by what [Commits - Get Commits](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-5.1)  returns

Either they return nothing or errors like
`TypeError: Cannot read property 'name' of undefined`

**Comment by rfennell** [comment]
To dump all the possible values you can use [this template](https://raw.githubusercontent.com/rfennell/AzurePipelines/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/release-with-WI-filter.md)

If you do this you see the commit information is limited you get

> {"id":"3a024da00dff5ca82503d9f487763bad3aa25165","message":"Automated Repo Update 
>  #67","type":"TfsGit","author":{"displayName":"Build user","id":null,"uniqueName":"builduser@dummy.local"},"timestamp":"2019-10-25T07:49:02.000Z","location":"https://richardfennell.visualstudio.com/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/3a024da00dff5ca82503d9f487763bad3aa25165 "}
 
You can get the author as follows.

```
### Associated commits
@@CSLOOP@@  
* ** ID ${csdetail.id} ** Commited by:  ${csdetail.author.displayName} (${csdetail.author.uniqueName}) ${csdetail.message}
@@CSLOOP@@
```

The repository is only available as a GUID, so without a back end change to build a CS object from scratch it will not be available. This is something I want to avoid to keep as close to the standard API calls as possible

If this does not answer the question just reopen the issue
