### ISSUE TITLE
@@BUILDLOOP@@ example for GenerateReleaseNotes (XPlat version)

### ISSUE THREAD

**Issue by amccool** [rfennell/AzurePipelines#567]
Im trying to use the @@BUILDLOOP@@ in the xplat generate notes

looks like variable names changed

```
@@BUILDLOOP@@
### ${build.definition.name}
```

yields: ``##[error]ReferenceError: build is not defined``

perhaps an update the sample template, or to the wiki page for the new variable names?

**Comment by rfennell** [comment]
You don't need the @@BUILDLOOP@@ in the xplat task. The API returns all the WI/CS as a block, not by build.

[You can find examples of templates here](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202) you need the Xplat V2 one, but the link points to that folder

If this does not get you going just reopen this issue
