### ISSUE TITLE
XplatGenerateReleaseNotes Sort Work Item types

### ISSUE THREAD

**Issue by Jryztndl** [rfennell/AzurePipelines#571]
### Azure DevOps Extension you are using
XplatGenerateReleaseNotes

### Where are you running it?
Azure DevOps Service (VSTS)

### Version of Extension/Task
V2

At first, this is a very nice extension. I use it to generate release notes of all work items. But i would like to sort them out in different WILOOPs.

So i could see alle the Bugs in a line, and for example leave the Issues and Tasks away. I don't want to use the TAG option to get it done, because the Work Items would look very messy when everywhere is says BUG.

I saw that in the PowerShell version, you can add an If statement in the WILOOPs, that is not possible here, ofcourse (#35)

The same question was also asked in #454

**Comment by rfennell** [comment]
Note sure how easy it is to do this, I will look into it, but happy to accept PRs too

**Comment by rfennell** [comment]
That was easier than I expected, there is not a checkbox on the advanced menu, the default is not set as before so the WI are listed in the default order, the WI ID. Check it and they are sorted alphabetically on the WI Type with a secondary order on the WI ID

It is released on 2.16.1

**Comment by Jryztndl** [comment]
Awesome! Thanks :)

**Comment by rfennell** [comment]
Closing this as has been released
