### ISSUE TITLE
In Azure pipeline, How to trigger releases using REST API?

### ISSUE THREAD

**Issue by akoliya01** [rfennell/AzurePipelines#577]
I have created a release pipeline in Azure DevOps. That pipeline contains a three different stages namely STAGING, QA and PROD. So, after completion of deployment in QA slot I want to trigger PROD environment using REST API. So, Is that possible to do the same?

**Comment by rfennell** [comment]
I am sure it is, bu not something I have ever tried to do. 

Have a look at [REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/?view=azure-devops-rest-5.1)

My first thought is to look at putting an Approval on the entry to PROD, then trigger the approval via the REST API

Hope that  helps
