### ISSUE TITLE
Allow the Cross Platform release notes task to work in builds

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#580]
### Azure DevOps Extension you are using
Cross platform generate release notes

### Where are you running it?
Any vaid location

### Version of Extension/Task
New feature

### Expected behaviour and actual behaviour
Can run in a build (both GUI and YAML based) and valid release information is produced

Based upon the request #525 

> This 'Build' check is actually preventing the extension from running in a Multi Stage Yaml Pipeline. These are the variables available in such a pipeline: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables
> 
> Could this be fixed?

from @SjoerdV

**Comment by rfennell** [comment]
Fixing this would also address #555

**Comment by rfennell** [comment]
This is a more complex problem than it sounds. It is easy to alter the manifest so you can use this task in a release. The problem is at present the task uses release specific API calls that have no meaning in a build whether a traditional build or YAML multistage one.

I will investigate adding some logic so something happens in a build. I am not sure what that will be as yet as I don't know the limitations

This is being tracked on #579

**Comment by rfennell** [comment]
This has been released as 2.17.10. 

The implementation with a build is simple, it just shows the current builds WI/CS. It is not aware of multistage YAML pipelines. That is a whole different question, there are not API calls for them as yet.

Hope it meets your needs

**Comment by SjoerdV** [comment]
@rfennell Sure does! Works like a champ, thanks for the swift updates

**Comment by rfennell** [comment]
Great thanks for the update
