### ISSUE TITLE
Issue cloning repo for WIKI Updater 

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#581]
### Azure DevOps Extension you are using
WIKI Updater

### Where are you running it?
- Azure DevOps Service (VSTS)
- Azure DevOps Server (on-premise TFS, if so what version)

### Version of Extension/Task
Current

### Expected behaviour and actual behaviour
Reported by Ana Carvalho via review
_Hi,

When i try to run the agent to create my release notes in azure devops I get the error
"2019-11-28T18:31:12.0534537Z ##[error]Error: Cloning into 'C:\agent\_work\r1\a\repo'..."
Someone had the same error? How I can solve this?
Thanks_

**Comment by rfennell** [comment]
The first is to see a detailed log can you run a build or release with the variable _system.debug=true_

The most common issue is that the URL of the repo is wrong, on Azure DevOps it is not obvious - I updated the documentation only a few days ago so if you have not already checkout https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Comment by luckyr-optimus** [comment]
Hello @rfennell , I am facing some issue while cloning the repo. I am attaching some snips for your reference.
**Error Details:** The requested URL returned error: 400.
Can you please help in resolving this issue?

![giterror1](https://user-images.githubusercontent.com/46810485/81051872-269f1600-8ee0-11ea-97a9-3694461c367c.PNG)
![giterror2](https://user-images.githubusercontent.com/46810485/81051878-2868d980-8ee0-11ea-8cca-44f8e6e61351.PNG)

**Comment by rfennell** [comment]
@luckyr-optimus  this is closed issue, as yours query is unrelated I have created its own issue #707
