### ISSUE TITLE
No link to work items

### ISSUE THREAD

**Issue by chris9263** [rfennell/AzurePipelines#582]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform) 2.16.1
Task version 2

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service release pipeline

### Expected behaviour and actual behaviour
I use the template from this blog post: https://medium.com/@mehmetugurgural/generating-release-notes-from-commits-an-azure-devops-pipelines-story-6b4952eafdfd

I expect to get links to each Work Item like this:
![image](https://user-images.githubusercontent.com/37179957/69967489-cb27c100-1518-11ea-9f32-42226a46ebc1.png)

But end up getting a markdown file that does not contain the work item links:
![image](https://user-images.githubusercontent.com/37179957/69967609-104bf300-1519-11ea-8c57-f3f7cd35e079.png)
 
### Steps to reproduce the problem
Use the template from the blog post and the Git based WIKI updater task to add the .md file to a repo.

**Comment by rfennell** [comment]
You are building a hyperlink in your template. i would expect your first column markdown to be something like

`[${widetail.fields['System.WorkItemType']} ${widetail.id}](${widetail.url}) `

If you view a markdown page inside the Azure DevOps web pages in some cases does this automatically, but I find it best to do this by hand.

Let me know if that help

**Comment by rfennell** [comment]
OK that was not right, the.rl give an API reference not the UI one.

However, another thought, Assuming you are publishing to the WIKI inside Azure DevOps there is an easier solution - Just put a # in front of the WI ID and the UI does the magic

So use a template like

```
## Notes for release  ${releaseDetails.releaseDefinition.name}    
**Release Number**  : ${releaseDetails.name}    
**Release completed** : ${releaseDetails.modifiedOn}     
**Build Number**: $(Build.BuildNumber)
**Compared Release Number**  : ${compareReleaseDetails.name}    

### All associated work items  
@@WILOOP@@  
* ${widetail.fields['System.WorkItemType']} #${widetail.id} Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
@@WILOOP@@  

### Associated commits
@@CSLOOP@@  
* ** ID ${csdetail.id} ** Commited by:  ${csdetail.author.displayName} (${csdetail.author.uniqueName}) ${csdetail.message}
@@CSLOOP@@
```

Any you get
![Annotation 2019-12-02 171249](https://user-images.githubusercontent.com/324718/69979859-ffa27980-1526-11ea-8237-955725f046fd.png)

Hope that works for you, if not reopen issue

**Comment by chris9263** [comment]
That worked perfectly, thank you so much for a useful task.

**Comment by rfennell** [comment]
Glad you found it useful
