### ISSUE TITLE
Question: can I update a variable in a group that is specified in yaml only.

### ISSUE THREAD

**Issue by wyrdfish** [rfennell/AzurePipelines#583]
### Azure DevOps Extension you are using
https://github.com/rfennell/AzurePipelines/blob/master/Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Latest public

### Expected behaviour and actual behaviour
I have to manually add (in the web UI) the variable group to a pipeline definition as well as  specifying the group in my yaml.
If I remove the group in the online definition but leave the reference in the yaml the task fails to find the variable to update (other tasks can use the variable).

**_##[error]Cannot set variable [ProjectBuildId] as variable could not be found in the a pipeline or associated variablegroups_**

### Steps to reproduce the problem
Add a variable group to a yaml build (set its permissions in the library). 
Add the step that updates the variable and run a build.

**Comment by rfennell** [comment]
That sounds like an API difference between the two ways of declaring the variable group. I will need to investigate. However, it might be a limitation at present

**Comment by wyrdfish** [comment]
Thanks, I'll take a closer look tomorrow, it just occurred to me that we will probably want to alter this group across branches so specifying the group in the UI is an issue.

**Comment by rfennell** [comment]
Spent a while reading about this. If I understand the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml) then I don't think you can do what you have outlined.

I think the variable groups entry in the YAML is a reference, a link, to a UI defined variable group.

I am surprised that the other tasks work

**Comment by wyrdfish** [comment]
Yes the variable groups are defined in the UI. But I am also having to edit the actual pipeline definition in the UI. I have to click edit pipeline (the yaml editor appears), then the three dots button and choose Triggers to get up the old style build page and go to the variables tab and associate the group with the pipeline.

I'll have a longer look tomorrow, its entirely possible I have got a permission wrong or something.

**Comment by rfennell** [comment]
OK, that article does make special mention over authorisation - probably worth another look.

Let me know how it goes

**Comment by wyrdfish** [comment]
Hi,
I have reproduced this. 
https://dev.azure.com/WyrdsoftOS/PublicBuildTesting/_build/results?buildId=74&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=32f188ea-5e98-5907-ea3f-173bf74782da&l=47

And it works with the same yaml, but linking the variablegroup to the pipeline definition in the web ui.
https://dev.azure.com/WyrdsoftOS/PublicBuildTesting/_build/results?buildId=75&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=32f188ea-5e98-5907-ea3f-173bf74782da

It seems that the api call to get build definition "$($tfsUri)/$($teamproject)/_apis/build/definitions/$($buildDefID)?api-version=$apiVersion"

does not return the variable groups collection if the asociation is in the yaml only. This makes complete sense in retrospect otherwise the api call would have to go away and start parsing the yaml, which is silly.

I'm just going to have to take a different approach and update the variable group item explicitly.

**Comment by rfennell** [comment]
Thank for looking into it and reporting back. Building up a history of issue like this is useful
