### ISSUE TITLE
Prepend instead of append Wiki file

### ISSUE THREAD

**Issue by richieto** [rfennell/AzurePipelines#591]
### Azure DevOps Extension you are using
Wiki Updater

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Current

### Expected behaviour and actual behaviour
First of all, great extension!

This is a follow up of issue #545 
I am using the wiki updater for a changelog, and I would expect to see the most recent change at the top. 

In the current behavior the text is appended and therefore at the bottom of the file.

I know prepend is not an option in fs, so it would require to read file first, then write twice (new data, then old)

Let me know your thoughts

**Comment by rfennell** [comment]
Interesting and useful enhancement. I have added it to the backlog. Not sure when I will get to it. 

Always happy to accept PRs

**Comment by richieto** [comment]
Glad to hear!

Do you think this could be the default behavior when the replaceFile is false? or should be an additional option (only applicable if replaceFile is false)?

**Comment by rfennell** [comment]
I try never to change existing default behaviour. So I would add this via a new checkbox to change the behaviour

**Comment by rfennell** [comment]
I got out of meeting early so had a few minutes. You should  have the option if you choose not to replace the file to append (the historic default) or now pre-pend

It is in 1.7.3

**Comment by richieto** [comment]
Awesome! that was fast!
The deployment failed though, some service connection issues in your production pipeline.
Looking forward to test this!

**Comment by vinishiru** [comment]
Is this option already published on marketplace?
I'm using Azure Devops Server 2019, with WIKI Updater extension 1.7.5, but this option does not shown.
Only "Append".
![image](https://user-images.githubusercontent.com/924290/72001694-ba0f5580-3224-11ea-9d35-1e268c9b3628.png)

Thanks.

**Comment by richieto** [comment]
> Is this option already published on marketplace?
> I'm using Azure Devops Server 2019, with WIKI Updater extension 1.7.5, but this option does not shown.
> Only "Append".
> ![image](https://user-images.githubusercontent.com/924290/72001694-ba0f5580-3224-11ea-9d35-1e268c9b3628.png)
> 
> Thanks.

Yes, 
append unchecked = prepend
