### ISSUE TITLE
XPlatReleaseNotes: No Associated Work Items or Commits found for Build process

### ISSUE THREAD

**Issue by cakeezer** [rfennell/AzurePipelines#597]
When running the task in DevOps I can get the basic build info, but no Work Items or Commits are showing. We are using VSTS and I am not getting any build errors. Also the Commit and Work Items are showing in the detailed summary for the build.
![image](https://user-images.githubusercontent.com/17857789/71687336-999a5380-2d6b-11ea-9d7b-02a6b81d4f28.png)

Release Notes that were generated; 
![image](https://user-images.githubusercontent.com/17857789/71687465-e1b97600-2d6b-11ea-9b0a-eab6c6ca452f.png)

We are using the Template that is provided in the documentation:
### Release ### 
${JSON.stringify(buildDetails)}     

### All associated work items  
@@WILOOP@@  
* **${JSON.stringify(widetail)}  
@@WILOOP@@  
 
### Associated commits
@@CSLOOP@@  
* ${JSON.stringify(csdetail)}  
@@CSLOOP@@

Here is what the task looks like in DevOps:
![image](https://user-images.githubusercontent.com/17857789/71687544-19c0b900-2d6c-11ea-9770-932dc5a4978d.png)

**Comment by cakeezer** [comment]
I was able to get it to work for releases. You have to enable Automatic linking of work items in the release and also reporting status to work in the release. Still cant get the build to see the related work items or change sets.

**Comment by rfennell** [comment]
Can you provide the detailed log of the task running. Set a variable system.debug=true

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
