### ISSUE TITLE
Versioning: When versioning an sqlproj project file gets written in ASCII instead of the original encoding

### ISSUE THREAD

**Issue by POFerro** [rfennell/AzurePipelines#603]
### Azure DevOps Extension you are using
VersionDacpacTask

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.24.3

### Expected behaviour and actual behaviour
Given the project file attached [SymetriaFI.DB.zip](https://github.com/rfennell/AzurePipelines/files/4065863/SymetriaFI.DB.zip) after task changes the version the file gets written in ASCII, instead of the original UTF-8, since in this case the file contains special characters ( in this example "çã" ), the file becomes an invalid xml and MSBuild stops 
building it.

### Steps to reproduce the problem
Apply the task to the attached project file and after the Version change validate the xml in Notepad++ for example, it should complain that the file contains invalid character for UTF-8 enconding

Thanks in advance and best regards
POFerro

**Comment by rfennell** [comment]
It is going to be the PowerShell Set-Content not honouring the file format. I will have a look at it

**Comment by rfennell** [comment]
This has been fixed in 1.25.1

I have added a unit test based on your sample to avoid regression
