### ISSUE TITLE
error in pester extension -using deprecated task execution handler

### ISSUE THREAD

**Issue by garthbf** [rfennell/AzurePipelines#606]
==============================================================================
Task         : Pester Test Runner from Black Marble
Description  : Run Pester tests by either installing the latest version of Pester at run time (if possible) or using the version shipped with the task (4.3.1)
Version      : 8.13.3
Author       : Richard Fennell
Help         : Version: 8.13.3. [More Information](https://github.com/rfennell/vNextBuild/wiki/Pester-Task/)
==============================================================================
##[warning]Task 'Pester' (8.13.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
Preparing task execution handler.
Executing the powershell script: D:\agent-pbc\_work\_tasks\Pester_31ef0033-64e3-4c55-b888-f446541474a6\8.13.3\Pester.ps1

**Comment by ChrisLGardner** [comment]
This is being fixed as part of moving the extension to a new publisher. I'm hitting some bugs in Azure DevOps that are preventing me from testing the changes properly, I've raised them with the team but need to chase it as I'd really like to move things forward with this.
________________________________

**Comment by rfennell** [comment]
As @ChrisLGardner  was we are in the process of depricating this extension, so no work will be done on it. 

A new improved version will be provided via a new publisher. There will be a final release of this task marking it is depricated and detailing the new home of the extension.
