### ISSUE TITLE
Work Items displayed for non-primary artifact

### ISSUE THREAD

**Issue by gigeld** [rfennell/AzurePipelines#607]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
V2

### Expected behaviour and actual behaviour
We have two artifacts linked to the release pipeline (only one marked as primary).
When running the Generate Release Notes (Crossplatform) task, we've expected to get only WIs from the primary artifact but the result displays Work Items from both.

### Steps to reproduce the problem
Run the Generate Release Notes (Crossplatform) task on a release pipeline with two linked artifacts

**Comment by rfennell** [comment]
That will need a code change as at present it loops around all artifacts, but should not be hard to do

**Comment by gigeld** [comment]
We've had the same issue with the PowerShell version and you've introduced a checkbox 'Generate for only primary artifact'

**Comment by rfennell** [comment]
Released in 2.20.1. The default behaviour is still the same,but there is now an argument for prime only

**Comment by gigeld** [comment]
Great support. Thank you!!!
