### ISSUE TITLE
I am getting Bad credentials, please advise

### ISSUE THREAD

**Issue by dperlyukDOITT** [rfennell/AzurePipelines#612]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)
- Azure DevOps Server (on-premise TFS, if so what version)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

**Comment by rfennell** [comment]
You have not answer any of the questions in the issue template so I don't know what extension your are using (this repo is used for more than one extension)

I need to know what your are trying to us and the detailed error message, preferably the log showing the failure

Sorry can't help without more information

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. if you gather enough information to allow me to help please reopen the call
