### ISSUE TITLE
VersionAngularFileTask: Version with double quotes (") not supported

### ISSUE THREAD

**Issue by alexwiese** [rfennell/AzurePipelines#614]
### Azure DevOps Extension you are using
VersionAngularFileTask

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Current version

### Expected behaviour and actual behaviour
`environment.ts` file contains the following:
```
export const environment = {  
  version: "0.0.1"
};
```

Expect the version to be updated by the task but it is not. Changing the version to use single quotes works:

```
export const environment = {  
  version: '0.0.1'
};
```

I can see the code is checking for single quotes only. I will submit a PR to fix this.

**Comment by rfennell** [comment]
Seems a reasonable ask, I will look into it. Should only be a regex change

**Comment by alexwiese** [comment]
> Seems a reasonable ask, I will look into it. Should only be a regex change

Pull request here: #615

**Comment by rfennell** [comment]
Thanks for the PR, the change is now live as 2.16.2
