### ISSUE TITLE
Groupe By Area Path

### ISSUE THREAD

**Issue by Bronx205** [rfennell/AzurePipelines#617]
### Extension concerned:
GenerateReleaseNotes

### Where are you running it?

- Azure DevOps Server (on-premise TFS, version December 2019)

### Version of Extension/Task
I got locally the powershell script (Create-ReleaseNotes.ps1), under .../AzureDevOpsPowershell/ it does the trick for me.

### Expected behaviour and actual behaviour
Im wondering if i can group by Areapath in my template
### Steps to reproduce the problem
Just take any sample template, and add "System.AreaPath" to it,
now what i want is to groupe workitems "System.AreaPath" so when the release not is generated, i could see my .md file in more organized way,

**Comment by rfennell** [comment]
Sorry there is no way to do grouping in the template. It is a possible enhancement. 

However, I have no plans to do any enhancements on this task as I am focusing all the effort related to release notes on [my Cross Platform version](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) as [detailed here](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes--Tasks)
