### ISSUE TITLE
Pester 4.10.0 failing - is it possible to force "Pester Test Runner Build Task" to use 4.9.0?

### ISSUE THREAD

**Issue by nathan-given-health-catalyst** [rfennell/AzurePipelines#619]
### Azure DevOps Extension you are using
Pester Test Runner Build Task

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version      : 8.13.3

### Expected behaviour and actual behaviour
We're using YAML builds that have a Pester Test Runner Build Task. Everything was working last week, but this week, all of our builds are failing with this error:

   ```
RuntimeException: The following error occurred while loading the extended type data file: 
      Error in TypeData "Gherkin.Ast.Scenario": The member ToString is already present.
      Error in TypeData "Gherkin.Ast.Feature": The member ToString is already present.
      at Install-RequiredPester, W:\myagent\_work\239\s\Installer\DosPlatformNewInstallerPowershell\tests\Utilities\testBootstrap.ps1: line 7
      at <ScriptBlock>, W:\myagent\_work\239\s\Installer\DosPlatformNewInstallerPowershell\tests\ManageModuleImports.tests.ps1: line 10
      at Invoke-Blocks, C:\Users\myuser.mydomain\Documents\WindowsPowershell\Modules\Pester\4.10.0\Functions\SetupTeardown.ps1: line 135
      at Invoke-TestGroupSetupBlocks, C:\Users\myuser.mydomain\Documents\WindowsPowershell\Modules\Pester\4.10.0\Functions\SetupTeardown.ps1: line 121
      at DescribeImpl, C:\Users\myuser.mydomain\Documents\WindowsPowershell\Modules\Pester\4.10.0\Functions\Describe.ps1: line 209

```

I know this is a Pester error, however, I was hoping to tell this task to explicitly use Pester 4.9.0, rather than downloading the latest version of Pester.

**Is it possible to tell this task to use an explicit version of Pester?**

### Steps to reproduce the problem
Use pester 4.10.0 with our pester tests

**Comment by nathan-given-health-catalyst** [comment]
I decided to try to edit the "Pester.ps1" file in `W:\myAgent\_work\_tasks\Pester_31ef0033-64e3-4c55-b888-f446541474a6\8.13.3`:

Changed line 86 from:
`$NewestPester = Find-Module -Name Pester | Sort-Object Version -Descending | Select-Object -First 1`
to
`$NewestPester = Find-Module -Name Pester -MaximumVersion 4.9.0 | Sort-Object Version -Descending | Select-Object -First 1`

That seems to have solved it for now (I'm not sure if that is the right way to do this, though :-) )

**Comment by ChrisLGardner** [comment]
That looks more like an issue with Pester 4.10 but I haven't had a chance to test that yet. This version of the extension doesn't currently support specifying a version and won't, I'm intending to deprecate it and move to a new version of the extension that's cross platform and published by the Pester org itself. I've got a few bugs I'm working out before I release a v1.0 of the extension, which will include version selection.

**Comment by nathan-given-health-catalyst** [comment]
Awesome, @ChrisLGardner .  Is it possible to start using the new extension?  (If so, how can we switch?)

**Comment by ChrisLGardner** [comment]
Not yet unfortunately, I've got some big bugs I want to work out and having some interesting issues getting it correctly installed into my Azure DevOps org when it's had this version of the extension installed that I want to work out before I open it up to normal users, especially if it's something I have to thoroughly document

**Comment by ChrisLGardner** [comment]
Tracking is at https://github.com/pester/AzureDevOpsExtension/issues/8 so updates will be posted there.
