### ISSUE TITLE
Wrong release date

### ISSUE THREAD

**Issue by TakhirMamirov** [rfennell/AzurePipelines#622]
I have a release pipeline in VSTS with TEST/QA/PROD releases to different environments. When I create a release on a certain build, all three sub-pipelines are usually initiated. Then, say, I release to TEST on Jan 21, and to PROD on Jan 23, from the same build. When I then look into release notes, the $release.modifiedOn is Jan 21, not Jan 23. How can I get the exact date/time of the deployment to PROD?

**Comment by rfennell** [comment]
Sorry for the delay in getting back, I have been off work sick.

Can you tell me the task you are using and the version, is it the legacy PowerShell or the newer Node (CrossPlatform) based version?

What I usually recommend is to use a [template](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates) that dumps all the values available and then look to see the name of the field that has the value you are after. Crude but effective

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
