### ISSUE TITLE
no parent items in widetail object dump

### ISSUE THREAD

**Issue by JakubSurfer** [rfennell/AzurePipelines#623]
I can't find parent work item in widetail object dump. Is there a way to access/display them ? 

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version: 2.20.1 (Current Public Release / Azure Market)

**Comment by rfennell** [comment]
Sorry for the delay in getting back I have been off work sick

I don't believe that this data is available in this extension. We only return the same data as you can see through the Azure DevOps pipelines API and that only shows direct associations

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
