### ISSUE TITLE
GenerateReleaseNotes for specific period

### ISSUE THREAD

**Issue by SuhasWadkar** [rfennell/AzurePipelines#626]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform Task

### Where are you running it?
cloud - Azure DevOps Service (VSTS)

### Version of Extension/Task
2.*

### Expected behavior and actual behavior
I am using “GenerateReleaseNotes Node based Cross Platform Task, it is working wonderful for now.

I wanted to ask you, if I can generate Release/Build notes based on date time. 
For example, If I can provide To_Date and From_Date and based on that all the commits and work items will be fetched from Azure. 

If it can not be achieved in the existing version, is there any workaround or do you have any plan to release something of this sort in future?

**Comment by rfennell** [comment]
Sorry, no the release notes cannot be generated against a date range as the call that is made to the Azure DevOps API to get the details use build/release IDs not dates i.e. get everything associated after release 10 and up to release 11.

So this change would be a major re-write and not something I am planning to do.
