### ISSUE TITLE
Tags for multiple builds

### ISSUE THREAD

**Issue by SuhasWadkar** [rfennell/AzurePipelines#627]
### Azure DevOps Extension you are using
GenerateReleaseNotes---Node-based-Cross-Platform-Task

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
GenerateReleaseNotes---Node-based-Cross-Platform-Task 2.*

### Expected behaviour and actual behaviour
Does Tags work for "Work-Items" from the current build in queue or it considers all the earlier builds and searches tag there as well and list them? 

Is there a way to get work items and commits from earlier builds as well?

**Comment by rfennell** [comment]
There is not support for build tags, the logic only looks back for the last build of the definition that has succeeded to find the list of changes.

So if you have 

1. Build succeed
2. Build succeed
3. Build Failed
4. Build Failed
5. Build succeed

The WI/Cs associated with Build 5 will be all those in 3, 4 & 5

Hope that helps.
