### ISSUE TITLE
Is it possible to filter commits in GenerateReleaseNotes Xplat?

### ISSUE THREAD

**Issue by KennethScott** [rfennell/AzurePipelines#629]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform Task

### Where are you running it?
Azure DevOps Server 2019 /  on-premise

### Version of Extension/Task
Latest public/V2

I am simply curious if it's possible to filter commits in the same manner you can filter workitems.  We use a pull request-based workflow and I'm wondering if you could do that to filter the redundant merge commits.

Thanks-

**Comment by rfennell** [comment]
No sorry there is currently no filtering on commits. How did you envisage the filter to work for commits?

**Comment by KennethScott** [comment]
I guess I was thinking something along the lines of a regex pattern that could be used to filter the commits based on the commit message?  For example our PR merges all have a message that starts with "Merged PR #:" so it would be nice to be able to exclude them maybe with a regex like:
`^Merged PR \d+:`

**Comment by rfennell** [comment]
Interesting idea. I have swapped this to an enhancement. Now sure when I will get round to it

**Comment by KennethScott** [comment]
Thanks for considering this!

**Comment by rfennell** [comment]
This has been released in 2.24.3

The new template format is detailed in the WIKI, but to summarise

`@@CSLOOP[^Merged PR #.+]@@` match only commits/changesets with a commit message in the form 'Merged PR #1234' 

So 
```
### Associated commits matches all
@@CSLOOP@@
* **ID ${csdetail.id} ** ${csdetail.message}
@@CSLOOP@@

### Associated commits with regex filter in form to match the text 'Merged PR #1234'
@@CSLOOP[^Merged PR #.+]@@
* **ID ${csdetail.id} ** ${csdetail.message}
@@CSLOOP[^Merged PR  #.+]@@
```

Let me know how it goes

**Comment by KennethScott** [comment]
This seems to be working great!  I did tweak the regex to be the inverse as I wanted to _exclude_ the merge commits `^(?!Merged PR \d+).*$` , but seems to be working well.  Thanks again for the quick turnaround!

**Comment by rfennell** [comment]
That's great news. It should work for any regex
