### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by JulienM28** [rfennell/AzurePipelines#632]
I was looking at this issue:
https://github.com/rfennell/AzurePipelines/issues/556

I tried this:

````
var datetime = new Date();
##${releaseDetails.name} ${datetime.getDay()}/${datetime.getMonth()}/${datetime.getFullYear()}
````
returns me datetime  is not defined

and this
````
${var datetime = new Date();}
##${releaseDetails.name} ${datetime.getDay()}/${datetime.getMonth()}/${datetime.getFullYear()}
````
returns me var is an invalid token

I missed something, it's obvious, but what ?

Thanks.

**Comment by rfennell** [comment]
I will try to have a look into that today. I think the issue is that lines are evaluated independently so variables are not carried across.

I assume you are trying to get a 'document generated date'

**Comment by JulienM28** [comment]
Yes I want to have the generation date of the release with format dd/MM/yyyy

**Comment by rfennell** [comment]
I have had a look and given the way the code works I cannot see a way generate a `DateTime.Now()` or equivalent to pass as cross line variable

I think the best option is to use some property of the `releaseDetails` object. You can get a full list (and it is long) using '${JSON.stringify(releaseDetails)}'

I suspect that `${releaseDetails.createdOn}` might do the job. If not that property, then one of the environment approval ones such as `createdOn'

I did a quick test with

```
${releaseDetails.createdOn}    
${releaseDetails.environments[0].preDeployApprovals[0].createdOn}    
```
And got

```
Tue Mar 03 2020 15:53:22 GMT+0000 (GMT Standard Time)
Tue Mar 03 2020 15:53:23 GMT+0000 (GMT Standard Time)
```

Does that help?

**Comment by JulienM28** [comment]
I already done that, but as you said, the output is 
Tue Mar 03 2020 15:53:22 GMT+0000 (GMT Standard Time)
But I want a shorter datetime format like
03/03/2020
So I was looking on how apply a format to the date.

**Comment by rfennell** [comment]
It is nasty, but try this, all as a single line

```
The date is ${new Date(releaseDetails.createdOn).getDate()}/ ${(+new Date(releaseDetails.createdOn).getMonth()+1)}/ ${new Date(releaseDetails.createdOn).getFullYear()}
```

This gives

```
The date is 3/ 3/ 2020
```

**Comment by KennethScott** [comment]
Just curious - is there any reason you couldn't simply do:

`The date is ${new Date(releaseDetails.createdOn).toLocaleDateString()}`

**Comment by rfennell** [comment]
No reason at all as long as it renders ok
