### ISSUE TITLE
Sort by Work item by date (or some other field)

### ISSUE THREAD

**Issue by JulienM28** [rfennell/AzurePipelines#633]
I have an issue with this template:

##Version ${releaseDetails.name}
###${releaseDetails.modifiedOn}

## Nouvelles fonctionnalités
@@WILOOP[ALL]:RN New feature@@
###${widetail.id} - ${widetail.fields['Custom.Titre']}
${widetail.fields['Custom.Details']}
@@WILOOP@@

## Améliorations
@@WILOOP[ALL]:RN Improvement@@
###${widetail.id} - ${widetail.fields['Custom.Titre']}
${widetail.fields['Custom.Details']}
@@WILOOP@@

## Corrections de bugs
@@WILOOP[ALL]:RN Bug@@
###${widetail.id} - ${widetail.fields['Custom.Titre']}
${widetail.fields['Custom.Details']}
@@WILOOP@@

I filter by tags, so I assumed I will have both features and user stories in my release note.
But there's only features, no user story even if some of them have the good tag.

Thanks.

**Comment by rfennell** [comment]
You template looks good. I am going to have to build a test rig to test your scenario as I think it should work.

A detail log might help, set a variable system.debug=true. This should show the filtering being done

**Comment by JulienM28** [comment]
My apologies, it was my fault, I realized that my user story was not related to a build....

There's still one question: that's the order of the work items.
1406
1619
1533
1622
1507
What is the ordering rule ? is it possible to order them by closing date descending for exemple ?

Thanks.

**Comment by rfennell** [comment]
Good that the first issue is resolved, lack of associations you expect gets me all the time too.

The sort order is numeric on the WI ID, this is the order we get back from the API. 

I would be a code change to swap to any other order

**Comment by rfennell** [comment]
I checked the code, my memory was off. the sort (if the parameter is set) is to sort on WI type then ID.

If the sort is not set then the order is as it comes back from the API 

```
if (sortWi) {
      agentApi.logInfo("Sorting WI by type then id");
      fullWorkItems = fullWorkItems.sort((a, b) => (a.fields["System.WorkItemType"] > b.fields["System.WorkItemType"]) ? 1 : (a.fields["System.WorkItemType"] === b.fields["System.WorkItemType"]) ? ((a.id > b.id) ? 1 : -1) : -1 );
 } else {
       agentApi.logInfo("Leaving WI in default order as returned by API");
 }
```

I guess some change could be made to pass through the name of field to sort on. But that feels prone to human error. 

Also your is the first request for anything other than ID based ordering, I wonder how much the feature would be used.

**Comment by rfennell** [comment]
I guess one idea would be to pass the name of the field to sort by. That is easy, I don't fancy putting in the complexity of handling for asc/desc.

**Comment by KennethScott** [comment]
I believe you could do this via the new [Handlebars](https://handlebarsjs.com/) template support with a custom [helper](https://handlebarsjs.com/guide/#custom-helpers).  Here's a handy [library](https://github.com/helpers/handlebars-helpers) of several different types of helpers.  If you look in the array section, there's a sort example.

**Comment by rfennell** [comment]
We now have an option to address this, @KennethScott has just provided a PR that adds handlebars support to this task. This gives a whole new range of options of templating options for generating reports.

Have a look at 2.27.4 and the updated [documentation on the new templating options](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task).

Also see 
https://handlebarsjs.com/
https://handlebarsjs.com/guide/#custom-helpers
https://github.com/helpers/handlebars-helpers

Given this new handlebars support, I will not be making any changes to the original templating engine to add further sort options.. Hence I am going to close this issue. 

If you have problems with the new templating engine please log a new issue detailing the problem, noting I can't offer support on the Handbars project code, only on how I trigger the call to Handlebars
