### ISSUE TITLE
How to escape special characters in HTML template for XplatGenerateReleaseNotes

### ISSUE THREAD

**Issue by KennethScott** [rfennell/AzurePipelines#634]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform Task

### Where are you running it?
Azure DevOps Server 2019 / on-premise

### Version of Extension/Task
Latest public/V2

Is there a template example (for the node version) or perhaps some nodejs-specific documentation somewhere that explains which characters must be escaped in a template file?  I'm trying to create an html template formatted to support viewing via web/mobile/desktop email and I'm getting errors I believe on the double-quotes (so far).  I found issue #599 that talks about escaping double-quotes, but I don't think it was properly formatted and I can't tell exactly how it's saying to escape them.  I'm assuming it's by a preceding backslash (\\).  It also mentions staying away from curly-braces (which will also be an issue in my template) but I don't think it's getting that far yet.

My full template is:

```html
<!doctype html>
<html lang="en" style="background:  white; font-size: 12px;">
<head>
    <meta charset="utf-8">
    <title>Release Notes</title>    
    <style type="text/css">
        tr:nth-of-type(even) { background-color: #f1f1f1; }         
    </style>
</head>
<body style="background: inherit; color: #333; font-size: inherit; padding: 5; font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif">

    <h1>Release Notes</h1>
    <div><span style="text-transform: capitalize;">${releaseDetails.releaseDefinition.name}</span> completed ${releaseDetails.modifiedOn}</div>

    <table style="border-spacing: 0; border-collapse: collapse;">
        <tr>
            <th>ID</th>
            <th>Developer</th>
            <th>Date</th>
            <th>Description</th>
        </tr>
        @@CSLOOP@@
        <tr>
            <td style="line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;">${csdetail.id}</td>
            <td style="line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;">${csdetail.author.displayName}</td>
            <td style="line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;">${csdetail.author.timestamp}</td>
            <td style="line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;">${csdetail.message}</td>
        </tr>    
        @@CSLOOP@@                                                    
    </table>

    <br/>
    <div>*${releaseDetails.name} was compared with ${compareReleaseDetails.name} to produce this report.</div>

</body>
</html>
```

I guess ultimately I'm concerned about the double-quotes, single-quotes, and curly-braces in my template and just looking for confirmation as to how to properly escape them - or if some part of this simply isn't compatible.  I hope if nothing else this might serve as a clear example to others if I can get it working.

From the debug log, I believe it's getting `SyntaxError: Unexpected identifier` when processing line 2.

Thank you!

**Comment by rfennell** [comment]
I will give your template a go in my test harness and try to work it out.

As to {} these can't be used in the template other than to show the start of the blocks to expand.

I will try to have a look today.

**Comment by rfennell** [comment]
I have had to do a code change to support the inline style sheet. This is released as 2.23.1

The template I used for testing was

```
<!doctype html>
<html lang='en' style='background:  white; font-size: 12px;'>
<head>
    <meta charset='utf-8'>
    <title>Release Notes</title>    
    <style type='text/css'>
        tr:nth-of-type(even) { background-color: #f1f1f1; }         
    </style>
</head>
<body style='background: inherit; color: #333; font-size: inherit; padding: 5; font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif'>

    <h1>Release Notes</h1>
    <div><span style='text-transform: capitalize;'>${releaseDetails.releaseDefinition.name}</span> completed ${releaseDetails.modifiedOn}</div>

    <table style='border-spacing: 0; border-collapse: collapse;'>
        <tr>
            <th>ID</th>
            <th>Developer</th>
            <th>Date</th>
            <th>Description</th>
        </tr>
        @@CSLOOP@@
        <tr>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${csdetail.id}</td>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${csdetail.author.displayName}</td>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${csdetail.author.timestamp}</td>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${csdetail.message}</td>
        </tr>    
        @@CSLOOP@@                                                    
    </table>

    <table style='border-spacing: 0; border-collapse: collapse;'>
        <tr>
            <th>ID</th>
            <th>WIT</th>
            <th>Title</th>
            <th>Tags</th>
        </tr>
        @@WILOOP@@
        <tr>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${widetail.id}</td>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${widetail.fields['System.WorkItemType']}</td>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${widetail.fields['System.Title']}</td>
            <td style='line-height: 1.5; vertical-align: top; border: 1px solid #bbbbbb; padding: 5px;'>${widetail.fields['System.Tags']}</td>
        </tr>    
        @@WILOOP@@                                                    
    </table>

    <br/>
    <div>*${releaseDetails.name} was compared with ${compareReleaseDetails.name} to produce this report.</div>

</body>
</html>
```
Points to note:
- {} inline css is now handled
- As each line gets wrapped in quotes so `the line` becomes `"the line"` to allow it to be evaluated this means you have to use single quotes ` for css and html attribute quoting in the template. The only place this might be problematic is for css font. I suggest using some that are single word name (less than perfect but should work) 
-I added some WI handling for completeness of testing. 

This gave me results as follows
![Capture](https://user-images.githubusercontent.com/324718/75787088-1b9ffc00-5d5e-11ea-9122-937e57b59754.PNG)

Let me know how it goes

**Comment by KennethScott** [comment]
Looks great! We've gotten the update and I've tweaked the HTML template as you indicated. I'm still making a few final tweaks now that it's working, but everything is looking really good.

Great job - I really appreciate the quick response!  If you want to leave this open a couple days, I'll share my final template HTML if you're interested.

Thanks again-

**Comment by rfennell** [comment]
Glad I was able to resolve your issue.

Any yes adding a template would be helpful when you have it working.
