### ISSUE TITLE
Error "##[error]Invalid JSON primitive: Â." in azure Devops Build pipeline.

### ISSUE THREAD

**Issue by kiranjunnuthula** [rfennell/AzurePipelines#640]
### Azure DevOps Extension you are using
I'm using Azure Repository only to build the the sppkg for sharepoint deployment. i'm using the below tasks in my build
Node Installed - to install the node
NPM Install - to install the required node modules
gulp build - to build the project
command line with the command "gulp clean && gulp bundle --ship && gulp package-solution --ship" - to bundle and build the package file for Dev Tenant
Publish Artifacts - Publishing the package file Dev Tenant.
Inline Powershell task - to generate the json file with the correct details for different tenant
command line with the command "gulp clean && gulp bundle --ship && gulp package-solution --ship" - to bundle and build the package file for QA Tenant.
Publish Artifacts - Publishing the package file for QA Tenant..

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)
Azure Pipelines with specifications VS2017-windows2016

### Version of Extension/Task
Inline Powershell version 1.*

### Expected behaviour and actual behaviour
It should generate the JSON file with configured details in the powershell task but it is giving the error "##[error]Invalid JSON primitive: Â."

### Steps to reproduce the problem
$FilePath = "Path of the appconfig.json file"
$JSONContent = (Get-Content $FilePath | ConvertFrom-Json)
try {
    $JSONContent.TrackerCSSUrl = "QA Tenant Value"
}
catch { 
}
$JSONContent | ConvertTo-Json -depth 100 | Set-Content $FilePath

above the code i'm using to generate the Json file with the qa details. But it is giving the below error.
"##[error]Invalid JSON primitive: Â."

Please let me know if you need any more details.

**Comment by rfennell** [comment]
@kiranjunnuthula  I think you have created this issue in the wrong GitHub instance. This is for support of the Azure DevOps Pipelines I have created.

The Inline PowerShell task was created by Microsoft and any issue should be reported at https://github.com/microsoft/azure-pipelines-tasks.

My guess is that there is a problem with the contents of your JSON file, I would test the script outside of Azure DevOps to see if the problem persists there. 

Sorry I cannot be of any more help.
