### ISSUE TITLE
Custom helpers not available in new Handlebars templates

### ISSUE THREAD

**Issue by KennethScott** [rfennell/AzurePipelines#644]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform Task

### Where are you running it?
Azure DevOps Server 2019 / on-premise

### Version of Extension/Task
Latest public/V2

I got a chance to play around with this today and everything seemed to be working as expected except for the custom helpers.  One thing that I didn't into take account is that the custom helpers by design can't reside within the template itself.  They would have to be defined within the calling (extension) code.  Obviously this means they're essentially useless for the end user, but I have an idea I wanted to run by you.  I believe we could extract the javascript code from the template where the user would define the custom handlers and eval it similar to what you are doing in the old style templates. In theory that would add the custom helpers to the Handlebars object and then they could be utilized within the template.  I don't think this would take much to add, so I will throw a PR together if you want to take a look.  It would also be transparent to the user.

A second, less powerful option might be to include a popular [library of custom helpers](https://github.com/helpers/handlebars-helpers) that might satisfy a chunk of the average users' needs.  You could just include in the documentation that this specific list is what's supported. I can include this in the PR as well if you want to take a look.

Thanks,

**Comment by rfennell** [comment]
I guess the best solution is to include the   helpers you suggest within the extension package. But also provide a parameter to   pass in a list of other helpers to load.

I guess the bit to investigate what has to be done in the extension code to load the helper, or can it just be referenced in the template?

**Comment by rfennell** [comment]
After a quick look adding the standard helps is easy.

In the task we need to register

```
npm install --save handlebars-helpers
```
and then in the process function make sure that a variable is declared to do the import.

```
var helpers = require('handlebars-helpers')();
//=> returns object with all (130+) helpers
```

I think for now this will be the best option, lets leave the custom helpers for a while

I will have a go at this tonight and see if my assumptions are correct

**Comment by rfennell** [comment]
I think I have it working I can now call templates in the form

```
## To confirm the handbars helpers is work
The year is {{year}} 
We can capitalize "foo bar baz" {{capitalizeAll "foo bar baz"}}
```

It is just running through the release pipeline for a final test

**Comment by KennethScott** [comment]
Nice!  I think just having those will help a variety of scenarios.  

I think I have it pretty much worked out if you want to consider the option of allowing users to include their own custom helpers within the templates themselves.

Prior to compiling and executing the Handlebars template, we could regex the script tags out of the template and eval them with something like this:

```js
...
// it is a handlebar template
agentApi.logDebug("Processing handlebar template");

// helpers will be in script tags (allow for multiples)
var re = /<script\b[^>]*>([\s\S]*?)<\/script>/gmi;
var match;
// grab any script tags from the template and eval their contents
while (match = re.exec(template)) {
  eval(match[1]);
}
// remove the script tags from the template so they don't show in markup/markdown/etc
template = template.replace(re, '');

// compile the template
var handlebarsTemplate = Handlebars.compile(template);
...execute the template as usual...

```

to test I just created the following simple custom helper:
```js
<script type="text/javascript">
Handlebars.registerHelper('formatDate', function(date) {
    return new Date(date).toLocaleDateString() + ' ' + new Date(date).toLocaleTimeString();
});
</script>
```

and added the following to a template:
`{{formatDate '2020-01-01'}}`

A couple thoughts:
1) You wouldn't necessarily have to remove the script tags after eval'ing them.  They obviously won't render anything in html, but in markdown they'd be visible unless the user commented them out.  I guess it's possible the user has other non-handlebar javascript in their template they wouldn't want removed.  Perhaps we use a script tag with a particular type attribute like the one used if referencing external handlebar templates - type="text/x-handlebars-template" ?
2) It might be a little strange to have script tags if you're using markdown, but since you'd have a way to keep them from rendering does it matter?

**Comment by rfennell** [comment]
Ok I have custom extensions working too, took a bit longer than expected.

There is now a new sections 'Handlebars' when you configure the task. In this section there is one parameter where you enter a custom module in the form

```
module.exports = {foo: function () {return 'Returns foo';}};
```

and you access it in the template as

```
{{foo}}
```
This is releases as 2.28.7

**Comment by KennethScott** [comment]
Very elegant solution!  Thanks for the hard work on this - I can't wait to try it out.

**Comment by KennethScott** [comment]
Tried a few custom helpers today - all worked perfectly!  Thanks again-

**Comment by rfennell** [comment]
Great news, I think it is a really worthwhile enhancement. Interesting to see how popular it becomes.

If you have any interesting template sample feel free to add the to the samples folder via pr
