### ISSUE TITLE
question on WILOOP

### ISSUE THREAD

**Issue by poplevente** [rfennell/AzurePipelines#647]
### Azure DevOps Extension you are using
XplatGenerateReleaseNotes
Generate Release Notes (Crossplatform)

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
latest

Question,

in the WILOOP, is it possible to list only the work items which are not tasks?

**Comment by rfennell** [comment]
Yes you filter based on a field, something like this

```
@@WILOOPLSystem.WorkItemType=Bug@@  
* **${widetail.fields['System.WorkItemType']} ${widetail.id}** ${widetail.fields['System.Title']}  
@@WILOOPLSystem.WorkItemType=Bug@@  
```

The other option is to switch to the [new Handlebars syntax](https://blogs.blackmarble.co.uk/rfennell/2020/03/11/a-major-new-feature-for-my-cross-platform-release-notes-azure-devops-pipelines-extension-handlebars-templating-support/), but I have extensive samples for that as yet

Hope that gets you going, just reopen the issue if you need to

**Comment by poplevente** [comment]
Hey, does not seem to be working. all work item types are included in the list

**Comment by poplevente** [comment]
Never mind, my fault ;)
