### ISSUE TITLE
Recommendation for debugging template changes against particular releases

### ISSUE THREAD

**Issue by KennethScott** [rfennell/AzurePipelines#650]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform Task

### Where are you running it?
Azure DevOps Server 2019 / on-premise

### Version of Extension/Task
Latest public/V2

Can you tell me your recommended approach for debugging/testing template changes against a particular release?  To explain, we run the release notes report on the releases (as opposed to the builds).  I find myself making a small template change, waiting for the next developer commit to kickoff another build/release deployment, and reviewing the results.  If something wasn't quite right, I have to tweak the template and wait for another commit to kickoff the process again...  because if we just manually run the release deployment again, it compares against the last one (that was successful) and I won't see any commits/workitems.

I guess I'm wondering if we're doing something wrong and there's a better way, or if there's some way to, for debugging/diagnostic purposes, temporarily have it always compare to a particular release (that did have commits/workitems).

Hopefully that makes sense.  Any advice/guidance would be appreciated.

Thanks-

**Comment by rfennell** [comment]
Unfortunately there is not easy way to run test locally at present. For other tasks I have written I have tried to separate all the Azure DevOps handling code into the other wrapper and all the basic processing into a function that can be tested independently. However, the history of this task involves a good few PRs from different people and we never ended up with that separation. It would be good to add, but not sure when I would get round to it. 

The way I test it is to have a validation release pipeline. This runs the task in a variety of ways and platforms

- Windows
- Linux
- Mac

But it also runs a build that generates more build artefacts with associated and  wi and commits. This is a link to one of my [validation releases](https://dev.azure.com/richardfennell/GitHub/_release?definitionId=23&view=mine&_a=releases) (I have a few)

The advantage of this model is
- if the release is OK you get the same test data for the next release - for comparison
- if the release fails you just get more associated items added, so still useful

Sorry I don't have a better solution at present. But does this help?

**Comment by KennethScott** [comment]
Yes, thank you!  If nothing else, it lets me know I'm not missing something obvious.  :)   It's really only relevant when you're trying to tweak a template anyway so not that big a deal.  I tried staring at the code awhile and looking at the DevOps API doc, but couldn't quite wrap my head around what options/if any there might be there.  Thanks for the explanation!
