### ISSUE TITLE
Commit messages returned from the DevOps API truncated at new lines

### ISSUE THREAD

**Issue by KennethScott** [rfennell/AzurePipelines#651]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform Task

### Where are you running it?
Azure DevOps Server 2019 / on-premise

### Version of Extension/Task
Latest public/V2

This is probably really a DevOps question, but I thought I'd ask it here in case you have run into it and might know a solution.  Do you know of a way to make DevOps return full/non-truncated commit messages?  It appears to truncate at the first new line (\\n) in the message.

I looked through the code and found that it's calling the [Get Commits Batch](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits%20batch?view=azure-devops-server-rest-5.0) API function.  I then fired up Postman and did some testing and found that the `comment` attribute text is truncated where the first new-line would be, and the `commentTruncated` property is set to `true`.

I can't seem to find any doc or example really explaining the use of the commentTruncated flag.  I guess it's good to know, but no one is going to want to make an additional call back to the server for each truncated commit message.  Surely there's some way to override it and have it just return the full message from the start?

Just for the heck of it, I made a call to the regular [Get Commits](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-server-rest-5.0) API function, and it does in fact return the full/non-truncated message.

Do you think they seriously expect you to make an additional API call back to **Get Commits** for each truncated message you want to expand?  That seems like a bunch of unnecessary overhead even though you can send in an array of ids and get a bunch at once.  I'm hoping you've encountered this or might have some insight?

Thanks,

**Comment by rfennell** [comment]
Yes it is an issue, you have to check the truncate flag to get the full message. There is an expand commits function or similar name in this task to do the job. 

This works fine Azure DevOps, but is problemic for GitHub hosted repos, I recently added special handling. But this only works for public projects. There is an issue for this.

**Comment by KennethScott** [comment]
Well, I saw the threads about GitHub repos, but we're using an on-premise instance of Azure DevOps Server (TFS2019).  That's what threw me about it.  I guess maybe it's a difference between Azure DevOps Services and Azure DevOps Server?

**Comment by KennethScott** [comment]
Another update..  I've been digging through the code a bit more and got the output from the logs.  It does appear it at least runs through the expansion code, however it doesn't seem to detect any as expanded?

```
2020-03-20T19:36:21.3676067Z Detected 6 commits/changesets and 0 workitems between the builds.
2020-03-20T19:36:21.3676092Z 
2020-03-20T19:36:21.3676141Z Expanding the truncated commit messages...
2020-03-20T19:36:21.3676174Z Finished expanding [0] commits.
2020-03-20T19:36:21.3676215Z Get details of [0] WIs
2020-03-20T19:36:21.3676243Z Total commits: [6]
2020-03-20T19:36:21.3676297Z Total workitems: [0]
```

There  should have been 1 commit that needed expanding, but I don't think it even tried based on the log messages (or lack thereof)?

**Comment by rfennell** [comment]
The way I debugged this in the past has been to run the API call to get the list of commits then look at json returned for the truncated flag.

At present the expand does nothing if it is false. But happens if you make the call anyway?

**Comment by KennethScott** [comment]
Can you take a look at PR #652 I just submitted and see if you agree that might be the issue?  From what I could tell, the json object has a property named `commentTruncated`, but it's not being set on the new commit object being created in `Issue349Workaround`.  I just added a line to add the attribute (with the name you're looking for later in the code) of `messageTruncated`.

Let me know what you think.  Thanks!

**Comment by KennethScott** [comment]
That seems to have done the trick.  The messages are being expanded now.  Thank you!
