### ISSUE TITLE
Custom Handlebars Extension failing for build pipeline on macOS-10.14 agent

### ISSUE THREAD

**Issue by gregwoodsit** [rfennell/AzurePipelines#654]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.30.5

### Expected behaviour and actual behaviour
Using a Build pipeline running on macOS-10.14 Agent

When using the Custom Handlebars Extension section an error occurs:
`
Writing output file undefined/customHandlebarsExtension.js
##[error]Error: ENOENT: no such file or directory, open 'undefined/customHandlebarsExtension.js'
`
### Steps to reproduce the problem
Configure a build pipelin on macOS-10.14 and add a custom handlebar extension

**Comment by rfennell** [comment]
I have a repo of this problem, I will look into a solution

**Comment by rfennell** [comment]
Seem it is a [known issue](https://github.com/Microsoft/azure-pipelines-agent/issues/168). Sorry the fact I had not spotted this before was poor testing on my part. Rest assured I have updated my release pipeline to address the gap in testing. I now test the handlebar extension loading on Mac, Windows and Linux.

The fix is

```
// cannot use process.env.Agent_TempDirectory as only set on Windows agent, so build it up from the agent base
// Note that the name is case sensitive on Mac and Linux
var customHandlebarsExtensionFolder = `${process.env.AGENT_WORKFOLDER}/_temp`;
```

I have fix it in 2.31.4, sorry for not catching it earlier

**Comment by gregwoodsit** [comment]
@rfennell works perfectly, thanks for fixing that so fast!!

I noticed a little typo in the log (but not a big deal):
```
Loading custom handlebars extension
Writing output file /Users/runner/runners/2.165.2/work/_temp/customHandlebarsExtension.js
**Finsihed** writing output file /Users/runner/runners/2.165.2/work/_temp/customHandlebarsExtension.js
Completed processing template
```

**Comment by rfennell** [comment]
Glad we got that sorted, I will address the typo in the next release
