### ISSUE TITLE
Pester Test Runner fails if no repositories are registered

### ISSUE THREAD

**Issue by masterofimages** [rfennell/AzurePipelines#657]
### Azure DevOps Extension you are using
Pester Test Runner v8.13.3

### Where are you running it?
Azure DevOps Server (Version Dev17.M153.3)

### Version of Extension/Task
Pester Test Runner v8.13.3

### Expected behaviour and actual behaviour
When running on a build server with no repositories registered, the task fails with the following error:

##[error]System.Exception: No match was found for the specified search criteria and module name 'Pester'. Try Get-PSRepository to see all available registered module repositories.

The task is failing at line 86 of Pester.ps1, calling Find-Module:

$NewestPester = Find-Module -Name Pester | ...

If no repositories are registered, the task should simply check that Pester is installed, and carry on.

### Steps to reproduce the problem
Run on a machine with no repositories registered.

**Comment by ChrisLGardner** [comment]
Thanks for reporting this. I'll be fixing it as part of the move to the Pester org and publishing under that publisher instead. I'm working through a few issues with it now so might take a week or two to get it released.

**Comment by ChrisLGardner** [comment]
Moving over to https://github.com/pester/AzureDevOpsExtension/issues/7 and tracking the work on this there.
