### ISSUE TITLE
Generate Release Notes Since Last Release to Production?

### ISSUE THREAD

**Issue by kingua** [rfennell/AzurePipelines#658]
### Azure DevOps Extension you are using
*Generate Release Notes (Crossplatform)

### Where are you running it?
*Azure DevOps Service (VSTS)

### Version of Extension/Task
*2

### Expected behaviour and actual behaviour
Is it possible to use this extension to do something like the following?
Release Dev -> Test
Release Dev -> Test
Release Dev -> Test -> Generate Build/Release Notes including all commits, etc. of above -> Release to Prod
Release Dev -> Test
Release Dev -> Test
Release Dev -> Test -> Generate Build/Release Notes includding all commits, etc. since last release to Prod -> Release to Prod

**Comment by rfennell** [comment]
The easiest way is to have a stage called 'Generate Build/Release Notes including all commits, etc. of above' (or maybe shorten that name a bit) that contains the generate release note task and is  run only when you progress through to 'Release & Prod'.

The other option is to look at the 'overrideStageName' option. That allow the release notes task to look for the last successful run in a different stage.

Does that help?

**Comment by kingua** [comment]
Thank you for the quick respose!

The first option seems to be the best.  That was my thinking, but I wasn't sure exactly how the task works.  Based on this suggestion, is it correct that the task compares with the last time the task was run, not just the previous release?

For example:
Release 1 to Dev and Test
Release 2 to Dev and Test
Release 3 to Dev and Test, Generate Release Notes (will look to release 1, since the notes haven't been generated yet)
Release 4 to Dev and Test
Release 5 to Dev and Test
Release 6 to Dev and Test, Generate Release Notes (will look to release 3, since the notes were last generated on release 3)

Also, do you pull any Pull Request Data as part of the task -- e.g. Code Review ID, Approved By, etc.?

Really great work on this as well as your Wiki Update task.

Cheers!

**Comment by rfennell** [comment]
Glad that got you sorted.

All the data available can be seen if you use the [Dump Template](https://github.com/rfennell/AzurePipelines/blob/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/release-dump-values.md). I have avoided 'enriching' this data with extra calls as it would be a never ending race as everyone wants different things

**Comment by kingua** [comment]
This works great now, but I do really need to be able to access Pull Request data as well for auditing purposes.  I totally get you can't take all suggestions for enriching the data, but that would be super helpful, and I'm sure others would find it useful.  Just a suggestion :)

Thanks!

**Comment by rfennell** [comment]
Its a reasonable suggestion. Let me see what I can do

**Comment by rfennell** [comment]
@kingua I have moved this enhancement to it's own issue. makes it easier to track 

#664
