### ISSUE TITLE
How work item loop works with build pipeline in release note generator(Cross platform)

### ISSUE THREAD

**Issue by Ajithachuthan** [rfennell/AzurePipelines#659]
### Azure DevOps Extension you are using
GenerateReleaseNotes Node based Cross Platform

### Where are you running it?
Running extension through build pipeline
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.*

### Expected behaviour and actual behaviour
 In my first run of WI loop from build pipeline, I am expecting it will return the entire work item set(From the first day I created my master branch). 

### Steps to reproduce the problem
Added below mentioned work item loop to the build pipeline to get all the work item details from my master branch. But it returns only a few(Which almost related with my current sprint)

@@WILOOP@@
* **${widetail.fields['System.WorkItemType']} #${widetail.id}** Assigned by: ${widetail.fields['System.AssignedTo']} - ${widetail.fields['System.Title']}
@@WILOOP@@

**Comment by rfennell** [comment]
Could you please answer the question in template, not just put it all in the title. I need as much detail as possible to be able help.

Specifically I need the the 'Steps to Reproduce', details logs help too. You can get these by setting a a variable `system.debug=true`

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
