### ISSUE TITLE
Allow generation for only Release.TriggeringArtifact.Alias

### ISSUE THREAD

**Issue by Olgsie** [rfennell/AzurePipelines#660]
### Azure DevOps Extension you are using
Generate Release Notes for Pipeline Build or Releases (Powershell)
(I know there's a newer version but my organisation doesn't support it atm..)

### Where are you running it?
- Azure DevOps Service (VSTS) - vs2017-win2016

### Version of Extension/Task
3.*

### Expected behaviour and actual behaviour
We have a single pipeline that is linked to several build artifacts, to be triggered when any one of them are build. In our pipeline we then use $(Release.TriggeringArtifact.Alias) to determine which if the builds is the one currently needing to be used in the release.
Expected:
For the generation of release notes we would therefore like only the triggering build to be included.
Just another checkmark like "Generate for only primary artifact" would be ideal.
Actual:
Now all the other builds that are also linked to this release but are not relevant are also included in release notes.

### Steps to reproduce the problem
Link multiple build artifacts to one release and build one of them to trigger the release. You can set for example the release name using $(Release.TriggeringArtifact.Alias) to verify which build is the trigger. Then create release notes and you will also see the irrelevant builds included.

**Comment by rfennell** [comment]
Oh,  really had wanted to make no more changes to this task, but that does sound a reasonable request. 

I need to check that I can detect that flag to see how easy it is

**Comment by rfennell** [comment]
OK have a look a 3.7.6.

This was harder than you might expect. There seems to be no easy way to work out what the trigger event was for a release.

You might expect if you get the release details using a REST call in the form

```
https://vsrm.dev.azure.com/richardfennell/GitHub/_apis/release/releases/1966
```
In the returned JSON you might expect the trigger would be the `$currentRelease.triggeringArtifactAlias`, but in my tests this is value is always null.

So I have have to resorted to string matching in the form

```
($currentRelease.description -eq "Triggered by $($artifact.definitionReference.definition.name) $($artifact.definitionReference.version.id).")
```

I don't like this solution, it feels 'brittle' and I fear it will fail if the user language is not English.

But lets see how it goes,  @Olgsie let me know you results

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Comment by Olgsie** [comment]
Hi, I've tried with your solution and it didn't work, notes now showed no build at all. Also tried to overwrite the value for Primary release artifact with the Trigger alias and use that check to generate for the correct build, also didn't work.. Starting to think we may need to create separate pipelines for each artifact after all

**Comment by rfennell** [comment]
Separate pipelines is often the best solution. I would also consider, given the current state of Azure DevOps and the roadmap, moving everything into multistage YAML pipelines, one per package. I am starting to do this for my extensions, [here are my notes](https://github.com/rfennell/AzurePipelines/wiki/Outlining-my-Azure-DevOps-CI-CD-Process-using-YAML-based-tools)

Do you want me to re-open this issue and look any further, or is this idea worked to its logical endpoint?
