### ISSUE TITLE
Wrong result release-notes file encoding. GenerateReleaseNotes (XPlat version)

### ISSUE THREAD

**Issue by denomi3** [rfennell/AzurePipelines#661]
### Azure DevOps Extension you are using
Generate Release Notes XPlatform
v.3
 
### Where are you running it?
- Azure DevOps Server (Version Dev17.M153.5)

### Version of Extension/Task
id: "BM-VSTS-XplatGenerateReleaseNotes"
version: "3.3.1"

### Expected behaviour and actual behaviour
Got release-notes .md file in wrong encoding for example:

### All associated work items
* ** User Story #4085671 ** Assigned by: Dmitry G. **  DE Redirect
* ** Task #4087819 ** Assigned by: Dmitry G. **  ???????? ???? ? ??????? ??? ????????? ?????

### Steps to reproduce the problem
Run on release task, related WI containes cyrillic characters

**Comment by rfennell** [comment]
Firstly are you sure it is the Cross Platform version and you are on version 3.3.1?

- The Cross Platform version is at 2.31.4
- The Powershell version is at 3.6.1

It might be worth looking at an update version, as I seem to remember we have done some file encoding work.

If that does not help what is the text in the title that is being encoded incorrectly so I can try to create a test showing the problem

**Comment by denomi3** [comment]
I'm sorry, I watched the version in the vss-extension.json file.
Where can I see the current version?

Yes, saw fix for Powershell version https://github.com/rfennell/AzurePipelines/issues/290#issue-310735954, but not for XPlat.

It looks like you need to fix XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts:

- function writeFile
- fs.writeFileSync (filename, data) -> fs.writeFileSync (filename, data, {encoding: 'utf8'})

**Comment by denomi3** [comment]
Title for test: Корректная кодировка для элементов с кириллицей

**Comment by rfennell** [comment]
Perfect, I will create a test for that title and check out the encoding

**Comment by rfennell** [comment]
Should be fixed in 2.32.2 which has just been released

Thanks for reporting it and please reopen if there are any issues
