### ISSUE TITLE
Avoid empty blocks

### ISSUE THREAD

**Issue by JulienM28** [rfennell/AzurePipelines#669]
I have this template:

##Version ${releaseDetails.name}
###${new Date(releaseDetails.createdOn).getDate()}/${new Date(releaseDetails.createdOn).getMonth()+1}/${new Date(releaseDetails.createdOn).getFullYear()}
###${new Date(releaseDetails.createdOn).toLocaleDateString('fr-FR')}

## Nouvelles fonctionnalités
@@WILOOP[ALL]:RN New feature@@
###${widetail.id} - ${widetail.fields['Custom.Titre']}
${widetail.fields['Custom.Details']}
@@WILOOP@@

## Améliorations
@@WILOOP[ALL]:RN Improvement@@
###${widetail.id} - ${widetail.fields['Custom.Titre']}
${widetail.fields['Custom.Details']}
@@WILOOP@@

## Corrections de bugs
@@WILOOP[ALL]:RN Bug@@
###${widetail.id} - ${widetail.fields['Custom.Titre']}
${widetail.fields['Custom.Details']}
@@WILOOP@@

and if there's no item to display in one of the following I have the title but nothing else.

Is there a way to do something like ?
if(foo.cout()>0) ....... to avoid display the title if the is no element to display.

Thank you.

**Comment by JulienM28** [comment]
If found that I cant use {{workitems.length}} with handlebars, but I didn't found how to filter these workitems using handlebars

**Comment by rfennell** [comment]
Using the legacy template system the answer is no, but there is a new option for templating that should help. 

I recently added [Handlebars template support](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) that is much more flexibly.

Handlbars allows conditionals [see the handlebar docs](https://handlebarsjs.com/guide/builtin-helpers.html#if). I also spotted that the [foreach option has the option to do something only on the first line](https://stackoverflow.com/questions/21094459/condition-in-handlebars-if-statement)

So you block could be something like

```
{{#each commits}}
    {{#if {{@first}}}}
### Associated commits ({{commits.length}})
   {{/if}}
* ** ID{{this.id}}** 
   -  **Message:** {{this.message}}
   -  **Commited by:** {{this.author.displayName}} 
{{/each}}
```
I have not had chance to test this, but it should be close

You can find a [sample handlebars templates here](https://github.com/rfennell/AzurePipelines/blob/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/release-handlebars-template.md)

Let me know how it goes and the template you end up with and maybe we can put it in the sample library.

**Comment by JulienM28** [comment]
How can I filter workitems, with tags for exemple, like in th legacy template engine ?

I didn't found how to translate this:
@@WILOOP[ALL]:RN New feature@@

with Handlebars

**Comment by rfennell** [comment]
Oh, interesting. It must be possible with handlebars, the question is whether it can be done would build in helpers or a custom module.

The tag is just a field with a comma separated list, so some sort of string compare

I will have to have a look, and experiment.

**Comment by rfennell** [comment]
Bit of testing, the form for title row only being shown if there are items

```
{{#each workItems}}
{{#unless isFirst}}### Associated Work Items (only shown if  WI) {{/unless}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
{{/each}}
```

**Comment by rfennell** [comment]
The code you need to only show a title of there are WI or Cs is

Note the swap from {{#each}} to {#foreach}} to get the extension that lets you know where you are the in loop

```
##  Associated Work Items ({{workItems.length}})
{{#forEach workItems}}
{{#if isFirst}}### Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
{{/forEach}}

## Associated commits  ({{commits.length}})
{{#forEach commits}}
{{#if isFirst}}### Associated commits  (only shown if CS) {{/if}}
* ** ID{{this.id}}** 
   -  **Message:** {{this.message}}
   -  **Commited by:** {{this.author.displayName}} 
{{/forEach}}
```

**Comment by rfennell** [comment]
Ok this will filter by tag, it uses regex is is very flexible

```

##  Associated Work Items with Tag1
{{#forEach workItems}}
{{#if (test (lookup this.fields 'System.Tags') (toRegex 'Tag 1')) }}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
{{/if }}
{{/forEach}}

```

What I cannot work out is how to only show the title if there is an array item with the matching tag. You can't use the `isFirst` as this does not take a filter. There seems to be no way to know if this is the first items that meets the regex filter.

I have added this to the [samples](https://github.com/rfennell/AzurePipelines/blob/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/release-handlebars-template.md)

**Comment by JulienM28** [comment]
This template do the job perfectly
Checking if the element is the first permit to display the title only if thre's at least one element.
Exactly what I wanted. 

##Version {{releaseDetails.name}}
###{{date}}

{{#forEach workItems}}
{{#if (test (lookup this.fields 'System.Tags') (toRegex 'RN New feature')) }}
{{#if isFirst}}
##Nouvelles fonctionnalités
{{/if}}
###{{this.id}} {{lookup this.fields 'Custom.Titre'}}
{{lookup this.fields 'Custom.Details'}}
{{/if}}
{{/forEach}}

{{#forEach workItems}}
{{#if (test (lookup this.fields 'System.Tags') (toRegex 'RN Improvement')) }}
{{#if isFirst}}
##Améliorations
{{/if}}
###{{this.id}} {{lookup this.fields 'Custom.Titre'}}
{{lookup this.fields 'Custom.Details'}}
{{/if}}
{{/forEach}}

{{#forEach workItems}}
{{#if (test (lookup this.fields 'System.Tags') (toRegex 'RN Bug')) }}
{{#if isFirst}}
##Corrections de bugs
{{/if}}
###{{this.id}} {{lookup this.fields 'Custom.Titre'}}
{{lookup this.fields 'Custom.Details'}}
{{/if}}
{{/forEach}}

**Comment by JulienM28** [comment]
I still have an issue:
Custom.Details is a textarea input and it contains html.

Generate release not is escaping this html, and I do'nt see option to avoid that.

**Comment by JulienM28** [comment]
I didn't have this issue with legacy template engine

**Comment by rfennell** [comment]
Does the triple {{{  }}} synatx help?

> I know that it escapes HTML values by default and that you have to use the triple brackets {{{text}}} in order for text: <p>Example</p> to be rendered as an HTML element.

I found this at https://stackoverflow.com/questions/10654234/how-to-decode-html-entity-with-handlebars

If that does not help you will need a custom helper to the decode

**Comment by JulienM28** [comment]
yes it's working, that's why I removed my comment, I remembered I seen triple mustache avoid escaping.

Thanks.

**Comment by rfennell** [comment]
Great, if is OK I will close this issue. Reopen if you need to.
