### ISSUE TITLE
Cannot read property 'commitId'

### ISSUE THREAD

**Issue by BSLuttrell** [rfennell/AzurePipelines#678]
### Generate Release Notes (Crossplatform)
*2.34.7

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS) -> Release Pipelines

### Version of Extension/Task
*2.34.7

### Expected behavior and actual behavior
Since latest upgrade 8 hrs ago  task is failing "Cannot read property 'commitId' of undefined"

Logs from Task
2020-04-16T00:52:29.3042006Z Detected 8 commits/changesets and 2 workitems between the builds.
2020-04-16T00:52:29.3047731Z 
2020-04-16T00:52:29.3054126Z Expanding the truncated commit messages...
2020-04-16T00:52:29.5768031Z Finished expanding [4] commits.
2020-04-16T00:52:29.5807494Z Get details of [1] WIs
2020-04-16T00:52:29.5808525Z Getting full details of WI batch from index: [0] to [1]
2020-04-16T00:52:29.7501304Z Adding [1] items
2020-04-16T00:52:29.7506219Z Total commits: [8]
2020-04-16T00:52:29.7507190Z Total workitems: [1]
2020-04-16T00:52:29.7508091Z Leaving WI in default order as returned by API
2020-04-16T00:52:29.8186662Z The default artifact for the release was not linked to a Azure DevOps Git Repo Pull Request
2020-04-16T00:52:30.2225817Z Checking for PRs associated with the commit 04c66797a50b3017a6ce6c42b05ecece15730fb4
**2020-04-16T00:52:30.2336731Z ##[error]TypeError: Cannot read property 'commitId' of undefined
2020-04-16T00:52:30.2579740Z ##[error]TypeError: Cannot read property 'commitId' of undefined**
2020-04-16T00:52:30.2583645Z ##[section]Finishing: Generate Release Notes for QA

### Steps to reproduce the problem
Inline template using handlebars 
```

## Notes for release  {{releaseDetails.name}}
**Release Number**  : {{releaseDetails.name}}
**Release completed** : {{releaseDetails.modifiedOn}}     
**Build Number**: {{buildDetails.id}}
**Compared Release Number**  : {{compareReleaseDetails.name}}    

### Associated Work Items ({{workItems.length}})
---
{{#each workItems}}
*  #{{this.id}}
{{/each}}

### Associated Commits ({{commits.length}})
---
{{#each commits}}
---
>*  **Commit ID:** {{this.id}}
>  -  **Message:** {{this.message}}
>  -  **Commited By:** {{this.author.displayName}} 
{{/each}}

```

**Comment by rfennell** [comment]
Looks to be a bug in the new code to try to find associated PRs, I will look into it

**Comment by rfennell** [comment]
@BSLuttrell am I right in assuming that your source code is not hosted on an Azure DevOps Repo ?

**Comment by vatho** [comment]
We're having the same issue on our tenant, where our source code is hosted on an Azure DevOps repo.

**Comment by rfennell** [comment]
I think the issue is a mixture of
- attempting to match GitHub commits with Azure DevOps PRs
- incorrectly handing empty list when filtering arrays.

I have just created what I hope is a fix, should at least give better logging. This has has just gone into my release pipeline, hope to have to published inside the hours for you to try

Sorry for the inconvenience the new feature has caused

**Comment by rfennell** [comment]
@BSLuttrell @vatho

2.35.2 has just been release - please let me know if this fixes your issues

**Comment by vatho** [comment]
@rfennell Seems to be working again, thanks for the quick fix!

**Comment by rfennell** [comment]
Phew!!!

I was not error trapping for all edge cases, sorry you had the problem at all.

**Comment by BSLuttrell** [comment]
Maybe I'm being silly but I'm still getting the error.
I confirmed the extensions been updated to 2.35.2

@rfennell to answer you're previous question our code is hosted in Azure Repos. 

Let me know if there is any more info you need. 

**Logs**
2020-04-16T12:10:12.5140547Z Looking for the [_BarcodeNextGen_Dev] in the most recent successful release [2020.04.23]
2020-04-16T12:10:12.5141053Z Found artifact [_BarcodeNextGen_Dev] with build number [20200415.3] in release [2020.04.23]
2020-04-16T12:10:12.5141615Z Checking what commits and workitems have changed from [20200415.3][ID 307] => [20200416.1] [ID 310]
2020-04-16T12:10:12.5143212Z Defaulting on the workaround for build API limitation (see issue #349 set 'ReleaseNotes.Fix349=false' to disable)
2020-04-16T12:10:12.5143706Z Using workaround for build API limitation (see issue #349)
2020-04-16T12:10:13.1959655Z Detected 59 commits/changesets and 53 workitems between the builds.
2020-04-16T12:10:13.1960226Z 
2020-04-16T12:10:13.1985961Z Expanding the truncated commit messages...
2020-04-16T12:10:15.1324234Z Finished expanding [30] commits.
2020-04-16T12:10:15.1354309Z Get details of [25] WIs
2020-04-16T12:10:15.1355211Z Getting full details of WI batch from index: [0] to [25]
2020-04-16T12:10:15.3205648Z Adding [25] items
2020-04-16T12:10:15.3208089Z Total commits: [59]
2020-04-16T12:10:15.3208403Z Total workitems: [25]
2020-04-16T12:10:15.3208863Z Leaving WI in default order as returned by API
2020-04-16T12:10:15.3733511Z The default artifact for the release was not linked to a Azure DevOps Git Repo Pull Request
2020-04-16T12:10:15.3735007Z Checking to see if any commits are associated with Azure DevOps Git Repo Pull Request
2020-04-16T12:10:15.6023864Z Found 84 Azure DevOps for PRs for project ByteSized.2DScannerApp_NextGen
2020-04-16T12:10:15.6025502Z Checking for PRs associated with the commit 04c66797a50b3017a6ce6c42b05ecece15730fb4
2020-04-16T12:10:15.6058068Z ##[error]TypeError: Cannot read property 'commitId' of undefined
2020-04-16T12:10:15.6258504Z ##[error]TypeError: Cannot read property 'commitId' of undefined
2020-04-16T12:10:15.6261714Z ##[section]Finishing: Generate Release Notes for Dev

**Comment by rfennell** [comment]
Ok, it was obviously two edge case issues. One down one to go.....

The line that is failing must be
```
var matches = allPullRequests.filter(pr => pr.lastMergeCommit.commitId === commit.id);
```
as this is only line in the code base that references `commitId`. I have to assume that on your system that there is no `lastMergeCommit` for each PR - but not sure why,

I can of course put in try/catch extra logic but I would like to find out why it is occurring and get it to work as opposed to just coding around it.

Could you please, in the same browser as you are logged into Azure DevOps can you please call the URL

```
https://dev.azure.com/<your org>/<your project fom logs appears to be ByteSized.2DScannerApp_NextGen>/_apis/git/pullrequests?searchCriteria.status=completed**
``` 
This should return the same 84 PRs found by the task as block of JSON. I would expect to see something like

```
value: [
{
  repository: {
  ....
  },
  pullRequestId: 18,
  codeReviewId: 18,
  status: "completed",
  createdBy: {
 ....
 },
  creationDate: "2020-04-16T09:37:20.43556Z",
  closedDate: "2020-04-16T09:37:34.4041029Z",
  title: "Updated readme.md",
  description: "Updated readme.md",
  sourceRefName: "refs/heads/test1",
  targetRefName: "refs/heads/master",
  mergeStatus: "succeeded",
  isDraft: false,
  mergeId: "aa83c930-0411-4d41-ade1-59fc2f40f94d",
  lastMergeSourceCommit: {
   ...
   },
   lastMergeTargetCommit: {
   ...
   },
   lastMergeCommit: {
      commitId: "79c194082c5a5d3f96afab020ff6c8daaf3184cb",
      url: "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/git/repositories/bebd0ae2-405d-4c0a-b9c5-36ea94c1bf59/commits/79c194082c5a5d3f96afab020ff6c8daaf3184cb",
   },
reviewers: [ ],
....
```

1. Can you let me know what you have for the lastMergeCommit on your PRS?
1. Are they all the same format or is one or more different?
1. What type of merge are you doing when you complete your PR, maybe I have missed a case

Thanks, and sorry again for the issue you are having

**Comment by BSLuttrell** [comment]
1. Below is the Response 
2. You mentioned it should return 84 but only one was returned. 
3. I'm merging develop into release using a PR  after the PR is approved. I did just realize I must have the delete branch after merge checked (oops) and it's deleting my develop branch. Not sure if that is the issue.

Happy to do a screen share if it makes it easier 
 
`{
   "value":[
      {
         "repository":{
            "id":"ab0d1917-dfc4-4b38-b8ed-5a67127272aa",
            "name":"ByteSized.2DScannerApp_NextGen",
            "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa",
            "project":{
               "id":"88547fdf-c99a-4868-8b65-d70343fa3df8",
               "name":"ByteSized.2DScannerApp_NextGen",
               "state":"unchanged",
               "visibility":"unchanged",
               "lastUpdateTime":"0001-01-01T00:00:00"
            
}
         
},
         "pullRequestId":215,
         "codeReviewId":215,
         "status":"active",
         "createdBy":{
            "displayName":"Brandon Luttrell",
            "url":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
            "_links":{
               "avatar":{
                  "href":"https://dev.azure.com/BSSProducts/_apis/GraphProfile/MemberAvatars/aad.NjZkY2E0MTctMzgyYi03YjExLTljNTgtYTY0ZWY3YTc4NGQ2"
               
}
            
},
            "id":"49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
            "uniqueName":"Removed By ME",
            "imageUrl":"https://dev.azure.com/BSSProducts/_api/_common/identityImage?id=49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
            "descriptor":"aad.NjZkY2E0MTctMzgyYi03YjExLTljNTgtYTY0ZWY3YTc4NGQ2"
         
},
         "creationDate":"2020-04-15T19:39:51.6015498Z",
         "title":"Fixed Issues with NDC and Showing non matched NDC",
         "sourceRefName":"refs/heads/feature/VisIssuesRound2",
         "targetRefName":"refs/heads/featureLogInPage",
         "mergeStatus":"succeeded",
         "isDraft":false,
         "mergeId":"23352701-03b3-429b-a7b9-bf0fde252db5",
         "lastMergeSourceCommit":{
            "commitId":"e407617a21ed40976ee9f8a215f0e65a1ee545dc",
            "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/e407617a21ed40976ee9f8a215f0e65a1ee545dc"
         
},
         "lastMergeTargetCommit":{
            "commitId":"6d89c0d4bb83a02110287fea5fd6f912a1ba61d4",
            "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/6d89c0d4bb83a02110287fea5fd6f912a1ba61d4"
         
},
         "lastMergeCommit":{
            "commitId":"90bd3b2727c4cd22b7db1f2c8105c0a2cf27e13a",
            "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/90bd3b2727c4cd22b7db1f2c8105c0a2cf27e13a"
         
},
         "reviewers":[
            {
               "reviewerUrl":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/215/reviewers/49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
               "vote":-10,
               "hasDeclined":false,
               "isFlagged":false,
               "displayName":"Brandon Luttrell",
               "url":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
               "_links":{
                  "avatar":{
                     "href":"https://dev.azure.com/BSSProducts/_apis/GraphProfile/MemberAvatars/aad.NjZkY2E0MTctMzgyYi03YjExLTljNTgtYTY0ZWY3YTc4NGQ2"
                  
}
               
},
               "id":"49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
               "uniqueName":"REMOVED BY ME",
               "imageUrl":"https://dev.azure.com/BSSProducts/_api/_common/identityImage?id=49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6"
            
}
         
],
         "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/215",
         "supportsIterations":true
      
}
   
],
   "count":1
}`

**Comment by rfennell** [comment]
I got the 84 from you log.

```
2020-04-16T12:10:15.6023864Z Found 84 Azure DevOps for PRs for project ByteSized.2DScannerApp_NextGen
```

Did you `?searchCriteria.status=completed` on the end of the URL, as the PR returned is active not completed.

But other than that all seems OK


I think the best option might be to expand the `filter` call into a loop so I can get line by line diagnostics. I will do a new release as soon as I make that change and test it locally

**Comment by rfennell** [comment]
@BSLuttrell actually a safer approach might be to use this test harness I have written

Just clone the repo https://github.com/rfennell/NodeTestHarness

It is all setup to just debug in VSCode

You do need to edit some value at the top of test.ts file

```
   let token: string = "<your PAT token>";
            var teamProject = "<your team project>"
            var org = "<your devops org>";
            var commitID = "b0fa863823f153861f7ba035273b82510be50054";
```

As I expect to see an error irrespective of the commitID we try to match on the first pass we can skip setting a valid commit ID to try to match,

I expect 
- ln 34 to report 84 PRs
- ln 37 to fail for you (if you comment it out for the next test
- ln 40 t loop around and tell us which PR is missing the property

Happy to so a screen share if it help, are you on Teams?

**Comment by BSLuttrell** [comment]
@rfennell  Ahhh i was a dinkus and left the ** at the end of the filter. It did return 84. After reviewing/ querying the result all the lastMergeCommit.CommitId have values.  Not sure if that helps. 

Let me know if you need any more info.

**Comment by rfennell** [comment]
Try 2.36.1, I have split out the PR filter line into a loop that checks for null objects

**Comment by BSLuttrell** [comment]
@rfennell I've been pulled in another direction and wont be able to run the test harness or a new release until later tonight. Sorry for the delay.

**Comment by rfennell** [comment]
No problem, hopefully the new release will at least fail safely so you get a set of release notes.

Let me know how it goes when you get a chance to have another look

**Comment by BSLuttrell** [comment]
@rfennell The latest updated worked with no issues. 

After running through the test harness found the issue to be with PR 131. I went to search the ADO portal for that specific PR and I get an error when searching for it.  I can search for any other PR just fine. So I'm not sure what is so special about this one?!?! Bellow is a screen shot of the error I got in ADO I also included the JSON from PR 131 and there is no lastMergeCommit element.  Thoughts?

![image](https://user-images.githubusercontent.com/29462872/79520306-721e7c80-8024-11ea-8245-77f4b708f080.png)

`{
   "repository":{
      "id":"ab0d1917-dfc4-4b38-b8ed-5a67127272aa",
      "name":"ByteSized.2DScannerApp_NextGen",
      "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa",
      "project":{
         "id":"88547fdf-c99a-4868-8b65-d70343fa3df8",
         "name":"ByteSized.2DScannerApp_NextGen",
         "state":"unchanged",
         "visibility":0,
         "lastUpdateTime":"0001-01-01T04:56:02.000Z"
      
}
   
},
   "pullRequestId":131,
   "codeReviewId":131,
   "status":3,
   "createdBy":{
      "displayName":"Project Collection Build Service (BSSProducts)",
      "url":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/b6120dbe-b5e7-42ab-ac04-78c68370b0ae",
      "_links":{
         "avatar":{
            "href":"https://dev.azure.com/BSSProducts/_apis/GraphProfile/MemberAvatars/svc.YmRhMWM1NDEtODc4MS00NTg1LTgwOTAtMmM5MWZiNjc4YmMzOkJ1aWxkOmIyMmMzNjA5LTc0ZDUtNGYxMi1iNDRkLWM0NDUyN2E0NTVkMg"
         
}
      
},
      "id":"b6120dbe-b5e7-42ab-ac04-78c68370b0ae",
      "uniqueName":"Build\\b22c3609-74d5-4f12-b44d-c44527a455d2",
      "imageUrl":"https://dev.azure.com/BSSProducts/_api/_common/identityImage?id=b6120dbe-b5e7-42ab-ac04-78c68370b0ae",
      "descriptor":"svc.YmRhMWM1NDEtODc4MS00NTg1LTgwOTAtMmM5MWZiNjc4YmMzOkJ1aWxkOmIyMmMzNjA5LTc0ZDUtNGYxMi1iNDRkLWM0NDUyN2E0NTVkMg"
   
},
   "creationDate":"2020-03-11T00:04:16.887Z",
   "closedDate":"2020-03-11T00:04:35.528Z",
   "title":"PR from Pipeline to Release 2020.03.37",
   "sourceRefName":"refs/heads/develop",
   "targetRefName":"refs/heads/release",
   "mergeStatus":3,
   "isDraft":false,
   "mergeId":"c85f1ba8-9564-437b-af65-ca0fa02cbb39",
   "lastMergeSourceCommit":{
      "commitId":"a6ecfc415a19ff62633927b92eda7d35bd997e89",
      "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/a6ecfc415a19ff62633927b92eda7d35bd997e89"
   
},
   "lastMergeTargetCommit":{
      "commitId":"395ca0447763dd8bfe34182cf525817dd4c8edb5",
      "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/395ca0447763dd8bfe34182cf525817dd4c8edb5"
   
},
   "reviewers":[
      {
         "reviewerUrl":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131/reviewers/e79dc00d-1375-475c-8f95-bf234d036d18",
         "vote":0,
         "hasDeclined":false,
         "isFlagged":false,
         "displayName":"Laura Rose",
         "url":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/e79dc00d-1375-475c-8f95-bf234d036d18",
         "_links":{
            "avatar":{
               "href":"https://dev.azure.com/BSSProducts/_apis/GraphProfile/MemberAvatars/aad.YjNmMzA0NzYtZTY1Zi03OWNhLWE0NjYtYjFmYTI3MDQzNmRk"
            
}
         
},
         "id":"e79dc00d-1375-475c-8f95-bf234d036d18",
         "uniqueName":"lrose@bytesizedsolutions.com",
         "imageUrl":"https://dev.azure.com/BSSProducts/_api/_common/identityImage?id=e79dc00d-1375-475c-8f95-bf234d036d18"
      
},
      {
         "reviewerUrl":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131/reviewers/16e282a8-aaa0-4d0a-8a9e-c46cee2018fa",
         "vote":0,
         "hasDeclined":false,
         "isFlagged":false,
         "displayName":"Stephanie Bakmaz",
         "url":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/16e282a8-aaa0-4d0a-8a9e-c46cee2018fa",
         "_links":{
            "avatar":{
               "href":"https://dev.azure.com/BSSProducts/_apis/GraphProfile/MemberAvatars/aad.MjlkZDkyOTEtYTg0Zi03ZGRmLWIzOTMtNDVhNjU2YzZlZDMx"
            
}
         
},
         "id":"16e282a8-aaa0-4d0a-8a9e-c46cee2018fa",
         "uniqueName":"sbakmaz@bytesizedsolutions.com",
         "imageUrl":"https://dev.azure.com/BSSProducts/_api/_common/identityImage?id=16e282a8-aaa0-4d0a-8a9e-c46cee2018fa"
      
},
      {
         "reviewerUrl":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131/reviewers/49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
         "vote":0,
         "hasDeclined":false,
         "isFlagged":false,
         "displayName":"Brandon Luttrell",
         "url":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
         "_links":{
            "avatar":{
               "href":"https://dev.azure.com/BSSProducts/_apis/GraphProfile/MemberAvatars/aad.NjZkY2E0MTctMzgyYi03YjExLTljNTgtYTY0ZWY3YTc4NGQ2"
            
}
         
},
         "id":"49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6",
         "uniqueName":"bluttrell@bytesizedsolutions.com",
         "imageUrl":"https://dev.azure.com/BSSProducts/_api/_common/identityImage?id=49ac001f-8a4e-4dd1-94ac-f05fdcacb6a6"
      
}
   
],
   "url":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131",
   "_links":{
      "self":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131"
      
},
      "repository":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa"
      
},
      "workItems":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131/workitems"
      
},
      "sourceBranch":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/refs/heads/develop"
      
},
      "targetBranch":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/refs/heads/release"
      
},
      "statuses":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131/statuses"
      
},
      "sourceCommit":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/a6ecfc415a19ff62633927b92eda7d35bd997e89"
      
},
      "targetCommit":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/commits/395ca0447763dd8bfe34182cf525817dd4c8edb5"
      
},
      "createdBy":{
         "href":"https://spsprodcus3.vssps.visualstudio.com/Abda1c541-8781-4585-8090-2c91fb678bc3/_apis/Identities/b6120dbe-b5e7-42ab-ac04-78c68370b0ae"
      
},
      "iterations":{
         "href":"https://dev.azure.com/BSSProducts/88547fdf-c99a-4868-8b65-d70343fa3df8/_apis/git/repositories/ab0d1917-dfc4-4b38-b8ed-5a67127272aa/pullRequests/131/iterations"
      
}
   
},
   "supportsIterations":true
}`

**Comment by rfennell** [comment]
Sorry no good idea, some stray HTML or markdown in a field? But that should show up in the JSON return.

Well on the plus side I guess we have a solution to the original problem

**Comment by BSLuttrell** [comment]
Yes It's all working now. Thanks again for the quick response and help.
