### ISSUE TITLE
Wiki Updater: Append file with new line characters

### ISSUE THREAD

**Issue by Calidus** [rfennell/AzurePipelines#682]
### Azure DevOps Extension you are using
Wiki Updater

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Latest public version

### Expected behaviour and actual behaviour
I am trying to use the appendToFile flag to edit an .order file. I expected to be able to add \r\n in my yaml string to create a new line but they seem to be stripped out when they are leading or trailing characters. Putting them in the middle of a string seems to work fine.

### Steps to reproduce the problem

- task: WikiUpdaterTask@1
displayName: 'Update Releases/.order'
condition: succeeded()
inputs:
  repo: 'dev.azure.com/org/project/_git/my.wiki'
  filename: 'Releases/.order'
  replaceFile: false
  appendToFile: true
  dataIsFile: false
  contents: "\r\n$(build.buildnumber)\r\n"
  message: '.Order Update'
  gitname: '$(Build.RequestedForId)'
  gitemail: '$(Build.RequestedForEmail)'
  UseAgentToken: true

**Comment by rfennell** [comment]
There is logic to replace `n with \r\n, but nothing to remove \r\n

If you swap ypur \r\n for `n do you get the new lines you expect?

Other than that I will need to do some testing

**Comment by rfennell** [comment]
This is a strange one

- if I test the logic from the command line calling the function that doe the work using `node mytest.js` the \r\n works fine
- if I test with a YAML based build I get the error you are seeing.

**The solution is to use the method I mention above use `n for a newline this works fine**

I guess there must be some trimming being done by the YAML parser
