### ISSUE TITLE
WikiUpdater: Add possibility to update to different branch than default.

### ISSUE THREAD

**Issue by richieto** [rfennell/AzurePipelines#688]
### Azure DevOps Extension you are using
WikiUpdater

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Currently public version

### Current behaviour
In a repository with multiple branches, the Default Branch is used for the commit and tag on this Extension.

In our case, we are using a development branch as a Default Branch, for all development tasks: new branches and PRs are set to the default branch automatically in Azure Devops.

When running the extension in a production release, the commit is added to the development branch (our Default Branch) because of this behavior.

### Expected behaviour
We would like to have an optional field  "branch" that, if added, would clone the repository to the specified branch in the field, rather than the default branch. 

Then the tag and the commit of the WikiUpdater could then be done in master branch even though this is not the Default Branch.

git command: 

![image](https://user-images.githubusercontent.com/33654399/80090163-5f91cf00-855f-11ea-9de9-3acc1d4959f2.png)

Simple-git supports this options:

.clone(repoPath, [localPath, [options]],   [handlerFn]) | clone a remote repo at repoPath to a local   directory at localPath (can be omitted to use the default of a directory with   the same name as the repo name) with an optional array of additional   arguments to include between git clone and the trailing repo local arguments
-- | --

Src

https://github.com/rfennell/AzurePipelines/blob/7e908423ea931ad9a15d04d235aea2e0facbe768/Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts#L103

**Comment by rfennell** [comment]
Seem a very reasonable suggestion i will look into it

**Comment by rfennell** [comment]
Give the new version 1.9.16 a go.

This allows you to specific a pre-existing branch name. After the clone an attempt is made to checkout this branch prior to the commit.
