### ISSUE TITLE
Enhancement request:  Ability to Grouping Work items(WI) as parent - children 

### ISSUE THREAD

**Issue by jungyu-rim** [rfennell/AzurePipelines#690]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version: 2.38.2

### Expected behaviour and actual behaviour
As you know, in Azure DevOps, Work items can have parent - children relationship.
However, in the current version of Generate Release Notes (Crossplatform), it seems to be hard to get Work items parent - children relationship.

It will be really great if there is a `option` that Work items can be grouped as parent - children relationship and appeared in auto-generated release notes like this
e.g)
- WorkItem1
  - Task1 for WorkItem1
  - Task2 for WorkItem1
- WorkItem2
  - Task3 for WorkItem2
  - Test1 for WorkItem2
  - Test2 for WorkItem2

**Comment by rfennell** [comment]
How do you envisage this working?
- we get back all the wi associated with the release, as now, but then sort them into a hierarchical tree? 
- we get back all the wi associated with with release, as now, but then find parents and/or children?

Obviously the first option is easier, and I think less likely to produce unexpected results

**Comment by jungyu-rim** [comment]
First option would be great. But I think that maybe we can provide more flexibility if we implement like this.

- add string comparison functionality in Handlerbars
```
{{#ifeq variable "string"}} 
    ... do this ... 
{{/ifeq}}
```
- add these kind of data field at each workitems (as you might know, there is a [api for this data field](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/work-item-links?view=azure-devops))

```json
 "Links": [{
            "SourceWorkItemId": 103,
            "TargetWorkItemId": 48,
            "LinkTypeName": "Child",
            "TargetWorkItem": {
                "WorkItemId": 48,
                "Title": "Story 15",
                "State": "Resolved"
            }
        }, {
            "SourceWorkItemId": 103,
            "TargetWorkItemId": 50,
            "LinkTypeName": "Child",
            "TargetWorkItem": {
                "WorkItemId": 50,
                "Title": "Story 17",
                "State": "Active"
            }
        }, {
            "SourceWorkItemId": 103,
            "TargetWorkItemId": 55,
            "LinkTypeName": "Child",
            "TargetWorkItem": {
                "WorkItemId": 55,
                "Title": "Story 22",
                "State": "New"
            }
        }, {
            "SourceWorkItemId": 103,
            "TargetWorkItemId": 112,
            "LinkTypeName": "Related",
            "TargetWorkItem": {
                "WorkItemId": 112,
                "Title": "Some issue",
                "State": "Active"
            }
        }]
```
And user can utilize it like this
 ```
# Global list of WI ({{workItems.length}})
{{#forEach workItems}}
{{#ifeq lookup this.fields 'System.WorkItemType' "Product backlog item"}} 
    ###  #{{this.id}} 
{{#forEach workItems.Links}}
{{#ifeq this.LinkTypeName "Child"}} 
    - #{{this.TargetWorkItemId}} 
{{/ifeq}}
{{/forEach}}
{{/ifeq}}
{{/forEach}}
```

**Comment by rfennell** [comment]
Changing the function that gets the details of workitems is easy to also get any references (and hence links. It is just a case of altering one parameter for the existing call.

This would get all the references associated with a work items (commits, other WI etc), which would all be accessible in an generated release notes. The problem is that for work item links all you get is the relationship and URL

```
- relations: [
  {
      rel: "System.LinkTypes.Hierarchy-Forward",
      url: "https://dev.azure.com/richardfennell/670b3a60-2021-47ab-a88b-d76ebd888a2f/_apis/wit/workItems/62",
      attributes: {
          isLocked: false,
          name: "Child",
     },
}...
```

You could make use of this in a template, but I am not sure the URL is enough for any practical use

```
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Description** {{{lookup this.fields 'System.Description'}}}
   - **Children**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Child')}}
         - {{this.attributes.name}} {{this.url}}
{{/if}}
{{/forEach}} 
{{/forEach}} 
```

I think to make this feature of any use I am going to have iterate across the set of associated work items and populate the details of parent and child work items before passing the results in handlebars.

However, it is hard to define how much information is enough

- Do you need both parent and child items
- Do you iterate down the tree forever for just immediate parent/child
- Do you need just the Title and ID, or more fields

**Comment by rfennell** [comment]
This has been added in 2.49.4

To make use of the feature make sure that it is enable on the task in the YAML (or the Handlebars section of the UI)

` getParentsAndChildren: true` 

and use a template in the form

```
{{#forEach this.workItems}}{{#if isFirst}}### WorkItems {{/if}}
* **{{this.id}}**  {{lookup this.fields 'System.Title'}}
- **WIT** {{lookup this.fields 'System.WorkItemType'}} 
- **Tags** {{lookup this.fields 'System.Tags'}}
- **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
- **Description** {{{lookup this.fields 'System.Description'}}}
- **Parents**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
{{/with}}
{{/if}}
{{/forEach}} 
- **Children**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Child')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
{{/with}}
{{/if}}
{{/forEach}} 
{{/forEach}} 
```
