### ISSUE TITLE
Unable to include Work Item Description

### ISSUE THREAD

**Issue by theejnar** [rfennell/AzurePipelines#693]
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
Azure DevOps Service (VSTS)

### Version of Extension/Task
2.38.2

### Expected behaviour and actual behaviour
Trying out this extension in a build pipeline but are not able to include the Work Item Description. This is what I have tested:
@@WILOOP:TAG 1@@  
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  ${widetail.fields['System.Description']}  
@@WILOOP:TAG 1@@       

This created an error and I think it was:
`##[error]SyntaxError: Unexpected string`
I saw that it should be possible to use:
`${JSON.stringify(propertyToDump)}`
and I tried this without success:
`${JSON.stringify(widetail.fields['System.Description'])}`

Do you have any solusions for how to include Work Item Descriptions?

**Comment by theejnar** [comment]
Tried again and it started to work... Sorry about the mess

**Comment by rfennell** [comment]
No problems glad you got sorted.

If you are new to this extension, could I suggest using newer Handlebars based templates. The reason I recommend this that this templating format is the future for this extension

**Comment by theejnar** [comment]
Ok, thanks. I got it working with Handlebars, howerver something is not working when it comes to the release number. Allso the WI descriptions has some `<div>:s` that I don't know how to get rid of. This is the template:

## Notes for release
**Release Number**  : {{build.buildnumber}}  

## Global list of WI ({{workItems.length}})
{{#forEach workItems}}
{{#if isFirst}}### Associated Work Items (only shown if WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - Work Item type: {{lookup this.fields 'System.WorkItemType'}} 
   - Assigned by: {{lookup this.fields 'System.AssignedTo'}}  
   - Work Item Description: {{lookup this.fields 'System.Description'}}  
   - Tags: {{lookup this.fields 'System.Tags'}}  
{{/forEach}}

**Comment by rfennell** [comment]
The  template is file format agnostic, the same is markdown, but could be anything. This means you control that is in the generated file re format controls. So any HTML encoding will is down to your template, remember it was what is inside your loop.

I think you build number issue is that you are looking at an array not a single objectTo export the values available use the form

`{{json builds}}` - to get the array of builds associated with the release
`{{json buildDetails}}` - to get the primary build associated with the release

**Comment by theejnar** [comment]
Thanks the building number works fine now.
Do you have any suggestions how I can register a Handlebar helper, something like this? Tryed to search thtough your source code without success.

```
Handlebars.registerHelper("striptags", function( txt ){
  console.log(txt)
  // exit now if text is undefined 
  if(typeof txt == "undefined") return;
  // the regular expresion
  var regexp = /<[\/\w]+>/g
  // replacing the text
  return txt.replace(regexp, '');
  
});
```

**Comment by rfennell** [comment]
It is documented in the [WIKI(https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task). 

Summary is there is a parameter that you can pass the extension is as string

**Comment by theejnar** [comment]
Thank you, everything works very well now.
```
# Release Notes  
**Build Number**: {{buildDetails.id}}  

## Work Items tagged Tag 1  
{{#forEach workItems}}
{{#if (eq (lookup this.fields 'System.Tags') "Tag 1")}}
*  [**{{this.id}}**](https://dev.azure.com/Projec/Repo/_workitems/edit/{{this.id}})  {{lookup this.fields 'System.Title'}}
   - Work Item type: {{lookup this.fields 'System.WorkItemType'}}  
   - Assigned by: {{lookup this.fields 'System.AssignedTo'}}  
   - Work Item Description: {{{lookup this.fields 'System.Description'}}}  
   - Repro steps: {{{lookup this.fields 'Microsoft.VSTS.TCM.ReproSteps'}}}  
  
{{/if}}  
{{/forEach}}
```
