### ISSUE TITLE
How can I get all WI list from Custom ReleaseId 

### ISSUE THREAD

**Issue by salahuddinquazi** [rfennell/AzurePipelines#705]
### Azure DevOps Extension you are using

Generate Release Notes (Crossplatform) (XplatGenerateReleaseNotes/V2/)

### Where are you running it? 
- Azure DevOps Service (VSTS) 
- Add task in Release Pipeline

### Version of Extension/Task 
Generate Release Notes (Crossplatform) (XplatGenerateReleaseNotes/V2/)

### Expected behaviour and actual behaviour
![image](https://user-images.githubusercontent.com/59020425/80896450-d2433d00-8d0b-11ea-8a75-365b3185f9ee.png)
I have multiple project in my organization as you can see in the attach image.I have added this extension release pipeline of my "Application 1 " it working fine giving all the WI related to Application1 based on last successful release . Now what I want list of all work items related to other applications (like Application2 ,Application3 )across all project from last production release. I can achieve this by adding this extension in each release pipeline but I have around 25 release pipeline for different application .
Please suggest me some approach how can I achieve this and also I want to configure compareRelease I want to compare with my custom releaseid.
also can we have more details documentation about Cross project PR option.

**Comment by rfennell** [comment]
The only way you can get release notes for all your applications in a single release pipeline is to have them all as of artifacts of a single pipeline.

If you want to keep your 25 separate pipelines I see two options

1. Do as you do now, generate your release notes but publish the notes to a WIKI. This would have 25 pages for the separate applications. It is at least it is one place to look, and a technique we use a lot. I have another task to help [here uploading pages to a WIKI](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WIKIUpdater-Tasks)
1. Add a new release that links to all 25 projects as artifacts, but only is used to generate release notes. You could get this release triggered by all your other releases. I have used this [task ](https://marketplace.visualstudio.com/items?itemName=dmitryserbin.release-orchestrator)to trigger releases from releases. 

Neither are perfect, but they are options

As to your custom.releaseid... the release will always compare the current release against the last successful release to the same stage (which you can override with a parameter to use a different named stage) when generating notes, so it will be based on your release's ID and stage. You cannot change this.

Finally, the cross-project PR switch is a new option that is part of the[ logic to discover any PRs ](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) related to commits associated with the release. 
- If disabled only PRs in the same Team Project as the release will be considered
- If enabled any PR found that contains a commit ID associated in the release will be considered.

I hope that this answers your questions

**Comment by salahuddinquazi** [comment]
Thanks. 
Again I have one question currently my task is getting failed I am using updated version i.e. 2.43.2
how I can downgrade the version of the task. 2 days back it is working fine .

![image](https://user-images.githubusercontent.com/59020425/81066200-5f4be900-8efa-11ea-9f02-b8a857cfd662.png)

**Comment by rfennell** [comment]
You cannot roll back a minor version, only major versions e.g. back to V1, which is very different version.

This is a bug I need to fix it. I will close this question and log a new issue dedicated to the bug

**Comment by salahuddinquazi** [comment]
okay thanks
