### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by daniel-tek** [rfennell/AzurePipelines#711]
I am analyzing to start using the WikiUpdater extension since I want to automate the generation of the documentation which we keep in the Wiki pages. We are generating dynamically a variable number of files containing the documentation files for the wiki which we then upload manually.

As what I see this extension allows to update ONE .md file to the Wiki pages, have you considered to extend the functionality of the extension to also get the files from a specific directory to support multiple files?

**Comment by rfennell** [comment]
The task was written to partner the release note generation task that produces a single file, hence the design. However, there is no reason not to support multiple files. I will have a look when I get a chance

**Comment by daniel-tek** [comment]
Thanks for the quick response!
I understand, that would be a good improvement on the task.

Should I close this issue?

**Comment by rfennell** [comment]
No I leave issues open marked as enhancements until they get done

**Comment by rfennell** [comment]
I have been having a think about this new feature and have decided that altering the current task to handle multiple files as well the current usage I think will be confusing. 

So what I propose is to add a second task to the extension, the second one will copy files based on a path/wildcard to a folder in a WIKI Git repo. This will be shipped side by side with the existing task.

I think having two tasks (in this same extension) with there differing parameter sets will be less confusing than a complex set of parameters on a single task, especially for YAML usage where I cannot hide invalid options as I can in the older UI.

So a few questions @daniel-tek 
1. Does this sound a reasonable approach?
1. When updating a repo with a list of files is it reasonable to assume all files are overwritten? My assumption is if a user wants to append they should use the existing task.

**Comment by rfennell** [comment]
This has been released as an extra task in the WIKI updater extension 1.10.21

**Comment by daniel-tek** [comment]
Cool! Yeah, that sounds like a much better idea, thanks!
