### ISSUE TITLE
More Details to oAuth needs enabling on the agent running the tasks

### ISSUE THREAD

**Issue by DanielGoehler** [rfennell/AzurePipelines#712]
Could you please provide more details about "oAuth needs enabling on the agent running the tasks"?

**Comment by rfennell** [comment]
Sorry your question is a little light on context, which extension are you talking about?

Here is a general answer

### What is OAUTH for
- The OAUTH token allows a task to perform with the rights used by the pipeline. It is only required if a task need to talk to a resource not on the build agent, e.g. uploading a file to some location, calling an API or similar operation 
- The task will only us OAUTH if it written to do so, so for example my extensions the Xplatform Release Notes and WIKI updater can use it, but my file versioning ones don't as they only operate on files on the local disk
 
# How to enable use of OAUTH
- If you are using YAML pipelines  the the OAUTH token is always available to be picked up by tasks, so you need to do nothing. 
- If using the older UI based build and release you enable OAUTH by checking a box at Agent level

![image](https://user-images.githubusercontent.com/324718/81287184-422e2c00-905a-11ea-8818-41c38939408b.png)

Does that answer your question?

**Comment by DanielGoehler** [comment]
Thanks for the fast response. I was talking about GenerateReleaseNotes (XPlat). Is it necessary for GenerateReleaseNotes (XPlat) to have a oAuth Token or is it just enough to enable this option?

**Comment by rfennell** [comment]
Just enable it (if in the UI, as it is already enabled for YAML). It uses the OAUTH token to access the API

**Comment by DanielGoehler** [comment]
Thanks!
