### ISSUE TITLE
How to include list of objects that are committed in a changeset?

### ISSUE THREAD

**Issue by manthacs** [rfennell/AzurePipelines#719]
How to include objects that are committed in a changeset? In my release notes, I want to include list of objects that are created, modified, deleted, etc. This would help in creating very detailed release notes.
Thanks in advance!

**Comment by rfennell** [comment]
Sorry but the Microsoft API I use to get the Changeset (or Commit in the case of Git Repos) 

```
IbuildApi.getChangesBetweenBuilds()
```
does not return a list of the files within the changeset or commit, just the title/comment and who performed the commit.  

You can see all the available fields if you use a 'dump template'

- Legacy template format 
```
@@CSLOOP@@
${JSON.stringify(csdetail)} 
@@CSLOOP@@
``
- Or handlebars format 
```
{{json  commits}}
```
So what you ask is not possible with a complete re-write of how the task access the REST API

**Comment by manthacs** [comment]
Thanks for the clarification. I had read through the API, and it doesn't give the handle to get the list of files. I am just sharing my use case here:
We are developing solutions on Microsoft D365FO, we distribute it to Partners/Clients. They can also extend our solution and build solutions extending/using our objects (classes/tables etc.). So it's important for them to know if any object has been removed/modified, etc. They can start preparing for release just by reading the release notes and don't have to find out by installing the solution. This could save a lot of time for Partners/Customers.

**Comment by rfennell** [comment]
@manthacs  You make a reasonable case, and you are not the first to ask for this. In the past I have avoided 'enriching' the returned data, but over the past couple of months it is something I have been starting to do.

I think what you ask is achievable without introduction a breaking change, I will look into it.

**Comment by rfennell** [comment]
I have written the enhancement it is release in 2.47.7. I have added a `changes` property to the `commit` objects that is an array of objects detailing the files edited in the changeset or commit.

This new data can only be used via the Handlebars based templating model, so you would use something like this

```
# Global list of CS ({{commits.length}})
{{#forEach commits}}
{{#if isFirst}}### Associated commits{{/if}}
* ** ID{{this.id}}** 
   -  **Message:** {{this.message}}
   -  **Commited by:** {{this.author.displayName}} 
   -  **FileCount:** {{this.changes.length}} 
{{#forEach this.changes}}
      -  **File path (use this for TFVC or TfsGit):** {{this.item.path}}  
      -  **File filename (using this for GitHub):** {{this.filename}}  
      -  **this will show all the properties availlable for file):** {{json this}}  
{{/forEach}}. 
{{/forEach}}
```
For more details see the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) for more details on Handlebars templates
