### ISSUE TITLE
How do I handle Html tags

### ISSUE THREAD

**Issue by mathiasfritsch** [rfennell/AzurePipelines#720]
Hi,

I am using this template

  - **Description** {{lookup this.fields 'System.Description'}}

In the result the Html-Tags that are automatically entered in the devops portal are encoded and beacuse of that are displayed as Html - tags by markdown frontends

For example in the beginning of a text the portal adds a div which get  ` &lt;div&gt;` and then gets displayed as `<div> `by a markdown frontend. Is there some way to not have the html tags encoded or have them removed?

The extension is realy helpfull! Great job

Mathias

**Comment by rfennell** [comment]
Goo question, not out the box but should be possible with the Handlebar extensions. At worst it is a list of string replacement. or maybe a customer module to do it more neatly.

I will have a look

**Comment by rfennell** [comment]
Turns out this is an easy one, Handlebars has support for just this requirement. You use the triple {{{ format to deal with the escaped HTML. Something like this

```
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Description** {{{lookup this.fields 'System.Description'}}}
{{/forEach}} 
```
