### ISSUE TITLE
Release notes makes compare to the same release

### ISSUE THREAD

**Issue by poplevente** [rfennell/AzurePipelines#727]
extension: Generate release notes crossplatform

Hi,

since a couple of releases the release notes generation is showing too much items, and we see that it's comparing to the same release.

Release-88 May release
completed on 27/5/2020 15:35
compared with Release-88 May release from 27/5/2020 15:35 to produce this report.

Release-88 is the variable ${releaseDetails.name}
and the compared with Release-88 is ${compareReleaseDetails.name}

is there a way to fix this? Will the new release fix it?

**Comment by rfennell** [comment]
I have re-checked the integration test logs for the last few releases and I cannot see this problem in them. As expected I can see the current and previous **successful** release to the stage the task is running in.

You usually see the same release listed when this is the first release to a given stage - could this be the problem in your case?

if you check the logs (you can enable detailed logging with a variable `system.debug=true`) you will be able to see the logic used to get the primary and compare release

**Comment by poplevente** [comment]
yeah, that probably could be it. since we recently change the release pipeline to a new one. so probably it's taking the last release from the current pipeline (not all pipelines).
