### ISSUE TITLE
Replace wiki task not working

### ISSUE THREAD

**Issue by Gijsreyn** [rfennell/AzurePipelines#728]
**Azure DevOps Extension you are using**

WIKI Updater Tasks 1.10.21 (Latest)

**Where are you running it?**

Azure Devops Services

**Expected behaviour and actual behaviour**

When using the Wiki updater tasks in YAML pipeline, the following is specified: 

`- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Wiki updater'
  inputs:
    repo: 'reponame'
    filename: 'filename'
    dataIsFile: true
    sourceFile: '$(Build.ArtifactStagingDirectory)\filename.md'
    message: 'Test commit'
    tagRepo: false
    gitname: BuildUser
    gitemail: 'BuildUser@builduser.com'
    useAgentToken: true
    appendToFile: false
    replaceFile: true
`

My expectation would be that everytime the pipeline runs, the wiki is updated and that you can see another revision in the wiki. This does not happen. No commits find place, yet I can see in the log:

Added filename to repo D:\a\1\s\repo
Committed to D:\a\1\s\repo with message "test commit
Pushed to reponame

**Comment by rfennell** [comment]
If the file has not changed then the wiki does not appear to update the page edit. I assume this is because the commit is in effect empty.

Could this be the case?

**Comment by Gijsreyn** [comment]
> 
> 
> If the file has not changed then the wiki does not appear to update the page edit. I assume this is because the commit is in effect empty.
> 
> Could this be the case?

This I of course checked and this is not the case.

**Comment by rfennell** [comment]
Could you get the task to exhibit the problem while debug logging is enabled, set a variable system.debug=true. 

Also also get the commit history for the wiki git repo.

If you can upload both the log and the history to this issue I will have a look.

**Comment by Gijsreyn** [comment]
> 
> 
> Could you get the task to exhibit the problem while debug logging is enabled, set a variable system.debug=true.
> 
> Also also get the commit history for the wiki git repo.
> 
> If you can upload both the log and the history to this issue I will have a look.

I just found it out. We restructured our wiki to be lowercase. I forgot that it was case-sensitive. Now it is working. My apologies.

**Comment by rfennell** [comment]
That sort of thing happens to us all.

I am going to put a change into the logging so the logs show the commit SHA to aid traceability,

Glad you are working
