### ISSUE TITLE
Error on commit message containing "CI"

### ISSUE THREAD

**Issue by martin-shields-sage** [rfennell/AzurePipelines#730]
Hi,

When ever I generate release notes with a commit message containing CI for example: Set up CI with Azure Pipelines

I am getting the following output:
```
*  **Set up CI with Azure Pipelines

[skip ci]**
    - **Id**  82d8e5d171fbf277181c6b5930766d445d3b420f
    - **TimeStamp** Wed Jun 03 2020 11:37:26 GMT+0000 (UTC)
*  **Set up CI with Azure Pipelines
```

This is what I am using as the handlebars template for commits:
```
## Commits
{{#forEach commits}}
*  **{{this.message}}**
    - **Id**  {{this.id}}
    - **TimeStamp** {{this.timestamp}}
{{/forEach}}
```

Is this an actual bug or am I missing something or doing something wrong?

**Comment by rfennell** [comment]
I will need to have a look at this, but I think it is marking a commit related to the [[skip ci]](https://developercommunity.visualstudio.com/idea/420289/add-support-ci-skip-and-azure-skip-to-azure-pipeli.html) functionality. But why this is occurring when you put 'CI' in the commit message I have no idea. Thought you had to add the extract string

That said, my task just gets the commits associated with the builds, it has no control over their content so I doubt there is much I can do. Other than suggest filtering the row in the template.

I will do some testing though, see what I can find

**Comment by martin-shields-sage** [comment]
Thanks very much for your reply I can see and understand what you mean now. When you say filter the row in the template are you reffering to the template I provided above as an example? If so do you have any resources that could help me with that?

**Comment by rfennell** [comment]
Don't have time to look today, but the filter will be similar to the sample below that filters by the contents of the tag files
```
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems with 'Tag 1'{{/if}}
{{#if (contains (lookup this.fields 'System.Tags') 'Tag 1')}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
{{/if}}
{{/forEach}} 
```

**Comment by martin-shields-sage** [comment]
Thanks very much for your help. If it helps you, it seems that these [skip ci] tags are not coming on when the title has CI on them but rather when I update my build yml file on the azure dev ops website itself. If i make changes in visual studio code and push those changes I do not get the issue. 
It maybe that theres nothing we can do about this, if not its worth while keeping note of this limitation when changing the yml file directly on the azure devops website

**Comment by rfennell** [comment]
That's interesting, must be a feature of the Azure DevOps UI. As I tend to create YAML in VSCode I have not seen it

You are right there is nothing I can do about this so I will close this issue, but mark it as a known issue
