### ISSUE TITLE
Include items between git tag, and this build in GenerateReleaseNotes (XPlat version)

### ISSUE THREAD

**Issue by theejnar** [rfennell/AzurePipelines#731]
**Is your feature request related to a problem? Please describe.**
We have a Build pipeline that is run daily. This pipeline is also used when we create a release. This makes it impossible as I understand to include all items (e.g. work items, pullrequests etc) from last release as the extension seems to only include items since the last pipeline run.

**Describe the solution you'd like**
My question is if it is somehow possible to tell GenerateReleaseNotes (XPlat version), to take all items between a user specified git tag, e.g. Release, and this current build. Would this be a interesting feature to the extension?

**Describe alternatives you've considered**
Another solution would maybe be to, every time it is time to do a release, merge the master branch (or whatever branch the release is going to be base on) into a release branch. If this is done only one time each time it's time to do a release, I guess the extension will take all, to that particular branch, new items since last successfull build. I havn't tried yet if it works like that though. 

If nothing of this would be possible, do you know of any workaround? Can the Azure DevOps REST API be used to somhow solve this problem?

**Additional context**

**Comment by rfennell** [comment]
The way this task is written is based on using an Azure DevOps API call that gets the changes between builds. There is no equivalent option to do this via tags. So any change would be a complete re-write of how associations are discovered. Not something I indent to do.

For people with your requirement, the option I have seen done most commonly is to add a stage to your Release Pipeline that generates the release notes that is not run nightly, but only on release (whether manually or via some conditional flag). As the task checks for the last successful release of the stage it is running it, this means it will generate the associated items related to the last release build, not the nightly build.

Hope that helps

**Comment by theejnar** [comment]
Ok, a follow up on this. When you write between builds, would it be possible to tell the task between which specific builds we want it to create release notes. For an instance I can see that the REST api supports this like this:
`GET https://dev.azure.com/{organization}/{project}/_apis/build/workitems?fromBuildId={fromBuildId}&toBuildId={toBuildId}&api-version=5.1-preview.2`
...with fromBuildId and toBuildId.

**Comment by rfennell** [comment]
That is what it uses, it gets the to and from ID from the list based on artefacts in the last successful deployment to the stage the task is in and the current releases artefacts

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Comment by svengeance** [comment]
@rfennell I'm in a **similar** situation here I believe.

Our company is switchign **to** YAML pipelines off of CI/CD.

I love the behavior of Releases where it grabs all workitems associated between **that stage** of **that release pipeline**.
Is there a way to emulate this behavior for YAML pipelines? This is necessary as we deploy to DEV always, deploy to TEST often, and deploy to PROD once - and I need the set of workitems on each.

At the moment I think I'll have to retain release pipelines **solely** to retain this behavior.

**Comment by rfennell** [comment]
That is an interesting request and one I think deserves its own issue i think.

I will have a look to see what I can do, my guess is I could look for last successful release to a stage, I will check
