### ISSUE TITLE
Conventional Commits Template

### ISSUE THREAD

**Issue by geraldnolan** [rfennell/AzurePipelines#747]
**Your question? Please describe.**
Just trying to pick your brain. Thanks again for the awesome projects! Do you have a template that works with Conventional Commits?
[https://www.conventionalcommits.org/en/v1.0.0/](https://www.conventionalcommits.org/en/v1.0.0/)

I am new to the handlebars template.  It would be nice if you could create an object from {{this.message}}?  I was looking for ways to remove feat:, fix: from the commit message.  {{#replace "BREAKING CHANGE:" "* **Breaking Change:**"}}this.message{{/replace}}  Didn't seem to work.

```javascript
**Build Number**: {{buildDetails.id}} <br />
**Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 

{{#forEach commits}}
    {{#contains this.message "fix:"}}
{{#if isFirst}}### Fixes  {{/if}}
 **Message:** {{this.message}}  |  {{this.author.displayName}}
    {{/contains}}
{{/forEach}}

{{#forEach commits}}
    {{#contains this.message "feat:"}}
{{#if isFirst}}### Features {{/if}}
 **Message:** {{this.message}}  |  {{this.author.displayName}}
    {{/contains}}
{{/forEach}}

{{#forEach commits}}
    {{#contains this.message "BREAKING CHANGE:"}}
{{#if isFirst}}### Breaking Change {{/if}}
 **Message:** {{this.message}}  |  {{this.author.displayName}}
    {{/contains}}
{{/forEach}}
```

**Project**
GenerateReleaseNotes

**Comment by rfennell** [comment]
That should be possible, I will have a look to see what I can come up with

**Comment by rfennell** [comment]
I have not tested this, but I am reasonably sure the format you need is as shown below, you need to add if's to the contains lines

I based this solution on the [filteting WI by tag filtering sample](https://raw.githubusercontent.com/rfennell/AzurePipelines/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/Handlebars/release-handlebars-template.md). 

```
{{#forEach commits}}
    {{#if (contains this.message "fix:")}}
{{#if isFirst}}### Fixes  {{/if}}
 **Message:** {{this.message}}  |  {{this.author.displayName}}
    {{/if}}
{{/forEach}}

{{#forEach commits}}
    {{#if (contains this.message "feat:")}}
{{#if isFirst}}### Features {{/if}}
 **Message:** {{this.message}}  |  {{this.author.displayName}}
    {{/if}}
{{/forEach}}

{{#forEach commits}}
    {{#if (contains this.message "BREAKING CHANGE:")}}
{{#if isFirst}}### Breaking Change {{/if}}
 **Message:** {{this.message}}  |  {{this.author.displayName}}
    {{/if}}
{{/forEach}}
``` 

If this does not work I will have to build a quick sample to try it out

**Comment by geraldnolan** [comment]
The code above was working with the **contains** without the **if.**

The git commit would look similar to this:

```bash
186cce90 feat: add disabled property
5b998d9a test: add scenario for readonly property
263288a5 fix: fix css when hover
c3fb85af feat: add button component
```
I want to remove **feat**: **test**: **fix**: **feature**:  from the message output {{this.message}}

I will keep working it out. Thanks

**Comment by rfennell** [comment]
Sorry I was reading on my phone pre-breakfast, I miss-understood

You do have access to the [Handlebar Helpers library](https://github.com/helpers/handlebars-helpers) but that I think would end up with complex templates.
 
I think the best option is probably a custom Handlebars extension. You can inject this via the task the string parameter `customHandlebarsExtensionCode`. In its simplest form the extension is `module.exports = {foo: function () {return 'Returns foo';}};` and you would use its `{{foo}}`

You inject a function you to do your replacements, I guess something like this in the most simple form

```
module.exports = {fixmsg: function (string msg) {return msg.replace('BREAKING CHANGE:','* Breaking Change:');}};
``` 

This would be called as `{{fixmsg this.message}}`

You could add an extension for each message type, or chain the replace functions to have just one

Sorry for my early morning confusion, and I hope that helps

**Comment by geraldnolan** [comment]
That is what I was looking for; unfortunately, I am unable to get it working.

```bash
Using in-line template
##[debug]Loading handlebar template
##[debug]Processing template
##[debug]  WI: 0
##[debug]  CS: 3
##[debug]  PR: 0
##[debug]  Builds: 0
##[debug]  Global Tests: 0
##[debug]  Release Tests: 0
##[debug]  Related WI: 0
##[debug]Processing handlebar template
Loading handlebars-helpers extension
##[debug]Saving custom Handlebars code to file in folder /home/vsts/work/_temp
Loading custom handlebars extension
Writing output file /home/vsts/work/_temp/customHandlebarsExtension.js
Finished writing output file /home/vsts/work/_temp/customHandlebarsExtension.js
(node:2506) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected identifier
```

```yaml
steps:
- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2
  displayName: 'Generate Release Notes based on Release Comparison API'
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)\RELEASENOTES.md'
    templateLocation: InLine
    inlinetemplate: |
     **Build Number**: {{buildDetails.id}} <br />
     **Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 
     
     {{#forEach commits}}
         {{#contains this.message "fix:"}}
     {{#if isFirst}}### Fixes  {{/if}}
     {{fixmsg this.message}}  |  {{this.author.displayName}}
         {{/contains}}
     {{/forEach}}
     
     {{#forEach commits}}
         {{#contains this.message "feat:"}}
     {{#if isFirst}}### Features {{/if}}
     {{fixmsg this.message}} | {{this.author.displayName}}
         {{/contains}}
     {{/forEach}}
     
     {{#forEach commits}}
         {{#contains this.message "BREAKING CHANGE:"}}
     {{#if isFirst}}### Breaking Change {{/if}}
     {{{fixmsg this.message}} | {{this.author.displayName}}
         {{/contains}}
     {{/forEach}}
    replaceFile: true
    customHandlebarsExtensionCode: 'module.exports = {fixmsg: function (string msg) {return msg.replace(''fix:'',''* Fixed'');}};'
```

**Comment by rfennell** [comment]
I think the issue is declaring the type of string on the function definition.  I used

`module.exports = {fixmsg: function (msg) {return msg.replace('fix:','* Fixed');}};`

and got the expected results.

**Comment by geraldnolan** [comment]
That did it! Thanks again for your help

Build Number: 2060
Build Trigger PR Number:

Fixed Add Comments | Gerald Nolan
