### ISSUE TITLE
How to use custom handlebars to make a counter

### ISSUE THREAD

**Issue by guilhermevd** [rfennell/AzurePipelines#750]
Hello!

First of all, thanks for this very usefull task GenerateReleaseNotes Node based Cross Platform Task YAML!

It's really helps a lot, to make powerfull and complete release notes, with workitems in Azure Devops!

Please I need some help, with my script.

I need to make a counter, for example, I need to write the quantity of tasks per type, like 300 tasks, 32 bugs, 30 Product Work Itens and etc

I try to make a function with javascript to make do the count, but I'm not get the way to use this, I follow the example in your wiki, but the Azure Devops says that my script is wrong.

Here my script:
`
          {{#forEach this.workItems}} 
          {{#if (contains (lookup this.fields 'System.Tags') 'RN-BUSINESS')}} {{#if isFirst}}# What's New <div>{{/if}} 
          {{{lookup this.fields 'System.Description'}}}
          {{/if}} {{/forEach}}

          # Task

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Task') }}
          * Fix [**{{this.id}}**](https://xxxxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}}
          Total : HERE I need to put the quantity         
          {{/if}}{{~/forEach~}} 

          # Improvement

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Improvement') }}
          * Fix [**{{this.id}}**](https://xxxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}}
          Total : HERE I need to put the quantity         
          {{/if}}{{~/forEach~}}           

          # Product Backlog Item

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Product Backlog Item') }}
          * Fix [**{{this.id}}**](https://xxxxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}} 
          Total : HERE I need to put the quantity          
          {{/if}}{{~/forEach~}}

          # Development Bug

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Development Bug') }}
          * Fix [**{{this.id}}**](https://xxxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}} 
          Total : HERE I need to put the quantity            
          {{/if}}{{~/forEach~}}           

          # Bugs

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Bug') }}
          * Fix [**{{this.id}}**](https://xxxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}} 
          Total : HERE I need to put the quantity              
          {{/if}}{{~/forEach~}}               

          # Issue

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Issue') }}
          * Fix [**{{this.id}}**](https://xxxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}} 
          Total : HERE I need to put the quantity             
          {{/if}}{{~/forEach~}}   

          # Technical Debt

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Technical Debt') }}
          * Fix [**{{this.id}}**](https://xxxxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}} 
          Total : HERE I need to put the quantity                 
          {{/if}}{{~/forEach~}}     

          # Vulnerability

          {{#forEach this.workItems~}}
          {{#if (contains (lookup this.fields 'System.WorkItemType') 'Vulnerability') }}
          * Fix [**{{this.id}}**](https://xxx/Projetos/_workitems/edit/{{this.id}}): {{{lookup this.fields 'System.Title'}}} 
          Total : HERE I need to put the quantity         
          {{/if}}{{~/forEach~}} 
        delimiter: ':'
        fieldEquality: '='
        anyFieldContent: '*'
        dumpPayloadToConsole: false
        dumpPayloadToFile: true
        replaceFile: true
        getParentsAndChildren: false
        customHandlebarsExtensionCode: module.exports = {foo: function () {return 'Returns foo';}};`

I really don't understand how to use customHandlebarsExtensionCode, note that in this example, I put the code that you mention on Wiki, but when I save, the Azure Devops broke the execution with this message: 

/azure-pipelines.yml: (Line: 144, Col: 61, Idx: 5901) - (Line: 144, Col: 61, Idx: 5901): Mapping values are not allowed in this context.

Sorry, if I doing a silly question, but I'm already a few days trying to understand how to do this.

If you need some more information, please let me know!

Thanks

Guilherme

**Comment by rfennell** [comment]
I am not sure that is possible as  in your template you need to store the counts across loops

If you had a simple loop you can use

```
Total WI {{this.workItems.length}}
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems with 'Tag 1'{{/if}}
{{#if (contains (lookup this.fields 'System.Tags') 'Tag 1')}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - Index in the loop {{@index}} 
{{/if}}
{{/forEach}} 
```

The problem is that the index does not know about the if filter. so you see jumps in the numbers.

```
Total WI 6
### WorkItems with 'Tag 1'

*  **14**  Bug with &#x27;Tag 1&#x27;
   - **WIT** Bug 
   - **Tags** Tag 1
   - Index in the loop 1 

*  **64**  PBI with &#x27;Tag 1&#x27; and &quot;TAG2&quot;
   - **WIT** Product Backlog Item 
   - **Tags** Tag 1; TAG2
   - Index in the loop 2 


*  **66**  PBI with &#x27;TAG2&#x27; &amp; &#x27;Tag 1&#x27;
   - **WIT** Product Backlog Item 
   - **Tags** Tag 1; TAG2
   - Index in the loop 4 

*  **67**  Bug with &#x27;Tag 1&#x27; &amp; &#x27;TAG2&#x27; &amp; &quot;TAG3&quot;
   - **WIT** Bug 
   - **Tags** Tag 1; TAG2; TAG3
   - Index in the loop 5 
```
You need your count to be outside of any loop do you not?

So I guess the custom module will be something like

`module.exports = {countItems: function (array) {return array. {count where correct type }};`

The problem is going to be the lookup of the field in the array.

I don't have time to experiment at present, but I hope that helps

**Comment by guilhermevd** [comment]
Yeah, if I have a simple loop I can use the code that you post, even the {{this.workItems.length}} will be perfect for me.

But, in this case, I will have the total of all types of work itens, but I need the total of each kind of work itens, so I think to make a counter inside of each loop, that I previsiouly check the type with de if sentence.

About your question, at the end, I want the value of the count variable outside of each loop, in the end, I think to prepare a table with the values, but as I wrote above, make the count inside the loop, for me was the first option to have the number.

I can use this custom module, but here is the second question that I make in the first post, I really don't understand how to use the custom module.

When I put the code, that you post in your Wiki, in the parameter customHandlebarsExtensionCode the Azure Devops respond with an error like this: (/azure-pipelines.yml: (Line: 144, Col: 61, Idx: 5901) - (Line: 144, Col: 61, Idx: 5901): Mapping values are not allowed in this context.).

I think that I miss something in how to use correctly this feature, if you could detail a little more for me please

Thanks

**Comment by guilhermevd** [comment]
I discover that the error that Azure Devops respond, with the code that is in the wiki is because of the : 

I attached two file, one with the : and other with not.

If I save with the : the execution of the script returns an error, with not the execution is ok, but the script doesn't work

![1](https://user-images.githubusercontent.com/40774022/85464839-7912bf80-b57e-11ea-963f-6cd730bf7519.PNG)

![2](https://user-images.githubusercontent.com/40774022/85464867-829c2780-b57e-11ea-8214-00d22e324bb8.PNG)

**Comment by rfennell** [comment]
I think the answer is to write an extension that takes the whole workitem array data set and then calculates the number  work items that meet a given criteria so the usage would be similar to the follow

`{{countWiByType this.workitem "Bug2}}`

Finding all the bugs. 

 I will write a sample when I get time

**Comment by rfennell** [comment]
How is this

In the template (outside the loops)

```
- Total WI {{this.workItems.length}}
- Bugs {{countWorkItemsByType this.workItems "Bug"}} 
- Product Backlog Item {{countWorkItemsByType this.workItems "Product Backlog Item"}} 
```

And the custom script text is 

```
module.exports = {countWorkItemsByType: function (array, typeName) {return array.filter(wi => wi.fields['System.WorkItemType'] === typeName).length;}};
```

You could of course alter the filter to check any field

**Comment by rfennell** [comment]
I have started to curate [sample custom Handlebars modules with the sample templates](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/Handlebars)

**Comment by guilhermevd** [comment]
@rfennell Hi!!!

It works perfectly!!!! 🥇 

But I need to do little change, like this:

`module.exports = {countWorkItemsByType(array, typeName) {return array.filter(wi => wi.fields['System.WorkItemType'] === typeName).length;}};`

It not works if you declares `countWorkItemsByType: function (array, typeName)...`, only works if the function declaration in this form `countWorkItemsByType(array, typeName)`

Anyway, thank you very much for your attention and help!

**Comment by rfennell** [comment]
I will update the sample to make sure the format is right there too.

Glad we hot you sorted
