### ISSUE TITLE
Use external defined variable

### ISSUE THREAD

**Issue by guilhermevd** [rfennell/AzurePipelines#754]
I'm using GenerateReleaseNotes Node based Cross Platform Task to do the release notes of ours applications, but they are iOS and Android Mobile applications, so, we defined the version their version using fastlane.

There is a method in fastlane to get version number information (bundle exec fastlane run get_version_number), It's possible to get the information with this method, and use in the template for the release notes?

Thanks

**Comment by rfennell** [comment]
The answer currently is no, there is no way built into the task to inject some value obtained from some other tool such as the fastlane command you detailed.

The only way I can think to do it is to place some block in your template file such as

```
Mobile app version: [[VERSONTAG]]
```
You could then generate your release notes as normal using my task, the tag would be unaltered, and then use one of the tag replacement tasks in the marketplace or a bash or powershell script to replace the tag with a version from you command line 

Does that help?

**Comment by guilhermevd** [comment]
Yes, I think that might help!

I'm gonna try here, I come back to tell you.

Thanks
