### ISSUE TITLE
Not able to use Release predefined variables in Release Notes task

### ISSUE THREAD

**Issue by salahuddinquazi** [rfennell/AzurePipelines#756]
I am using Generate Release Notes (Crossplatform) with Handlerbar template. In that I want to display pre defined variable of VSTS release pipeline like $(env:RELEASE_PrimaryArtifactSourceAlias) . I am able to print variable value in powershell task but not in release notes task you can see in attach image
![image](https://user-images.githubusercontent.com/59020425/86350709-b8c55f80-bc80-11ea-9ddb-73ffe7da92e0.png)
Please let me know how can use this variable with handlebar.

**Comment by rfennell** [comment]
There is no way built into the task to inject some value obtained from an environment variable. Handlebars only knows about the variables (WI/CS etc) generated by task.

The only way I can think to do it is to place some block in your template file such as

Mobile app version: [[VERSONTAG]]

You could then generate your release notes as normal using my task, the tag would be unaltered, and then use one of the tag replacement tasks in the marketplace or a bash or powershell script to replace the tag with a version from you command line

Does that help?

**Comment by salahuddinquazi** [comment]
I am able to use release variable inside the handlerbar template.

![image](https://user-images.githubusercontent.com/59020425/86914127-6337f980-c13d-11ea-9fb1-a9ee455bdbbe.png)

**Comment by rfennell** [comment]
Ah yes that will work as $xxx.yyy} variables are expanded by the agent prior to being passed into the task. 

This is as opposed to $Env.xxx variables which are not expanded and so would need to be evaluated inside the Handlebars engine which it can't do as the object is not passed into it.

Glad you are unblocked
