### ISSUE TITLE
Stages support for Cross Platform Release notes in YAML

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#758]
> Originally made as comment in #731 by @svengeance. Is a different request hence a new issue

Our company is switching to YAML pipelines off of CI/CD.

I love the behaviour of Releases where it grabs all workitems associated between the last successful deploy of that release stage. Is there a way to emulate this behaviour for YAML pipelines? This is necessary as we deploy to DEV always, deploy to TEST often, and deploy to PROD once - and I need the set of workitems on each.

At the moment I think I'll have to retain release pipelines solely to retain this behaviour.

**Comment by rfennell** [comment]
This is under investigation to see what can be done

**Comment by rfennell** [comment]
I think the solution is as follows, but it is a fair bit of work 

1. Add a parameter to enable this new feature, as opposed to just getting what is associated with the current build
1. Get the current stage name (maybe allow this to be overridden as you can for a release)
1. Get this history of builds of the current definition 
1. Get the timelines for the previous build and check if the current stage was completed successfully using `/_apis/build/builds/<ID>/Timeline`.
1. Find all the WI/CS etc from this last successful build to the current one
1. Generate the release notes

So I think that is a plan, I will look to getting it written, not sure how long it will take to get done
I need to work out the exact API calls

**Comment by svengeance** [comment]
This would be a huge boon for us - but I totally understand the complexities involved (having read through all of your GenerationReleaseNotesFunctions class). I will say that the data _seems_ to be present for what I need for **builds**, which is surprising - I thought that builds had much less data.

**Comment by rfennell** [comment]
I think I have a working prototype, I will fully test it over the next few day

**Comment by rfennell** [comment]
The first release of the task (3.1.7) is available that allows checking of the state of changes within a multistage YAML pipeline. 

To enable the feature you need to set the `checkStage: true` flag and potentially the `overrideStageName: AnotherStage` if you wish the comparison to compare against a stage other than the current one.

**Note:** the Stage name does have to be unique within the pipeline to avoid false stage detection

```
         - task: XplatGenerateReleaseNotes@3
              inputs:
                outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
                outputVariableName: 'outputvar'
                templateLocation: 'InLine'
                checkStage: true
                inlinetemplate: |
                  # Notes for build 
                  **Build Number**: {{buildDetails.id}}
                  **Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 
      
                  # Associated Pull Requests ({{pullRequests.length}})
                  {{#forEach pullRequests}}
                  {{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
                  *  **PR {{this.id}}**  {{this.title}}
                  {{/forEach}}
      
                  # Builds with associated WI/CS ({{builds.length}})
                  {{#forEach builds}}
                  {{#if isFirst}}## Builds {{/if}}
                  ##  Build {{this.build.buildNumber}}
                  {{#forEach this.commits}}
                  {{#if isFirst}}### Commits {{/if}}
                  - CS {{this.id}}
                  {{/forEach}}
                  {{#forEach this.workitems}}
                  {{#if isFirst}}### Workitems {{/if}}
                  - WI {{this.id}}
                  {{/forEach}} 
                  {{/forEach}}
      
                  # Global list of WI ({{workItems.length}})
                  {{#forEach workItems}}
                  {{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
                  *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
                    - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
                    - **Tags** {{lookup this.fields 'System.Tags'}}
                  {{/forEach}}
      
                  # Global list of CS ({{commits.length}})
                  {{#forEach commits}}
                  {{#if isFirst}}### Associated commits  (only shown if CS) {{/if}}
                  * ** ID{{this.id}}** 
                    -  **Message:** {{this.message}}
                    -  **Commited by:** {{this.author.displayName}} 
                  {{/forEach}}
``` 

@svengeance let me know how it goes.

**Comment by svengeance** [comment]
Will do - we are in the process of setting up the second stage (Test environment) where this becomes important, so I will let you know how it integrates. Ideally the addition of this task to that stage means that **all** of the workitems accrued from each iteration of the first stage will be present.

**Comment by svengeance** [comment]
Apologies - I forgot to get back to you on this.

So far it **seems** like this tool is doing exactly what I expect. I'm noticing some very _odd_ things in the AzDo yaml pipelines though, where a particular build will have a heck of a lot more workitems associated with it than I expected.. but the tool is doing its job and reporting them all, and I can't blame it for that.

Thank you!

**Comment by rfennell** [comment]
Great news, I will close this issue then

**Comment by soccerjoshj07** [comment]
@rfennell Is there an equivalent, or any plans for an equivalent, for the {{compareReleaseDetails}} property when using this task in multi-stage YAML pipelines?

**Comment by rfennell** [comment]
There is no equivalent feature at present. ot at present. In YAML I guess it would be compareBuildDetails, can't see good reason not to add it as a feature. I will add a new issue to track it

**Comment by soccerjoshj07** [comment]
Thank you good sir! I just created issue #788, but feel free to close mine out in favor of yours though.
