### ISSUE TITLE
[GenerateReleaseNotes Template] Sample Template Proposal

### ISSUE THREAD

**Issue by svengeance** [rfennell/AzurePipelines#760]
I figured I'd make an issue first before making a PR. This template has a small amount of setup, and I was curious if it's too bespoke to my company or if you like what you see @rfennell 

I put a fair amount of work into a template I'm pretty proud of that follows the GitFlow model 
As you know, this model follows a release pattern that looks like -

```
---DEV----DEV-----DEV------DEV--------DEV------------------------
------\----------------------------------\-----------------------
-------TEST-------------------------------TEST------TEST---------
-----------\--------------------------------------------\--------
------------PROD------------------------------------------PROD---
```

This template addresses this release flow cycle by having 3 separate templates in one - one for DEV/TEST/PROD. Since this amazing tool captures all work items between the last successful release, we can capture all the DEV releases in the TEST stage, and all TEST releases in the PROD stage. This continually prepends each section onto the wiki page.

Part of what makes this a valuable resource is that it links **everything**. Commits, PRs, Tests, Work Items, Users, Builds, and Releases are all defined and navigable URLs

- The DEV Template is good for developers who wish to look at each commit and pull request, and also see features/tasks/bugs
- The TEST template is good for testers who need to analyze features and bugs
- The PROD template is good for product owners who wish to see a high-level overview of features & bugs

**Note:** This template makes use of 3 custom fields. On Bugs and PBIs we have 'Release Notes' which is an HTML text editor, and on Bugs we have 'Expected Results' and 'Actual Results', which QA/Testers can use to determine if a bug is truly resolved. Anyone using this template can simply change these fields to be discussions, comments, etc.

These templates are driven by a parameterized handlebars helper, which looks like - 
```js
module.exports = {
  template: function () {
    return '$(ReleaseStage)';
  }
};
```

Template: https://gist.github.com/svengeance/302a37aada97c23b4071ff6750d606f3

Lastly - the result.. **note** that I only have one DEV/TEST release here, but in reality there will be multiple.
![image](https://user-images.githubusercontent.com/6847381/86543077-5a4eea00-bee9-11ea-927c-228d4878afbc.png)

**Comment by rfennell** [comment]
I think any template that shows application of the task are useful. 

Maybe the best way to have the PR is in three files with an associated name 
- The template
- The module export 
- A readme

**Comment by svengeance** [comment]
Perfect - I'll get a PR for this up by this weekend. Apologies - I did not mean to leave this issue open for so long.
