### ISSUE TITLE
I want to create release plan with WI attach with PR only

### ISSUE THREAD

**Issue by salahuddinquazi** [rfennell/AzurePipelines#761]
Hi ,
I am using Generate Release Notes (Crossplatform). I am using in release pipeline. I have created with one release plan where I have around 27 build artifacts added I have created one stage with tasks.
1. Generate Release Notes
2. Wiki Updater.
![image](https://user-images.githubusercontent.com/59020425/86915669-f83bf200-c13f-11ea-8458-730ba7484629.png)
![image](https://user-images.githubusercontent.com/59020425/86915709-1275d000-c140-11ea-8868-9d4b87e14016.png)

The current process of release pipeline process  is whenever I merge my dev branch in release branch the Release Notes pipeline get triggered and display list WI. sometimes it display the huge work items list which is not attached in PR. 
I am using this inline template in my Generate Release notes extension 
**template :**
{{#forEach workItems}} {{#if isFirst}}{{/if}}
{{#if (or (contains (lookup this.fields 'System.WorkItemType') 'User Story') (contains (lookup this.fields 'System.WorkItemType') 'Defect'))}}
  - [ ]  #{{this.id}}  $(Release.TriggeringArtifact.Alias) 
 {{/if}}{{/forEach}}

Problem :  I have created one feature branch from release branch, I did some changes and raised the PR with 2  WI. 
when I complete PR My Release Notes pipeline get triggered and uploaded release notes to wiki but 20+ WI which I haven't attach to my PR. I am not able to understand why it's happening .

Solution which I am looking  : I want exact WI list which is there in my Pull Request. 
suppose in my PR I have around 5 items, it should display only 5 items.

Please let me know if you need more clarification on this.
Thanks.

**Comment by rfennell** [comment]
On option is to focus you release notes in the pull requests, not sue if that helps

```
{{#forEach pullRequests}}
{{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
*  **PR {{this.id}}**  {{this.title}}
{{/forEach}}
```

After that I would need to see a detailed log of what is gong on. If you set an environment variable `system.debug=true` the log will contain detailed steps of where it finds all the work item i.e which artifact the are released to. That might give a pointer
