### ISSUE TITLE
Get Change Sets included in a merge for Wiki-Release Notes

### ISSUE THREAD

**Issue by Daswad** [rfennell/AzurePipelines#762]
Hi,

im using "Generate Release Notes" and the Plugin works so far in our build pipeline.
Now I have the following question:
When we merge from branch A to branch B, is it possible to get all ChangeSets which where included in the merge (inlc. workitems and user stories) for the release note page in the Wiki?
I found already some soloutions for the REST API and Shell Scripts but how could they be used.

Thanks,

**Comment by rfennell** [comment]
Are you using 
- the older PowerShell based version, which I am make no more changes to, that is Windows only
- or the newer Cross-platform version, which is far richer in features.

In the cross platform version there is support for Git PRs, but as you mention ChangeSets I assume you are using TFVC source control so this is of no use.

I think all you can do is trigger a build on the merge and make sure that this merge changeset has all the required WI associated.

**Comment by Daswad** [comment]
Yes right now I'm using the PowerShell based version but i can switch to cross-platform anytime. We are using TFVC source control no GIT.

**Comment by rfennell** [comment]
I would swap to the cross platform version as it is under active support, but there is no special handling for TFVC as there is no concept like a Git PR. 

The merge into the trunk is just another Changeset so we have to rely on what is associated with that Changeset and is hence picked up by a build as associated items. This will require users to make that association
