### ISSUE TITLE
Problem with enrichment of file details in commits

### ISSUE THREAD

**Issue by SjoerdV** [rfennell/AzurePipelines#765]
**Your question? Please describe.**
I seem to be getting no 'changes' object returned for commits (YAML Pipeline), when I drill down myself I do find the actual files being modified and the strange thing was, it was working this morning, but not any more, the produced markdown file is also empty

**Extension Details**
Azure DevOps (cloud) Generate Release Notes (Crossplatform):
version 3.1.7

**HBS template**

```handlebars
# Notes for build: {{buildDetails.buildNumber}}

**Build Number**: {{buildDetails.id}}

**Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}}

**Build Source Branch** - {{buildDetails.sourceBranch}}

**Build Name** - {{buildDetails.definition.name}}

**Build Reason** - {{buildDetails.reason}}

# Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
{{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
*  **PR {{this.id}}**  {{this.title}}
{{/forEach}}

# Global list of WI ({{workItems.length}})
{{#forEach workItems}}
{{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}}
  - **Tags** {{lookup this.fields 'System.Tags'}}
  - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/forEach}}

# Global list of CS ({{commits.length}})
{{#forEach commits}}
{{#if isFirst}}### Associated commits{{/if}}
* ** ID{{this.id}}**
  -  **Message:** {{this.message}}
  -  **Commited by:** {{this.author.displayName}}
  -  **Timestamp:** {{this.timestamp}}
  -  **FileCount:** {{this.changes.length}}
{{#forEach this.changes}}
      -  **File path (TFVC or TfsGit):** {{this.item.path}}
{{/forEach}}
{{/forEach}}
```

- `this.changes.length` generates the error:
`##[debug]Processed: ##vso[task.issue type=error;]Error Processing handlebars [TypeError: Cannot read property 'length' of undefined]`

**Redacted Pipeline Log**
[redactedlog.txt](https://github.com/rfennell/AzurePipelines/files/4907523/redactedlog.txt)

Thanks for your help.

**Comment by rfennell** [comment]
That I think is a bug, you are using the new compare between stages functionality in a YAML pipeline and on the path you are using it is failing to make the call to get the file name details.

I will fix it

**Comment by rfennell** [comment]
Should be fixed in 6.2.2

**Comment by SjoerdV** [comment]
Excellent, just checked and working as advertised in version 3.2.2.
@rfennell, thanks very much for the swift action, great extension!

**Comment by SjoerdV** [comment]
Hi @rfennell I have to reopen this issue as I have exactly the same error message on version 3.3.10.
Can you confirm?

**Comment by SjoerdV** [comment]
weird stuff, the error dissipated again. So all is fine.

**Comment by palaciowagner** [comment]
I keep getting the same error. I've realized on the code for `enrichChangesWithFileDetails` that it checks if the URL has "dev.azure.com" for TfsGit but I'm on a private repository which uses another URL and then fails. I provided a githubPat as a parameter to it, but keep getting the same thing.

```
Get the file details associated with the commits
Enriched change 34434647a688ddd9c740acb7382d209e95c03de7 of type TfsGit
Cannot enriched as location URL not in dev.azure.com format
```

What should I do?

**Comment by rfennell** [comment]
The `enrichChangesWithFileDetails` feature is only supported if you are using the `https://dev.azure.com/<my org` url format i.e not when you are using the old `https://<my org>.visualstudio.com` format.

For details on swapping between these settings [see the Microsoft docs](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration)
