### ISSUE TITLE
Truncated PR description

### ISSUE THREAD

**Issue by eestein** [rfennell/AzurePipelines#779]
**Describe the bug**
I'm using Generate release notes (XPlat).
The PR description is being truncated at around ~385 chars. I tested with 2 long descriptions and they were both trimmed, one at 377 and another at 393. I'm guessing the difference is related to the fact I'm using markdown formatting in the description. I couldn't find an option on the task for that, that's why I'm opening this issue.

**To Reproduce**
1. Create a Generate Release Notes (XPlat) task
2. Use the PR description 
```
{{#forEach pullRequests}}
{{#if isFirst}}
### Pull Requests 
{{/if}}
**PR {{this.pullRequestId}}** {{this.title}}  
**By**: {{this.createdBy.displayName}}  
**Description:**  
  
{{{this.description}}}
{{/forEach}}
```
3. Create a "long" PR with over 400 characters 
4. See generated file for truncated description

**Expected behavior**
The full description displayed.

**What is the issue see:**
 - Azure DevOps Services (VSTS)

Please note I'm using `{{{` to sanitize.

**Comment by rfennell** [comment]
Sorry for not getting back sooner, I have been on annual leave. I don't have an immediate answer,  I will need to investigate this issue and get back to you

**Comment by eestein** [comment]
@rfennell thank you, I appreciate it :)

**Comment by rfennell** [comment]
I can't repo this issue, I used the template

```
# Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
{{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
*  **PR {{this.id}}**  {{this.title}} - {{this.description}}
{{/forEach}}
```

and got approx 500 characters back

![image](https://user-images.githubusercontent.com/324718/88546705-ad155080-d014-11ea-92f4-26ed49aca56b.png)

when the PR was set as follows

![image](https://user-images.githubusercontent.com/324718/88546778-c61e0180-d014-11ea-875d-435208699497.png)

Not sure were to go now with this one. Best I can come up with is that there is a terminating character in your description.

You could look at one of the dump options (as shown below, or one of the newer dump parameters)  to see of the data is present (and just not rendering). Maybe try

```
{{json this.pullRequests}}
```

This will show all the object array in the output

**Comment by eestein** [comment]
@rfennell thank you, I'll do the dump test, but do you know which terminating character that would be?

**Comment by eestein** [comment]
So, I've just tested with and without sanitize and it breaks at the same place. Evaluating the dump showed me the description field is being returned truncated, but there's another field `completionOptions.mergeCommitMessage` that has the full text with some extras. It has the following structure:

Merged PR 13607: `[PR title]`\n\n`[Full description]`\n\nRelated work items: #107981

I thought it could be some limitation on my rules, but I checked the completed PRs and they all have the full description there.

Any ideas? :/

**Comment by rfennell** [comment]
Could you send over the output of the PR dump, might be easier to understand

**Comment by eestein** [comment]
Here it is https://codebeautify.org/jsonviewer/cb3ca9c1

**Comment by rfennell** [comment]
The `completionOptions.mergeCommitMessage` are there because either 

- your PR is merged and that was the commit message
- you have set automated completion and that is to be the message

I tried dropping your description text into my test PR, still seems to work.

What do you get if you look at the PR via the API, something like

`https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullrequests/<id>`

e.g.
`https://dev.azure.com/richardfennell/GitHub/_apis/git/repositories/VSTSBuildTaskValidation/pullrequests/28'

Does this show the field truncated too?

**Comment by eestein** [comment]
No, if I use the URL you provided, it returns the complete `description` field.

**Comment by rfennell** [comment]
Very strange, that would suggest it is the Node SDK or my code doing the trim. Strange thing is I have now done an and to end using test with a release pipeline and your PR descriptin and I get no truncation.

I will keep digging

**Comment by eestein** [comment]
Thank you, I agree, that makes perfect sense. And here it is the result from the API request, so you can safely focus on that: https://codebeautify.org/jsonviewer/cb19c235

Thank you, again :)

**Comment by rfennell** [comment]
Sorry I can't repeat the problem you are having and can't see any code that could be causing the problem.

All the task does is get all the PRs in the project, it then selects the PRs that are linked to any commits associated with build/release. At no point is there any processing done to the PR objects returned from API, so I am just returning the `description` as returned by the API

As I cannot get a repo, all I can suggest is you do some diagnostics on your local system. You might find the [command line tester could help](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/XplatGenerateReleaseNotes/V3/testconsole). This will allow you to rerun the build/release that is showing the issue.

I will mark this as a known issue for now

**Comment by eestein** [comment]
@rfennell thanks Richard, I'm thinking here... which URL do you use to get that data? The one you shared or you get one that is returned with some metadata request on the project (I don't know). 
The reason I ask is because when I tried the URL you shared (new pattern dev.azure...) I got the full description, but when I run the task I get it truncated. So I'm thinking that if you use some sort of metadata to get the PR URL it could be that I'm using the old pattern on this project (xxx.visualstudio.com) and that the endpoint behaves differently (like truncating). What are your thoughts on that? Because honestly, other than that and the task having a bug (which you already discarded) I'm out of ideas as well.

**Comment by rfennell** [comment]
I use the [Azure DevOps Node API](https://github.com/microsoft/azure-devops-node-api) which is just a one for one wrapper for REST API calls.

As I mentioned I first get all the completed PRs for the project

```node
export async function getPullRequests(gitApi: GitApi, projectName: string): Promise<GitPullRequest[]> {
    return new Promise<GitPullRequest[]>(async (resolve, reject) => {
        let prList: GitPullRequest[];
        try {
            var filter: GitPullRequestSearchCriteria = {
                creatorId: "",
                includeLinks: true,
                repositoryId: "",
                reviewerId: "",
                sourceRefName: "",
                sourceRepositoryId: "",
                status: PullRequestStatus.Completed,
                targetRefName: ""
            };
            prList = await gitApi.getPullRequestsByProject( projectName, filter);
            resolve(prList);
        } catch (err) {
            reject(err);
        }
    });
}
```
So this should get the PR with a full description as this is just 'https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullrequests'

I then loop array this list to match merge commits, I never touch the objects, I push select the ones that match and add them to an array

```node
  var allPullRequests: GitPullRequest[] = await getPullRequests(gitApi, prProjectFilter);
                if (allPullRequests && (allPullRequests.length > 0)) {
                    agentApi.logInfo(`Found ${allPullRequests.length} Azure DevOps for PRs`);
                    globalCommits.forEach(commit => {
                        if (commit.type === "TfsGit") {
                            agentApi.logInfo(`Checking for PRs associated with the commit ${commit.id}`);

                            allPullRequests.forEach(pr => {
                                if (pr.lastMergeCommit) {
                                    if (pr.lastMergeCommit.commitId === commit.id) {
                                        agentApi.logInfo(`- PR ${pr.pullRequestId} matches the commit ${commit.id}`);
                                        globalPullRequests.push(pr);
                                    }
                                } else {
                                    console.log(`- PR ${pr.pullRequestId} does not have a lastMergeCommit`);
                                }
                            });

                        } else {
                            agentApi.logDebug(`Cannot check for associated PR as the commit ${commit.id} is not in an Azure DevOps repo`);
                        }
                    });
                } else {
                    agentApi.logDebug(`No completed Azure DevOps PRs found`);
                }
```

The bit I don't understand is why I cannot repo the problem. I seem to be able to get any length of description.

As I said all I can suggest is using my [local test harness (that I use to develop templates and Handlebars extensions](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/XplatGenerateReleaseNotes/V3/testconsole) and adding extra code to dump out the object as each point to see what is occurring or monitor the network with fiddler, but I can't do that as I cannot repeat the issue on my system

**Comment by eestein** [comment]
I understand and appreciate your help.
I'll continue to use completionOptions until I can test it properly.

Thank you very much!

**Comment by rfennell** [comment]
Do you want to leave this issue open, or close it and re-open if more information comes to light?

**Comment by eestein** [comment]
Well, for maintenance purposes, I think it might be better to close it. If anything else changes, I'll reopen. Thanks.
