### ISSUE TITLE
Create compareBuildDetails object for multi-stage yaml pipelines

### ISSUE THREAD

**Issue by soccerjoshj07** [rfennell/AzurePipelines#788]
**Is your feature request related to a problem? Please describe.**
No. Discussed in #758 as it related to the `checkStage` and `overrideStageName` options that were added

Remember that there are a number of Azure DevOps (VSTS) extensions in this repo so please say which one you are using, and if an extension contains multiple tasks which task also
cross platform

**Describe the solution you'd like**
Just like there is a `{{compareReleaseDetails}}` object, create a `{{compareBuildDetails}}` object. It would be nice to get the run time, build run ID, etc. from the build we are comparing to.

**Describe alternatives you've considered**
N/a

**Comment by rfennell** [comment]
I will try to have a look at it over the weekend

**Comment by rfennell** [comment]
I have made the change and it has been released a 3.6.2. 

There is a new object available in the Handlebars template `compareBuildDetails`, this is Build object, of the same type as the `buildDetails` object

```
# Build {{buildDetails.buildNumber}}
* **Branch**: {{buildDetails.sourceBranch}}
* **Tags**: {{buildDetails.tags}}
* **Completed**: {{buildDetails.finishTime}}

# Last Build {{compareBuildDetails.buildNumber}}
* **Branch**: {{compareBuildDetails.sourceBranch}}
```

Remember this new object is only populated if the `checkStage` parameter is set to `true` and a past pipeline has run and the stage the task is in (or the named `overrideStage`) has been successful.  If no pipeline has completed successfully for the stage the new object is empty.

**Comment by soccerjoshj07** [comment]
Awesome, works as intended. 

```markdown
# 🚀  Notes for release  

## Current Build 
**Build Number**: 20200815.18 
**Build Ran** : Sat Aug 15 2020 21:49:56 GMT+0000 (Coordinated Universal Time)     
**Branch**: refs/heads/master
**Requested For**: Josh Johanning

## Last Build Deployed to Prod
**Build Number**: 20200815.9
**Deployment Completed**: Sat Aug 15 2020 21:24:24 GMT+0000 (Coordinated Universal Time)
**Branch**: refs/heads/master
**Requested For**: Josh Johanning
```

I had a bit of a struggle at first getting the {{compareBuildDetails}} object to populate, I needed *two** successful runs to that stage, it seemed. It works now, but if you want any more details on that I can dig into further. Here's a screenshot:
![image](https://user-images.githubusercontent.com/19912012/90322377-e3116a80-df18-11ea-9ccb-8e7beab8e0ac.png)

What is it using to compare stages? I see in your code it's `System.StageName`, that is the stage ID, such as: `- stage: dev` ?

**Comment by rfennell** [comment]
By default it gets the stage name the release notes task is in, but you can orrride this with a named one passed as a parameter. It then looks back for the last build that completed successfully that stage.

If you run with the variable system.debug=true it will log out its discovery process
