### ISSUE TITLE
Handlebars custom extension code and conditional if block

### ISSUE THREAD

**Issue by ddprince-yaksa** [rfennell/AzurePipelines#802]
Hi, 

The question is for the extension XplatGenerateReleaseNotes@3.

I am trying to conditionally display a block under the handlebars template, but I am currently not able to do so. I have the following custom extension code for the property customHandlebarsExtensionCode: 
```
          module.exports = {
            stringToBool: function stringToBool(val) {
                return (val + '').toLowerCase() === 'true';
            },
            isProduction: function isProduction() {
                return module.exports.stringToBool('${{ parameters.RequestedForProduction }}');
            },
            environmentName: function environmentName() {
                return '${{ parameters.Environment }}'
            },
            ifCond: function ifCond(v1, v2, options) {
                if (v1 === v2) {
                    return options.fn(this);
                }
                return options.inverse(this);
            }
          };
```

And the following content inside my template: 
```
DEBUG: Variable state for 'isProduction': {{isProduction}}
DEBUG: Variable state for 'environmentName': {{environmentName}}

{{#ifCond isProduction true}}
   Render Is Production
{{else}}
   Rendered when NOT isProduction
{{/ifCond}}
```

Problem is, even though 'isProduction' returns true, my template is still rendering the "else" section has shown here in my screen capture: 
![image](https://user-images.githubusercontent.com/57116058/92004134-d8741500-ed0f-11ea-97ef-607dc3efd848.png)

The custom extension 'ifCond' has been recently added, because I wasn't able to use if neither. Using the following instead yielded the same results: 
```
{{#if isProduction}}
   Render Is Production
{{else}}
   Rendered when NOT isProduction
{{/if}}
```

Is it me or something under handlebars isn't properly working? 

I looked inside the source code and may have found a bug, but I am not entirely confident this is really "the" problem per se. Under the file "ReleaseNotesFunction.ts", line 526, it seems it is registering the "handlebars-helpers", which should includes the "if" extension normally provided by handlebars (to my understanding). But as we can see, the variable helpers isn't used anywhere else in the code. handlebars.registerHelper isn't event called like it's done just below at line 555 for registering the custom extensions from the task. 

Maybe this is why the conditional block isn't working? Can you reproduce this problem on your side? 

Thanks for your help!

**Comment by rfennell** [comment]
I will have a look when I get a chance, might not be for a few days though

On a first quick look, I know `if` is working as many of my [sample templates](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203) use it

```

{{#forEach pullRequests}}
{{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
 *  **PR {{this.id}}**  {{this.title}}
{{/forEach}}
``` 

The way I have tackled this type of thing is to get all my rendering/logic inside my custom extension. But I have little experience in handlebars development, it is only a recent addition to this task via [PR](https://github.com/rfennell/AzurePipelines/pull/642)

**Comment by ddprince-yaksa** [comment]
Maybe @KennethScott's input could help then? 

Thanks for taking a look once you'll have a chance. I'll simply use two different templates under my pipeline as a workaround during that time.

**Comment by rfennell** [comment]
I have just tried this template
```
## Global list of CS ({{commits.length}})
{{#forEach commits}}
{{#if isFirst}}
### Show on first
{{else}}
### Not first
{{/if}}
* **{{truncate this.id 7}}** {{this.message}}
{{/forEach}}
```

and it does exactly as you would expect

```
## Global list of CS (3)
### Show on first
* **e6f961e** Add the compareBuildDetails for YAML (#790)
### Not first
* **9fd45ba** Tenplate and sample fixes (#786)
- Correct sample with correct way to get PullRequest ID
- Added handlebars sample to get just the first line of a multiline string
### Not first
* **98ac443** Add a pair of test that had been incorrecly excluded (#785)
```

so I don't think there is anything fundamentally wrong with the IF/Else construct in the task.

I think the issue is that the `production` variable is not being passed into Handlebars processor, it does not have access to all Azure DevOps variables. Have a look at #756 
 
FYI I have been testing using the [standalone tester](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/XplatGenerateReleaseNotes/V3/testconsole) as a quick way to try out ideas.

**Comment by ddprince-yaksa** [comment]
Hi @rfennell . 

I finally figured it out. Basically, the "variable" isProduction was coming from a custom helper under handlebars. In order to adequately make the condition work, we need to call the help inside the helper so that the variable is properly interpreted. Basically, my fix was as followed: {{#if (isProduction)}}. Yes, that's it, by only including the parenthesis, handlebars understands it needs to resolve the help instead of something coming from the data. 

Hopes this can help anyone. 

Thanks!

**Comment by rfennell** [comment]
Great glad you are unblocked

**Comment by sawatsky** [comment]
@rfennell Is the solution from @ddprince-yaksa documented anywhere? I just faced the same problem:
```yaml
customHandlebarsExtensionCode: |
  module.exports = {
    pythonPackageVersion() { return "1.2a3"; },
    nugetPackageVersion() { return "1.2.3-a"; },
  };
```
```
Version: **{{#if pythonPackageVersion}}{{pythonPackageVersion}}{{else}}{{nugetPackageVersion}}{{/if}}**
pythonPackageVersion: {{pythonPackageVersion}}, typeOf: **{{typeOf pythonPackageVersion}}**
nugetPackageVersion: {{nugetPackageVersion}}, typeOf: **{{typeOf nugetPackageVersion}}**
```
Broken output:
> Version: **1.2.3-a**
> pythonPackageVersion: 1.2a3, typeOf: **undefined**
> nugetPackageVersion: 1.2.3-a, typeOf: **undefined**

---

Wrapping in parentheses worked, but I didn't find that information in the documentation:
```
Version: **{{#if (pythonPackageVersion)}}{{pythonPackageVersion}}{{else}}{{nugetPackageVersion}}{{/if}}**
pythonPackageVersion: {{pythonPackageVersion}}, typeOf: **{{typeOf (pythonPackageVersion)}}**
nugetPackageVersion: {{nugetPackageVersion}}, typeOf: **{{typeOf (nugetPackageVersion)}}**
```
Fixed output:
> Version: **1.2a3**
> pythonPackageVersion: 1.2a3, typeOf: **string**
> nugetPackageVersion: 1.2.3-a, typeOf: **string**

I am a complete amateur at Handlebars so I have no idea why this works, but I would've loved to read this solution in the [documentation](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task/).
