### ISSUE TITLE
How to increase the number of workitems and commits from default 50 to more number while using Releasenote generation Cross platform

### ISSUE THREAD

**Issue by jabimi** [rfennell/AzurePipelines#804]
**I want to increase the number of workitems and commits obtained by the Releasenote (Crossplatform) in a build from the default set value of 50 to atleast 200 each for workitems and commits**

Iam using the handlebar syntax as follows
#Release Note
---------------------------------
* Release Date : $(Release Date)
* Build Number : $(Build.BuildNumber) 
# Associated WorkItems  ({{workItems.length}})
----------------------------------
{{#each workItems}}
*  **{{this.id}}** {{lookup this.fields 'System.Title'}}
    - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
    - **Tags** {{lookup this.fields 'System.Tags'}}
    - *Description :* {{{lookup this.fields 'System.Description'}}}
{{/each}}
## Associated commits  ({{commits.length}})
------------------------------
{{#each commits}}
* ** ID{{this.id}}** 
   -  **Message :** {{this.message}}
   -  **Commited by :** {{this.author.displayName}} 
{{/each}}

**Comment by rfennell** [comment]
Have a look a #349 and it associate PR #352. If you set a build/release variable `ReleaseNotes.Fix349` to `true` the feature should be used. You should see a message in the logs says `Using workaround for build API limitation (see issue #349)`

Let me know how that goes

**Comment by jabimi** [comment]
I tried adding a variable in the build pipeline  ReleaseNotes.Fix349  to  true but it is still showing the same result.Its only picking first 50 WorkItems and first 50 commits etc

The below shown is a portion of the log details of the run task. For the record we are using **Inline handlebar template** in ReleaseNote crossplatform

_Get details of [50] WIs
Getting full details of WI batch from index: [0] to [50]
Adding [50] items
Total build artifacts: [0]
Total commits: [50]
Total workitems: [50]
Total related workitems: [0]
Total release tests: [0]
Total tests: [0]
Leaving WI in default order as returned by API_

please advice

**Comment by jabimi** [comment]
Another issue that i have noticed is that while running the **Generate release notes (PowerShell)** and **Generate Release Notes (Crossplatform)** in the same build Iam obtaining entirely different workitems and commits with no correlation to each other

**Comment by rfennell** [comment]
I will have to setup a test with enough WI and Commits, might be a few days before I get around to it, but I will have a look

**Comment by jabimi** [comment]
Ok thanks for the update.Hoping to get a reply soon

**Comment by rfennell** [comment]
Turns out there is a code path that did not make use of the #349 style fix in the new YAML pipeline specific code. The calls made do default to 50 items, I have altered these to 5000. I am currently testing a new release it will be 3.11.x
