### ISSUE TITLE
Unable to Link Work Items

### ISSUE THREAD

**Issue by Aditya-Capgemini** [rfennell/AzurePipelines#805]
I am unable to get the work items to link or display on the generated release notes using this template. Do you have a sample of what the generated release notes would look like when exported?

<img width="379" alt="No Work Items" src="https://user-images.githubusercontent.com/68606001/92120221-c6a17900-edc6-11ea-8f95-4e6a02e16a28.PNG">

**Comment by rfennell** [comment]
There is no sample of the output as it depends on the template you make use of.

The sample template for the different versions of the tasks (and I recommend using V3 of the Crossplatform version) are [here](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates)

To see what being done set a variable `system.debug` to `true` and check the logs, it shows all the process it uses to find content.
