### ISSUE TITLE
Getting all ancestors

### ISSUE THREAD

**Issue by j71h** [rfennell/AzurePipelines#807]
Hi,

I was looking for a way to get all the ancestors of a work item.
The way we organize our backlog makes Tasks and User Stories somewhat lacking in context and I would like to get the associated Feature as well. Our Tasks is very low level, so I would not like to include them at all in our release notes (this is the easy part, as I can filter them out in the template) but how do I get the parent item of a parent item?

  Br, Johan

**Comment by rfennell** [comment]
The Crossplatform release notes task already has the feature to get the immediate parents/children of the WI linked to a build/release

```
# Global list of WI with parents and children
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
   - **Description** {{{lookup this.fields 'System.Description'}}}
   - **Parents**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
{{/with}}
{{/if}}
{{/forEach}} 
   - **Children**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Child')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
{{/with}}
{{/if}}
{{/forEach}} 
{{/forEach}} 
```

If you needed to get 'further up the tree' the task would have to be edited to to in turn keep getting the parents until none existed. 

This would be a fairly major change to the code and I am not sure exactly how it would be exposed in a template, I guess it would be nested foreach's.

At this time this was not something I am rushing to implement as the recursion logic needs some thought. So at this point in time there is no way to get the parent of a parent.

**Comment by j71h** [comment]
Thanks for you reply.

I've managed to create two custom handlers, one that filters the workItems and relatedWorkItems to return a single list of all items we want to display. The second handler iterates the list, starting with items that have no parent, then recursively (for each item) iterate its children and so on.

As my template for each item is a unnumbered list item I provide an indention which is added to each iteration level and by that making each sub level a sub list in the current item.

Works and looks really great. The wish from stakeholder is to at least get 'Feature' level (all the time) so that items would be generated like this. (Right now feature level is not included all the time)

- **1234** [Feature/Active] My cool feature
   Description of what my cool feature should do
   - **23456** [User Story/Closed] A story in my feature
     Description of the story
     - **45678** [Bug/Closed] This aspect is not working
       \-
   - **23457** [User Story/PO Approval] A second story in my feature
     Description of the story

**Comment by rfennell** [comment]
Does that mean you are sorted?

If you think the custom extensions and template would be of use to other could to submit them as PR to **AzurePipelines/SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/**  with

- The .JS code
- The template that uses the extension
- A Readme explaining usage

**Comment by j71h** [comment]
Well, sort of. Getting to the Feature level i.e. grandparent would be ideal and that is not happening right now. With that said, we will make due with what we have right now.

I'll look into if the code is publishable and what I need to do to get it to be.

**Comment by rfennell** [comment]
If can make `getAllDirectRelatedWorkitems` recursive I think it will meet your needs, the templates will  have to be nested to the depth you require, but I can't see a way t avoid that.

I will have a look

**Comment by rfennell** [comment]
I have added a new option for getting the whole tree of parent work items, this is in addition to existing direct parent/child relationships. This will been shipped as 3.12.2 it issue currently being deployed

The parent related boolean properties are now 
- getParentsAndChildren - get the direct parent and children as before
- getAllParents - gets the parents all the way back up to the root WIs

In both cases all the WI get dumped into the `relatedWorkItems` array.

You do need a custom template that 'knows' about your internal WI hierarchy. I have tested with this template block

``` 
# Global list of WI with parents and children
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
   - **Description** {{{lookup this.fields 'System.Description'}}}
   - **Parents**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
      {{#forEach this.relations}}
      {{#if (contains this.attributes.name 'Parent')}}
      {{#with (lookup_a_work_item ../../../../relatedWorkItems  this.url)}}
         - {{this.id}} - {{lookup this.fields 'System.Title'}} 
      {{/with}}
      {{/if}}
      {{/forEach}} 
{{/with}}
{{/if}}
{{/forEach}} 
   - **Children**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Child')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
{{/with}}
{{/if}}
{{/forEach}} 
{{/forEach}}
```

Note that
- It seems that you need to be careful with the number of  `../` levels to make sure you reference where the actual array is. You seem to have to go up 2 level foreach level of WI hierarchy  
- There could be a neater way to achieve the same in Handlebars OTB (I am not an expert) or via a custom extension

Let me know how it goes

**Comment by j71h** [comment]
This is grand!
I'm using a javascript extension to handlebars to sort the hierarchies and another to recursively output each level. Cannot wait to update and see the new option and result.

I'll post back once I've tried it.

**Comment by j71h** [comment]
Testing using the test tool seems to work just like it should.

This is my template:

```md
# Notes for release from {{releaseDetails.releaseDefinition.name}}  

{{#with (itemAt (split buildDetails.url '_') 0) as | url |}}  

**Release Number**: [{{../releaseDetails.name}}]({{url}}_releaseProgress?_a=release-pipeline-progress&releaseId={{../releaseDetails.id}}) ({{../releaseDetails.id}})  
**Release completed**: {{../releaseDetails.modifiedOn}}  
**Build Number**: [{{../buildDetails.buildNumber}}]({{url}}_build/results?buildId={{../buildDetails.id}}&view=results) ({{../buildDetails.id}})  
**Compared Release Number**: [{{../compareReleaseDetails.name}}]({{url}}_releaseProgress?_a=release-pipeline-progress&releaseId={{../compareReleaseDetails.id}}) ({{../compareReleaseDetails.id}})  

## Included items

{{#with (filter_items ../workItems ../relatedWorkItems) as | items |}}  
*Listing {{inflect (length items) 'item' 'items' true}}*  
{{#each_in_hierarchy items '  '}}

* **[{{this.id}}]({{url}}_workitems/edit/{{this.id}})** [{{lookup this.fields 'System.WorkItemType'}}/{{lookup this.fields 'System.State'}}] - {{lookup this.fields 'System.Title'}}  
  *{{{trim (lookupOrDefault this.fields 'System.Description' '\-')}}}*  

{{/each_in_hierarchy}}  
{{else}}  
*No items to display*  
{{/with}}  

{{/with}}
```

As you can see I use some custom handlebars extension `filter_items` and `each_in_hierarchy`.
The first filters all work items (using `workItems` as the start to get the related leaves) into a single list of items.
The second recursively iterates the items (depth first) and prints the template, in this case a list item that is indented for each level.

The result looks something like this:

## Notes for release from My-Release

**Release Number**: [Release-2](https://dev.azure.com/MyOrg/MyProj/_releaseProgress?_a=release-pipeline-progress&releaseId=1001) (1001)  
**Release completed**: Wed Sep 16 2020 16:15:03 GMT+0200 (GMT+02:00)  
**Build Number**: [2020.09.16.002](https://dev.azure.com/MyOrg/MyProj/_build/results?buildId=14897&view=results) (14897)  
**Compared Release Number**: [Release-1](https://dev.azure.com/MyOrg/MyProj/_releaseProgress?_a=release-pipeline-progress&releaseId=1000) (1000)  

### Included items

*Listing 5 items*  

* **[1234](https://dev.azure.com/MyOrg/MyProj/_workitems/edit/1234)** [Bug/Closed] - Some error in functionality  
  *This bug is related to some technical story or other type that is not included by the filter.*  

* **[123](https://dev.azure.com/MyOrg/MyProj/_workitems/edit/123)** [Feature/Active] - My nice feature  
  *<div>Description of the feature</div>*  

  * **[124](https://dev.azure.com/MyOrg/MyProj/_workitems/edit/124)** [User Story/QA Approval] - A user story in the feature  
    *<div>As a  user I want to ...</div><div>So that ...</div>*  

  * **[125](https://dev.azure.com/MyOrg/MyProj/_workitems/edit/125)** [User Story/QA Approval] - Another user story in the feature  
    *<div>As a  user I want to ...</div><div>So that ...</div>* 

    * **[1023](https://dev.azure.com/MyOrg/MyProj/_workitems/edit/1023)** [Bug/Closed] - The xxx aspect of the user story did not work as expected  
      *\-*

**Comment by rfennell** [comment]
Great I will close this issue then
