### ISSUE TITLE
Linking Work Items

### ISSUE THREAD

**Issue by Aditya-Capgemini** [rfennell/AzurePipelines#810]
Hello, I am using Generate Release Notes in addition to the Wiki Updater Extension. I used template "build-handlebars-template.md" from your sample templates but was wondering if there was any way to specifically link the work items in the release notes so that they clicked on within the wiki to navigate directly to them. In this image below, under the Global List of Work Items section, the work items are listed by name but not directly linked. However, in the Global List of Commits section, the work items are directly linked and can be clicked on. What is the discrepancy here?

![Release Notes Extension](https://user-images.githubusercontent.com/68606001/92744753-c0c01080-f34f-11ea-95fd-238067d8c66a.png)

**Comment by rfennell** [comment]
You are seeing an 'interesting feature' of the Azure DevOps WIKI. 

If it sees WI that is related to a commit then it automatically adds the link to the WI - **you have no control over this**. 

If you look at the 'raw' markdown you will see that your line has no special tags to make it a link e.g.

![image](https://user-images.githubusercontent.com/324718/92891589-f62c3300-f40f-11ea-86fe-dfe20793ba16.png)

You can make your WI section also contain links, but this would require you to put the correct markdown tags in the template e.g. something like

```
# Global list of WI ({{workItems.length}})
{{#forEach workItems}}
{{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
  - **Tags** {{lookup this.fields 'System.Tags'}}
  - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
  - **Link** [{{this.id]]({{lookup this.fields 'System.url'}}_

{{/forEach}}
```

This generates

-  **Link** [13](https://richardfennell.visualstudio.com/_apis/wit/workItems/13) 
```
