### ISSUE TITLE
option to include only builds with specific tag/tags

### ISSUE THREAD

**Issue by gyozob** [rfennell/AzurePipelines#811]
Hello, I need a small thing for the release notes generation task so I have forked this repo and made the necessary updates to add the option to include only builds with a specific tag/tags in the release notes. Can you please merge these changes?
https://github.com/gyozob/AzurePipelines/commit/2a6858246b45189d445145bc08eec792999550f9

Thank you very much

**Comment by rfennell** [comment]
Thanks for the contribution, could you create PR into this repo and I will look to getting it merged

**Comment by gyozob** [comment]
Here it is https://github.com/rfennell/AzurePipelines/pull/812 :), thank you

**Comment by rfennell** [comment]
And it has been release as 3.8.1.

Thanks for the contribution

**Comment by gyozob** [comment]
thank you very much, I'm already using it, works perfectly :P
