### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by jwilkenss** [rfennell/AzurePipelines#814]
Hi, 

The Generate Release Notes (Crossplatform) extension is being used to send out release notes to a markdown file in our pipelines. There is a new error for any new pipeline that is created to use this extension. Existing pipelines seem to be fine. Looking to see how this error can be resolved. Not sure if this has something to do with setup of the extension, or the code that drives the extension. The version of the extension being used is 3.11.2. Notice this error in the last week.

Handlebars Template:

{{#forEach this.relatedWorkItems}}
{{#if isFirst}}{{/if}}
{{#if (and (contains (lookup this.fields 'System.Tags') 'Release')(contains (lookup this.fields 'System.WorkItemType') 'User Story')(contains (lookup this.fields 'System.State') 'Closed'))}}
{{lookup this.fields 'System.Title'}} Item # {{this.id}}
   {{{lookup this.fields 'System.Description'}}}
{{/if}}
{{/forEach}}

Error Description:

(node:8464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at relatedWorkItems.find.element (c:\agent\_Work13\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.11.2\ReleaseNotesFunctions.js:446:67)
    at Array.find (<anonymous>)
    at c:\agent\_Work13\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.11.2\ReleaseNotesFunctions.js:446:43
    at Generator.next (<anonymous>)
    at fulfilled (c:\agent\_Work13\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.11.2\ReleaseNotesFunctions.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rfennell** [comment]
Looking at you error log the problem appears lies in the line ` if (!relatedWorkItems.find(element => element.id === id)) {` we have no `id`

This is strange as we should only be trying to match relations that are either parents or children, which must have a valid URL with a WI ID as shown in the code below

```
export async function getAllDirectRelatedWorkitems (
    workItemTrackingApi: IWorkItemTrackingApi,
    workItems: WorkItem[]
) {
    var relatedWorkItems = [...workItems]; // a clone
    for (let wiIndex = 0; wiIndex < workItems.length; wiIndex++) {
        var wi  = workItems[wiIndex];

        agentApi.logInfo(`Looking for parents and children of WI [${wi.id}]`);
        for (let relIndex = 0; relIndex <  wi.relations.length; relIndex++) {
            var relation  =  wi.relations[relIndex];
            if ((relation.attributes.name === "Child") ||
                (relation.attributes.name === "Parent")) {
                var urlParts = relation.url.split("/");
                var id = parseInt(urlParts[urlParts.length - 1]);
                if (!relatedWorkItems.find(element => element.id === id)) {
                    agentApi.logInfo(`Add ${relation.attributes.name} WI ${id}`);
                    relatedWorkItems.push(await workItemTrackingApi.getWorkItem(id, null, null, WorkItemExpand.All, null));
                } else {
                    agentApi.logInfo(`Skipping ${id} as already in the relations list`);
                }
            }
        }
    }
```

A few things to try

- Re-run with the `system.debug=true` pipeline variable set to get detail logging, this may show something happening before that cause a knock on error
- Set the task parameters `dumpPayloadToFile` and `dumpPayloadFileName` so we get the raw JSON payload data so we can look to see what we are working with (see the [WIKI for details](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task-YAML))
- You might find my  [command line task runner](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/XplatGenerateReleaseNotes/V3/testconsole) useful to easy re-testing
