### ISSUE TITLE
Auto-generating release notes in Azure DevOps pipelines- missing template and handlebars format error

### ISSUE THREAD

**Issue by ankku** [rfennell/AzurePipelines#818]
Hi,

I am learning the use of this app in my devops pipeline which is suppose to generate release notes. Since I am new to this devops platform, i am finding it hard to use it in best way or right way.

I inserted a stage and added this task in my pipeline. So my pipeline now have a stage coming from artifacts which is connected to this block. On creating the release the stage triggers and at the end i get below error in logs. The parameters and template was same as shown in the above shared link.

error:
2020-09-17T20:13:02.5517977Z ##[error]The template is not on handlebars format, load template has been skipped
2020-09-17T20:13:02.5535703Z ##[error]Missing template file
2020-09-17T20:13:02.5653767Z ##[error]Missing template file

**Comment by rfennell** [comment]
I recently wrote a blog post that should help - [have a look at it](https://blogs.blackmarble.co.uk/rfennell/2020/09/15/how-can-i-automatically-create-azure-devops-release-notes-and-how-can-i-publish-them/). Also there is a usage sample for this task in issue #813 

All the error means is that you either 
- Have provided no template (as a file reference or an inline string)
- Or you have a template that is not in Handlebars format. Note that V1 & V2 of this extension support a different templating engine, V3 only support Handlebars templates.

You can find template samples [here](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203)

Hope that helps
