### ISSUE TITLE
Cannot read property 'attempt' of undefined

### ISSUE THREAD

**Issue by ryanpete** [rfennell/AzurePipelines#824]
When providing a value in the "Name of stage (override)" field on the release task I get the following errors upon execution

2020-09-30T17:08:04.8571718Z Show associated items for primary artifact only is set to false
2020-09-30T17:08:04.8572513Z Getting deployment count for stage
**2020-09-30T17:08:04.8613589Z ##[error]TypeError: Cannot read property 'attempt' of undefined
2020-09-30T17:08:04.8628406Z ##[error]TypeError: Cannot read property 'attempt' of undefined
2020-09-30T17:08:04.8736885Z ##[error]TypeError: Cannot read property 'attempt' of undefined**

These errors are only seen when a value is provided for the "Name of stage" field.  I have confirmed that the name I am providing in the field represents a uniquely named stage in the release pipeline as well.

My intention was to run this from an early stage in the pipeline comparing to "Prod" so I can generate  release notes that would map to "What would the release look like if this were deployed to prod?"... without having to actually deploy to prod/ie as the final step in the pre-prod stage.

**Env info**
Name: Generate Release Notes (Crossplatform)
I am running version 3.15.3 (I see the same error if I switch to a 2.* version as well)

**Comment by rfennell** [comment]
It would appear that in your case there has been no pre deployment approval for the named stage so it cannot get an attempt count. I will get a new version (it will be 3.17.x) that will add an extra check that pre deployment deployment is not null.

Let me know if that fixes you issues.

**Comment by ryanpete** [comment]
Thank you for the fast turnaround here.  However, while this did fix the original error, the scenario still fails (different error now)

2020-10-01T17:04:44.8146611Z Show associated items for primary artifact only is set to false
2020-10-01T17:04:44.8148018Z Getting deployment count for stage
2020-10-01T17:04:44.8178088Z **##[error]Failed to locate stage with name prod so cannot get attempt**

Perhaps casing is the cause?
The stage name I am attempting to use here is "Prod" while the error message mentions "prod"

A shortened version of my pipeline
StageName: Dev
-Has this task; specifies "Prod" (no quotes) in the 'Name of stage' field

StageName: Prod
- Has a predeployment approval (not executed)

Dev --> Prod

**Comment by ryanpete** [comment]
Sure, here is a link to the log.

[tasklog_6.log](https://github.com/rfennell/AzurePipelines/files/5317472/tasklog_6.log)

**Comment by rfennell** [comment]
The reason you are seeing different log results to me is that you have a `stopOnRedeploy=true` set. This is a rarely used feature, enabling it triggers a check to see how many previous releases have been made and if greater an 0 aborts the release notes generation. 

You had found a bug that an exception was being thrown that meant it thought there was a past release when there was none.

I have altered the logic so that if it finds no release to stage then it return a zero count as expect (as opposed to the exception). This will be released as 3.18.x later today when all the automated tests have run.

An immediate fix would be to set `stopOnRedeploy=false` to bypass the problematic logic

**Comment by ryanpete** [comment]
Looks good.  I ran it again after your 3.18.x update (stopOnRedeploy=true) and targeting another stage for comparison (vs current stage) all looks good.  Thank you for the quick turnaround here!
