### ISSUE TITLE
Cannot install Wiki PDF Export Tasks

### ISSUE THREAD

**Issue by Sebbl22** [rfennell/AzurePipelines#827]
**Describe the bug**
I cannot install Wiki PDF Export Tasks on my local Azure DevOps Server 2019.

**To Reproduce**
1. Go to Azure DevOps Server, upper right corner (shopping bag), "Browse Marketplace
2. Go to "WIKKI PDF Export Tasks page
3. Click on "Get it free"
4. An error message appears: 
>Task definition input 'cloneRepo' and Task definition input 'useAgentToken' must belong to same group as they are dependent inputs for Task with ID '48d40d27-32e1-460e-8ea6-0dfb48abdd6f'.
![grafik](https://user-images.githubusercontent.com/10319545/94916812-a6410900-04af-11eb-96fd-2b933fff415a.png)

**Expected behavior**
The collection select screen appears
![grafik](https://user-images.githubusercontent.com/10319545/94916844-b6f17f00-04af-11eb-9c13-0b2408bd0b3c.png)

**What is the issue see:**
- Azure DevOps Server 2019; Version Dev17.M153.5
- Server can access the internet
- Other extensions can be installed from marketplace

Maybe I am missing some important steps?
Thank you for your help

**Comment by rfennell** [comment]
I had some cross group visibility logic in the task.json manifest. Strange that the Marketplace and Azure DevOps Services are happy with it, but on premise Azure DevOps Server is not. Guess they must have altered the validation tool.

I have fixed the issue and will release a new version

**Comment by Sebbl22** [comment]
Thanks, I can install the extension now
