### ISSUE TITLE
Escaping html output

### ISSUE THREAD

**Issue by basland** [rfennell/AzurePipelines#828]
Thanks a lot for this amazing piece of work! I'm very happy using it in my projects. 

However, in one of my projects I have a requirement to output the release notes in a JSON structure. That works, however for some work item descriptions I get HTML code with " characters, which invalidates the JSON. Is there any way we can remove this from the results? 

Would like to hear from you, thanks! 

Best regards,
Bas

**Comment by rfennell** [comment]
The answer is to use a Handlebars extension. There are two options

- You could create custom one and pass it in a parameter. There are some [samples here](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203)
- But I suspect one of the the [Handlebar Helpers Library](https://github.com/helpers/handlebars-helpers) will do the job, and all these a build into the Azure DevOps task

So I suspect using the `replace` extension will do the job, something like

```
{{wi.descripition}}
```

with something like

```
{{replace wi.descripition "\"" "-"}}
```

It will take a bit of experimentation with the escaping. You might might my [command line tester](https://github.com/rfennell/AzurePipelines/tree/master/Extensions/XplatGenerateReleaseNotes/V3/testconsole) will help rapid template development

Hope that sorts you out

**Comment by basland** [comment]
Thanks a lot, that will help!
