### ISSUE TITLE
Define which changes should be considerd for release notes

### ISSUE THREAD

**Issue by andreasglaubitz** [rfennell/AzurePipelines#846]
Hi, 

I am currently using the **Generate Release Notes (Crossplatform)** task *(XplatGenerateReleaseNotes@2)* in our YAML pipeline. My problem is, that the task only generates releasenotes for changes since the last build. But I'm wondering, if there is a possibilty to define which changes should be included to the build. I will also include changes that was already part in older builds (e.g. all changes made in repo since the latest tag). 

best regards
Andreas

**Comment by rfennell** [comment]
Yes there are in V2 and more in V3. So I would recommend you update your builds to use the V3 version and hence a Handlebars based template. You then have the options

1. Use a build tag as the check for the last successful build(in V2 & V3)
2. If using UI based Releases create an extra stage that is only used for generating release notes. You trigger this manually when you need the release generated (V2 & V3)
3. You can do the same as 2 but for multi-stage YAML in V3 if you enable the `checkstages` option (V3 only)
4. You can set a specific build or release number as the old build/release to compare to by settings the `overrideBuildReleaseId` parameter (V3 only)

Once you are comparing against the right build then you could then filter the items listed based on whatever rules you want using the templating language. This is where V3 really helps as Handlebars is much more flexible.

One of these should do the job, check the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) for more details

**Comment by andreasglaubitz** [comment]
The 4th option seems exactly what I need. I tried it and it seems to work. 
But I think there is one missing information in the documentation. If you want to use `overrideBuildReleaseID` the parameter `checkStage` must be set to `true`. Otherwise `overrideBuildReleaseID` is ignored.

**Comment by rfennell** [comment]
Thanks for the feedback, I will do an documentation update
