### ISSUE TITLE
Cant override the maxmium number of Workitems or ChangeSets

### ISSUE THREAD

**Issue by WarrenBirch** [rfennell/AzurePipelines#855]
Hi, 

Despite changing the following variables in GenerateReleaseNotes.ps1

             $maxChanges= 1000 #Get-VstsInput -Name "maxChanges"
             $maxWi = 1000 #Get-VstsInput -Name "maxWi"

There is still a limit on the number is items coming back into the release note.

Are there any other variables I need to change ? Also when will it be possible to set these in the task as these are greyed out.

Regards
Warren

**Comment by rfennell** [comment]
I would suggest you don't use this older extension, as I plan to deprecate the old soon. Much better to to have a look at my newer [Cross Release Notes](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) this has full handling for larger CS/WI & PR. It also has a far more flexible templating model and richer set of options.

As to this issue, most to Azure DevOps API REST call seem to have a 1000. To get back more items you have to use a batching model.

**Comment by WarrenBirch** [comment]
Many thanks for the quick response, I have downloaded it and am trying to install, but it is saying 

The task.json file was not found in contribution task

Thanks
Warren

**Comment by rfennell** [comment]
Where a you trying to run the extensions, it does not sound like you are using Azure DevOps Services?

If it is on premises what version are you using - I only test on the current versions of the on-premise versions

**Comment by WarrenBirch** [comment]
Hi,

We are using Microsoft VSTFS Version 15.112.26307.0

**Comment by rfennell** [comment]
That is [TFS 2017.Update 1 RTM](https://stackoverflow.com/questions/46937655/identifying-version-of-tfs-via-web-interface) this is too old, and out of support from Microsoft. My extensions both assume later versions of the REST APIs, shipped with later versions. I doubt either extension will work, I certainly don't test back to such an old version. 

If you check [Microsoft's End of life site ](https://support.microsoft.com/en-gb/lifecycle/search/10453) you can see that only -TFS 2017.Update3 (latest patch version) is currently supported](https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2017-update3).

I would strongly recommend you consider upgrading to a newer version of Azure DevOps Server (2019.1 or 2020) and make an effort to keep patching it regularly, every few months, to make sure you the latest features and security patches.

So the summary is without an upgrade to the version of TFS > Azure DevOps Server 2019.1 (or later) else my and many other extension will not work.
