### ISSUE TITLE
Is there a defined list of Work Item fields or objects I can refer to in the Release Notes?

### ISSUE THREAD

**Issue by Aditya-Capgemini** [rfennell/AzurePipelines#856]
When configuring the release notes extension, I am able to refer to specific Work Item fields like title, state, assigned, tags, etc. I am wondering if there is a defined list of Work Item fields that are able to be referred to in the release notes.

**Comment by rfennell** [comment]
Given the previous questions you have asked I am assuming you are using the Cross Platform Release Note task.

The WI fields depend upon your process template customisation. This [list](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops) details the bulk of the common ones.

However, the best option is to use the task's properties `dumpPayloadToFile=true` and 'dumpPayloadFileName=$(Build.ArtifactStagingDirectory)\payload.json`. If used with a publish artifact task this will publish this extra file as a build artifact. This JSON file details the whole object that is available to the template, so you look to see the names of all the fields you available.

**Comment by Aditya-Capgemini** [comment]
Thanks for that, I was able to retrieve those values. Another question: In the advanced options of the task, I selected "Find Related WI" as well as "Find Parent WI" but neither seem to be generating the related work items. I even tried adding a section in the template for "Global List of Related WI" and "Global List of Parents", but I'm overall unable to generate these related work items. Do you have any suggestions?

![No Related WI's](https://user-images.githubusercontent.com/68606001/96748693-e3563800-1397-11eb-9d38-f78d02d34c23.PNG)

**Comment by rfennell** [comment]
The first thing to check is to set the variable `system.debug=true` this will enable detailed logging. You will be able to see that task working getting the number of related and parent WI e.g.

```
Getting direct parents and children of WorkItems
Looking for parents and children of WI [120148]
Looking for parents and children of WI [120130]
Add Child WI 120144
Add Child WI 120139
Getting all parents of known WorkItems
Looking for parents of WI [120148]
Looking for parents of WI [120130]
Looking for parents of WI [120144]
Skipping 120130 as already in the found parent list
Looking for parents of WI [120139]
Skipping 120130 as already in the found parent list
```

You should then see the list of these associated WI (of any type) in the `relatedWorkItems` object when you check the dump payload file.

You could just list out this object

```
{{#forEach relatedWorkItems}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
  - **Tags** {{lookup this.fields 'System.Tags'}}
  - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/forEach}}
```

But usually you do a lookup to this array based in the type of line

```
# Global list of WI with PRs, parents and children
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
   - **Description** {{{lookup this.fields 'System.Description'}}}
   - **PRs**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Pull Request')}}
{{#with (lookup_a_pullrequest ../../pullRequests  this.url)}}
      - {{this.pullRequestId}} - {{this.title}} 
{{/with}}
{{/if}}
{{/forEach}} 
   - **Parents**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
      {{#forEach this.relations}}
      {{#if (contains this.attributes.name 'Parent')}}
      {{#with (lookup_a_work_item ../../../../relatedWorkItems  this.url)}}
         - {{this.id}} - {{lookup this.fields 'System.Title'}} 
      {{/with}}
      {{/if}}
      {{/forEach}} 
{{/with}}
{{/if}}
{{/forEach}} 
   - **Children**
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Child')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}} 
{{/with}}
{{/if}}
{{/forEach}} 
{{/forEach}}
```

**Comment by Aditya-Capgemini** [comment]
Thank you! The second template you have helped with linking the parent work items. One more question - when I am using an File Template it seems like it projects to the Wiki in the original handlebar format, without accounting for formatting like bolding, etc. Is there a way to format the File template so that it projects to the Wiki appropriate with bolding? 

![Release Notes Template](https://user-images.githubusercontent.com/68606001/97015484-a1ed9600-1519-11eb-8ea7-7e0353faab93.PNG)

**Comment by rfennell** [comment]
No sure why you are seeing that. my Azure DevOps WIKI handles the format correctly

![image](https://user-images.githubusercontent.com/324718/97019761-9feefb80-1548-11eb-8575-b87a750ef2e7.png)

What happens if you edit the page in the WIKI, can see see what is wrong with it handling the format

**Comment by Aditya-Capgemini** [comment]
Thanks for your help. I got it to work, seemed like it was just an issue with my indentation.

**Comment by rfennell** [comment]
That makes seems
