### ISSUE TITLE
List of Commits per Pull Request are missing

### ISSUE THREAD

**Issue by striky1** [rfennell/AzurePipelines#866]
Hi,

I'm using Tasks XplatGenerateReleaseNotes@3 and WikiUpdaterTask@1 on Release pipeline.

Maybe I misunderstood something but I'm not getting information that I would expecting.

Let's imagine that we have structure of repository:

**Master** branch
**Develop** branch (created from **Master**)

When we are working on some features/bugfixes everything is going into **Develop** branch except situation when creating new stuff is already "closed". In that time we are creating new **Release** branch from **Develop**.

Developers can continue with their work, **Release** branch is "locked" and under testing and if there are some issues, HotFixes are comming to **Release**/**Develop** branches in separated PRs.

In the end, **Release** branch is merged into **Master** via single **PR** with all commits which we did from last time when **Develop** branch was merged into **Master**.

What I was expecting when I did Release Pipeline with GenerateReleaseNote plugin? That I'll have same list of commits as it is shown on Azure in PR details under "Commits" TAB. (Left Sidebar Menu -> Pull Request -> Completed -> {{somePR}} -> Commits)
_Note: I did same with regular pipeline and for both situation I'm using printing debug values into terminal, to check what I can use to generate Release Notes into Wiki._ 

What I got? Single commit with small information about what was done like: id, message, type, author, timestamp, location.. and so on.

My question is, it's possible to get informations about all commits which we are merging as new Release into Master via single PR? It's not purporse of this plugin or I'm doing something wrong? 

Thank you so much.

Best regards, striky..

**Comment by rfennell** [comment]
The logic to find pull request is as follows

1. Get a list of all the PRs in the repo (or project based on the `searchCrossProjectForPRs` parameter
1. Select the ones that are related to the build based on being either
   - the one that matches the one referenced in the build trigger
   - or has a matching `lastMergeCommit.commitId` that mayches the `commit.id` of one of the associate commits 

The extracted list is then returned.

So if you don't have a matching last merge commit the PR will not be listed.

If you run the build with the `system.debug=true` variable you will see the selection logic.

It might be the current logic is not correct for your usage. But check the logs to confirm that

**Comment by striky1** [comment]
I did PR with ID: 6176 which contains 4 commits.

I checked log from Release Build and there is:

```
2020-10-27T12:02:37.9097279Z - PR 6176 matches the commit f9cdb2aef
2020-10-27T12:02:37.9097838Z - PR 4005 does not have a lastMergeCommit
2020-10-27T12:02:37.9098388Z - PR 3933 does not have a lastMergeCommit
2020-10-27T12:02:37.9106778Z - PR 2096 does not have a lastMergeCommit
2020-10-27T12:02:37.9107381Z - PR 2042 does not have a lastMergeCommit
2020-10-27T12:02:37.9110077Z - PR 1344 does not have a lastMergeCommit
2020-10-27T12:02:37.9111209Z - PR 1124 does not have a lastMergeCommit
2020-10-27T12:02:37.9111718Z - PR 1106 does not have a lastMergeCommit
2020-10-27T12:02:37.9113357Z - PR 630 does not have a lastMergeCommit
2020-10-27T12:02:37.9113821Z - PR 626 does not have a lastMergeCommit
2020-10-27T12:02:37.9115145Z - PR 86 does not have a lastMergeCommit
2020-10-27T12:02:37.9115726Z - PR 68 does not have a lastMergeCommit
```

Why it is not searching for 6175, 6173, 6172 and 6171 which are as part of 6176 via Commits, I rlly don't know 🤷🏻‍♂️

I'm running pipelines with unchecked `searchCrossProjectForPRs` 'cause from my understanding, it's enough to have it unchecked if I want searching for PR in that exact repository on which was Pipeline run or should I run it with that? 

Thank you

**Comment by rfennell** [comment]
My assumption is that only the final merge commit (that ends the PR) is the only one detected as it is the only one associated with the build. The others commits are associated with the PR, but not the build, and  provide no mechanism to get to them at present

So the issue is I am limited by what the MS REST API has returned as WI & CS associated with the build, it does not chain down into PRs details unless I write extra code.

I could look at enhancing the PR object so that all the associated Commits are listed. Note that I only recently enriched the PR object array to include the associated work items.

So my thought is

- When the PR list has been filter enrich each PR so that each object includes
    - What is returned by the REST API for PR details
    - The associated WI - it does this now
    - Add the associated commits

**Comment by striky1** [comment]
Alright, I understand. If I can help you somehow, let me know but fyi I'm "just" FrontEnd developer, I don't have big knowledge about API of Azure and so on, tbh :)

**Comment by rfennell** [comment]
Ok, ow I understand and can make a code change. I will try to get it out ASAP

**Comment by rfennell** [comment]
This has been shipped as 3.27.3.

There is now a extra property on each PR that details the commits in the PR source branch. Note the commits listed here might not be associated directly with the build.

A sample of the usage is

```
## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
* **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
* Associated Work Items
{{#forEach this.associatedWorkitems}}
   {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}} 
   {{/with}}
{{/forEach}}
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
{{#forEach this.associatedCommits}}
    - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
{{/forEach}}
{{/forEach}}
```

**Comment by striky1** [comment]
@rfennell nice, thank you. It works!

I checked changes on your PR and I thought that this plugin is written in .NET or something similar 🤷🏻‍♂️ 

So, I checked Azure DevOps Node API and possible functions. It seems that we are in the end of what is possible to get. What is the problem? Associated Commits are fine, it's shame that they didn't returning Work Items (based on `GitInterfaces.GitCommit` interface)` who know why not, but main problem is that this `interface` don't contains simple "title" but description as `comment` property which including generated text by Azure (title, description and related work items), example: 

```
Merged PR 6175: [Bug] - Example Title\n\nCommit Message Example\n\n+ added not-in-develop.ts File\n\nRelated work items: #123
```

My idea was that I want to divide list of commits by Title of PR which that commit created. 
1. Let's say that PR have title as above: [Bug] - Example Title. 
2. Based on prefix I want to use `{{#if contains..}}` to filter it.
3. It will works 'cause `contains` will do his job but I need to create, probably, custom handlerbars function to get Title of commit from desc based on `\n\n` characters what is highway to hell 'cause what if Azure decide to change this format to something else?

So, I checked what we are able to ask for based on properties in `GitInterfaces.GitCommit` interface and seems that we are not able to find PR related to that commit what is strange 'cause if you open link from `remoteUrl`property, in Details Tab u can see to which PR is commit related to.

Do you see any other possible way or am I right and it is as it is? :) 

Thank you

**Comment by rfennell** [comment]
On your first point, all Azure DevOps pipeline tasks are written in PowerShell (original PowerShell not Core) or Node. I have written in both, but over time have tended to favour Node to give cross platform support. I only use PowerShell now for tasks that are Windows specific.

As to formatting the output, you can address problems like the comment being multiline by using the [Handlebars Helpers](https://github.com/helpers/handlebars-helpers) that are loaded by the tasks, or write your own as detailed in the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task). These allow you to create the release notes you need as I cannot support all the format people will request

So for example, if you did not want the full Git commit SHA, just the more common first 7  characters, and limit the comment to the first line you could swap from 

```
{{#forEach this.associatedCommits}}
    - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
{{/forEach}}
```
to
```
{{#forEach this.associatedCommits}}
    - [{{truncate this.commitId 7}}]({{this.remoteUrl}}) -  {{(split this.comment '/n')[0]}}
{{/forEach}}
```

**Comment by striky1** [comment]
@rfennell sure, sure, I know that this is my specific behaviour. It's not problem at all to make custom format.

 I was asking about if it's possible to get information about Pull Request which is connected with that specific commit. To not creating crazy handlebars function for extracting Title of Commit from Commit Description which is generated by Azure in some format (and this format can be changed in the future).

Sorry if I confused you.

**Comment by rfennell** [comment]
You have to use a lookup from the commits associated with the build into the associated PR, it is based on the matching the PR's `lastMergeCommit.commitId`.

So the template would be something like 

```
## Global list of CS ({{commits.length}})
{{#forEach commits}}
* **{{truncate this.id 7}}**
{{#with (lookup_PR_by_LastCommitId ../pullRequests this.id)}}
  - Associated PR {{this.pullRequestId}}
{{/with}}
{{/forEach}}
```

You need a custom helper  `lookup_PR_by_LastCommitId` that is declared as a parameter for the task 

```
# Generate Release Notes (Crossplatform)
# Description - Generates a release notes file in a format of your choice from the build or release history
- task: XplatGenerateReleaseNotes@3
  inputs:
      ... other parameters
     customHandlebarsExtensionCode: |
         module.exports = {lookup_PR_by_LastCommitId (array, id) {
             return array.find(element => element.lastMergeCommit.commitId === id);
         }};
```

This will just add the associated PR if one can be found

**Comment by striky1** [comment]
There are not any others PRs in build. We are in scope:

```
{{#forEach pullRequests}}
  {{#forEach this.asssociatedCommits}}
     ..your suggestion for lookup..
  {{/forEach}}
{{/forEach}}
```

but PullRequest contains one Object, with 4 objects of associated commits. Nothing more.

That's reason why I was checking MS Azure Node API to understand how we can do another call/change in your code to get Details

**Comment by rfennell** [comment]
Not sure if you are aware that you can get the available data as a JSON file by setting the `dumpPayloadToFile and `dumpPayloadFileName` parameters. This make looking that the data available to a template much easier.

One question, what merge model are you using for PRs? 

The logic as it stands works for merge commits and squashes, but I am unsure what will happen with other PR workflows. 

At present there needs to be merge commit as this was this is the commit that is directly associated with the build (the commits returned by `getChangesBetweenBuilds()`, hence only the PR listed will be the ones that match a last merge commit id with a commit associated with the build.

**Comment by striky1** [comment]
I didn't know it but it's not problem to check logs from Release Pipeline, it's big issue but ty for tip 👍 

We are using "Merge strategy: Squash commit".

well, as I wrote before our strategy is:

Master -> Develop <- pushing features/bugfixes and so on (in this case above, 4 PRs). After two sprints we make new branch -> Release.

Release branch is merged as single PR -> Master 

Release Pipeline is on Master branch and I got information about that single PR with 4 commits (connected to 4 PRs originally from Develop). So, I want to ask if there is a chance to get PR based on that commits (PRs are not as part of that build).

I saw that we can use for example `getPullRequests` which expecting `GitInterfaces.GitPullRequestSearchCriteria` but not sure if we are able to find PR based on `includeLinks` for example which are available on Associated Commits. 

Interface:

```
export interface GitPullRequestSearchCriteria {
    /**
     * If set, search for pull requests that were created by this identity.
     */
    creatorId?: string;
    /**
     * Whether to include the _links field on the shallow references
     */
    includeLinks?: boolean;
    /**
     * If set, search for pull requests whose target branch is in this repository.
     */
    repositoryId?: string;
    /**
     * If set, search for pull requests that have this identity as a reviewer.
     */
    reviewerId?: string;
    /**
     * If set, search for pull requests from this branch.
     */
    sourceRefName?: string;
    /**
     * If set, search for pull requests whose source branch is in this repository.
     */
    sourceRepositoryId?: string;
    /**
     * If set, search for pull requests that are in this state. Defaults to Active if unset.
     */
    status?: PullRequestStatus;
    /**
     * If set, search for pull requests into this branch.
     */
    targetRefName?: string;
}
```

What do u think? :)

**Comment by rfennell** [comment]
Sorry for being so slow on the uptake, getting my head around issues can take a while sometimes, but I think I have it now...

- You see the PR from Develop > Master
- You also want to see the 4 PR from working branches > Develop that come before the PR you do see

I will have to think about that, but no quick solution leaps out without something very custom. I do aim to keep this task as generic as possible.

Best I can come up with now is maybe a workaround is to use the task on the builds triggered by the PRs for the working branch to > Develop branch and store each of these documents in a WIKI (maybe merging them into one document the WIKIUpdater can do that) and then append the Develop > Master release notes? 

Not the solution you asked for but might get you close

**Comment by striky1** [comment]
No prob, take your time as u need ;) 

Yep, that was my previous idea when we were resolving another issue about missing Work Items per PR (#861).

I did it as u said. On Develop branch I had Regular Pipeline and I stored info about each PR to Wiki and then on Master I had Release Pipeline to append data. Result was:

# :rocket: v1.1.0
**Release Number**:  Release-47
**Release completed**: Wednesday, 28 October 2020 06:53:42     
**Build Number**: 8013

## Associated Pull Requests:

### :bug: Example Title
**PR**: [6184]()
**Author**:  Lukas Strisovsky 
**PR completed**: Wednesday, 28 October 2020 06:53:00
**Approved by**:  Lukas Strisovsky
####Associated Work Items:
| ID | Title | Team | Sprint |
|--|--|--|--|
| [123]() | Some Work Item Title  | Some\Team\Structure | Some\Phase\Sprint 1 |
&nbsp;
 
### :bug: Example Title 2
**PR**: [6183]()
**Author**:  Lukas Strisovsky 
**PR completed**: Wednesday, 28 October 2020 06:33:00
**Approved by**:  Lukas Strisovsky
####Associated Work Items:
| ID | Title | Team | Sprint |
|--|--|--|--|
| [121]() | Some Work Item Title 2  | Some\Team\Structure | Some\Phase\Sprint 1 |
&nbsp;

But problem is with Release branch which we are creating when we decide to release new version of App. This branch we are using for testing (for a some period, let's say a week). So we have in same time:

Master
Develop -> development is continue but new features are not going to Release branch
Release -> if testers find bug, we will fix it and create PR for this branch + for Develop

After tests are done, we are merging Release into Master what means that in meantime we can merge new stuff to Develop branch but not to Release. Result is that in Wiki will be something what is not as part of that Release. It will be as part of next Release.

For that reason is not possible to have that behaviour with updating Wiki based on Develop branch changes.

Thank you a lot for your time, if you will have any new ideas/update, let me know. If I can help u somehow, don't hesitate to ask me (I have limited knowledge about Azure API yet but I'm working with JS).

**Comment by rfennell** [comment]
Ok, I have come up with what I think is a solution.

- I have added a new boolean so this new functionality is off by default, to enable set the task parameter `getIndirectPullRequests` to true
- If enabled the task now
   - Checks the newly added associated commits for each PR for any that are a last merge i.e. associated with a PR
   - These indirectly associated PRs are added to a new array available to the Handlebars template `inDirectlyAssociatedPullRequests`

A sample template of how this could be use with a Gitflow workflow is as follows

```
## Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
* **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
* Associated Work Items
{{#forEach this.associatedWorkitems}}
   {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}} 
   {{/with}}
{{/forEach}}
* Associated Commits (this includes commits on the PR source branch not associated directly with the build)
{{#forEach this.associatedCommits}}
    - [{{truncate this.commitId 7}}]({{this.remoteUrl}}) - {{get_only_message_firstline this.comment}}
    {{#with (lookup_a_pullrequest_by_merge_commit ../../inDirectlyAssociatedPullRequests  this.commitId)}}
      - Associated PR {{this.pullRequestId}} - {{this.title}} 
    {{/with}}
{{/forEach}}
{{/forEach}}
``` 

This will be shipped as 3.29.x as soon as my testing is complete

**Comment by striky1** [comment]
@rfennell awesome! It looks rlly great. Ty for your help with it.

I'm trying to test it but unfortunately for some reason in Pipelines or Release pipelines I have still older version even we have updated your plugin correctly, see screenshot below. 

Release Pipeline:
![Screenshot 2020-11-02 at 16 05 38](https://user-images.githubusercontent.com/8904756/97883708-8195b680-1d25-11eb-84e1-16ee5112dc97.png)

Extensions settings:
![Screenshot 2020-11-02 at 16 05 43](https://user-images.githubusercontent.com/8904756/97883714-835f7a00-1d25-11eb-82ac-25b0bfc40b36.png)


We are doing something wrong or it's something wrong with this Release, pls?

Thank you so much!

**Comment by rfennell** [comment]
It should come down automatically, not sure why it has not. But there have been some Azure DevOps pipeline issues today. Might be worth trying later

**Comment by striky1** [comment]
👋 

sorry for late answer. I was busy with other issues. 

Thank you a lot, u did it! It works nice and I reached the goal 👏

P.S.: Yep, Azure DevOps had some issues.
