### ISSUE TITLE
Using separate pipeline for XplatGenerateReleaseNotes

### ISSUE THREAD

**Issue by flcdrg** [rfennell/AzurePipelines#873]
My initial use of XplatGenerateReleaseNotes was with a multi-stage pipeline (as mentioned in https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes#overview), with the deployment stage going to an empty environment that requires approval to proceed.

Because we don't need every build deployed I was hoping this would provide a way to be selective about which builds were released (and aggregate release notes from the last release). That does work, but the problem is we end up with a bunch of builds with the second (release) stage never approved.

So I was wondering if we could run the release stage in a separate pipeline (that has a resource dependency on the original build pipeline)?

**Comment by rfennell** [comment]
Sorry I can't think of away to avoid this without have cancel release stages or ones left undeployed with a two stage approach. I was wondering if conditions on stages might help, but I can't see rules that would give the results you want.

But, there is no reason why you cannot split the single multistage pipeline into two and get the results you are after (this is how classic build and release worked)

- Pipeline 1 does your build as now
- Pipeline 2 consumes pipeline 1's output as a resource, can still use an environment for manual approval, but the whole pipeline could be manually triggered to avoid the unapproved release notes builds.
 
However, IMHO I would stick with your current option, as I think there is value in see you built something and choose not to deploy it.

**Comment by flcdrg** [comment]
If there was a way to keep the multistage pipeline and have a 'skip' option for the approval then that would solve it, but [that's not available yet](https://developercommunity.visualstudio.com/idea/697467/manually-triggered-stages-in-yaml-multi-stage-pipe.html).

I've done some experimenting and it seems like it might work having two pipelines. I'll comment back once I can confirm that.

**Comment by rfennell** [comment]
You can put your stage YML inside a condition, but I am not sure how you would enter the value to pick the condition. It sort of gets you back to the same problem, no means to enter a skip

```
stages:
  - ${{ if eq(parameters.deploy-it, 1) }}:
      - stage: DEPLOY
        displayName: Deploy
        jobs:
          - ... 

```

You are not alone in this request - https://stackoverflow.com/questions/61503762/skip-stage-with-manual-approval-in-azure-devops-pipelines-yaml
