### ISSUE TITLE
WIKI Updater authentication error

### ISSUE THREAD

**Issue by Shafeeqts89** [rfennell/AzurePipelines#877]
**Describe the bug**
Hi, I am trying to use the Release Notes Generator and Wiki Updater together azure devops pipeline. Am using PAT to authenticate the WIKI repo to link the release note. The following error occurs. 

Error: Cloning into 'D:\a\1\s\repo'... git: 'credential-manager-core' is not a git command. See 'git --help'. fatal: Authentication failed for 'https://dev.azure.com/xxx/xx%2520Online/_git/xxx-Online.wiki/'

**Comment by rfennell** [comment]
Can you re-run the task with the variable `system.debug=true` set to get a detailed log?

It does should like the permissions could be wrong, make sure you get all the relevant details in the [wiki](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks)

**Comment by Shafeeqts89** [comment]
Here is the log after enabling debug
git: 'credential-manager-core' is not a git command. See 'git --help'.
fatal: Authentication failed for 'https://dev.azure.com/xxx/xxx%2520Online/_git/xxx-Online.wiki/'

##[debug]Processed: ##vso[task.issue type=error;]Error: Cloning into 'D:\a\1\s\repo'...%0Agit: 'credential-manager-core' is not a git command. See 'git --help'.%0Afatal: Authentication failed for 'https://dev.azure.com/xxx/xxx%2520Online/_git/xxx-Online.wiki/'%0A
##[debug]task result: Failed
##[error]Error: Cloning into 'D:\a\1\s\repo'...
git: 'credential-manager-core' is not a git command. See 'git --help'.
fatal: Authentication failed for 'https://dev.azure.com/xxx/xxx%2520Online/_git/xxx-Online.wiki/'

##[debug]Processed: ##vso[task.issue type=error;]Error: Cloning into 'D:\a\1\s\repo'...%0Agit: 'credential-manager-core' is not a git command. See 'git --help'.%0Afatal: Authentication failed for 'https://dev.azure.com/xxx/xxx%2520Online/_git/xxx-Online.wiki/'%0A
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Cloning into 'D:\a\1\s\repo'...%0Agit: 'credential-manager-core' is not a git command. See 'git --help'.%0Afatal: Authentication failed for 'https://dev.azure.com/xxx/xxx%2520Online/_git/xxx-Online.wiki/'%0A
Finishing: Git based WIKI File Updater


Here is the YAML for the task
steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI File Updater'
  inputs:
    repo: 'xxx@dev.azure.com/xxx/iQS%20Online/_git/xxx-Online.wiki'
    filename: 'releasenote-test.md'
    dataIsFile: true
    sourceFile: '$(System.DefaultWorkingDirectory)/zip/releasenotes.md'
    message: 'Release note added'
    gitname: builduser
    gitemail: shafeeq
    useAgentToken: false
    user: shafeeq
    password: '$(pat)'
  enabled: true

**Comment by rfennell** [comment]
I have never seen that error before, it should like the copy of Git being picked up the task is either very old or corrupt.

My task just uses [simple-git](https://www.npmjs.com/package/simple-git) for the git operations. This just runs whatever version of git is available via the default path.

I am assuming you are using a private build agent, can you check the version of git installed and whether it runs form a prompt.

The other option is to try this task in a hosted agent to prove it is a load issue.

FYI: the agent will use it's own copy of git.exe, not the default on the PC, to download any clone operation, So the fact you can clone a repo is not guide to this problem.

**Comment by Shafeeqts89** [comment]
Hi Fennell,
I am using a hosted agent, see the screenshot.
![image](https://user-images.githubusercontent.com/60779307/98072921-21218900-1e8d-11eb-9bf2-1d901e679c3b.png)

This is a private project repo does that count here?
Did you see any other mistake in my task parameters?

**Comment by rfennell** [comment]
That is really strange. I still cannot find and reference to that error message.

Not sure it is important, but which exact hosted VMImage are you using? 

The message does point to an authentication issue, so lets continue down that path 

<hr>

On looking at your YAML again, I think your `user` name might be wrong

``
user: shafeeq
password: '$(pat)'
```

My understanding of Git URL based authentication and Azure DevOps is that if you are using a PAT the user portion of the URL should match the Azure DevOps organisations e.g.

```
user: xxx
password: '$(pat)'
```

However, Looking at one of my test pipelines I have even left this parameter undefined and this worked too.

```
- task: WikiUpdaterTask@1
  displayName: 'Update Releases/.order'
  condition: succeeded()
  inputs:
    repo: 'dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki'
    filename: 'page.md'
    replaceFile: false
    appendToFile: true
    dataIsFile: false
    contents: "`n$(build.buildnumber)`n"
    message: 'Order Update'
    gitname: 'Build.RequestedForId'
    gitemail: 'Build.RequestedForEmail'
    UseAgentToken: false
    password: $(pat)
``` 

Either way I would expect the log to show something similar to the following

```
The provided repo URL is dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki
The protocol is https
The provided repo URL is dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki
Trimmed the URL to dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki
URL used https://undefined:***@dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki
Cleaned C:\agents\richardfennell\_work\21\s\repo
Cloned dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki to C:\agents\richardfennell\_work\21\s\repo
Set GIT values in C:\agents\richardfennell\_work\21\s\repo
No sub-directory passed change to C:\agents\richardfennell\_work\21\s\repo
Pull in case of post clone updates from other users
Working file name is page.md
Appended to the page.md in C:\agents\richardfennell\_work\21\s\repo
Added page.md to repo C:\agents\richardfennell\_work\21\s\repo
Committed file "C:\agents\richardfennell\_work\21\s\repo" with message "Order Update" as SHA 73c66b0
Attempt 1 - Push to dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki
```

They key is that it does report a URL in the form
```
https://<user>:<*** in place of the encodedPAT>@dev.azure.com/<Org>/<project>/_git/<wiki>
```

**Comment by Shafeeqts89** [comment]
Hi,
Agent and Host details;
![image](https://user-images.githubusercontent.com/60779307/98100840-6fe41880-1eb7-11eb-8788-81bf6c787fec.png)
Tried with org name, but no luck :(

**Comment by Shafeeqts89** [comment]
I have tried with the build agents OAUTH Token for authentication and that is working. But wondering why PAT is not working.

**Comment by rfennell** [comment]
For me during testing, the most common issue is a cut and past error when entering the PAT as a variable. You think you entered the PAT but it blank or not what you think it is.

But anyway glad you are unblocked

**Comment by foosfam** [comment]
Richard, the final thing I wanted to get working was the useAgentToken **true** option.
We really can't move ahead with this with a user and PAT token in the pipeline.

**For the life of me, I cannot see why this won't work, but I am getting a new error now:**
```
##[error]Error: remote: 001f# service=git-receive-pack
remote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\<GUID>', scope 'repository'.
remote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\<GUID>', scope 'repository'.
fatal: unable to access 'https://XXXXXXX.visualstudio.com/XXXXXXX/_git/XXXXXXX.wiki/': The requested URL returned error: 403

```
Does this have anything to do with the older visualstudio URL?

I have checked the permissions up and down and the Build Service user definitely has Contribute permissions.

Also, the "Limit job authorization scope to referenced Azure DevOps repositories" is off at both the project and org level.

Anything you can do to get me over this one last hurdle would be fantastic.

**Comment by rfennell** [comment]
It should have nothing to do with the old for new format of the URL.

The only things I know that can cause this problem with OAUTH are
- Giving rights to the wrong use. [OAUTH can run as Project Collection build user or Team Project build user](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops), try granting rights to both in turn
   - <project> build user
   - Project Collection Build User
- The limit scope is the most common current cause, but you say you have checked that
- If using a private agent, corporate proxies can cause the problem, but this will not be cause if you are using a hosted agent

Sorry I don't have another suggestion

Oh and on another note, I am working on a PR to fix the CS enrichment not working for older URL formats #881

**Comment by wooferclaw** [comment]
Having exact the same issue as @Shafeeqts89 using **windows-2019** hosted pipeline 
![image](https://user-images.githubusercontent.com/8898952/98547372-2164be80-22a9-11eb-859f-30b1076fdfce.png)

**Comment by rfennell** [comment]
I have just retested with the following YML, so same agent pool and using OAUTH

```
pool:
  vmImage: 'windows-2019'

- task: WikiUpdaterTask@1
  displayName: 'Update  Page.md OAUTH'
  condition: succeeded()
  inputs:
    repo: 'https://richardfennell@dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki'
    filename: 'page.md'
    replaceFile: false
    appendToFile: true
    dataIsFile: false
    contents: "`n$(build.buildnumber)`n"
    message: 'Order Update OAUTH'
    gitname: 'Build.RequestedForId'
    gitemail: 'Build.RequestedForEmail'
    UseAgentToken: true
```

The log showed the following

```
Using OAUTH Agent Token, overriding username and password
##[debug]Getting credentials the agent is running as
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Found an OAUTH token
The provided repo URL is https://richardfennell@dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki
The protocol is https
The provided repo URL is https://richardfennell@dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki
Removing leading http:// or https:// block
Removing leading username@ block
Trimmed the URL to dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki
URL used https://buildagent:***@dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki
Cleaned D:\a\1\s\repo
Cloned dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki to D:\a\1\s\repo
Set GIT values in D:\a\1\s\repo
No sub-directory passed change to D:\a\1\s\repo
Pull in case of post clone updates from other users
Working file name is page.md
Appended to the page.md in D:\a\1\s\repo
Added page.md to repo D:\a\1\s\repo
Committed file "D:\a\1\s\repo" with message "Order Update OAUTH" as SHA 9e56017
Attempt 1 - Push to dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki
Push completed
```

The permissions are set as as follows
![image](https://user-images.githubusercontent.com/324718/98550935-9da0d700-2294-11eb-9059-c8e6c06dd773.png)

And the settings for all Agents
![image](https://user-images.githubusercontent.com/324718/98550187-b066dc00-2293-11eb-93bd-2a4c29148d85.png)

I am not sure what else I can do to help

**Comment by wooferclaw** [comment]
I have double checked the settings, it looks the same.

**YAML**
```
steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI File Updater'
  inputs:
    repo: 'https://builduser@my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki'
    filename: 'Reporting release notes'
    replaceFile: true
    dataIsFile: true
    sourceFile: report.md
    message: 'release notes'
    tagRepo: false
    gitname: Build.RequestedForId
    gitemail: Build.RequestedForEmail
    useAgentToken: true
    injectExtraHeader: false
```

This is my failing log (i have removed tokens from the url)
```
Variable: SourCeFile [report.md]
Variable: Tag Repo [false]
Variable: Tag [undefined]
Variable: Branch [undefined]
Variable: InjectExtraHeader [false]
Variable: Retries [5]
Variable: trimLeadingSpecialChar [false]
Using OAUTH Agent Token, overriding username and password
##[debug]Getting credentials the agent is running as
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Found an OAUTH token
The provided repo URL is https://builduser@my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki
The protocol is https
The provided repo URL is https://builduser@my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki
Removing leading http:// or https:// block
Removing leading username@ block
Trimmed the URL to my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki
URL used https://buildagent:***@my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki
Cleaned D:\a\1\s\repo
##[error]Error: Cloning into 'D:\a\1\s\repo'...
git: 'credential-manager-core' is not a git command. See 'git --help'.
fatal: unable to update url base from redirection:
  asked for: https://buildagent:***@my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki/info/refs?service=git-upload-pack
   redirect: https://spsprodweu4.vssps.visualstudio.com/_signin?realm=my-test-project.visualstudio.com&reply_to=https%253A%252F%252Fmy-test-project.visualstudio.com%252FVertex%252F_wiki%252Fwikis%252FVertex.wiki%252Finfo%252Frefs%253Fservice%253Dgit-upload-pack&redirect=1&hid=<tokens>
##[debug]Processed: ##vso[task.issue type=error;]Error: Cloning into 'D:\a\1\s\repo'...%0Agit: 'credential-manager-core' is not a git command. See 'git --help'.%0Afatal: unable to update url base from redirection:%0A  asked for: https://buildagent:***@my-test-project.visualstudio.com/Vertex/_wiki/wikis/Vertex.wiki/info/refs?service=git-upload-pack%0A   redirect: https://spsprodweu4.vssps.visualstudio.com/_signin?realm=my-test-project.visualstudio.com&reply_to=https%253A%252F%252Fmy-test-project.visualstudio.com%252FVertex%252F_wiki%252Fwikis%252FVertex.wiki%252Finfo%252Frefs%253Fservice%253Dgit-upload-pack&redirect=1&hid=<tokens>
##[debug]task result: Failed
```
I have the same picture, trying to use OAUTH agent token of username and PAT

**Comment by rfennell** [comment]
Sorry I no other suggestions at this time, as I cannot repo the issue, than to just keep using a PAT stored as pipeline variable.

Sorry it is not answer you are looking for, bit it is at least a workaround

**Comment by foosfam** [comment]
@wooferclaw - Try the PAT authentication method.
Click on the 3 dots next to your wiki and click "Clone wiki" - Then click "Generate Git Credentials"
It worked the first time for me.

Then set:
UseAgentToken: false
user: <USERNAME>
password: <PASSWORD>

It may not be ideal but I stored them in a variable group called so I can reuse it across all pipelines.
