### ISSUE TITLE
How to get list of work items in azure boards using a command in Azure CLI 

### ISSUE THREAD

**Issue by swkoganti** [rfennell/AzurePipelines#879]
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/work-item?view=azure-cli-latest#ext_azure_devops_az_boards_work_item_show
refer to this above url I did not find any related command to list all work items

**Comment by rfennell** [comment]
Not sure why you have logged and issue on this repo as it is not the home of Azure CLI - it's home is [here](https://github.com/Azure/azure-cli) I suggest you log the issue there.
