### ISSUE TITLE
Handler Template needed.

### ISSUE THREAD

**Issue by Shafeeqts89** [rfennell/AzurePipelines#884]
Hi,
I have been trying to create a release note for one of our classic build pipeline. The details I am trying to write to release note are Build Number and its Associated work item details, but not working. Could you please provide one template with such information?

**Comment by rfennell** [comment]
There are sample templates [here](https://github.com/rfennell/AzurePipelines/tree/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203).

A basic build one in the sample is also shown below, this lists the build details and WI and CS

```
# Notes for build 
**Build Number**: {{buildDetails.id}}
**Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 

# Associated Pull Requests ({{pullRequests.length}})
{{#forEach pullRequests}}
{{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
*  **{{this.pullRequestId}}** {{this.title}}
{{/forEach}}

# Global list of WI ({{workItems.length}})
{{#forEach workItems}}
{{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
  - **Tags** {{lookup this.fields 'System.Tags'}}
  - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/forEach}}

# Global list of CS ({{commits.length}})
{{#forEach commits}}
{{#if isFirst}}### Associated commits  (only shown if CS) {{/if}}
* ** ID{{this.id}}** 
  -  **Message:** {{this.message}}
  -  **Commited by:** {{this.author.displayName}} 
{{/forEach}}
```

**Comment by Shafeeqts89** [comment]
Hey, thanks for the quick response.
I have a custom build number format(see screenshot), but it is not reflecting in the release note.
![image](https://user-images.githubusercontent.com/60779307/99072464-1cba4600-25da-11eb-9c0f-a57fd73ad91f.png)
instead, the default build number is taken in the release note
![image](https://user-images.githubusercontent.com/60779307/99072545-42474f80-25da-11eb-927b-17ad2b9eefb6.png)

**Comment by rfennell** [comment]
The `{{buildDetails.id}}` is the unique numeric ID of the build.

I think you need the `{{buildDetails.buildNumber}}` property

If you want to see all the field available to you use the JSON dump function `{{json buildDetails}}` and you can pick out what you are after, you can use this for any object

**Comment by Shafeeqts89** [comment]
Thanks, @rfennell, Build number property worked.
I have been trying to add some more details to the template like the Description and the Parent UserStory of the associated work item. But not working. below is my template, could you please correct me on what went wrong there?
![image](https://user-images.githubusercontent.com/60779307/99359492-2ba04180-28d5-11eb-828a-c56b514b18e6.png)

**Comment by rfennell** [comment]
By default the task does not look for parent or child workitems, only directly associated work items. You have to tell it to populate the related WI array. Until you do this the template you have above, which looks OK, will not show the parents

The details of all the parameters are in the [documentation](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task), but the two of interest are

> (Advanced) Get Direct Parent and Children for associated work items, defaults to false
> (Advanced) Get All Parents for associated work items, recursing back to workitems with no parents e.g. up to Epics, defaults to false

or in [YAML](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task-YAML)

```
# Generate Release Notes (Crossplatform)
# Description - Generates a release notes file in a format of your choice from the build or release history
- task: XplatGenerateReleaseNotes@3
  inputs: 
     ... other arguments
     getParentsAndChildren: True
     getAllParents: True
```

You should enable one or both of these depending upon the results you want.

Once you enable can see the task building the list via the logs if you set a build variable `system.debug=true`. You should be able to see the adding of the parent and child WIs

**Comment by Shafeeqts89** [comment]
Great!! that works.
Parent is now available in the note. One more help, Is there any way to format the WI description as same as the source? With this, I can finalize the release note.

Orginal:
![image](https://user-images.githubusercontent.com/60779307/99376023-6496e100-28ea-11eb-8967-298b86ecc403.png)

In the release note:
![image](https://user-images.githubusercontent.com/60779307/99375956-4e892080-28ea-11eb-8c27-b95ca009461a.png)

**Comment by rfennell** [comment]
Yes there is, again it is the [documentation](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task)

> Note: if a field contains escaped HTML encode data this can be returned its original format with triple brackets format {{{lookup this.fields 'System.Description'}}}

**Comment by Shafeeqts89** [comment]
Fantastic, thank you @rfennell Now the note looks cool.
It would have been great if I could map the WI and Parent ID to its URL in the release note.

**Comment by rfennell** [comment]
Do you mean you want Hyperlinks in your release notes, that can be done have a look #810 but the core is a template 

```
# Global list of WI ({{workItems.length}})
{{#forEach workItems}}
{{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
  - **Link** [{{this.id]]({{lookup this.fields 'System.url'}}_

{{/forEach}}
```
This generates

> **13** My WI  
>  - Bug
>  - Link [13](https://dummy.local/13)

**Comment by Shafeeqts89** [comment]
seems like wrong sysntax here in the line "- **Link** [{{this.id]]({{lookup this.fields 'System.url'}}_".

**Comment by rfennell** [comment]
Sorry try this

```
{{#forEach workitems}}
    - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}} 
{{/forEach}}
```

The key fact to know is that you can dump all properties of an object like this

```
{{#forEach workitems}}
    - {{json this}}
{{/forEach}}
```

You can then see all the property values available and use them to build the strings you need. Remember you have all [these Handlebars extensions](https://github.com/helpers/handlebars-helpers) to help
