### ISSUE TITLE
The `compareReleaseDetails` becomes the same as `releaseDetails` when manually retrigger the deployment (additional: empty workitems issue)

### ISSUE THREAD

**Issue by LouisSung** [rfennell/AzurePipelines#885]
**Is your feature request related to a problem? Please describe.**
I am now using the [`XplatGenerateReleaseNotes:v3.x`](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes) to generate report, with **Option 1: Generate notes since the last successful release**.
However, I soonly face a problem that when I want to change the note template by `Edit release, change the template format, and Deploy`, the output content gets changed.

This might happens due to the mechanism to find last successful release doesn't exclude the release itself.
For example, in my `Logs > Deployment attempt #1` for the second release:
```md
# Notes for release Foo  
**Release Number**: Foo-2  
**Compared Release Number**: Foo-1  
```
in `Deployment attempt #2`, it becomes:
```md
# Notes for release Foo  
**Release Number**: Foo-2  
**Compared Release Number**: Foo-1  <!--compare to the release itself because it just becomes successful-->
```

**Describe the solution you'd like**
After some quick survey, I found that someone has already mention this issue in #727 .
However, it was treated as running the stage at the first time, but not sure if the same issue for `different attempts` happened because it's a bug, an undefined behavior, or by design?

I think it might be an undefined behavior because releases are usually triggered automatically; however, it's somehow not intuitive if the result cannot be reproduced for different attempts within the same release.

It might not be that easy to change the logic for function [`getLastSuccessfulBuildByStage`](https://github.com/rfennell/AzurePipelines/blob/b33e8f0886494ad81c5a800983759ddf61f37b7b/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts#L750), but I expect it can realize that it's under different attempt instead of other situations like the first release.

Thank you :)

**Comment by rfennell** [comment]
But it is true to say that all the design is based about a build or release being run once, everything else is a edge case.

I need to have a bit of a think about what I can do to address your points.

**Comment by rfennell** [comment]
I have had a bit of think about this, the key fact is that the Microsoft release API will always look for the last successful release to the current stage for it's comparison. When you see 'deployment attempt 1, 2' etc. the compare will always compare against the first successful release to the stage, as you have noted.

I think adding logic to `getLastSuccessfulBuildByStage` to allow it to skip back past previously completed stage eployments would be confusing when, though this can be an issue while creating new pipelines/templates, it is not usually an issue for production usage.

If you are struggling to develop templates, can I suggest [my command line tester](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/V3/testconsole), it is the tool use for all my template development

**Comment by LouisSung** [comment]
Sorry for the late reply due to missing the email notification _(:3

OK, just to make sure things are by designed.
What confuses us is the the same artifact generates different report (both different releases or attempts), but somehow it's the Azure DevOps's concept (based on stage instead of artifact or commit)

**Comment by LouisSung** [comment]
BTW, just for sharing so I am not creating a new issue if not needed

Recently, we solve an issue for getting the [`workItems`](https://github.com/rfennell/AzurePipelines/blob/b33e8f0886494ad81c5a800983759ddf61f37b7b/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts#L605) and [`relatedWorkItems`](https://github.com/rfennell/AzurePipelines/blob/b33e8f0886494ad81c5a800983759ddf61f37b7b/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts#L617) as EMPTY Arrays (`[]`).

By checking the mechanism you acquire an access token ([`getSystemAccessToken()`](https://github.com/rfennell/AzurePipelines/blob/241460827b40e3bea6cc92b714d75dfb5f38314a/Extensions/XplatGenerateReleaseNotes/V3/agentSpecific.ts#L83-L86)), and override it with our own PAT (via [`overridePat`](https://github.com/rfennell/AzurePipelines/blob/ad5d23c33e0d6e462be867f2da823c346bb817ee/Extensions/XplatGenerateReleaseNotes/V3/task.json#L269-L274)), which can get the correct workItems.

We finally find out that the organization setting `Limit job authorization scope to current project for release pipelines
` should be disabled in order for the API to get workItems with the generated OAuth token.

I haven't seem it be documented or be an issue (or I just miss one?)
It spend days to find it out (e.g., make sure it's not because we set the PAT with wrong permission to our on-premise agent), maybe it can be mentioned somewhere (e.g., Readme?)

**Comment by LouisSung** [comment]
Here is the screenshot for the setting, it was enabled by default (this is a new organization I just newly create)
The forth one should be disabled for the plugin `XplatGenerateReleaseNotes` to get the `workItems` in the `release pipelines`, whereas the third one for `non-release pipelines`
![image](https://user-images.githubusercontent.com/37973545/101245689-729d8c00-3749-11eb-92a4-8208f232d126.png)

**Comment by LouisSung** [comment]
Reopen this issue for a few days for the `empty workitems issue` to be seeable, feel free to close it as needed (e.g., after readme updated)

**Comment by rfennell** [comment]
Thanks you for the feedback, I will get the documentation updated.
