### ISSUE TITLE
Filter markdown file to show User Story only

### ISSUE THREAD

**Issue by jayeshmohane** [rfennell/AzurePipelines#889]
Hi,

I am using the Generate Release Notes Build Task (Poweshell) to generate Release Notes from our pipeline. This works fine and I get the release notes page added to our git based Wiki. The only issue with using the below template for the markdown is that it loops through all the Work Items and adds them to the release note:

```
# Release notes for Version $(date).$($build.buildnumber).0
**Build Number**  : $($build.buildnumber) 
**Build Configuration** :  $($build.parameters | ConvertFrom-Json | select -ExpandProperty BuildConfiguration )
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)  
**Source Branch** $($build.sourceBranch)  
  
## Associated work items  
@@WILOOP@@
* #$($widetail.id)
@@WILOOP@@
```

Is there a way or is it possible to filter this down somehow to get User Story work items only? We don't want to see other work items that are linked to the build other than the User Stories and Bugs? Would appreciate if anyone knows a way or another workaround to achieve this.

Many thanks,
Jay

**Comment by rfennell** [comment]
You can enter a filter into the loop, something like. The value after the `WorkItemType=` should match the value of the `$($widetail.fields.'System.WorkItemType')` when you list out all the WI

```
# All the Bugs
@@WILOOP[ALL]:System.WorkItemType=Bug@@
* #$($widetail.id)
@@WILOOP@@

# All the UserStories
@@WILOOP[ALL]:System.WorkItemType=UserStory@@
* #$($widetail.id)
@@WILOOP@@
```

<hr>

As a side note, I see you are using my PowerShell based release Notes tools.  As the release notes state


> # IMPORTANT NOTE
> This PowerShell based task was the first Release Notes Extension I built. It was designed to run only on Windows based Agents and in Builds, as this was all there was at the time. It has since been enhanced, with my own logic to work out associated work items and changesets/commits, to work within releases.
>
>Since creating this extension I have also built a [Node based Release Notes Generator](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) that can run on any agent platform and uses standard Microsoft API calls to work out the associated work items and commits/changeset. Since December 2019 this newer extension supports both Releases and Builds
>
>I STRONGLY RECOMMEND that if you are starting now that you should consider using my newer Node based Release Notes over this extension. This is because of
> - cross platform support
> - use of the same means to find the associated items as the Microsoft UI
> - enhanced workitem filtering
>
> Note: I have no plans to further enhance this extension, and plan to deprecate it at some point in the future to focus on the Node based Release Notes extension, which is more flexible and feature rich.

So, incase you choose to swap to the Node version, the filter you require is something like

```
# All the WI
{{#forEach workItems}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
  - **Tags** {{lookup this.fields 'System.Tags'}}
  - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/forEach}}

# Just the bugs
{{#forEach workItems}}
{{#if (eq (lookup this.fields 'System.WorkItemType') 'Bug')}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
  - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
  - **Tags** {{lookup this.fields 'System.Tags'}}
  - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/if}}
{{/forEach}}

```

**Comment by jayeshmohane** [comment]
Thank you @rfennell for getting back to me so quickly. I tired that method however the Wiki doesn't seem to display the Work Items Correctly:
![image](https://user-images.githubusercontent.com/47626144/100438139-ac132f00-3099-11eb-9f95-feb564cf3f86.png)

**Comment by jayeshmohane** [comment]
I've just seen your other comment about Node based so I will try that and get back you.

**Comment by jayeshmohane** [comment]
@rfennell Just wanted to say Thank You for the Note Based tool; that has done the trick and I am now getting Release Notes generated and filtered for Stories and Bugs

**Comment by jayeshmohane** [comment]
Another quick question sorry, how can I get the build start and finish time using Handlebars? I tried few things but couldn't get the template to work. And I assume whatever you provide will also be the same for the release pipeline?

**Comment by rfennell** [comment]
For any question like this the first step is to see what data you have available. You have a number of of options to help here

- Inside a template use  `{{json builddetails}}` (or any other object name) to dump the contents of the object 
- Set the task parameter `dumpPayloadToConsole=false` - the payload is logged out to the build log - but this can make the UI slow to respond, so I don't use this much
- Set the task parameters `umpPayloadToFile=true` and `dumpPayloadFileName=payload.json` - remember you do need to include in a folder path in the filename  to a location you have access to, maybe make the dump part of the build artefacts?

Once you have the object contents you can look for fields that contain what you need, ones of interest in this case are probably

- buildDetails.queueTime
- buildDetails.startTime
- buildDetails.finishTime

**Comment by jayeshmohane** [comment]
Awesome - thank you for this. I will now close this issue. Thanks again for creating this great tool :D
