### ISSUE TITLE
Suppressing duplicate parent work items

### ISSUE THREAD

**Issue by smholvoet** [rfennell/AzurePipelines#890]
How can I suppress duplicate parent work items? Let's say I have 3 linked work items which all have the same parent work item:

![image](https://user-images.githubusercontent.com/13507392/100439638-129d4a80-30a4-11eb-9377-7f1a2c93de15.png)

It finds the same parent 3 times over, which results in:

![image](https://user-images.githubusercontent.com/13507392/100439385-c6520a80-30a3-11eb-92bf-bb05864a1725.png)

My handlebars template looks like this:

```handlebars
#### 🐞 Bugs
{{#forEach workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
#{{../id}}  
{{/if}}
{{/with}}
{{/forEach}}

#### 🔨 Tasks
{{#forEach workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Task')}}
#{{../id}}  
{{/if}}
{{/with}}
{{/forEach}}

 #### 🔗 Parents 
{{#forEach this.workItems}}
{{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
#{{this.id}}  
{{/with}}
{{/if}}
{{/forEach}} 
{{/forEach}}
```

**Comment by rfennell** [comment]
A few ideas....

1. You could nest your foreach blocks so you see a drill down

- foreach bug
   - foreach child - will get the tasks
   - foreach parent - will get the parents WI

Not really a solution to the problem you ask, but will make the duplications less confusing

2. You could just loop across the {{#forEach this.relations}}, a WI only appears once in this list, so you look for ones that have children or even specific children as defined by the list {{#forEach this.workItems}} - this might need option 3

3. Or you could write a custom Handlebars extension to keep a track of the parent WI listed so they are only shown one.

**Comment by smholvoet** [comment]
@rfennell Thanks for your suggestions 💪

I managed to solve this by using the [`return_parents_only`](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/return_parents_only.js) custom Handlebars extension.

This somehow seems to work as the function in itself checks for duplicate parent items:
```js
...
if (!foundList.includes(parent)) {
  foundList.push(parent);
  ret += block.fn(parent);
}
...
```

We only link _Tasks_ to our PR's, which will either have a _Bug_ or a _User Story_ as their respective parent WI... so the following template works just fine and gets rid of any duplicate parent WI's:

```handlebars
#### 🐞 Bugs
{{#forEach workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
#{{../id}}  
{{/if}}
{{/with}}
{{/forEach}}

#### 🔨 Tasks
{{#forEach workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Task')}}
#{{../id}}  
{{/if}}
{{/with}}
{{/forEach}}


#### 🔗 Parent user stories

{{#return_parents_only this.workItems this.relatedWorkItems}}
#{{this.id}}
{{/return_parents_only}} 
```

Result:
![image](https://user-images.githubusercontent.com/13507392/106026371-0c3e4580-60ca-11eb-910f-2071b2bdda04.png)

**Comment by luisen22** [comment]
Good approach, how can I add this "Handlebars extension"?

**Comment by luisen22** [comment]
Good approach, do you know the syntaxis for a release pipeline?

**Comment by rfennell** [comment]
See the [wiki](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) for details, but the quick answer is you can either pass in the extension code as an inline parameter

```
- task: XplatGenerateReleaseNotes@3
   inputs:
      outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
      # all the other parameters required
      customHandlebarsExtensionCode: |
         module.exports = {foo() {
            return 'Returns foo';
         }};
```
or the custom extension can be passed as file

```
- task: XplatGenerateReleaseNotes@3
   inputs:
      outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
      # all the other parameters required
      customHandlebarsExtensionFile: $(System.SourceDirectory)\customcode.js
```

**Comment by luisen22** [comment]
> See the [wiki](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) for details, but the quick answer is you can either pass in the extension code as an inline parameter
> 
> ```
> - task: XplatGenerateReleaseNotes@3
>    inputs:
>       outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
>       # all the other parameters required
>       customHandlebarsExtensionCode: |
>          module.exports = {foo() {
>             return 'Returns foo';
>          }};
> ```
> 
> or the custom extension can be passed as file
> 
> ```
> - task: XplatGenerateReleaseNotes@3
>    inputs:
>       outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
>       # all the other parameters required
>       customHandlebarsExtensionFile: $(System.SourceDirectory)\customcode.js
> ```

Thank you

**Comment by luisen22** [comment]
**In case you need to use tags with work item parents**

{{#return_parents_only this.workItems this.relatedWorkItems}}
{{#if (contains (lookup this.fields 'System.Tags') 'Tag#1')}}
  - #{{this.id}}
{{/if}}
{{/return_parents_only}}

**Comment by JaydeepUniverse** [comment]
@smholvoet @rfennell I am following same way to segregate WI type wise as below

```
#### 🐞 Bugs
{{#forEach workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
#{{../id}}  
{{/if}}
{{/with}}
{{/forEach}}
```
However apart from only WI ID, I need to have other details as well like Assigned to, Tags, Parents in table format

I tried as below but AssignedTo is not working, so just want help here

```
#### 🐞 Bugs
| WI ID | Tags | Assigned To |
|--|--|--|
{{#forEach this.workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
| #{{../id}} | {{'System.Tags'}} | {{#with (lookup 'System.AssignedTo')}} {{displayName}} {{/with}} |
{{/if}}
{{/with}}
{{/forEach}}
```
```
{{'System.AssignedTo.displayName'}} -------- it worked but didnt get output
{{#with System.AssignedTo}} {{displayName}} {{/with}} -------- it worked but didnt get output
{{#with (lookup 'System.AssignedTo')}} {{displayName}} {{/with}} -------- didnt work
{{#with 'System.AssignedTo'}} {{displayName}} {{/with}} -------- it worked but didnt get output
{{System.AssignedTo}} {{displayName}} -------- it worked but didnt get output
```
And how can I use parent in same table?

```
#### 🐞 Bugs
| WI ID | Tags | Assigned To | Parent |
|--|--|--|--|
{{#forEach this.workItems}}
{{#with fields}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
| #{{../id}} | {{'System.Tags'}} | {{#with (lookup 'System.AssignedTo')}} {{displayName}} {{/with}} | {{#return_parents_only this.workItems this.relatedWorkItems}} #{{this.id}} {{/return_parents_only}}  |
{{/if}}
{{/with}}
{{/forEach}}
```

Please advise. Thanks.

**Comment by rfennell** [comment]
> I have answered this here, but I would usually recommend opening a new issue or discussion for a new question

Your basic idea for a table is correct, it is just the loop mechanism that is wrong. I would not use the outer `{{#with}}` wrapper

```
#### 🐞 Bugs
| WI ID | Tags | Assigned To |
|--|--|--|
{{#forEach this.workItems}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
| #{{this.id}} |  {{lookup this.fields 'System.Tags'}} |  {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}} |
{{/if}}
{{/forEach}}

```

As to the parent lookup, it will be something like

```
#### 🐞 Bugs
| WI ID | Tags | Assigned To | Parent |
|--|--|--|--|
{{#forEach this.workItems}}
{{#if (eq (get 'System.WorkItemType' this) 'Bug')}}
| #{{this.id}} |  {{lookup this.fields 'System.Tags'}} |  {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}} |  {{#forEach this.relations}}
{{#if (contains this.attributes.name 'Parent')}}
{{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
      - {{this.id}} - {{lookup this.fields 'System.Title'}}
      {{#forEach this.relations}}
      {{#if (contains this.attributes.name 'Parent')}}
      {{#with (lookup_a_work_item ../../../../relatedWorkItems  this.url)}}
         - {{this.id}} - {{lookup this.fields 'System.Title'}}
      {{/with}}
      {{/if}}
      {{/forEach}}
{{/with}}
{{/if}}
{{/forEach}}
  |
{{/if}}
{{/forEach}}

```
