### ISSUE TITLE
How to fetch the details of release note from Release Info section?

### ISSUE THREAD

**Issue by sahildavawala** [rfennell/AzurePipelines#895]
**Describe the bug**
How to fetch the details of release note from Release Info section?
I want to fetch the information from the Work Items into a Release where I am using the task 'Generate Release Notes for Pipeline Builds or Releases' for generating the release notes.

**To Reproduce**
1. Go to any Work Item
2. Add some data in the Release Note section under the tab Release Info
3. Go to Azure DevOps Release
4. Add a task "Generate Release Notes for Pipeline Builds or Releases" in the release.
5. Try to execute the same and it will not fetch the data for tags like $($widetails.fields.'System.AddtoReleasenotes') & $($widetail.fields.'System.DetailsforReleaseNote')

**Expected behavior**
Need the exact tag for fetching the details from Work Items.

**Screenshots**
Attached a couple of screenshots for the same.
![image](https://user-images.githubusercontent.com/38693613/100836566-8620cc80-3495-11eb-8112-d804e2880d3e.png)
![image](https://user-images.githubusercontent.com/38693613/100836672-b36d7a80-3495-11eb-8a9d-71101ab17a38.png)

**What is the issue see:**
 - Azure DevOps Services

**Additional context**

**Comment by rfennell** [comment]
The tags are not stored in named fields, but as a comma separated list in the field `$($widetails.fields.'System.Tags')`.


> # IMPORTANT NOTE
> This PowerShell based task was the first Release Notes Extension I built. It was designed to run only on Windows based Agents and in Builds, as this was all there was at the time. It has since been enhanced, with my own logic to work out associated work items and changesets/commits, to work within releases.
>
>Since creating this extension I have also built a [Node based Release Notes Generator](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) that can run on any agent platform and uses standard Microsoft API calls to work out the associated work items and commits/changeset. Since December 2019 this newer extension supports both Releases and Builds
>
>I STRONGLY RECOMMEND that if you are starting now that you should consider using my newer Node based Release Notes over this extension. This is because of
> - cross platform support
> - use of the same means to find the associated items as the Microsoft UI
> - enhanced workitem filtering
>
> Note: I have no plans to further enhance this extension, and plan to deprecate it at some point in the future to focus on the Node based Release Notes extension, which is more flexible and feature rich.

So, incase you choose to swap to the Node version, the filter you require is something like

**Comment by sahildavawala** [comment]
@rfennell ,
Thanks for the updates on Release Notes Extension. I got the point that the existing one will get deprecated sometime in future and the new one which you have shared will be in working state.

But my concern is whether is there a way or possibility in which I get to fetch the details or data from _Work Items >> Release Info_ tab where my actual Release Notes related information is available? **Is there a tag which can help me here?** 

As per the current setup I am getting the list of Work Items, Title of the WI, Description, ID, etc. but I am more interested towards the details of Release Note to get auto fetched from the WI itself.

Kindly let me know if you are familiar with such tags then it can help me in achieving my task.

**Comment by rfennell** [comment]
I don't think those fields are available as part of the release or work item objects. There is no quick way to check with the PowerShell based task. However if you use the Node based one you can dump the contents of any of the returned objects to see what fields are available. You have a number of of options to help here

- Inside a template use `{{json builddetails}}` (or any other object name) to dump the contents of the object
- Set the task parameter `dumpPayloadToConsole=false` - the payload is logged out to the build log - but this can make the UI slow to respond, so I don't use this much
- Set the task parameters `dumpPayloadToFile=true` and `dumpPayloadFileName=payload.json` - remember you do need to include in a folder path in the filename to a location you have access to, maybe make the dump part of the build artefacts?

So I would dump the object out and look for the field that contains the information you are after. Hopefully it is present

**Comment by sahildavawala** [comment]
@rfennell ,

Thanks for the updates. I migrated to this new plugin "Generate Release Notes (Crossplatform)" and did some modifications in my Azure release pipeline.
Unfortunately I am unable to get any data by using the Handlebar template provided in https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes&ssr=false#overview

I am not sure what is wrong here but it doesn't fetch any data in my .md or .htm file which is set as the output.

Looking forward for some suggestions or help, appreciate it!

**Comment by rfennell** [comment]
A few things...

- There are sample templates [here](https://github.com/rfennell/AzurePipelines/tree/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203)
- If you run your pipeline with diagnostics enabled, the check box on the run pipeline dialog, or set the variable `system.debug=true` you can see all the steps the task has taken. This will show the artifact discovery
- If you want to test a template outside of the pipeline, have a look [here](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/V3/testconsole) 

If you still have issue upload the log file and I will have a look

**Comment by sahildavawala** [comment]
@rfennell ,

It is still not working. I am attaching the log file for your reference. 
[Generate_RS_logs.txt](https://github.com/rfennell/AzurePipelines/files/5635976/Generate_RS_logs.txt)

**Comment by rfennell** [comment]
The log shows that the task has found the build, but there have been no changes e.g. WI, CS or PRs since the last successful build

```
2020-12-03T12:17:45.3261466Z Total Builds: [1]
2020-12-03T12:17:45.3318064Z Total Commits: [0]
2020-12-03T12:17:45.3319042Z Total Workitems: [0]
2020-12-03T12:17:45.3321734Z Total Related Workitems (Parent/Children): [0]
2020-12-03T12:17:45.3349184Z Total Release Tests: [0]
2020-12-03T12:17:45.3366382Z Total Tests: [0]
2020-12-03T12:17:45.3373898Z Total Pull Requests: [0]
2020-12-03T12:17:45.3378526Z Total Indirect Pull Requests: [0]
```

This is by design. The release notes are what has changed since the last successful build to that branch/stage.

As the [WIKI](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) details

| Option | Multi Stage YAML | Classic Build/Release |
|-|-|-|
| Generate notes for just the current build | Requires `checkstages=false` parameter| Run inside the build |
| Generate notes since the last successful release.  <br>Option 1. Place the task in a stage that is only run when you wish to generate release notes. Usually this will be guarded by branch based filters or manual approvals.  |  Requires `checkstages=true` parameter | Run inside the release. Supported and you can override the stage name used for comparison using the `overrideStageName` parameter
| Generate notes since the last successful release.  <br>Option 2. Set the task to look back for the last successful build that has a given tag |  Requires `checkstages=true` and the `tags` parameters| Not supported 
| Generate notes since the last successful release.  <br>Option 3. Override the build that the task uses for comparison with a fixed value |  Requires `checkstages=true` and the `overrideBuildReleaseId` parameters | Run inside the release. Requires the `overrideBuildReleaseId` parameter

So if you want to generate changes since some fixed release you can use the `overrideBuildReleaseId`  option

**Comment by sahildavawala** [comment]
I think that's not the case because the same logic which is part of https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task&ssr=false#overview gives the output and details of all the work items.

Anyways this might not help us in achieving the exact requirement of release note details so will think some other way.

Thanks for all the support and assistance.

**Comment by rfennell** [comment]
The old PowerShell version does not make use of the current standard Microsoft APIs to find associated items. It predates the API and uses some very 'interesting' home grown logic - this is why it going to be deprecated. It's behaviour is confusing

The Node based task should list the same associated items as the Microsoft UI
