### ISSUE TITLE
Get work items associated with other repo's

### ISSUE THREAD

**Issue by v-sammy** [rfennell/AzurePipelines#899]
I'm using the 'Generate release notes (Crossplatform)' task in our pipeline, but can't seem to figure out how to get the associated work items processed.

We have one pipeline that check's out code from different repo's (frontend, backend, ...), builds and deploys to different environments.
However, work items associated with those other repo's don't get picked up by the task. In the provided example, only 2 of the three associated work items are picked up.

This is how it looks in the Azure Devops GUI:
![image](https://user-images.githubusercontent.com/75687143/101508504-0c4a8080-3978-11eb-9f74-7d58055f5bf4.png)

![image](https://user-images.githubusercontent.com/75687143/101508469-00f75500-3978-11eb-9e85-55fea2cf9d48.png)

**Comment by rfennell** [comment]
The best first step is to run the pipeline with either

- The diagnostics checkbox ticked
- Set a pipeline variable `system.debug=true` 

You will then get detailed logs of the process the task has used to find associated items, that might explain what you are seeing

**Comment by v-sammy** [comment]
Thanks for the super fast reply 👍 
I see only the commits on the repo where the YAML pipeline is committed are evaluated, not the other repo's used in the pipeline.
Is there a combination of parameters that can be used to change this behavior?

**Comment by rfennell** [comment]
No my task just calls the Azure DevOps REST API call for 'the wi/commits between build XXX and YYY'. So that call will only get the directly associated items.
