### ISSUE TITLE
PullRequest description is truncated

### ISSUE THREAD

**Issue by AlexTheBold** [rfennell/AzurePipelines#915]
Hi 
I use the ReleaseNoteGenerator V3 on Azure DevOps Services 

I have some Pull request descriptions which are over than 400 characters. When I retrieve them by ReleaseNoteGenerator, the description is truncated at 418 characters length.

To reproduce, simply put a big description in  a Pull Request, and then let generate release note whit this task:
``` yaml
- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: 'foo.md'
    templateLocation: InLine
    inlinetemplate: '{{releaseDetails.id}}'
    dumpPayloadToFile: true
    dumpPayloadFileName: '$(System.ArtifactsDirectory)/templateData.json)'
    showOnlyPrimary: false
    checkStage: true
```

When I read the templateData file, the description of my Pull request is truncated

The Pull request description : 
>- Ajout du composant accordéon :
>```html
><eic-accordion id="accordion-utilisation" expanderPosition="Left">
>    <eic-accordion-item [contentTemplate]="contentTemplate" [headerTemplate]="headerTemplate" [expanded]="true">
>        <ng-template #headerTemplate>ASP.NET</ng-template>
>        <ng-template #contentTemplate>
>            <div>Microsoft ASP.NET is a set of technologies in the Microsoft .NET Framework for building Web
>                applications and XML Web
>                services. ASP.NET pages execute on the server and generate markup such as HTML, WML, or XML that is sent
>                to a desktop
>                or mobile browser. ASP.NET pages use a compiled,event-driven programming model that improves performance
>               and enables
>                the separation of application logic and user interface.</div>
>        </ng-template>
>    </eic-accordion-item>
>    <eic-accordion-item [contentTemplate]="contentTemplate2" header="ASP.NET MVC">
>        <ng-template #contentTemplate2>
>            <div>The Model-View-Controller (MVC) architectural pattern separates an application into three main
>                components: the model,
>                the view, and the controller. The ASP.NET MVC framework provides an alternative to the ASP.NET Web Forms
>                pattern for
>                creating Web applications. The ASP.NET MVC framework is a lightweight, highly testable presentation
>                framework that
>                (as with Web Forms-based applications) is integrated with existing ASP.NET features, such as master
>                pages and membership-based
>                authentication.
>            </div>
>        </ng-template>
>    </eic-accordion-item>
>    <eic-accordion-item [contentTemplate]="contentTemplate2" header="Angular" [disabled]="true">
>        <ng-template #contentTemplate2>
>            <div>Disabled content</div>
>        </ng-template>
>    </eic-accordion-item>
>    <eic-accordion-item [contentTemplate]="contentTemplate2" header="React" [visible]="false">
>        <ng-template #contentTemplate2>
>            <div>invisible content</div>
>        </ng-template>
>    </eic-accordion-item>
>    <eic-accordion-item header="NET .CORE">        
>    </eic-accordion-item>
></eic-accordion>
>```
>
>- Correction id à undefined

And the Pullrequest part of the templateData.json. You can see the full message in mergeCommitMessage, but not in the description
>  "pullRequests": [
>    {
>      "pullRequestId": 8077,
>      "codeReviewId": 8077,
>      "status": 3,
>      "createdBy": {xxxxx},
>      "creationDate": "2020-12-21T22:51:55.442Z",
>      "closedDate": "2020-12-23T06:11:02.616Z",
>      "title": "composant accordÃ©on + correction id Ã  undefined",
>      "description": "- Ajout du composant accordÃ©on :\n```html\n<eic-accordion id=\"accordion-utilisation\" expanderPosition=\"Left\">\n    <eic-accordion-item [contentTemplate]=\"contentTemplate\" [headerTemplate]=\"headerTemplate\" [expanded]=\"true\">\n        <ng-template #headerTemplate>ASP.NET</ng-template>\n        <ng-template #contentTemplate>\n            <div>Microsoft ASP.NET is a set of technologies in the Microsoft .NET",
>      "sourceRefName": "refs/heads/***s/xxx/composant-accordeon",
>      "targetRefName": "refs/heads/master",
>      "mergeStatus": 3,
>      "isDraft": false,
>      "mergeId": "58023dde-c8d3-40b2-912d-12a49dca8ab8",
>      "lastMergeSourceCommit": {
>        "commitId": "b6c03a217d06e434f6e0d3d1b252a0908a3a653e",
>        "url": "https://dev.azure.com/xxxx"
>      },
>      "lastMergeTargetCommit": {
>        "commitId": "7d9299a5a7f56187cb73c091cd2ea354c2a6ef9b",
>        "url": "https://dev.azure.com/xxxx"
>      },
>      "lastMergeCommit": {
>        "commitId": "ed88833f100eb6e4ee94c565b57db8365a4500c8",
>        "url": "https://dev.azure.com/xxxx"
>      },
>      "reviewers": [
>      ],
>      "completionOptions": {
>        "mergeCommitMessage": "Merged PR 8077: composant accordÃ©on + correction id Ã  undefined\n\n- Ajout du composant accordÃ©on :\n```html\n<eic-accordion id=\"accordion-utilisation\" expanderPosition=\"Left\">\n    <eic-accordion-item [contentTemplate]=\"contentTemplate\" [headerTemplate]=\"headerTemplate\" [expanded]=\"true\">\n        <ng-template #headerTemplate>ASP.NET</ng-template>\n        <ng-template #contentTemplate>\n            <div>Microsoft ASP.NET is a set of technologies in the Microsoft .NET Framework for building Web\n                applications and XML Web\n                services. ASP.NET pages execute on the server and generate markup such as HTML, WML, or XML that is sent\n                to a desktop\n                or mobile browser. ASP.NET pages use a compiled,event-driven programming model that improves performance\n                and enables\n                the separation of application logic and *** interface.</div>\n        </ng-template>\n    </eic-accordion-item>\n    <eic-accordion-item [contentTemplate]=\"contentTemplate2\" header=\"ASP.NET MVC\">\n        <ng-template #contentTemplate2>\n            <div>The Model-View-Controller (MVC) architectural pattern separates an application into three main\n                components: the model,\n                the view, and the controller. The ASP.NET MVC framework provides an alternative to the ASP.NET Web Forms\n                pattern for\n                creating Web applications. The ASP.NET MVC framework is a lightweight, highly testable presentation\n                framework that\n                (as with Web Forms-based applications) is integrated with existing ASP.NET features, such as master\n                pages and membership-based\n                authentication.\n            </div>\n        </ng-template>\n    </eic-accordion-item>\n    <eic-accordion-item [contentTemplate]=\"contentTemplate2\" header=\"Angular\" [disabled]=\"true\">\n        <ng-template #contentTemplate2>\n            <div>Disabled content</div>\n        </ng-template>\n    </eic-accordion-item>\n    <eic-accordion-item [contentTemplate]=\"contentTemplate2\" header=\"React\" [visible]=\"false\">\n        <ng-template #contentTemplate2>\n            <div>invisible content</div>\n        </ng-template>\n    </eic-accordion-item>\n    <eic-accordion-item header=\"NET .CORE\">        \n    </eic-accordion-item>\n</eic-accordion>\n```\n\n- Correction id Ã  undefined\n\nRelated work items: #7771",
>        "squashMerge": true,
>        "mergeStrategy": 2,
>        "autoCompleteIgnoreConfigIds": []
>      },
>      "supportsIterations": true,
>      "completionQueueTime": "2020-12-23T06:11:00.739Z",
>      "labels": [],
>      "associatedWorkitems": [
>        {
>          "id": 7771,
>          "url": "https://dev.azure.com/xxxx"
>        }
>      ],
>    }
>  ],

**Comment by rfennell** [comment]
All I do for pull requests is call the API and return the results, I do no special processing so if the contents is being truncated I fear there is little I can do. 

Unlike the the commit API there is no flag I can see on the PR API to tell me the message/description is truncated so I know to make an extra call.

I wonder if it is related to this [issue over PR templates size](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6870)

**Comment by AlexTheBold** [comment]
You are right. I just try this api. On the pull request with the big description, the description is truncated, but not the completionOptions.mergeCommitMessage, wich is bigger. I write a post on Microsoft site [https://developercommunity.visualstudio.com/content/problem/1295365/rest-api-pullrequests-truncated-description.html](https://developercommunity.visualstudio.com/content/problem/1295365/rest-api-pullrequests-truncated-description.html)
