### ISSUE TITLE
Error during the export

### ISSUE THREAD

**Issue by yfrindel** [rfennell/AzurePipelines#925]
Hello,

When I try to export a wiki, I have the following error : 

![image](https://user-images.githubusercontent.com/22955005/103903497-3ff60300-50fc-11eb-9079-a131ea566fda.png)

Do you have an idea why?

Other question, Is it possible to export a specific folder of the wiki? (because I just need to export a part of the wiki)

Thx

**Comment by rfennell** [comment]
That is an issue with the tool MaxMelcher/AzureDevOps.WikiPDFExport my task wrappers, you  will need to log an issue in that [projects repo](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues).

You can run the command locally on your PC to try to diagnose the issues, usage of the tool is detailed [here](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport)
