### ISSUE TITLE
Add ability to export only part of a WIKI as a PDF

### ISSUE THREAD

**Issue by rfennell** [rfennell/AzurePipelines#926]
We then, I will convert this discussion to be an issue and look to make the change

_Originally posted by @rfennell in https://github.com/rfennell/AzurePipelines/discussions/924#discussioncomment-267219_

**Comment by rfennell** [comment]
Shipped as 1.4.16

**Comment by yfrindel** [comment]
I have an additional question please. Could you tell me if it's possible to add the page number for each page? (for example page 2/10)

**Comment by rfennell** [comment]
This would have to be implemented by the underlying tool [MaxMelcher/AzureDevOps.WikiPDFExport](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport) which does all the export work. My task just passes parameters to this.

I have checked on that tool's [repo](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues) for any information on page numbering and can find nothing, so I suspect the answer to your question is no, but you could raise the question on Max's repo.

The closest was that you can enable new page after each file and set fixed footer content. Both of these features are set with command line parameters. If you wished to use these they can be passed to the tool from my tasks using the `ExtraParameters` property.

**Comment by yfrindel** [comment]
No, that's fine. It's possible with the WIKIPDFExport Parameters
Thx

**Comment by rfennell** [comment]
Oh is it, that's interesting, if you get it working can you provide a sample of the extra parameters so I can add them to the task WIKI

**Comment by yfrindel** [comment]
that's my parameters : --attachments-path $(System.DefaultWorkingDirectory)\repo\.attachments --footer-right [page]/[topage] --footer-center [date] --header-center "Build process"

![image](https://user-images.githubusercontent.com/22955005/104300448-c88eed80-54c6-11eb-937b-0a6580d32498.png)

based on this page : https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport 

![image](https://user-images.githubusercontent.com/22955005/104300195-72ba4580-54c6-11eb-862b-adf7396754bc.png)
