### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by yfrindel** [rfennell/AzurePipelines#930]
All the images with a blank in the name file are missing : 

![image](https://user-images.githubusercontent.com/22955005/104298749-a5633e80-54c4-11eb-9960-08368fcad7b3.png)

![image](https://user-images.githubusercontent.com/22955005/104298916-d5aadd00-54c4-11eb-922e-e694800fc490.png)

**Comment by rfennell** [comment]
This will be down to the underlying tool, I can see this has already been logged in that tool's repo [MaxMelcher/AzureDevOps.WikiPDFExport as #38](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues/38). 

Hence, there is no immediate action I can take beyond the obvious of suggesting not using space in image names.

**Comment by yfrindel** [comment]
"This will be down to the underlying tool, I can see this has already been logged in that tool's repo" => that's my post ;)

**Comment by kbilkhoo** [comment]
I also have issues when viewing images in PDF, have logged this [here](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues/42)
