### ISSUE TITLE
Release based release note generation is not getting associated work items (V3)

### ISSUE THREAD

**Issue by sdzunenko** [rfennell/AzurePipelines#977]
Hi!

I am struggling with the issue to obtain list of the associated WI during release deployment.
It looks for me that everything I do is correct, so kindly ask to support on this.

We have Azure DevOps used as our CI/CD system and a bug tracker. 
We use GitHub as repository. 
Association between commits and work items implemented by the prefix in commit messages (like "AB#XXXX ..." where XXX is the number of the work item.
It is reflected on the UI as expected:
![image](https://user-images.githubusercontent.com/57891762/111383650-2d2a1c80-86b1-11eb-9d0e-514682dd795b.png)

According to the debug tool provided in current repo it is fetching correct build number, able to obtain the test results, but not commits or work items.
This is output from the tool:

```
Loading settings from release-settings.json
Creating Azure DevOps API connections for https://dev.azure.com/{MyCompanyName} with 'allowRetries' set to 'true' and 'maxRetries' count to '3'
Creating the credential handler using override PAT (suitable for local testing or if the OAUTH token cannot be used)
Getting the current release details
Show associated items for primary artifact only is set to false
Getting the Environment Id
Identified [full] as having id [41]
Found 8 successful releases
Finding the last successful release Release-1145
Getting all artifacts in the current release...
Found 1 artifacts for current release
Getting all artifacts in the most recent successful release [Release-1145]...
Found 1 artifacts for most recent successful release
Looking at artifact [ADF]
Artifact type [Build]
Build Definition ID [39]
Build Number: [20210316.6]
Is Primary: [true]
Looking for the [ADF] in the most recent successful release [Release-1145]
Found artifact [ADF] with build number [20210311.2] in release [Release-1145]
Checking what commits and workitems have changed from [20210311.2][ID 9126] => [20210316.6] [ID 9284]
Using workaround for build API limitation (see issue #349)
Getting test associated with the latest build [9284]
##vso[task.debug]Found 473 test results associated with the build
##vso[task.debug]Get batch of tests [0] - [1000] for test run 43766
##vso[task.debug]Adding 182 tests
...................
##vso[task.debug]The updated global test array contains 473 items
Adding the build [9284] and its association to the unified results object
Get details of [0] WIs
Detected 0 commits/changesets and 0 workitems between the current build and the last successful one
Detected 473 tests associated within the current build.

##vso[task.debug]No tests associated with release 2564 environment Web app (dev slot)
##vso[task.debug]No tests associated with release 2564 environment Full
##vso[task.debug]The global test array contains 473 items
##vso[task.debug]The updated global test array contains 473 items
Removing duplicate Commits from master list
Removing duplicate WorkItems from master list
Expanding the truncated commit messages...
Expanded truncated commit messages 0
Get details of [0] WIs
Getting direct parents and children of WorkItems
Getting all parents of known WorkItems
Added 0 parent WI to the list of direct relations
Sorting WI by type then id
##vso[task.debug]Getting the details of build 39 from default project
**Could not get details of Trigger PR an error was seen: TypeError: Cannot read property 'repository' of null**
```

And the results in output file is following:

```
# Notes for release  HCM Development Pipeline    
**Release Number**  : Release-1159
**Release completed** : Tue Mar 16 2021 18:44:48 GMT+0200 (GMT+02:00)     
**Build Number**: 
**Compared Release Number**  : Release-1145    
**Build Trigger PR Number**:  

# Associated Pull Requests (0)

# Builds with associated WI/CS (1)
## Builds 
-  Build 20210316.6

# Global list of WI (0)

# Global list of WI with parents and children

# Global list of CS (0)


# Global list of test (473)

// Results omitted for clearness 
```
So for me it looks like that both builds and releases setup correctly, but for some reason extension is not fetching commits properly.

Any ideas or suggestions?

Thanks,
Sergey

**Comment by rfennell** [comment]
There is currently no support for association of Azure DevOps WI to GitHub commits using the #AZ123 method.

I will have investigate what is possible via the API

**Comment by sdzunenko** [comment]
I also debug a bit extension itself and see those request return nothing for me:
`https://dev.azure.com/Company/Project_GUID/_apis/build/workitems?fromBuildId=Prev_Nimber&toBuildId=Next_Number`

Not sure how it's reflected on the UI in that case

**Comment by rfennell** [comment]
The documentation does not discuss gettings WI associated via the `AB#123` method. I have reached out to the Azure DevOps product group to see how you are meant to retrieve this information (if you even can).

It will require a modification to task to get the extra data

**Comment by sdzunenko** [comment]
I make some additional test - I do not see difference here if commit was added manually to WI via interface or via `AB#nnnn` method. Looks like Azure DevOps subscribed to the repo and create those links manual.

See an example:

![image](https://user-images.githubusercontent.com/57891762/111468583-648ade80-872e-11eb-9ab9-2729e0f4e066.png)

AB#5884 was added manually, AB#5885 - dynamically, via patterned commit message.

This is described in [documentation](https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-mention-to-link-from-github-to-azure-boards-work-items).

Also I am able to see both work items and commits in the triggered build
![image](https://user-images.githubusercontent.com/57891762/111470113-2989aa80-8730-11eb-875c-34472f2db207.png)

But also have no results coming from api:
![image](https://user-images.githubusercontent.com/57891762/111470342-6c4b8280-8730-11eb-8456-bf3c62c48032.png)


I do not think it is related to the current project itself, looks lie something wrong with Azure DevOps.
I propose to keep those bug to be open until I come with solution. Promise that will keep you informed 😄

Also if somebody can point me to correct direction - appreciate this.

**Comment by rfennell** [comment]
I have been unable to find an Azure DevOps API call to return the WI associated via AB#123 syle GitHub/Azure DevOps link as yet. I will keep looking, but it does not appear too promising as yet.

**Comment by rfennell** [comment]
I have logged this issue with Mircosoft https://developercommunity.visualstudio.com/t/What-REST-API-call-should-I-used-to-set/1382081

**Comment by rfennell** [comment]
I can't do anything to solve this problem. The information is not available via the published Azure DevOps REST API

See the [issue I raised with Microsoft](https://developercommunity.visualstudio.com/t/What-REST-API-call-should-I-used-to-set/1382081) for details
