### ISSUE TITLE
ChangeSet URL/Link of Release notes broken due to DevOps Project Name with a space

### ISSUE THREAD

**Issue by josalama** [rfennell/AzurePipelines#980]
Hi!

My customer is implementing the Generate Release notes + Wiki File updater extensions functionality in a D365 FnO project, We find an issue at the Wiki Release notes with the URL and/or Hyperlink related to the **ChangeSets**. 

The  DevOps Project name "CONTOSO CARIBE" has an space character that the URL bring as an blank space and not as an url encoding "%20"

In the following image we can see the url that is generated once the release notes is completed.

![image](https://user-images.githubusercontent.com/40414971/111536444-3f02d280-8738-11eb-8656-4b15f2ed46d4.png)

In the following image the url adjusted manually to complete the URL completed and the changeSets correctly hyperlinked

![image](https://user-images.githubusercontent.com/40414971/111536728-a02aa600-8738-11eb-936c-03d58a8707bf.png)

Originals URLS

https://grwit.visualstudio.com/CONTOSO CARIBE/_versionControl/changeset/23271)**

https://grwit.visualstudio.com/CONTOSO CARIBE/_versionControl/changeset/23269)**

As should be the URLS

https://grwit.visualstudio.com/CONTOSO%20CARIBE/_versionControl/changeset/23271)**

https://grwit.visualstudio.com/CONTOSO%20**CARIBE/_versionControl/changeset/23269)**

**Comment by rfennell** [comment]
This is just the reason hate spaces in file paths or URLs.

This type of problem could pop up anywhere in the returned object model. I don't want to be checking all the properties, so I think the best bet is to fix it in the template, only when there is a problem property

You need to use the template block similar to

`{{replace this.url "" "%20"}}`

**Comment by josalama** [comment]
Thank you for your response Richard. I agree, also hate spaces in critical names, in my customer case the DevOps project name..

I have tried to use your recommendation in several ways with not success , i think due to I am not much familiar with PowerShell...

below is the fragment of the template that we are using with thethe ChangeSet url reference ($($csdetail._links.web.href))...Could you please help me to guide how to insert the replace block recommended in this part of the template code?  ( {{replace this.url " " "%20"}} )

@@WILOOP@@
>>## **Last Added Changesets**
@@CSLOOP@@
>>**Changeset ID [$($csdetail.changesetid)$($csdetail.commitid)]($($csdetail._links.web.href))**
>>**Comment** : _$($csdetail.comment)_
>>
@@CSLOOP@@

Many thanks

**Comment by rfennell** [comment]
Sorry, I thought you were using the newer [Cross Platform version that uses Handlebars based templates](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes). I would recommend that version as it is much more flexible. Also, the plan is to deprecate the PowerShell at some point in the next few months 

However, that said, the PowerShell equivalent will something like

```
Changeset ID [$($csdetail.changesetid)$($csdetail.commitid)] ($($csdetail._links.web.href.Replace(" ","")))**
```

**Comment by josalama** [comment]
Thank you Richard!!!

It works!!!

I will recommend my team and customer to use the newer   Cross Platform version that uses Handlebars based templates.

Issue closed!
