### ISSUE TITLE
XplatGenerateReleaseNotes fails to parse handlebars template but task still succeeds

### ISSUE THREAD

**Issue by agilenut** [rfennell/AzurePipelines#985]
I'm using the XPlat release notes generation task and when my handle bars template has an error, the task still completes successfully. Is there a way to force the task to fail so that I can see the failed YAML pipeline step?

**Comment by rfennell** [comment]
At present, there is no flag to change the behaviour on a template issue. 

FYI: The current behaviour was a pass feature request, a silent, but logged failure.

I think it is a reasonable enhancement to add a flag to allow the pipeline to be stopped on a template error, it is on the backlog

**Comment by rfennell** [comment]
This feature has been added to 3.49.7.

There is a new parameter

`stopOnError: true`

If enabled will stop the pipeline if there is a Handlebars template error, if false the task will log the error but continue (default is false)
