### ISSUE TITLE
update testconsole node depedencies to counter package vulnerabilities 

### ISSUE THREAD

**Issue by AlexKeySmith** [rfennell/AzurePipelines#987]
Currently when you run npm install inside \Extensions\XplatGenerateReleaseNotes\V3\testconsole you get this (rather unnerving) warning. It's not as high priority as the message suggests as it's tooling used in the background i.e. not on a production platform, but it would be nice to upgrade the packages to keep the mind at ease.

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:

  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
npm WARN XPlatGenerateReleaseNotesTask@ No repository field.

added 880 packages from 1162 contributors and audited 882 packages in 51.919s

5 packages are looking for funding
  run `npm fund` for details

found 190 vulnerabilities (125 low, 5 moderate, 58 high, 2 critical)

**Comment by rfennell** [comment]
I have done one of my regular dependency updates, it will be published in the next release. However, highlight.js is an indirect dependency via [handlebar-helpers](https://www.npmjs.com/package/handlebars-helpers) and does not seem a very active project

**Comment by AlexKeySmith** [comment]
Good to know thanks rfennell, keep up the good work.
